ethereum/EIPs

EIPS/eip-3.mediawiki
As discussed in [Gitter EIP](https://gitter.im/ethereum/EIPs) channel, this is a proposed EIP for introducing a new opcode, `CALLDEPTH`.
=> EIP for CALLDEPTH opcode

EIPS/eip-2.mediawiki
we passed 720,000 a while back
@wanderer said the new one is 0xF4240 (1000000)
=> EIP02 - update hard fork block number

EIPS/eip-8.md
This is the first Networking EIP, in which I am trying to sneak some changes
into all implementations before the Homestead release. These changes should
make network protocol upgrades a lot easier in the future.
Merry :christmas_tree: everyone.
=> EIP-8: devp2p Forward Compatibility Requirements for Homestead

README.md
Added link to EIP-8 which was accepted, but for some reason wasn't added to the README.md
=> Add EIP-8 to README.md

EIPS/eip-2.mediawiki
EIP2 should be set to 'final', because:
- EIP2 is already in 'accepted' state
- EIP2 is already implemented in more than two clients
- EIP2 is already added to the yellow paper specification
This PR might not be perfect, but you get the idea.
=> I propose to update EIP2 status to 'final'.

EIPS/eip-1.md
=> Remove redundant slashes

README.md
Some of the URLs for the EIP numbers pointed to non-existent pages. Fixed by using absolute rather than relative paths.
=> Fix up URLs for the EIPs.

EIPS/eip-150.md
This copies the text from https://github.com/ethereum/EIPs/issues/150, adds a preamble, and consolidates the spec and rationale to the version that was accepted and finalized (version 1c).
=> formatted file for EIP 150

EIPS/eip-137.md
This PR adds a note to EIP 137, warning implementers about how to treat resolvers with unset addr records. This is intended to prevent user mistakes resulting in sends of funds or tokens to address 0.
=> EIP 137: Add warning for implementers against treating 0 like other addresses

EIPS/eip-ens-initial-registrar.md
@Arachnid @alexvandesande I've update this to reflect the current design, but would appreciate a quick review to see if I've missed anything. Hopefully moving this to the new EIP format will remove me as a bottle neck for updating the spec. 
Similar to #629, this is already implemented and deployed.
=> Update and move ENS Initial Registrar spec to new EIP format

EIPS/eip-615.md
The loop in `validate_subroutine()` should stop when it sees `BEGINDATA`.  I chose `return true` to exit the loop.
=> eip-615: BEGINDATA instruction finishes the analysis

EIPS/eip-55.md
The reference implementations for EIP-55 didn't include the `ethereum-utils` library which includes tools for both generating checksummed addresses as well as verifying them.  This is a *better* reference as it's tested and installable as a library rather than copy/pasting code.
Added the implementation to the list after the existing implementation.  I'd suggest replacing the current listed python implementation but I didn't want to take that liberty unless someone else concurs that it's the right thing to do.
=> Add reference to EIP-55 implementation in ethereum-utils library

README.md
[EIP 86](https://github.com/ethereum/EIPs/pull/208) was deferred at [All Core Devs Meeting 20](https://github.com/ethereum/pm/issues/18).
=> move EIP 86 to deferred table

README.md
According to the consensus seen in the [Core Dev meeting 22](https://github.com/ethereum/pm/issues/20), this PR moves EIP-96 from Accepted to Deferred.
=> Defer EIP96 from Byzantium to Constantinople

README.md
https://github.com/ethereum/EIPs/pull/658 (Embedding transaction return data in receipts)  supersedes https://github.com/ethereum/EIPs/issues/98 (Removal of intermediate state roots from receipts). So #98 should be removed from the Accepted table.
=> remove intermediate state roots from accepted table (#98)

README.md
https://github.com/ethereum/EIPs/pull/669 (Metropolis Difficulty Bomb Delay and Issuance Reduction) was accepted, superseding https://github.com/ethereum/EIPs/issues/186 (Reduce ETH issuance before proof-of-stake). [AllCoreDevs Meeting 21](https://github.com/ethereum/pm/issues/19#issuecomment-318680440)
=> add EIP 649 (difficulty bomb and issuance reduction) to accepted table

EIPS/eip-145.md, EIPS/eip-draft_bitwise_shifts.md
Introduce bitwise shifting.
(Replaces the old issue #145.)
=> Bitwise shifting instructions in EVM

EIPS/eip-devp2p-snappy.md
Ping @fjl @Arachnid @vbuterin @Souptacular @arkpar @holiman.
Open question: Should we enforce compression for all connections running devp2p v5, or should we add a capabilities bitset instead which can be used to signal current (and potentially future) compression capabilities and let clients agree on common ones? The non obvious thing here is the extra complexity if multiple conflicting capabilities match (e.g. multiple compression algos, which one do we chose).
Update:
* **2017-09-08**: Per @gumb0's suggestion and a brief discussion, I've updated the spec to enforce limiting decompressed message sizes to 16MB (**2^24-1**). This ensures that higher level applications have the same guarantees about network messages as until now and makes the implementation simpler too as it doesn't need …
=> Snappy compression for DEVp2p

README.md
Maybe there's a better way to express this, but it seems there could be more clarity about the distinction between 'planned' and 'deferred'.
=> Add split metropolis HF names to README

README.md
=> Byzantium is now live

EIPS/eip-100.md
Create a file for https://github.com/ethereum/EIPs/issues/100, and edit the text to meet the guidelines in https://github.com/ethereum/EIPs/pull/687.
=> add file for EIP 100

EIPS/eip-100.md
I merged an EIP by mistake with `METROPOLIS` in it.  The fork should now be called `BYZANTIUM`.
=> Replace a METROPOLIS with BYZANTIUM

EIPS/eip-161.md
When EIP 161 was initially implemented in ethereumjs-vm, it also failed to revert empty account deletions. This clarification should be noted in the EIP text.
=> amend 161 (state trie clearing) to clarify revert behavior

EIPS/eip-609.md
This PR modifies a title of an EIP in the Byzantium EIP list.  The title has already been changed in the EIP itself.
=> Fix a title of a Byzantium EIP

EIPS/eip-55.md
The spec code calls a non-existent `checksum_encode2()` instead of the defined `checksum_encode()`.
=> eip-55 checksum_encode spec typo

EIPS/eip-20-token-standard.md
In the current file, the sentence "A token contract which creates new tokens SHOULD trigger a Transfer event with the _from address set to 0x0 when tokens are created." is part of the "transfer" method section.
This sentences is linked to the "Transfer" event, not the "transfer" method.
I suggest to move it to the appropriate "Transfer" section.
=> Move the sentence about Transfer event at creation

EIPS/eip-1.md
In [the last Core Devs meeting](https://github.com/ethereum/pm/issues/27), there was a consensus that EIPs should be licenced with CC0.
=> Add 'Copyright Waiver' to 'What belongs in a successful EIP?'

EIPS/eip-55.md
copy the test cases from the issue https://github.com/ethereum/EIPs/issues/55, and change the section order.
=> add test cases to EIP-55

EIPS/eip-801.md, EIPS/eip-canary-standard.md
The canary can e.g. be used as a [warrant canary](https://en.wikipedia.org/wiki/Warrant_canary).
A standard interface allows other applications to easily interface with canaries on Ethereum - e.g. for visualizing the state, automated alarms, apps to feed the canary or contracts (e.g. insurance) that use the data.
Solves the following problems with current (warrant) canaries:
> In addition to a digital signature, it provides a recent news headline as proof that the warrant canary was recently posted as well as mirroring the posting internationally.
>
> Source: https://en.wikipedia.org/wiki/Warrant_canary
Signing a news headline is more work and less secure than using Ethereum for this task. The effort it takes to sign a news headline also leads to organisations not going this route at all …
=> Canary Interface ERC

EIPS/eip-20-token-standard.md
Fix broken link to https://github.com/ConsenSys/Tokens/blob/master/contracts/StandardToken.sol, as ConsenSys renamed it to https://github.com/ConsenSys/Tokens/blob/master/contracts/eip20/EIP20.sol and made other associated changes recently in this commit https://github.com/ConsenSys/Tokens/commit/44c3a1e46dc9b5e49c65f20bddad1f7ad9e7e3fa
=> Fix broken ConsenSys link in eip-20-token-standard.md

README.md
Adds a table with links to the HF meta-EIPs: https://github.com/ethereum/EIPs/pull/607 https://github.com/ethereum/EIPs/pull/608 and https://github.com/ethereum/EIPs/pull/606. An [Informational EIP](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md#eip-types) on the DAO fork remains to be written.
=> add table of HF meta-EIPs

EIPS/eip-162.md
The header for this EIP was not consistent with EIP-1 which defines that and ERC is of type Standard Track.
Also added the sub category for clarity.
=> Update EIP-162 as Standard Track with category ERC

README.md
Puts the already merged non-final EIPs in a table in the README. These may need to be moved to **Rejected**, **Withdrawn**, **Replaced** or to **Accepted**, but for now this makes them more visible.
=> List all non-final EIPs in README table

EIPS/eip-20-token-standard.md
This PR adds historical links to the ERC 20 standard, so that people can follow the discussion up until the finalisation, and why certain choices where made.
=> Added historical links to ERC20

EIPS/eip-615.md
`validate_jumps()` function contains two loops, but the second loop was sometimes skipped before this PR.  The two loops check different kinds of properties, and somehow I thought the second loop should be entered in this case.
=> eip-165: when the first loop hits BEGINDATA, the second loop should still run

eip-X.md
Source of specification: 
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md#what-belongs-in-a-successful-eip
> Preamble - RFC 822 style headers containing metadata about the EIP, including the EIP number, a short descriptive title (limited to a maximum of 44 characters), the names, and optionally the contact info for each author, etc.
=> Limit title length

EIPS/eip-831.md
as discussed with @nagydani - extracting the container format from #681 for a cleaner future 
cc @rmeissner
=> EIP-831: Standard URL Format

EIPS/eip-695.md, EIPS/eip-rpc_eth_chain_id.md
Rel ethereum/go-ethereum#15002
/cc @sorpaas @tcz001
=> EIP: Implement `eth_chainId` method in JSON-RPC

EIPS/eip-606.md
As per https://blog.ethereum.org/2016/02/29/homestead-release/.
=> Include EIP 8 in EIP 606

EIPS/eip-161.md
Newly-creation: this is wrong. You use adverbs before verbs. Creation implies that it is new, so it is a tautology to say new creation or newly created; rather like "I killed him dead".
=> EIP-161: Grammar fixes and block fork number parameters

EIPS/eip-858.md, EIPS/eip-reduce_block_reward.md
This EIP is proposal to reduce the block reward to 1 ETH / block from the present 3 ETH / block at a future, as present unplanned hard fork to be named Perinthos (before Constantinople). The rationale for reducing the block reward stems from the present tremendous growth in hashrate (and corresponding environmental costs) as well as the counter-productiveness of fostering growth in GPU mining.
=> Reduce block reward

EIPS/eip-868.md
This EIP defines an extension to Node Discovery Protocol v4 to enable authoritative
resolution of [Ethereum Node Records (ENR)](https://github.com/ethereum/EIPs/pull/778).
=> EIP-868: Node Discovery v4 ENR Extension

README.md
EIP-1 is in the wrong table and no table exists for EIPs that are both Finalized
and Active. Quoting the EIP:
> Some Informational and Process EIPs may also have a status of “Active” if they are never meant to be completed. E.g. EIP 1 (this EIP).
This can lead to confusion just like it happened
[here](https://github.com/ethereum/EIPs/pull/867#issuecomment-364483227).
To avoid that I am moving the EIP in the Readme to its own special table.
@pirapira Do you think this is an appropriate change in the Readme?
=> Add finalized but active table

EIPS/eip-1.md
As discussed in https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2031.md#10957-decision-process-for-eips
@nicksavers is now an editor for the EIPs.
=> Add Nick Savers, remove Yoichi on EIP editors list

EIPS/eip-165.md
**Reference**
* The original ERC-165 issue https://github.com/ethereum/EIPs/issues/165
**Work plan**
BELOW IS A COMPLETE COPY OF THE [LATEST FULL TEXT PROPOSAL](https://github.com/fulldecent/EIPs/blob/patch-4/EIPS/eip-165.md) **(VERSION 03c67d2)** FOR YOUR CONVENIENCE.
---
```
EIP: <to be assigned>
Title: ERC-165 Standard Interface Detection
Author: Christian Reitwießner <chris@ethereum.org>, Nick Johnson <nick@ethereum.org>, Fabian Vogelsteller <fabian@frozeman.de>, Jordi Baylina <jordi@baylina.cat>, Konrad Feldmeier <konrad.feldmeier@brainbot.com>, William Entriken <github.com@phor.net>
Type: Standard Track
Category: ERC
Status: Draft
Created: 2018-01-23
```
Creates a standard method to publish and detect what interfaces a smart contract implements.
Herein, we standardize the following: …
=> ERC-165 Standard Interface Detection

EIPS/eip-681.md, EIPS/pay_req_url_fmt.md
Payment request URL specification for QR codes, hyperlinks and Android Intents.
=> EIP: Payment request URL specification

README.md
=> Add ERC-165 and ERC-681 to README

EIPS/eip-721.md
We want it to only be callable by the NFT owner.
Also corrects a typo.
As mentioned on #841. cc @fulldecent
=> EIP-721: Be explicit about setApprovalForAll's msg.sender requirement.

EIPS/eip-721.md
And tweak the description to more clearly indicate its difference from the other, per-NFT operations. Hopefully mentioning `msg.sender` specifically will make it more clear that this operation affects an address rather than an asset.
As discussed in #925.
=> EIP-721: Remove throw condition for setApprovalForAll.

EIPS/eip-20.md
As the `constant` modifier for functions [is deprecated and planned to be dropped in Solidity 0.5](http://solidity.readthedocs.io/en/develop/contracts.html#view-functions), wouldn't it make sense to reflect this in this standard's code examples?
=> Change `constant` modifier to `view` in functions

EIPS/eip-197.md
It is different from that of G1.  See https://github.com/ethereum/yellowpaper/pull/659
=> Fix the curve equation of G2 in the pairing checker

EIPS/eip-778.md
This pull request proposes Ethereum Node Records, a new format for p2p connectivity information.
=> EIP-778: Ethereum Node Records

EIPS/eip-778.md
Use "Standards Track" instead of "Standard Track" to match all other EIPs.
=> EIP-778: fix type field

.travis.yml, EIPS/eip-1.md, PULL_REQUEST_TEMPLATE.md, README.md
This PR adds an autocommit bot that runs when the build succeeds. It automatically merges PRs if the following conditions are met:
- The PR modifies only existing draft-state EIPs.
- The PR doesn't change any EIPs to a status other than draft.
- The EIPs being modified all specify the PR creator as an author.
The idea here is to alleviate administrative load, and to reduce the round-trip time for drafts under active editing. It should further encourage people to set up a persistent discussion channel instead of trying to use PRs for this. This should also encourage people to spend less time getting their first draft *just so*, since updates are easier and don't require waiting for an editor. All in all, I'm hopeful it leads to more, and more up to date, drafts in the …
=> Add autocommit bot and descriptions of it

EIPS/eip-884.md
No substantive changes, just some updates to grammar, spelling, and overall written style.
* Where appropriate stocks are now referred to as shares.
* Capitalisation has been made consistent.
* Some text has been reworded for improved clarity
=> [Optimisation, ERC-884] spelling, grammar and style adjustments

EIPS/eip-969.md, EIPS/eip-X-ASIC-resistant-block-mining.md
Pull request based on the conversation in https://github.com/ethereum/EIPs/issues/958
=> Early ASIC Mitigation Hardfork

EIPS/eip-615.md
`validate_jumps()` function has two loops.  Both should start with `current_sub` initialized to zero.
After doing this, I didin't see the argument `PC` used anywhere.  So I removed it.
=> eip-615: initialize current_sub variable

EIPS/eip-191.md
=> Create EIP 191

EIPS/address-collision-exceptional-halt.md, EIPS/eip-689.md
This follows the discussion in [coredev meeting 22](https://github.com/ethereum/pm/issues/20), where no objections were made to the proposal to make contract creation fail in the case of address collision.
=> Address Collision of Contract Address Causes Exceptional Halt

EIPS/eip-681.md
The old one is not maintained anymore - the new one is updated - e.g. now contains tuples.
This also uncovers another problem here. We are specifying this against a moving target (OK a very slowly moving target - but still moving) - this could cause incompatibilities in the future.
cc @nagydani
=> Update to new ABI spec URL

EIPS/eip-820.md
This is the PR discussed in #820 
Currently, there is no open issues/conflicts in this standard proposal.
=> ERC-820 Pseudo-introspection using a registry contract.

EIPS/eip-721.md
Minimal changes. Swapping a 6 and a 5, twice.
=> EIP-721: Fix typo, uint265 -> uint256

EIPS/eip-758.md
Change eth_newFilter with params=["returnData"] to eth_newReturnDataFilter to be consistent with rest of JSON-RPC api.
This is the first and most straightforward of the modifications to EIP-758 I suggested in [Issue #963](https://github.com/ethereum/EIPs/issues/963).  I've been in contact with both @tinybike (original EIP author) and @adisney (he's working on the Parity implementation of it, while I'm working on the Geth implementation) about this, and both are in support of it.
=> EIP-758 update

EIPS/eip-778.md
This change makes information in ENR compatible with the existing
discovery protocol:
- The default identity scheme is now called "v4" to make the name shorter.
- Node addresses are derived as the hash of the uncompressed public key.
- The "ip4" and "ip6" keys are merged into a single "ip" key which
can hold a IPv4 or IPv6 address.
- The "discv5" key is now called "udp".
- The new "tcp" key holds the TCP port.
=> EIP-778: simplify ENR for v4 compatibility

EIPS/eip-1051.md, EIPS/eip-x-overflow.md
This EIP proposes a pair of flags and opcodes to efficiently detect arithmetic overflow, reducing gas costs for contracts that need to prevent arithmetic overflow.
=> Arithmetic overflow detection for the EVM

EIPS/eip-1052.md, EIPS/eip-x-codehash.md
This EIP proposes an 'EXTCODEHASH' opcode, which returns the keccak256 hash of a contract's code.
=> 'EXTCODEHASH' opcode

EIPS/eip-820.md
The name used in ERC777 is actually `TokensRecipient` instead of `TokensReceiver` so I changed the example to be coherent with the ERC777 standard.
=> Set the example name compatible with a real example

EIPS/eip-1062.md, EIPS/eip-X.md
Initial pull request for the "Formalize IPFS hash into ENS(Ethereum Name Service) resolver" EIP.
The goal is to specify the mapping protocol between resources stored on IPFS and ENS(Ethereum Naming Service).
=> Formalize IPFS hash into ENS(Ethereum Name Service) resolver

EIPS/eip-918.md
Cleaned up presentation code and added adjustment interval getter to base interface
=> Adjustment Interval

EIPS/eip-1066.md
This proposal outlines a common set of Ethereum status codes (ESC) in the same vein as HTTP statuses or BEAM tagged tuples. This is a shared set of signals to allow smart contracts to react to situations autonomously, expose localized error messages to users, and so on.
ERC-1066 is purely about convention, requires no changes to the EVM, and is usable today. Further investigation is being done into potentially adding these to the status field of transactions, but is out of scope of this EIP.
We have intentionally left portions of the status code chart blank. Rather than impose a complete set up front, we hope to consult to broader community on what may be the most useful and widely applicable codes.
=> Status code proposal

EIPS/eip-1077.md
Allowing users to sign messages to show intent of execution, but allowing a third party relayer to execute them is an emerging pattern being used in many projects. Standardizing a common format for them, as well as a way in which the user allows the transaction to be paid in tokens, gives app developers a lot of flexibility and can become the main way in which app users interact with the Blockchain.
* [Ethereum Magician's discussion](https://ethereum-magicians.org/t/erc1077-and-1078-the-magic-of-executable-signed-messages-to-login-and-do-actions/351)
* [Talk introducing this at UX Unconf Toronto](https://www.youtube.com/watch?v=qF2lhJzngto)
=> ERC: Executable Signed Messages refunded by the contract

EIPS/eip-1011.md
changelog:
- Expand and update glossary
- Change name of `SIGHASHER` to `MSG_HASHER`
- Initialize casper contract with an explicit CALL to `init` rather than with a constructor in EVM init code.
- Remove `vote_gas_limit`. Add `vote_gas_used` and clarify `gas_used` in `vote` transaction receipts
- Update fork choice to include full pseudocode. New pseudocode utilizes casper contract fork choice helpers -- `highest_justied_epoch(min_deposits)` and `highest_finalized_epoch(min_deposits)`
- add param `INITIALIZE_EPOCH_BYTES` to more clearly define the previous `0x5dcffc17` magic number
- add param `VOTE_BYTES` to help clients filter transactions for `vote` transactions
- add param `WARM_UP_PERIOD` to provide a stretch of blocks for validators to initially deposit before FFG functionality …
=> EIP-1011 updates

EIPS/eip-721.md
The mutability of the `name()` and `symbol()` functions in the metadata extension should be `view` not `pure`. Having it set to `pure` assumes that the token name and symbol will be hard-coded into the contract functions, rather than set (for example, in the constructor).
The mutability guarantee rules allow you to go stricter, (ie move from `view` to `pure`), but not the other way, so dropping it down to `view` wouldn't take anything away but would allow for these variables to be set and stored elsewhere in the contract.
- The PR edits …
=> Change name and symbol functions to view for Metadata extension

EIPS/eip-918.md
Per discussion with @montyanderson, it was determined that passing the challenge_digest to mint is practically redundant. Additionally pulled 4 phase mint operations into base ERC918 Interface
=> Removed redundant submission of challenge_digest

EIPS/eip-1.md
=> Fix formatting EIP-1

EIPS/eip-777.md
This PR modifies the EIP-777 draft as follow:
- Remove `send` overloading
- Clarfiy ERC-820 Registration
- Fix some language, grammar, typos & links
> We decided to remove the `send` overloading based on [some](https://github.com/ethereum/EIPs/issues/777#issuecomment-378946400) [comments](https://github.com/ethereum/EIPs/issues/777#issuecomment-385583277) from the community and to ensure the standard can be implemented in languages such as Vyper which do not support overloading.
=> ERC777: Remove `send` overloading and clarifications

EIPS/eip-1102.md, EIPS/eip-web3-access.md
MetaMask and most other tools that provide access to web3-enabled environments do so automatically and without user consent. This exposes users of such environments to fingerprinting attacks since untrusted websites can check for a `web3` object and reliably identify web3-enabled clients.
This proposal outlines a new dapp initialization strategy in which websites request access to the web3 API instead of relying on its preexistence in a given environment
- [Ethereum Magician's discussion](https://ethereum-magicians.org/t/opt-in-web3-access/414)
=> EIP: Opt-in web3 access

EIPS/eip-1123.md
#1123 
- Remove extraneous quotes in inline code literals, or correct quotes to JSON-valid
- Remove suggestion to use "package" metonymously to mean "package manifest"
=> Make minor updates to EIP-1123

EIPS/eip-173.md
Please pull in my request to create EIP 173.
EIP 173 is the Contract Ownership Standard
It provides a standard interface for querying and assigning ownership to contracts.
Discussion of this standard is here: https://github.com/ethereum/EIPs/issues/173
=> EIP 173: Contract Ownership Standard

EIPS/eip-721.md
Thank you @shrugs.
This harmonizes punctuation used in NatSpec:
- @notice, @param, @return are fragments (not a sentence, no period at end)
- @dev is a sentence (period at end)
This PR supercedes https://github.com/ethereum/EIPs/pull/1151
=> Fix 721 punctuation natspec

EIPS/eip-721.md
Before approving this PR please verify the correct value of
`bytes4(keccak256("onERC721Received(address,address,uint256,bytes)"))`
This might be done quickly here: https://emn178.github.io/online-tools/keccak_256.html for `onERC721Received(address,address,uint256,bytes)` and confirm that for previous signature `onERC721Received(address,uint256,bytes)` it returns `f0b9e5ba`.
=> Add operator parameter to onERC721Received function.

EIPS/eip-721.md
This pull requests promotes ERC-721 from Last Call status to Final status.
One immaterial change was made during the Last Call and all questions were addressed.
The time now is Thursday in UTC time zone. We have added two days to the Last Call in good taste.
Relevant policy is given in [EIP-1](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md) for when to promote an EIP from Last Call status to Final status:
> ➡️ Final (Not core EIPs) -- A successful Last Call without material changes or unaddressed complaints will become Final.
ERC-721 began Last Call with commit https://github.com/ethereum/EIPs/commit/c9a9320#diff-a87271f8186c59c075e229cd7421f205
Every change since then are viewable with the compare view: https://gith ub.com/ethereum/EIPs/compare/c9a9320...master#diff-a87271f818 …
=> 721, the first graduate from the Last Call process

.travis-ci.sh, .travis.yml
Best practice stolen from:
- https://github.com/fulldecent/html-website-template/blob/master/.travis.yml#L8-L10
- https://github.com/fulldecent/lightning-sites/blob/master/lib/lightning_sites.rb#L229-L231
Maybe you didn't know I'm also on the html-proofer project :-p
---
Build times of external link check.
BEFORE change 2 min 2 sec -- https://travis-ci.org/ethereum/EIPs/builds/394136680
AFTER change 1 min 29 sec -- https://travis-ci.org/ethereum/EIPs/builds/394195566
THE MAGIC -- https://travis-ci.org/ethereum/EIPs/jobs/394195569#L1147
=> Cache external link checks

EIPS/eip-1154.md, EIPS/eip-oracle_interface.md
Please see #1161 for the discussions thread.
=> Oracle interface

EIPS/eip-1102.md
This PR removes web3-specific verbiage from EIP-1102 and replaces it with more-generalized, provider-specific verbiage.
=> EIP-1102: remove web3-specific verbiage

EIPS/eip-823.md
Current version of EIP-823 implies using of unsafe global variable `tx.origin`.
As you can see on `Exchanging Tokens` diagram, exchange service contract must call `__exchangerCalback` on source token contract with address of token holder (here `0xa12`), but it doesn't know this address from `exchangeToken` arguments. Next, `__targetExchangeCallback` in target token contract also must know token holder address (for correct changing balance and emitting `Exchange` event), but doesn't have such argument.
Same problem with `Exchanging And Spending Tokens` diagram.
I implemented current version of EIP-823 with `tx.origin` usage in test contracts and successfully stole tokens via phishing contract under some conditions.
=> EIP-823: security improvements

EIPS/eip-1066.md
Work on implementation of ERC-1066 now happens [here](https://github.com/expede/ethereum-status-codes/). This PR updates the link. It also adds a link to the [npm](https://www.npmjs.com/package/ethereum-status-codes) deployment of the same.
=> Update EIP-1066 links to new code repo

EIPS/eip-1240.md, EIPS/eip-xxxx.md
The difficulty bomb operates under the assumption that miners decide what code economic participants are running, rather than economic participants deciding for themselves. In reality, miners will mine whatever chain is most profitable and the most profitable chain is the one that economic participants use. If 99% of miners mine a chain that no economic participants use then that chain will have no value and the miners will cease mining of it in favor of some other chain that does have economic participants. Another way to put this is that miners will follow economic participants, not the other way around.
With the difficulty bomb removed, when Casper is released it will be up to economic participants to decide whether they want the features that Casper enables or not. If they do not want …
=> Creates Remove Difficulty Bomb EIP

EIPS/eip-1276.md
```
eip: 1276
title: Eliminate Difficulty Bomb and Adjust Block Reward on Constantinople Shift
author: EOS Classic (@eosclassicteam)
discussions-to: https://ethereum-magicians.org/t/eip-1276-eliminate-difficulty-bomb-and-adjust-block-reward-on-constantinople-shift/908
type: Standards Track
category: Core
status: Draft
created: 2018-07-31
```
**Abstract**: Starting with `CNSTNTNPL_FORK_BLKNUM` the client will calculate the difficulty without considering the current block number. Furthermore, block rewards will be adjusted to a base of 2 ETH, uncle and nephew rewards will be adjusted accordingly.
Read the draft here: [eip-1276.md](https://github.com/eosclassicteam/EIPs/blob/master/EIPS/eip-1276.md)
Orthogonal intention and not compatible with #1234 .
=> EIP-1276: Eliminate Difficulty Bomb and Adjust Block Reward on Constantinople Shift

EIPS/eip-1.md
Update EIP-1 to fix `discussion-to` and `resolution` URL field
=> Update EIP-1 to fix `discussion-to` and `resolution` URL field

EIPS/eip-1285.md
Added EIP #1285 proposing to increase the gas stipend given for a called contract for a non zero value calls from 2,300 to 3,500.
=> EIP 1285: Increase Gcallstipend gas in the CALL OPCODE

EIPS/eip-1.md, README.md
All of the recent changes to the EIP process have been made to ensure that the EIP process is a technical one, and not one of sentiment analysis.  There is a lot of discussion going on with regards to how we can improve the process and get valid community sentiment analysis pre-fork, but there doesn't exist a complete solution yet at this time (just proposals).
It appears that the Last Call PR introduced sentiment analysis into the process, which I do not believe was intended.  From my recollection of the discussions around the Last Call stuff, the goal wasn't to fundamentally change how governance works, but rather to ensure that EIPs don't get stuck indefinitely in limbo.
This change simply removes the sentiment analysis wording from the process and makes it more clear that the EIP …
=> Changes EIP-1 wording to focus on technicals not community sentiment.

EIPS/eip-1283.md
Version II is recommended. Putting Version I there causes confusion.
=> EIP-1283: remove Version I

EIPS/eip-1102.md
This pull request updates EIP-1102 to respond with an Ethereum provider API by emitting a CustomEvent instead of injecting a global and posting a message back to the dapp context.
=> 1102: Emit a custom event upon user approval

EIPS/eip-1087.md
Consider a transaction with only one SSTORE that sets a slot from 1 to 0. This shouldn't benefits from gas reduction. Currently it costs 5000 gas plus 15000 gas refund, and in this EIP it should cost the same.
=> Fix R_RESET refund for EIP-1087

EIPS/eip-1319.md
Specifies an interface for smart contract package registries like EthPM. See discussion in #1319.
=> ERC 1319 Smart Contract Package Registry Interface

EIPS/eip-137.md
In the example addr function returns an address, not an hash
=> Fixed misleading var name

_config.yml
This adds Twitter Card metadata to the site, using the format that
[`jekyll-seo-tag`](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md),
a dependency of Minima, understands. This should make the site render better
on Twitter.
I tested this locally and it seemed to work.
=> [site] Add Twitter Card metadata

EIPS/eip-1328.md
=> ERC-1328 - WalletConnect Standard URI Format

EIPS/eip-725.md
- Added an underscore to the purpose parameter in `keyHasPurpose` to match other parameters of solidity functions.
- Added an explicit `public` keyword to `keyHasPurpose`.
- Added `removeKey` which is described in the spec but not found in interface.
=> EIP725 - Fix interface code

EIPS/eip-1102.md
This pull request updates EIP-1102 so that dapp browsers inject a read-only provider populated with no accounts until user approval.
=> EIP-1102: Inject read-only provider

EIPS/eip-1102.md
This pull request updates EIP-1102 by removing the `isEnabled` flag from the provider since this can be set manually by the dapp if desired.
=> EIP-1102: Remove isEnabled flag from provider

EIPS/eip-1013.md
- Remove EIP-210 from list
- Replace EIP-1087 with EIP-1283
- Add EIP-1234
As discussed at https://github.com/ethereum/pm/issues/55; see also https://github.com/ethereum/pm/issues/53
=> Update Constantinople Meta-EIP 1013

EIPS/eip-712.md
This example originated as a copy-paste of the 0x codebase, and it still had "order" instead of "mail" in it
=> EIP-712: fix assembly hashStruct example

EIPS/eip-1014.md
Do not refer to the hash function as `sha3` because it is SHA3. Use more precise `keccak256` name.
=> EIP-1014: Use keccak256 name instead of sha3

EIPS/eip-198.md
"Exponent" used twice when listing lengths in the same example, where once "modulus" was meant to be.
=> eip-198: fix minor typo + clarify a bit.

EIPS/eip-627.md
I didn't write this EIP but it is clearly miscategorized. The document
describes a devp2p protocol and should be in the Networking category.
=> EIP-627: move to Networking category

EIPS/eip-1459.md
This document describes a scheme for authenticated, updateable Ethereum node lists
retrievable via DNS.
=> EIP-1459: Node Discovery via DNS

EIPS/eip-145.md
The value `0x100` in test case 16 of the SAR test cases is supposed to mean `0x0100`
=> Corrected wrong hex value in EIP-145

EIPS/eip-1283.md
The spec is finalized, covered with test cases, and had an [informal proof](https://gist.github.com/sorpaas/27b8026c40e4777ede889c40e3824a04). See discussion on https://github.com/ethereum/pm/issues/55
=> Move EIP-1283 status to last call

EIPS/eip-900.md
Adding another reference implementation to ERC-900.
The reference includes:
- A basic implementation
- A credits implementation where staking rewards integer-based credits
- A weighted implementation where stakes can gain weight over time by accruing interest
=> Add another reference implementation for ERC-900

EIPS/eip-55.md
We have implemented eip-55 checksum addresses for ETH, ETC and ERC20 token addresses in the new version of Jaxx which is known as Jaxx Liberty.
=> Added Jaxx Liberty 2.0.0

EIPS/eip-1386.md, EIPS/eip-1387.md, EIPS/eip-1388.md
These 3 EIP's give a guideline to managing decentralised identifiers both on and off chain. 
Please see #1386 #1387 #1388 & our repo [here](https://github.com/alpha-wallet/blockchain-attestation)
=> add eip 1386, 1387 & 1388

EIPS/eip-1444.md
Giving up on vertical bars of any kind, and switching to function notation to express cardinality
=> ERC1444: appease markdown renderer

EIPS/eip-1102.md
This pull request updates EIP-1102 with a deprecation warning about `ethereum.enable()` and points developers to the new RPC method `eth_requestAccounts`.
=> EIP-1102: add deprecation warning about ethereum#enable

EIPS/eip-725.md
There was an inconsistency between the description and the proposed interface. At the description, the `key` has `uint256[] purposes`. But at the interface, it is `uint256 purpose`. I updated all the places to be to be a `uint256` instead of `uint256[]`.
=> Update eip-725.md (every key has one purpose)

EIPS/eip-1013.md
Added fork block 4,230,000 and new link to progress tracker on pm-wiki instead of the tracked issue.
=> Update EIP-1013 with Ropsten fork and progress tracker

EIPS/eip-1283.md
The Last Call period to 10-29 has ended. So I think it might be fine to move this to Accepted.
The entire set of changes are:
* Minor grammar fixes.
* Clarified in spec that while overall transaction refund counter cannot go negative, call-frame specific refund counter can go negative.
* Added a formal proof!
* @fulldecent raised a question about whether this gas scheme can result in high memory usage because of storage cache. The conclusion is that an attacker (given its goal is to cause as high memory usage as possible) cannot allocate more memory via storage cache -- whenever we need storage cache allocation, the gas cost is the same as current gas scheme, and refund counter cannot be used in current transaction.
* @fulldecent also raised some questions regarding the economics aspect …
=> Move EIP-1283 status to Accepted

EIPS/eip-1450.md
We are removing the references to LDGRToken to make sure this ERC is a standard and not interpreted as a custom company token project.
=> Renaming LDGRToken to ERC-1450

EIPS/eip-721.md
While the previous JSON may be valid for some interpreters (like JavaScript's) it's not valid according to [RFC 4627](https://www.ietf.org/rfc/rfc4627.txt) due to the trailing commas [1].
[1] "An object structure is represented [...]. A single comma separates a value from a following name."
=> Fix JSON syntax

EIPS/eip-155.md
Adding the chain ids for the two new testnets
**Görli:** (6284)
https://github.com/goerli/testnet
**Stureby:** (314158)
https://gist.github.com/5chdn/baf0eb40cbaff5a90befc52815d6950b
=> Add goerli and stureby chain_ids

EIPS/eip-1066.md
After gathering feedback from the community and several dozen companies, this is the first change to ERC1066: simple clarifying text.
* ESC -> status codes (esp. since the project has been rebranded "FISSION")
* Add `[reserved]` to currently unused codes
* By popular request, _put the code table back in_
* Expand motivation section
* Clarify in **several** more places that this is fully compatible with `revert`
More standardized codes are coming very, very soon!
=> Add clarifying text to ERC1066

EIPS/eip-###.md, EIPS/eip-1616.md
This pull request proposes an ERC for an Attribute Registry standard, a basic interface for querying a registry for attribute metadata assigned to Ethereum accounts.
For discussions-to, see [issue #1616](https://github.com/ethereum/EIPs/issues/1616).
=> EIP: Attribute Registry Standard (ERC)

EIPS/eip-1283.md, EIPS/eip-820.md
These EIPs have been in "last call" for more than two weeks, with no updates from their author justifying moving to final, or back to draft. As a result, this PR moves them back to draft state.
=> Revert "last call" status

EIPS/eip-820.md
The Last Call period for ERC820 ended on 2018-12-30 without further comments, suggestions or modifications. Hence I would like to move 820 to a final status.
I'd also like to thank everyone who contributed and helped with ERC820, (including in no particular order): @fulldecent @mcdee @jaycenhorton @Recmo @hyperfekt @wighawag @thegostep @Arachnid @Souptacular and everyone I forget.
=> ERC820: Move to Final

EIPS/eip-1.md
=> EIP1 formatting improvements

_config.yml, last-call.xml
This is a simple fix to make Last Call feed work.
I am also going to propose changes to fix #1535 and some additional feeds (e.g. global feed for all EIPs, JSON version of EIPs, etc. etc.)
I'll file a separate issue to gather suggestions for feed updates / wishlist.
=> Fix Last Call, remove jekyll-feeds plugin

EIPS/eip-1706.md
Moving proposal from pull request to existing EIP into a new one. 
See discussion:
https://github.com/ethereum/EIPs/pull/1701
=> Net gas metering for SSTORE with a reentrancy protection

EIPS/eip-20-token-standard.md
Preferred citation format is specified at https://github.com/ethereum/EIPs#preferred-citation-format
=> Use new preferred citation format

assets/eip-712/Example.js
As per the [latest](https://github.com/ethereumjs/ethereumjs-util/commit/9396416913125711e526a05591e3ce8471c3a528) commits on `ethereumjs-util`, `sha3` has been renamed to `keccak256` to avoid confusion.
=> Replaced sha3 with keccak256 in EIP-712 assets

EIPS/eip-902.md
* Modernize formatting
* Specify return codes as following `ERC1066`
* [_Use author GitHub usernames instead of emails_](https://github.com/ethereum/EIPs/pull/1516/files#diff-ccd638ef008081355e7f092db26088bfR4) (UPDATE: see @eip-automerger's comment)
* Update implementation repo
* Set `discussions-to`
I'm going to out on a limb and guess that this won't automege because we used company email addresses rather than usernames. All of the authors have since left that company, so this PR fixes that. As some proof that I am in fact the author of ERC902, here is the original PR: https://github.com/ethereum/EIPs/pull/902
=> ERC902: Modernize formatting & specify codes as ERC1066

EIPS/eip-1193.md
* Remove constructor constraint
* Add `isEIP1193`
* Define minimum viable implementation of EventEmitter
=> Updates EIP-1193

EIPS/eip-1066.md
Update EIP-1066 ("status codes") to last call for v1.0.0. This will still be open to further codes, but we are happy with this as a first version to be widely used.
(Also fix a typo 😅)
=> Set Status of EIP-1066 to Last Call

EIPS/eip-1066.md
Previous PR (#1735) was missing a `review-period-end`. Mea culpa!
https://ethereum-magicians.org/t/erc-1066-ethereum-status-codes-esc/283/38
=> Add review end date to EIP-1066

EIPS/eip-1013.md
All the other HF EIPs contain a link to the "ethereum.org blog" post about the HF. Not sure if this is useful, but follows "tradition".
=> Add ethereum.org blog post about constantinople

EIPS/eip-1716.md
```
eip: 1716
title: "Hardfork Meta: Petersburg"
author: Afri Schoedon (@5chdn)
type: Meta
status: Draft
created: 2019-01-21
requires: 1013, 1283
```
Since @5chdn doesn't want to coordinate the Hardfork process anymore, he deleted his PR.
This is just a copy of his PR which can be found here: https://github.com/ethereum/EIPs/pull/1716
This meta-EIP specifies the changes included in the Ethereum hardfork that removes [EIP-1283](./eip-1283.md) from [Constantinople](./eip-1013.md).
=> EIP-1716 Hardfork Meta: Petersburg (a.k.a. "Constantinople Fix")  by @5chdn

EIPS/eip-721.md
Just fixing a simple typo in the EIP-721 text:
`Axternal` -> `External`
=> Fix typo in EIP-721

EIPS/eip-615.md
Another author was confused about automerge criterea. Putting my Github username back, as have had issues in the past when locked out of a specific email (GH will authenticate many email addresses).
=> EIP-615: author's GH name, not hardcoded email

EIPS/eip-1193.md
After carefully reading this again, i noticed that there was an issue with the subscription.
One should put the subscription type in, so that the notification can pre-filter based on the subscription type (`eth_subscription`, `ssh_subscription`). Athen the returned object is within this subscription type, and mapping of sub IDs can be done properly.
Also the standard should not talk about JSON RPC, as this provider is meant to abstract that away. Under the hood it probably will have to create a son roc object, depending on how it communicates with the node.
I'm personally not sure if the `accountsChanged` and `networkChanged` events should be in this standard.
I certainly think the `eth_requestAccounts` should be in another standards proposal and not in the initial one here.
Ps. I took …
=> Fixed subscription API, and simplified

EIPS/eip-777.md
Fix a small copy/paste mistake where the wrong the `tokensToSend` hook is mentioned instead of the `tokensReceived`, leading to confusion.
=> Fix copy/paste mistake in function name

EIPS/eip-615.md
* Fix a layout typo
* Missing a backtick turned it into a table
* Remove trailing whitespace
=> Fix layout error in EIP-615

EIPS/eip-1057.md
Update params to reflect original "0.9.2" values and proposed "0.9.3" params.  
0.9.2 are what is on the gangnam testnet and 0.9.3 are what @IfDefElse propse for mainnet
Also, remove references in text to 50 block default period.
=> Update params to reflect  "0.9.2" and "0.9.3" params

EIPS/eip-1474.md, EIPS/eip-rpc.md
Much of Ethereum's effectiveness as an enterprise-grade application platform depends on its ability to provide a reliable and predictable developer experience. Nodes created by the current generation of Ethereum clients can expose RPC endpoints with differing method signatures; this forces applications to work around method inconsistencies to maintain compatibility with various Ethereum RPC implementations.
Both Ethereum client developers and downstream dapp developers lack a formal Ethereum RPC specification. This proposal attempts to standardize such a specification in a way that's versionable and modifiable through the traditional EIP process.
This initial draft was based on the [current Ethereum RPC wiki documentation](https://github.com/ethereum/wiki/wiki/JSON-RPC) with necessary …
=> EIP: Remote procedure call specification

EIPS/eip-607.md
This updates to use the preferred citation format as per https://github.com/ethereum/EIPs#preferred-citation-format
=> Update to use preferred citation format

EIPS/eip-609.md
This updates to use the preferred citation format as per https://github.com/ethereum/EIPs#preferred-citation-format
=> Use preferred reference format

EIPS/eip-1167.md
This requirement is already specified in the EIP proper. The EIP-211 bytecodes (`0x3d`, `0x3e`) are used in the proxy specification. This PR adds EIP-211 as a requirement for EIP-1167 in the EIP metadata.
=> Add EIP-211 to metadata

EIPS/eip-20.md
The transfer function documentation currently references a non-existent `_from` parameter. This is clearly a copy-paste of the `transferFrom` function and clearly the intent is to reference the message caller (in Solidity, `msg.caller`). So I have corrected the language.
=> Fix language for transfer function

EIPS/eip-1.md
The `created` header supposed to be a single date, when the given EIP/ERC was created. EIP-1 itself violates this and includes multiple dates when significant changes have happened.
This proposal introduces the `updated` header which is optional and contains a list of dates when "substantial" changes were made.
=> Introduce "updated" date header in EIP-1

EIPS/draft_unlimited_swapdup.md, EIPS/eip-663.md
=> Unlimited SWAP and DUP instructions

EIPS/eip-1716.md
All the other HF EIPs contain a link to the "ethereum.org blog" post about the HF. Not sure if this is useful, but follows "tradition".
=> Add ethereum.org blog post about petersburg

EIPS/eip-191.md
As of the latest stable version of solidity (0.4.25), a contract can reference its own address by calling `address(this)` not just `this`. Furthermore, `keccak256` will no longer accept multiple parameters in the future, hence now we need to use `abi.encodePacked`.
=> Updated solidity syntax in EIP-191 specs

EIPS/eip-698.md, EIPS/eip-opcodeBLKREWARD.md
From #698 and #669 
Simple Summary
This EIP adds an additional opcode to the EVM which will return a finalized blocks reward value. 
See commits and files
=> Add opcode 0x46 blockreward

EIPS/eip-1681.md, EIPS/eip-draft_temporal_replay_prot.md
This PR adds an EIP about temporal replay protection, basically `valid-until` in the form of a timestamp to transactions.
=> add temporal replay protection

EIPS/eip-55.md
When Vitalik initially proposed the idea it was quite different, using the binary form of the address, which added complexity. I created the first implementation in that form, and suggested the simplified version `If it's 0-7 then it should be lowercase, otherwise, it should be uppercase.` I also pushed the first implementations. His original post has been edited by EIP editors as we didn't have the PR format yet.
Would that be enough to be a co-author? I don't mind if this is rejected, just wanted to point that up.
=> Adding co-author of ERC55

EIPS/eip-155.md
context: https://github.com/ethereum/EIPs/pull/1755#issuecomment-470863529 and #1703 
cc @nicksavers
=> Strip the list of chain ID's

EIPS/eip-1812.md, EIPS/eip-eth-verifable-claims.md
Reuseable Verifiable Claims using [EIP 712 Signed Typed Data](https://github.com/ethereum/EIPs/issues/712).
A new method for Off-Chain Verifiable Claims built on [EIP 712](https://github.com/ethereum/EIPs/issues/712). These Claims can be issued by any user with a EIP 712 compatible web3 provider. Claims can be stored off chain and verified on-chain by Solidity Smart Contracts, State Channel Implementations or off-chain libraries.
Reusable Off-Chain Verifiable Claims provide an important piece of integrating smart contracts with real world organizational requirements such as meeting regulatory requirements such as KYC, GDPR, Accredited Investor rules etc.
[ERC 735](https://github.com/ethereum/EIPs/issues/735) and [ERC 780](https://github.com/ethereum/EIPs/issues/780) provide methods of …
=> Ethereum Verifiable Claims

EIPS/eip-1155.md
Moving 1155 to last call. I've set the review end date to March 28 to provide adequate time for finalization.
=> Status changed to Last Call for ERC-1155

EIPS/eip-1319.md
```solidity
// Returns the total number of unique packages in a registry.
function numPackageIds() public view returns (uint totalCount);
// Returns the total number of unique releases belonging to the given packageName in a registry.
function numReleaseIds(string packageName) public view returns (uint totalCount);
```
This data can be typically found somewhere in a registry implementation (i.e. `ReleaseDB.getNumReleasesForNameHash()` in the [Solidity reference implementation](https://github.com/ethpm/escape-truffle/blob/master/contracts/ReleaseDB.sol)). However, it's quite useful to standardize how this data can be accessed via the primary registry interface since the `totalCount` is used in the pagination scheme of other standard interface functions (`getAllPackageIds()` and …
=> Proposal to add numPackageIds() and numReleaseIds()

EIPS/eip-225.md
Adds a small note about transaction execution for Clique Consensus.  Clarifies spec ambiguity.
=> eip-225: add note about transaction execution

eip-600.md, eip-draft-ethereum-purpose.md
This EIP defines a logical hierarchy for deterministic wallets based on [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) and the purpose scheme defined in [BIP43](https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki).
This EIP is a particular application of BIP43.
=> Ethereum purpose allocation and path scheme for deterministic wallets

EIPS/eip-601.md, EIPS/eip-draft-hdwallets.md
This EIP defines a logical hierarchy for deterministic wallets based on [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki), the purpose scheme defined in [BIP43](https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki) and eip-draft-ethereum-purpose.
This EIP is a particular application of eip-draft-ethereum-purpose.
=> Ethereum hierarchy for deterministic wallets

EIPS/eip-725.md
The discussion is ongoing here https://github.com/ethereum/EIPs/issues/725
This change, changes the proposal radically and modularises it a lot.
725v2 is now the core proxy account, that can have one owner, which itself can be a smart contract like #734 and in the `setData` a #780 or #735 can be referenced.
This makes it super flexible and creates a *manageable verifiable* account.
=> Changed draft to ERC725v2

EIPS/eip-1155.md
This updates to use the preferred EIP format for all references.
Source: https://github.com/ethereum/EIPs#preferred-citation-format
Also I have added (DRAFT) for references that are not (yet!) published standards.
=> Use preferred reference format for EIP references

EIPS/eip-1155.md
Update language to RFC-2119 specific language.
Subordinate SPECIFICATION to a level-2 heading. And reflow child headings as appropriate.
=> Wording + formatting

README.md, index.html
Update README and index.html to be consistent with EIP-1 and this PR: https://github.com/ethereum/EIPs/pull/1858/
=> Updated README and index.html to be consistent with EIP-1

EIPS/eip-778.md
- Sequence number is unsigned integer
- Keys must be unique
- Ports are big-endian
- Remove confusing notation
- "v4" signature doesn't contain recovery ID
- Add test vector
=> EIP-778: address review feedback

EIPS/blockhash-eip-draft.md, EIPS/eip-1898.md
For JSON-RPC methods which currently accept a default block parameter, additionally allow the parameter to be a block hash.
=> Add blockhash as option for some JSON-RPC methods

EIPS/eip-777.md
- Remove default from for operatorSend/Burn
- cleanup of function parameters
=> ERC777: remove default `from`

EIPS/eip-1820.md, EIPS/eip-820.md
There was no significant changes and no functional changes to ERC1820.  
The only change made was a change to the natspec comments on the registry.  
(See 556cc58428a0044141a878ad5e68b18bc69e13f0 for the changes.)
Thanks to @mcdee and @fulldecent for the reviews.
@nicksavers Could you please merge the PR and make 1820 final? Thanks
=> ERC1820: Move to final, mark 820 as superseded

EIPS/eip-777.md
Changes to #777:
- Clarify behavior with missing `tokensReceived` hook
- Fix some language mistakes
=> ERC777: Clarify behavior with missing tokensReceived

EIPS/eip-1890.md, EIPS/eip-credible_commitment.md
Sample geth implementation: https://github.com/GregTheGreek/go-ethereum/commit/a1ea205b8a4693b9578463735a486d198e2801d7
Sample Trinity implementation: https://github.com/lrettig/py-evm/commit/ee5a23f80eacfa1db05d025a2802003a05b2d48d
(These reference an old EIP number, #1789, and can be updated.)
=> EIP-1890: Commitment to Sustainable Ecosystem Funding

EIPS/eip-1898.md
Per discussion in https://github.com/ethereum/go-ethereum/issues/19394 and https://github.com/ethereum/go-ethereum/pull/19459, this commit clarifies error-handling behavior and adds a field so that the caller can specify whether they accept non-canonical block data.
=> Add canonical block details for EIP 1898

EIPS/eip-1679.md, EIPS/eip-233.md
@axic I've made some proposed changes to [233](https://eips.ethereum.org/EIPS/eip-233) and updated 1679 to match.
Doesn't look very controversial, just embeds timeline and also includes sections for Proposed / Accepted / Included EIPs.
=> Improvements to Hardfork Meta process

EIPS/eip-1679.md
=> EIP-1679: Add EIP-1344 as proposed to Istanbul

EIPS/eip-1319.md
Changed some variable names to enforce greater consistency across functions. 
`offset` -> `pointer` update for various return types, since Solidity doesn't allow you to declare the same variable name twice.
=> Minor updates to EIP

EIPS/eip-1155.md
=> id substitution example was not lowercase.

EIPS/eip-1155.md
=> Better wording on impl specific api rules.

EIPS/eip-777.md
This pull request contains improvements on #777 from the review process during the last call period.
=> ERC777 Last Call improvements

EIPS/eip-1108.md
=> Update EIP-1108 with latest gas metering benchmarks

EIPS/eip-1679.md
This is a PR to add eip-1108 to the list of proposed EIPs for Istanbul
=> updated eip-1679 to contain eip-1108

EIPS/eip-1155.md
=> Minor change on links to other standards still in draft. The status of those standards can be checked on their own landing pages.

EIPS/eip-1820.md, EIPS/eip-897.md
Some of the current links are not working, they have an extra `s` in the URL.
=> Fix pull request links

EIPS/eip-1679.md
Related Cat Herders issue (hope I get this right): https://github.com/ethereum-cat-herders/PM/issues/69
=> Add EIP-1283 and EIP-1706 to proposed EIP list for Istanbul

EIPS/eip-1679.md
* Add EIP-615 to proposed EIPs section of Istanbul Meta
* Editor stripped out trailing whitespace
* Can revert line that if needed, but it shouldn't be there anyway 🤷‍♀️
=> Add EIP-615 to Istanbul Meta

EIPS/eip-615.md
* Remove stray backtick
* Add missing backticks around a big-O for consistency
* Remove trailing whitespace
=> Fix EIP-615 backtick typo

EIPS/eip-165.md
```
eip: 165 v1.0.1
title: Fix Wrong Input Length - ERC165 Example
author: Agustin Aguilar (@Agusx1211)
type: Standards Track
category: ERC
status: --
created: 2018-12-07
```
Input should be 36 bytes (4 signature bytes + 32 bytes parameter)
Solidity 5 validates the length of msg.data, reverting on the 32 bytes input, all contracts using the broken 'doesContractImplementInterface' will not be able to read an ERC165 implementation targetting Solidity 5.
A legacy-compatible strategy should be defined to make all the "ERC165 readers" sending a 32 bytes sized data compatible with ERC165 contracts compiled targeting this new version of the compiler.
A possible solution could be to add a keyword on Solidity to disable the validation of the calldata length on a given function.
=> Fix Wrong Input Length - ERC165 Example

EIPS/eip-1108.md
Per https://github.com/ethereum/EIPs/pull/1987#discussion_r282513653, added more details on the proposed gas cost for EC precompilesl Per https://github.com/ethereum/EIPs/pull/1987#issuecomment-494968355, added the copyright statement.
Not sure if we need an approval from @zac-williamson as well here since this adds a copyright statement on work that's already been written.
=> EIP-1108: Add gas cost clarification + copyright assignment

EIPS/eip-1193.md
I've removed the ``requestAccounts`` method from this EIP because it should be defined by side of this provider. I've also changed the subscriptions handling back to the state before the accidentally merge happened.
=> EIP-1193 improvements

EIPS/eip-778.md
This update adds the `tcp6`, `udp6` keys and explains their use. It also changes the text representation to base64url with no padding. I expect this to be the final update to EIP-778
unless something super-critical comes up.
=> EIP-778: final update to IPv6 keys, use URL-safe base64

EIPS/eip-1261.md
=> Update examples to solidity 0.5.x

EIPS/eip-1155.md
=> ERC-1155 Extra note for NFTs, and updating some author emails

EIPS/eip-695.md
`eth_chainId` is implemented in geth and parity. And at this moment, for parity, we would want to know whether we can mark this API as standardized or experimental. So I propose to move EIP-695 to last call status.
=> Propose to move EIP-695 to last call status

EIPS/eip-1702.md
=> EIP-1702: Move extensions into separate EIPs and remove variant II

EIPS/eip-747.md, EIPS/eip-777.md
A method for web3 wallets to allow Dapps to suggest assets that the user might want to "watch". The first reference example is for adding a token to the user's list of watched tokens.
This feature is in [MetaMask v4.10.0](https://github.com/MetaMask/metamask-extension/releases/tag/v4.10.0) and can be tested against [this web app](https://metamask.github.io/Add-Token/#add?tokenAddress=0xdc1adf1d0bf59ec597e1b1b8e3dceb31aafd793f&tokenImage=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F723268858644037632%2Fu-kjO4___400x400.jpg&tokenName=Danbucks&tokenNet=3&tokenSymbol=DBX&tokenDecimals=2).
Latest discussion on the feature can be found here:
https://ethereum-magicians.org/t/eip-747-eth-watchtoken/1048
Fixes #747.
=> EIP 747: wallet_watchAsset

EIPS/eip-1948.md, EIPS/eip-nonfungible_data_token.md
A proposal to standardize on tokens with dynamic data. Data that can be modified during a token's live-time enables novel use-cases for NFTs:
- cryptokitties that can change color.
- intellectual property tokens that encode rights holders.
- tokens that store data to transport them across chains.
=> ERC-1948: Non-fungible Data Token

EIPS/eip-1474.md
=> Add block identifier spec from eip1898 to eip1474

EIPS/eip-1613.md
=> Document 'approval' and 'preRelayedCall' mechanics; switch to CamelCase

EIPS/eip-1186.md, Gemfile, Gemfile.lock
=> Update eip_validator to 0.8.2

EIPS/eip-1355.md
Reject EIP-1355 "Ethash 1a" because it is not useful.
=> Reject EIP-1355 "Ethash 1a"

EIPS/eip-2159.md, EIPS/eip-common_metrics.md
Add a new draft Informational EIP defining names and meanings for common Prometheus metrics.
=> Add information EIP:  Common Prometheus metrics

EIPS/eip-1985.md
- Address @Arachnid's comments about presenting constants and how an address value is limited.
=> EIP-1895: Improvements

EIPS/eip-225.md
This changes the status of the clique EIP to **final**. cc @karalabe 
The reason behind this is that Clique engine is already implemented in the following clients:
- Go Ethereum (and Multi Geth)
- Parity Ethereum
- Pantheon
- Nethermind
- EthereumJS
In addition, this engine powers a couple of production networks, such as 
- Rinkeby
- Görli
- Kotti Classic
Changes to the clique engine would require a new proposal replacing or upgrading 225 at this stage. Therefore, I propose to move the Clique EIP to final.
=> EIP-225: mark Clique engine status as final

EIPS/eip-1884.md
This PR adds an increase of `EXTCODEHASH`to 1884.
=> 1884: also increase EXTCODEHASH

EIPS/eip-1108.md
As requested by @axic at https://ethereum-magicians.org/t/eip-1108-reduce-alt-bn128-precompile-gas-costs/3206/5 .
=> EIP-1108: Add reference to issue 1187

EIPS/eip-1102.md
I think overall this EIP is still too prescriptive in its wording, but I wanted to keep the initial change small to see if there is support for the direction first.
My view on standards is very libertarian: The purpose of standards isn't to tell people how to behave on an individual level, it is to tell people how to behave when they are interfacing with third parties so that communication is possible without first knowing everyone you might want to talk to.  Saying that the "standard language for signage is English" is useful, because it lets people know that if they want to make signs that anyone can read they should do so in English, and if people want to be able to read signs they should learn English.  Saying that "everyone must learn English and speak it in the home" on the other …
=> EIP 1102: Loosens the constraints a bit.

EIPS/eip-1900.md, EIPS/eip-dtype.md
We are proposing a decentralized Type System for Ethereum (`dType`), to introduce data definition (and therefore ABI) consistency. This ERC focuses on defining an on-chain Type Registry and a common interface for creating types, based on `struct`s.
=> EIP-1900 Decentralized Type System for EVM

EIPS/eip-1884.md
This PR
- Moves `SELFBALANCE` from `0x46` to `0x47`, to avoid conflicts with https://eips.ethereum.org/EIPS/eip-1344 which adds `CHAINID` at `0x46`. cc @fubuloubu 
- Addresses some review comments from https://github.com/ethereum/EIPs/pull/2175
=> 1884: move SELFBALANCE op from 0x46 to 0x47

EIPS/eip-1.md, EIPS/eip-1015.md, EIPS/eip-3.md, EIPS/eip-616.md, README.md, _data/statuses.yaml, index.html
It doesn't seem to serve any purpose. It could suggest those EIPs have been properly discussed
and accepted, but are deferred. It could also suggest there's no point discussion them now,
but that doesn't seem to be too different from draft.
=> Remove Deferred from the status list

EIPS/eip-1679.md
=> Updated Accepted and Rejected EIPs from ACD call

EIPS/eip-1344.md
It was ambiguous what the return value was for this opcode, so added that the size is a 256 bit integer.
This size is justified as there have been discussions if setting the value of chain ID from a hash as potential future proposals.
=> EIP-1344: Add datatype to opcode return value

EIPS/eip-1344.md
- One additional reviewer added comment
- No technical updates suggested
Moving to Final, with inclusion into Istanbul determined by EIP-1679, with discussion [here](https://ethereum-magicians.org/t/hardfork-meta-istanbul-discussion/3207).
=> EIP-1344: Move to Final after Last Call Review

EIPS/eip-1577.md
I created my implementation of EIP 1577 for Python [here](https://github.com/filips123/ContentHashPy). I want to link it from EIP to notify developers about other implementations of the content hash in different programming languages.
=> EIP 1577: Add link to Python implementation

EIPS/eip-1679.md
Agenda: https://github.com/ethereum/pm/issues/116
Livestream: link: https://www.youtube.com/watch?v=fJd_xYnYrUU1
=> Change EIPs status based on ACD Call #67

EIPS/eip-1193.md
I suggested the errors defined in the EIP be changed to:
| Status code | Name                         | Description                                                              |
| ----------- | ---------------------------- | ------------------------------------------------------------------------ |
| 4001        | User Rejected Request        | The user rejected the request.                                           |
| 4100        | Unauthorized                 | The requested method and/or account has not been authorized by the user. |
| 4200        | Unsupported Method           | The requested method is not supported by the given Ethereum Provider.    |
In summary, these changes:
- Generalize the meaning of the `4001` error code to `User Rejected Request`
- A single "user rejection" …
=> Simplify EIP 1193 error codes

EIPS/eip-2159.md
Links have all been moved to the bottom as a reference section and inline links removed.
=> Move links to a reference section

EIPS/eip-1884.md
Adding reference for backwards compatibility issue on affected EIP
=> Add reference to affected EIP

EIPS/eip-2015.md
Every other RPC extension is under the Interface category.
@pedrouid please acknowledge this.
=> Change category of EIP-2015 from ERC to Interface

EIPS/eip-2256.md, EIPS/eip-wallet_get_owned_tokens.md
Add ERC for `wallet_getOwnedAssets`
This is a proposal targeting wallet API standardization: a new JSON-RPC method for retrieving a selection of owned assets by an Ethereum address, with the user's permission.
=> Add ERC for wallet_getOwnedAssets

EIPS/eip-1.md
This PR has two parts:
1) attempts to document the current process around Core EIPs a bit better
2) renames `Accepted` to `Ready`
On https://gitter.im/ethereum/EIPs there was a discussion about the `Accepted` state being misleading. Some new names were proposed: Reviewed, Stable, Live.
I think `Ready` is the best way to describe this status. It is ready to be reviewed by the "All Core Devs" and consider it for inclusion in a protocol update.
=> EIP-1: clarify the process around core EIPs

EIPS/eip-152.md
After [feedback from the last AllCoreDevs call](https://github.com/ethereum/EIPs/issues/152#issuecomment-528919091), I've adjusted the EIP to more accurately distinguish between the 64-bit BLAKE2 family of hash functions and functionality specific to BLAKE2b, the 12-round 64-bit BLAKE2 variant.
> The EIP also should include the actual compression function and parameters (SIGMA, IV) – and not leave it as a reference to the RFC.
Note that I wasn't easily able to follow the suggestion to include direct `SIGMA` and `IV` definitions -- as many client implementations might have different definitions due to library and language-specific optimizations, the `SIGMA` and `IV` definitions don't further specify the EIP over the provided test cases.
As there hasn't been much activity on [Gitter from …
=> Generalize EIP-152 to other BLAKE2 variants

EIPS/eip-1459.md
This updates the spec to the final design that we intend
to ship in go-ethereum:
- The 'enr' and 'link' trees are separated so the client can
sync the complete link tree before looking at any ENRs.
- Text encoding of entries is simplified: link entries and URLs
now look the same. ENR entries match the canonical text form of ENRs
defined in EIP-778.
- base64 padding is removed.
=> EIP-1459: update spec to match Go implementation

EIPS/eip-2304.md
=> Add binance chain to EIP2304

EIPS/eip-2309.md
**Original discussion in https://github.com/ethereum/EIPs/issues/2309**
**Future discussion should be done in this PR**
A standardized event emitted when creating/transferring one, or many non-fungible tokens using consecutive token identifiers.
The optional ERC-721 Consecutive Transfer Extension provides a standardized event which could be emitted during the creation/transfer of one, or many non-fungible tokens. This standard does not set the expectation of how you might create/transfer many tokens it is only concerned with the event emitted after the creation, or transfer of ownership of these tokens. This extension assumes that token identifiers are in consecutive order.
This extension is provides even more scalibility of the ERC-721 specification. It is possible to create, transfer, …
=> EIP-2309: ERC-721 Consecutive Transfer Extension

EIPS/eip-2124.md
This PR adds special casing for 2 fork scenarios that we didn't differentiate in the original fork id spec, but scenarios that we do have enough information to handle. These were described by @ritzdorf in ethereum/EIPs#2125 (comment) and a solution sketched in ethereum/EIPs#2125 (comment).
This PR doesn't change the format or spec of the fork id, just makes validation a tad smarter.
=> EIP 2124: add chain divergence special cases to the verifier

EIPS/eip-1679.md
* Remove all but included EIPs
* List activation blocks
=> EIP-1679: Update Istanbul Meta EIP

EIPS/eip-225.md
The code `{{signer: "A"}}` gets hidden on the website. Liquid template system interprets the double curly braces as a template expression.
This PR changes indentation to fix the display problem.
[Website](https://eips.ethereum.org/EIPS/eip-225): 
Raw code:
=> Fix: double curly braces causes syntax error on Liquid template system

EIPS/eip-2330.md
Initial draft submission, cross-posting on ethereum-magicians
=> Added EIP-2330: EXTSLOAD

EIPS/eip-1716.md
I see that the EIP is finalized for a while, but the block number for Rinkeby is plain wrong. Block 9,999,999 would be created in [two years from now](https://rinkeby.etherscan.io/block/countdown/9999999).
For historical reasons, we should fix it to the block number 4,321,234, set by [geth 1.8.24](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.24).
@5chdn @MariusVanDerWijden @karalabe
=> Updates Petersburg block number for Rinkeby

EIPS/eip-2327.md, EIPS/eip-draft-begindata.md
Waiting for EIP number to be assigned. Will post link to discussions after having opened this PR.
=> Draft EIP: BEGINDATA opcode

EIPS/eip-1108.md
Since the Istanbul meta-EIP has EIP-1108 listed for the hardfork and the implementation tracker lists everyone as having merged, this EIP seems reasonable to move to Final status.
=> Update EIP-1108 to reflect Final status

EIPS/eip-1191.md
Fixes indentation mistake [discovered](https://github.com/ethereum/EIPs/issues/1121#issuecomment-550080361) by @MicahZoltu
=> Add newline for Jekyll to render correct HTML indentation

EIPS/eip-2019.md, EIPS/eip-2384.md
Initial submission of EIP-2019 which would delay the difficulty bomb.
=> EIP-2384 - Difficulty Bomb Delay

.bundle/config, EIPS/eip-1.md, EIPS/eip-1155.md, EIPS/eip-1261.md, EIPS/eip-1319.md, EIPS/eip-1470.md, EIPS/eip-1761.md, EIPS/eip-2135.md, EIPS/eip-2255.md, EIPS/eip-233.md, PULL_REQUEST_TEMPLATE.md, README.md
Currently GitHub is misspelled on some pages. This fixes it.
=> Fix spelling of GitHub [R4R]

EIPS/eip-1921.md, EIPS/eip-dtype-functions.md
In the context of dType, the Decentralized Type System described in [EIP-1900](https://eips.ethereum.org/EIPS/eip-1900), we are proposing to add support for registering functions (with a preference for `pure` and `view`) in the dType Registry.
=> dType Functions Extension - Decentralized Type System for EVM

EIPS/eip-1052.md
This previously proposed by https://github.com/ethereum/EIPs/pull/2144/files#r296935881, but that fork cannot be updated by maintainers.
It was approved by @Arachnid and @chfast.
Closes #2144.
=> Clarify that empty accounts also return 0 in EIP-1052

EIPS/eip-1996.md
An extension to the ERC-20 standard token that allows tokens to be put on hold. This guarantees a future transfer and makes the held tokens unavailable for transfer in the mean time. Holds are similar to escrows in that are firm and lead to final settlement.
A hold specifies a payer, a payee, a maximum amount, a notary and an expiration time. When the hold is created, the specified token balance from the payer is put on hold. A held balance cannot be transferred until the hold is either executed or released. The hold can only be executed by the notary, which triggers the transfer of the tokens from the payer to the payee. If a hold is released, either by the notary at any time, or by anyone after the expiration, no transfer is carried out and the amount is available again for the payer.
=> EIP-1996: Holdable token

EIPS/eip-2019.md, EIPS/fundable-token-draft.md
An extension to the ERC-20 standard token that allows Token wallet owners to request a wallet to be funded, by calling the smart contract and attaching a fund instruction string.
Token wallet owners (or approved addresses) can order tokenization requests through  blockchain. This is done by calling the ```orderFund``` or ```orderFundFrom``` methods, which initiate the workflow for the token contract operator to either honor or reject the fund request. In this case, fund instructions are provided when submitting the request, which are used by the operator to determine the source of the funds to be debited in order to do fund the token wallet (through minting).
=> EIP-2019: Fundable Token

EIPS/eip-2009.md, EIPS/eip-draft_compliance_service.md
This EIP proposes a service for decentralized compliance checks for regulated tokens. 
A regulated token needs to comply with several legal requirements, especially KYC and AML. If the necessary checks have to be made off-chain the token transfer becomes centralized. Further the transfer in this case takes longer to complete as it can not be done in one transaction, but requires a second confirmation step. The goal of this proposal is to make this second step unnecessary by providing a service for compliance checks.
=> EIP-2009: Compliance Service

EIPS/eip-2021.md, EIPS/payoutable-token-draft.md
An extension to the ERC-20 standard token that allows Token wallet owners to request payout from their wallet, by calling the smart contract and attaching a payout instruction string.
Token wallet owners (or approved addresses) can order payout requests through  blockchain. This is done by calling the ```orderPayoutFrom``` or ```orderPayoutFrom``` methods, which initiate the workflow for the token contract operator to either honor or reject the payout request. In this case, payout instructions are provided when submitting the request, which are used by the operator to determine the destination of the funds.
=> EIP-2021: Payoutable Token

EIPS/eip-1767.md
Suppose I run `block { account(address: "0x...")  { balance, code, address }` with a valid but unknown address.  I find it clearer to get back null for the account than some default values for each field.
=> Make the return value of `account()` optional

EIPS/eip-1193.md
This PR edits EIP-1193 in two ways:
* Updates it's `discussion-to` link
* Adds a References section with links to the previous discussion channels. 
Two Discord servers were used to discuss this EIP, but I didn't add their links in the Reference section as they are invitation links that may stop working in the future.
=> Update discussion-to in EIP-1193 and add References section

EIPS/eip-634.md
If we have twitter mentioned here -so we should also mention peepeth which is more native to Ethereum
paging @ricmoo 
also wondering as the implementations section is empty yet if I should do a PR to add https://github.com/komputing/KEthereum/tree/master/ens / https://github.com/komputing/KEthereum/tree/master/erc634 
Or should this section just be about smart-contract implementations of this EIP?
=> EIP-634: Add peepeth and made it more DRY

EIPS/eip-1155.md
Proposing this change so that this URL will work:
> https://eips.ethereum.org/EIPS/eip-1155#backwards-compatability
Because I want to reference it
=> EIP-1155: Rename backwards compatibility section to "Backwards compatibility"

EIPS/eip-2384.md
Move #2384 to Final from Last Call as three core clients have already implemented. Note: this would skip accepted but that is as a matter of formality due to the oversight in progressing the EIP prior to client teams implementing.
=> Update EIP-2384 to Final Status

EIPS/eip-1193.md
Updates to EIP 1193:
* Improve opening summary.
* Promote use of eth_chainId and note networkChanged as deprecated.
* Clarify web3.js provider backwards compatibility.
=> Updates to 1193

EIPS/eip-918.md
Added decimals to base interface and removed abstracted lifecycle methods
=> Added decimals to base interface

EIPS/eip-1077.md
Updates interface to allow any type of "execution", abstracting only gas relay mechanism here (not execution or account contracts stuff).
A standard interface for gas abstraction in top of smart contracts. 
Allows users to offer [EIP-20] token for paying the gas used in a call. 
A main barrier for adoption of DApps is the requirement of multiple tokens for executing in chain actions. Allowing users to sign messages to show intent of execution, but allowing a third party relayer to execute them can circumvent this problem, while ETH will always be required for ethereum transactions, it's possible for smart contract to take [EIP-191] signatures and forward a payment incentive to an untrusted party with ETH for executing the transaction. 
Standardizing a common format for them, as well as a …
=> ERC-1077 (gas relay interface) update

EIPS/eip-1962.md
This PR updates the EIP1962 text to the current state. Through the development process and discussion with other Ethereum developers there were changes to binary interfaces, structuring of operations (not it's 10 separate precompile addresses as requested by Core Devs) and explanation of gas schedule.
=> Update EIP1962 to the current state

EIPS/eip-2315.md
**Specification**
* `JUMPSUB`  Jumps to the address on top of the stack. This must be a `JUMPDEST`.
* `RETSUB`  Returns to the most recently executed `JUMPSUB` instruction.
**Rationale**
This is the smallest possible change that provides native subroutines without breaking backwards compatibility...
=> subroutines

EIPS/eip-1702.md
Links from specs.that.world are now moved to specs.corepaper.org. This commit updates those links.
=> EIP-1702: Update some links

EIPS/eip-777.md
Changed `ERC777TokensSender` to `ERC777TokensRecipient` in `ERC777TokensRecipient And The tokensReceived Hook` section.
=> EIP-777: typo fix

EIPS/eip-1753.md
Parameter names to be line with naming convention on EIP-1812.  By aligning with this EIP, there could be a use case for inheriting 1812 stregthening both EIPs. https://eips.ethereum.org/EIPS/eip-1812
=> Updated parameter names

EIPS/eip-3.md
Martin Swende gave is OK to move EIP 3 to Abandoned status.
=> Moving EIP 3 to Abandoned status

EIPS/eip-2515.md, EIPS/eip-tbd.md
The difficulty Freeze is an alternative to the Difficulty Bomb that is implemented within the protocols difficulty adjustment algorithm. The Difficulty Freeze begins at a certain block height, determined in advance, and freezes the difficulty. This does not stop the chain, but it incentivizes devs to upgrade at a regular cadence and requires any chain split to address the difficulty freeze.
=> Replace the Difficulty Bomb with a Difficulty Freeze

EIPS/eip-1559.md
I've updated the EIP1559 doc to reflect the implementation found [here](https://github.com/vulcanize/go-ethereum-EIP1559/tree/rebase) or [here](https://github.com/vulcanize/go-ethereum/tree/eip1559_rebase) if you want to see the tests passing. The PR for the implementation is now open [here](https://github.com/ethereum/go-ethereum/pull/20618).
The magicians thread for this can be found [here](https://ethereum-magicians.org/t/eip-1559-go-etheruem-implementation/3918). Please let me know if there is any additional feedback or updates to incorporate!
Thanks!
=> Eip1559 updates

EIPS/eip-1193.md
Fix typo; putting `Error` in backticks for consistency.
=> EIPs: Fix typo on eip-1193.md

EIPS/eip-2542.md
During our work on the Gas Station Network we have encountered a problem with the way such concepts as gas limit and gas refund are somewhat hidden from smart contracts. With the current EVM, the core GSN smart contract (RelayHub) is not able to precisely track the gas usage by a transaction due to these limitations.
Exposing such parameters as transaction gas limit, current execution frame gas limit, and current refund counter is an extremely simple and useful improvement to the EVM.
=> EIP 2542 - add TXGASLIMIT, CALLGASLIMIT opcodes

EIPS/eip-2315.md
This PR changes 2315. I've had some discussions with @gcolvin about this, and he asked me to take co-authorship over 2315 and try to get the spec in order. 
This PR changes a couple of things: 
- More strict definition of the opcodes, 
- Spec-level introduction of `return_stack`, 
- More examples, 
- Removal of that `end-of-stack` prefilled item on the `return_stack`
=> eip-2315: updated spec and examples

EIPS/eip-1193.md
Link to file: https://github.com/rekmarks/EIPs/blob/rekmarks-1193-update/EIPS/eip-1193.md
Makes the following updates to EIP 1193, in light of recent discussions in #2319:
- Deprecates `send` and `sendAsync`
- Providers may continue to support these methods
- Specifies a new method, `request`, with the same Promise signature as the `send` currently at `ethereum/EIPs#master`
- Per @MicahZoltu's [suggestion](https://github.com/ethereum/EIPs/issues/2319#issuecomment-591194700)
- Changes the interface of the `notification` event, such that a generalized object is emitted
- This was done to support other notifications than `eth_subscription`
- Makes the spec transport- and RPC protocol-agnostic, per the contributions of @ryanio
- Adds the `message` event for generalized messaging, and …
=> Update EIP 1193

EIPS/eip-1193.md
File: https://github.com/rekmarks/EIPs/blob/1193-open/EIPS/eip-1193.md
- Adds the `disconnect` event, intended to:
- supersede the `close` event
- make it clear that it's the counterpart of the `connect` event
- Deprecates the `close` event
The above follows discussions with @ryanio 
In addition:
- Adds the following Provider errors:
- `4900: Not Connected`
- `4901: Chain Not Connected`
- Adds the section `Connectivity` for defining "connected" and "disconnected"
This allows consumers to tell whether their requests are failing because the Provider is disconnected.
=> 1193: `disconnect` event, connectivity errors

EIPS/eip-1193.md
File: https://github.com/rekmarks/EIPs/blob/1193-availability/EIPS/eip-1193.md
For the purpose of this PR, let's define the problem of how to expose the Provider API as "availability" or "the availability problem."
Per [this comment](https://github.com/ethereum/EIPs/issues/2319#issuecomment-544795458) by @alcuadrado, one of the concerns from the 1193 meeting at Devcon 5 was:
>1. EIP-1193 began as a spec on how to expose a provider in a dapp browser, but mutated into specifying its interface. It still depends on EIPs related to browser-specific stuff.
>2. The way a provider is exposed (i.e. `window.ethereum`) only supports a single provider. This is in conflict with users installing multiple wallet extensions, and may be problematic with a multi-chain future.
Meanwhile, the proposed …
=> 1193: Make spec availability-agnostic

EIPS/eip-2315.md
Ref: 
https://github.com/openethereum/openethereum/pull/11612#discussion_r404788297
Geth had the wrong opcodes defined, so the provided example bytecode/traces were wrong. Fixed with this PR
=> EIP-2315: fix opcodes in examples

EIPS/eip-1193.md
File: https://github.com/rekmarks/EIPs/blob/1193-request-arg/EIPS/eip-1193.md
New signature for the `request` method:
```typescript
interface RequestArguments {
method: string;
params?: Array<any> | { [key: string]: any };
[key: string]: any;
}
Provider.request(args: RequestArguments): Promise<unknown>;
```
Example call:
```javascript
Provider.request({ method: 'eth_accounts' })
.then((accounts) => console.log(accounts))
.catch((error) => console.error(error));
```
See document for further details.
This is motivated by discussions with @frozeman and others, and enables a future for the Provider interface generally and the `request` method specifically where any of the following holds:
- Multiple chains are served by a single Provider at once
- Multiple protocols are served by a single …
=> 1193: single object argument for `request` method

EIPS/eip-2315.md
This update to 2315 contains 
- One more example testcase which shows the behaviour when the `RETURNSUB` destination is off the end of the code. 
- A clarification about the implementation of the returnstack.
=> EIP-2315: updates

EIPS/eip-2378.md
Adds EIP-2315 and EIP-2537 both of which are EFI and Accepted for Berlin.
=> Add EFI EIPs

EIPS/eip-2378.md
Change name of EIP-2537 to its actual name, "Precompile for BLS12-381 curve operations". Source: https://github.com/ethereum/EIPs/pull/2537/files
=> Fix misnamed EIP

EIPS/eip-1706.md
While 1706 was never 'final' on its own, I think keeping it as 'draft', or marking it 'abandoned' or 'rejected' creates a false perception that the logic specified in it never made it to the EVM. 
EIP-2200 explicitly states it includes all provisions of this EIP word-by-word.
=> Abandon EIP-1706

EIPS/eip-1193.md
Moves EIP 1193 to Last Call, with the review period ending after 6 weeks on 2020-06-04 (June 4, 2020).
Review period format follows the convention of the majority of EIPs in Last Call, e.g. https://eips.ethereum.org/EIPS/eip-875
=> 1193: Move to Last Call

EIPS/eip-1363.md
```
eip: 1363
title: ERC-1363 Payable Token
author: Vittorio Minacori (@vittominacori)
discussions-to: https://github.com/ethereum/eips/issues/1363
status: Final
type: Standards Track
category: ERC
created: 2020-01-30
requires: 20, 165
```
Description of a **Payable Token** compatible with the ERC-20 definition. 
Also description of a Token **Receiver** and/or **Spender** that accepts Payable Token payments.
Closes #1363 
The following describes standard functions a token contract and contracts working with specified token can implement to make a Token Payable.
This proposal allows to implement an ERC-20 compatible token that can be used for payments.
It defines `transferAndCall` and `transferFromAndCall` functions that will call an `onTransferReceived` on a `ERC1363Receiver` contract.
It …
=> ERC-1363 Payable Token

EIPS/eip-1193.md
Removes `web3` from examples in 1193.
@ryanio 
#2319
=> 1193: Remove web3 from example

EIPS/eip-1193.md
File: https://github.com/rekmarks/EIPs/blob/1193-remove-dependencies/EIPS/eip-1193.md
Removes the following EIPs from the list of required EIPs, and adds them to references at the end of the document:
- 1102
- 1474
- 1767
#2319
=> 1193: Remove unnecessary EIP dependencies

EIPS/eip-695.md
This addresses https://ethereum-magicians.org/t/eip-695-create-eth-chainid-method-for-json-rpc/1845/19
We clarify that chain ID returned should always be corresponding to the head block. This is also how OpenEthereum currently implements it. The rationale is that by doing this we ensure caller can always use the retrieved information to sign transactions on top of the head.
=> EIP-695: clarify what happens if a chain initially does not have chain ID or chain ID has changed

EIPS/eip-2457.md, EIPS/eip-2458.md
EIP-2458: Add updates and updated-by EIP Header Options for active EIPs
Type: Informational
Status: Draft
Adds EIP header options for EIPs that are, or relate to, active EIPs. Proposes change to EIP update process for EIPs in `active` status. 
#2453, https://ethereum-magicians.org/t/eip-2458-add-updates-and-updated-by-eip-header-options-for-active-eips/4113
=> EIP-2458: Updates, updated-by header

EIPS/eip-1193.md
[Link to rendered file with updates.](https://github.com/rekmarks/EIPs/blob/1193-clarify-disconnect-errors/EIPS/eip-1193.md)
The errors related to connectivity were somewhat underspecified, and oddly named. Their names and descriptions have been updated, and a non-normative comment has been added.
=> Rename and clarify disconnection errors

EIPS/eip-695.md
This PR specifies that `eth_chainId` should "return a suitable error" if the latest head block "has no chain id".
=> ERC-695: Specify behavior in absence of chainId

EIPS/eip-695.md
[Link to file in feature branch.](https://github.com/rekmarks/EIPs/blob/695-security-considerations/EIPS/eip-695.md)
- Adds `Security Considerations` section as required by `EIP 1`
- Adds @rekmarks as author, per the recommendation of @sorpaas
- Minor cleanup for consistency
cc: @axic
=> ERC-695: Add security considerations; rekmarks as author

EIPS/eip-2315.md
As proposed by Pawel, Andrei and Alex @chfast @gumb0 @axic 
> Change the specification in a way that `BEGINSUB` can only be reached via `JUMPSUB` . > 
> Specifically:
>
> 1. Execution of `BEGINSUB` causes exception (OOG: all gas consumed) and terminates execution. This way `BEGINSUB` behaves like `INVALID` (aka `0xfe` ) and it should never be executed in a well-formed EVM program.
> 2. `JUMPSUB` sets the `pc` to `location + 1` ( *As opposed to `location` in the current spec* ).
> 3. In the edge case when `BEGINSUB` is the last instruction in code and this subroutine is jumped-to, the implementations should execute `STOP` . This is consistent with the other similar case of returning from a subroutine jumped-to from the `JUMPSUB` being the last instruction in code.
=> enter only via jumpsub

EIPS/eip-1057.md
Add tables for clients, pools and exchanges to track status.
=> readiness tables

EIPS/eip-2384.md
After a Last Call status is moved to Final, the **Review Period End <date>** column can be removed
Fixes #2447.
=> Remove review period after final EIP-2384

EIPS/eip-2387.md
After a Last Call status is moved to Final, the **Review Period End <date>** column can be removed
Fixes #2449.
=> Remove review period after final EIP-2387

EIPS/eip-2315.md
This PR contains the updated testcases with the recent changes. Also some clarifications and I re-added cost of `BEGINSUB`. All opcodes should have a defined cost, IMO.
=> EIP-2315: updated testcases + clarifications

EIPS/eip-2315.md
This  PR incorporates the proposed fix to prevent the EVM from stepping (as opposed to jumping) to BEGINSUB -- JUMPSUB transfers control to the instruction after BEGINSUB; BEGINSUB itself aborts.   This PR does not prevent "jumping into subroutines."
EIP-2315 “Simple Subroutines for the EVM” - AnalysisPawel Bylica @chfast, Andrei Maiboroda @gumb0, and Alex Beregszaszi @axic.
https://ethereum-magicians.org/t/eip-2315-simple-subroutines-for-the-evm-analysis/4229
=> BEGINSUB as unexecutable marker

EIPS/eip-2315.md
another try at getting this past travis
=> struggling with travis

EIPS/eip-2315.md
This PR 
- Adds back a testcase that went missing (walk into subroutine) in https://github.com/ethereum/EIPs/pull/2662
- Fixes another testcase where `BEGINSUB` was present, 
- Changes cost of `JUMPSUB` to `8`. 
I'm marking this as draft since otherwise the trigger-happy autobot will merge it. Can I please get a thumb up from: 
@gcolvin , @ordian (or @sorpaas , or @vorot93 ?), @makt 
Just want to make sure everyone is on the same page here...
=> EIP-2315: update jumpsub gascost and add back testcases

EIPS/eip-695.md
https://github.com/ethereum/EIPs/pull/2356#issuecomment-563025007
=> Mark EIP-695 as Final

EIPS/eip-1559.md
This EIP previously changed the mechanism for calculating block size from a miner-voted mechanism to a hard-coded mechanism.  This change is not necessary for the implementation of EIP1559, so this PR removes it and updates EIP 1559 to retain miner voted block sizing.
Riders are very unhealthy for governance.  While in this case I suspect that the rider may not have been intentionally underhanded, I think we (EIP authors/editors/core devs) need to be very cautious about allowing riders to become a norm.  I have seen them included in more and more EIPs lately, especially controversial topics like miner issuance reductions.
I do not think it is unreasonable to change from miner voted block size to core dev defined block sizes, but that should occur as its own EIP and debated on its own …
=> Removes block size and transaction size riders from EIP 1559.

EIPS/eip-2537.md
Fixes the following codespell failure, preventing CI from passing on all branches based on current `master`:
```
EIPS/eip-2537.md:243: operaiton ==> operation
```
=> 2537: Fix failing codespell check

EIPS/eip-1193.md
Link to file: https://github.com/rekmarks/EIPs/blob/1193-update-interfaces/EIPS/eip-1193.md
- Remove index signatures from interfaces
- i.e. no more `[key: string]: unknown`; the ability to add properties is implied
- `RequestArguments`
- `params?: unknown` -> `params?: unknown[] | object`
- Explicitly define relationship between `RequestArguments` fields and RPC method names and parameters
- You could say that relationship was heavily implied, but 🤷 
- Remove redundant **MAY** statements.
- Various minor fixups and clarifications
- Clarify author intentions in certain places
After review, here's where I currently stand on the signature of `request`.
- `request` takes a single, options bag argument, to make it as extensible as possible. We are extremely unlikely to have to revisit it ever …
=> Update interfaces, clarify type intentions

EIPS/eip-1193.md
Link to file: https://github.com/rekmarks/EIPs/blob/1193-final-draft/EIPS/eip-1193.md
- Normative
- Update `Events` specification
- Change recommendation to extend `EventEmitter` from normative to non-normative
- In recognition that the `EventEmitter` API, while [stable](https://nodejs.org/api/documentation.html#documentation_stability_index) is growing over time
- Remove leftover index type on one interface
- This should have already been done
- Remove all normative references to "Client"
- Non-normative
- Trim "Summary" section
- Trim `message` event "Subscription" subsection in API documentation
- Remove all deprecated methods and events from the API documentation
- They were only specified in the API documentation
- Remove "Availability" section from specification (non-normative …
=> 1193: Final edits in response to feedback

EIPS/eip-1193.md
File: https://github.com/rekmarks/EIPs/blob/1193-sections/EIPS/eip-1193.md
- Reorganize and add missing sections per [EIP-1](https://eips.ethereum.org/EIPS/eip-1#what-belongs-in-a-successful-eip)
- Normative change: don't require Providers to implement the `emit` method
- For the purposes of the spec, it's an implementation detail
- Various minor cleanup/fixups
=> 1193: Reorganize and add missing sections

EIPS/eip-601.md
No discussion has happened for a while and the longer we wait, the more entrenched current non-standard paths become.
=> Moves EIP 601 to Last Call.

EIPS/eip-155.md
As someone implementing stuff related to signing in this space I have had to come back and read this EIP many times to remind myself how to properly sign/recover a transaction post EIP-155.  Each time, I read this EIP and am left confused about what I'm actually supposed to do when signing.  After once again digging to figure out what I'm supposed to do I decided to edit this EIP to hopefully prevent future developers (including myself) from running into the same frustration.
This change is non-normative and only attempts to improve clarity of the process.  If a normative change was made, this means my understanding is flawed and corrections should be made before this PR is merged.
The major change is to include a section for how to generate a valid post-155 signature.  The original text …
=> Adds clarifying text to the EIP-155 specification.

EIPS/eip-55.md
Ethereum doesn't use `sha3` anywhere, and later in the document it explicitly states that this is actually `keccak256`.  To avoid people implementing SHA3 only to find out it doesn't work (like I did), I'm fixing this to be `keccak256`.
=> Changes reference to `sha3` to `keccak256`.

EIPS/eip-600.md
Has received no meaningful discussion for some time, and the longer we put this off the more entrenched the current non-standard derivation paths become.
=> Moving EIP-600 to last call.

EIPS/eip-2700.md, EIPS/eip-TBD.md
A standard mechanism for JavaScript Ethereum Providers to notify clients about chain state changes when both are able to interface with each other via a shared JavaScript object.
=> Creates EIP-2700: JavaScript Provider Event Emitter

EIPS/eip-2718.md
* Changes legacy transactions to no longer be supported.
* Explicitly calls out that these changes are for devp2p (which implies they don't necessarily apply to JSON-RPC).
* Changes second item to be opaque bytes rather than an RLP array.
* Adds some rationale from discussions around alternative options and the standard defined prior to this PR.
=> Removes support for legacy transactions.

EIPS/eip-2333.md
* It was unclear whether the indexing was inclusive or exclusive of the bounds
* That BIP39 should be used to derive seeds
* `derive_master_SK`, and `HKDF_mod_r` now require a minimum input length of 32 bytes to line up with the definition in the BLS specs
=> Eip2333 clarifications

EIPS/eip-2733.md, EIPS/eip-tx-package.md
Rendered: https://github.com/lightclient/EIPs/blob/transaction-package/EIPS/eip-2733.md
=> Initial draft of transaction package EIP

EIPS/eip-2335.md, EIPS/eip-2733.md
* Unicode passwords are now explicitly supported via NFKD & UTF-8
* Descriptions have been added to help distinguish keystores. (Tackles the same thing as #2671, but under a different name to help make clear that descriptions are not necessarily unique)
=> EIP2335 Unicode Password support & Descriptions

EIPS/eip-1474.md
The note doesn't make sense because it isn't possible to get logs for block/pending filters.
=> Remove note about block/pending filters for eth_getLogs

EIPS/eip-2515.md
Current output from `eip-validator`:
```console
Warning: EIPS/eip-2515.md        undefined method `requires (*optional)=' for #<EipValidator::Validator:0x0000557ce931cf48>
```
Additionally, it appears that the assigned EIP is incorrect as #2512 is unrelated.
=> Fix misformatted fields in EIP-2515

EIPS/eip-2565.md
Current output from `eip-validator`:
```console
Warning: EIPS/eip-2565.md        undefined method `Requires=' for #<EipValidator::Validator:0x00005652718d22b8>
```
=> Fix misformatted requires field for EIP-2565

EIPS/eip-2615.md
Current output of `eip_validator`:
```console
Warning: EIPS/eip-2615.md        undefined method `requires (*optional)=' for #<EipValidator::Validator:0x000055916209fc10>
```
=> Fix misformatted requires field on EIP-2615

EIPS/eip-1271.md
This changes the proposal to use a `bytes32` hash for the signature to prevent the requirement of specific implementation checks within this signature verification functions.
Those can be either done off-chain, or in other smart contract functions, and funnel those to this function to verify the signature.
- If matching on email address, the email …
=> Change ERC1271 to bytes32 hash

EIPS/eip-2711.md, EIPS/eip-2718.md
Current output of `.travis-ci.sh`:
```console
Warning: EIPS/eip-2711.md        undefined method `requires (*optional)=' for #<EipValidator::Validator:0x000055bc8db14370>
Warning: EIPS/eip-2718.md        undefined method `requires (*optional)=' for #<EipValidator::Validator:0x000055bc8dab6860>
```
=> Remove misformatted requires field on EIPs 2711 & 2718

EIPS/eip-2696.md
Non-normative change to final EIP.  This EIP was extracted from 1193 and @remarks indicated that adding their name as author was acceptable.
=> 2696: Adds an author

EIPS/eip-1193.md
Added `readonly` keyword to all typescript interface definitions.
I decided to avoid `readonly` on the `ProviderRpcError` because it extends `Error` which does not have its properties as readonly. We can assume that this is a really bad Javascript standard that we have to follow. In addition `message` property was removed from the interface because it is defined in original `Error` interface:  https://github.com/microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L972
https://github.com/ethereum/EIPs/issues/2319#issuecomment-654343547
=> [EIP-1193] Strict readonly typing for typescript definitions

EIPS/eip-1155.md
EIP-1155 is final but according to the eip process as defined in EIP-1 a final draft should be updated to correct errata.
EIP-1155 mentions EIP-1538 in the Upgrades section. But EIP-1538 has been abandoned and replaced with EIP-2535. This pull request replaces the mention of EIP-1538 with EIP-2535.
I am the author of both EIP-1538 and EIP-2535 and I have no problem with this.
=> Update eip-1155 errata.

eip-2801.md, eip-2803.md
Support 'rich transactions' by allowing transactions from externally owned accounts to execute bytecode directly.
=> Creates EIP-2803: Rich Transactions

_layouts/eip.html
Extracted from PR at https://github.com/ethereum/EIPs/pull/2738
=> Add JSON-LD for EIPS

_layouts/eip.html
Test case:
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Feips.ethereum.org%2FEIPS%2Feip-721
https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=url&id=yOTWiA3q_VkILqYA5dvtFQ
---
Originally introduced here: https://github.com/ethereum/EIPs/pull/2796
I tested it on production and some pages are not getting parsed properly by Google because of invalid tags. This fixes it.
=> Remove fancy formatting in metadata

_layouts/eip.html
This fills in extra JSON-LD fields, addressing Google errors raised here:
https://github.com/ethereum/EIPs/pull/2796#issuecomment-661912226
---
All this information is duplicative to other properties in the JSON-LD already. And I don't see that these fields are *required* by Schema.org. But the Google validator flagged them, so perhaps it is worth merging this.
=> Fill in extra JSON-LD fields

EIPS/eip-2159.md
Add a note to EIP-2159 about the potential for existing metrics with the same names but different meanings and move it to final.
=> Mark EIP-2159 Common Metrics as final

EIPS/eip-2831.md
=> EIP-2831 Transaction Replacement Message Type

_layouts/eip.html
For anybody that took the time to publish an EIP, and then well-known authors are citing your work as "EIP-xxx. The Ethereum Editors. 2017.," this PR is for you!
This PR provides a recommended citation text for each EIP. It is based on the IEEE citation format.
Also, this includes full data for the semantic web for scrapers. (The *original* Web 3.0, ahem.)
And all conformances are documented to authoritative sources.
Enjoy!
=> Preferred citation format

EIPS/eip-2786.md
cc: @MicahZoltu 
This is a draft PR with some suggested changes.
- Lint using `prettier` (added blank lines after headings)
- Remove comment under `Specification` heading
- Change `connect` event parameters from `('connected', { chainId })` to `({ chainId })`
- Since the event is named `connect`, I don't think the listeners need to be called with the string `connected`. `connect` and `disconnect` are also already in production per 1193, which specifies the single parameter as `{ chainId }`
- Add examples appendix
- Examples only include `connect` for now, with `disconnect` to be added in a follow-up PR
=> 2786: Cleanup, edit 'connect' params, add examples

EIPS/eip-1559.md
It clarifies the meaning of the terms :)
Discussion log:
=> Rename tx.gas -> tx.gasLimit

EIPS/eip-1679.md
The HTML generator is having trouble with the double colon in the title line of EIP-1679. I removed the quotes when adding the new validator, and for some reason the HTML generator raised it as a warning rather than an error. I've logged [this issue](https://github.com/lightclient/eipv/issues/6) with `eipv`, but we should go ahead and fix this ASAP.
=> Fix eip-1679 rendering

EIPS/eip-2876.md
This ERC defines a simple contract interface for managing deposits. It also defines a new address format that encodes the extra data passed into the interface's main deposit function.
=> Add ERC for deposit address and contract interface

EIPS/eip-2612.md, EIPS/eip-X.md
An ERC for the `permit` token extension, as popularized by the Dai ERC20. Will update eip number and `discussions-to` once I find out which PR this ends up being
=> ERC for `permit`: 712-signed token approvals

_includes/head.html
Title before: `EIP 1: EIP Purpose and Guidelines`
Title after: `EIP-1: EIP Purpose and Guidelines`
Reflects the style guide in EIP-1:
> When referring to an EIP by number, it should be written in the hyphenated form EIP-X where X is the EIP’s assigned number.
=> Update html title to be EIP-N

EIPS/eip-2537.md
It's very useful to have it, because noble is the only library that has all possible optimizations of final exponentiation used for pairings. Go and Rust codes don't have all of 'em. Also, it's the only JS implementation. 
https://github.com/paulmillr/noble-bls12-381
=> Update eip2537: Add link to noble library.

EIPS/eip-2926.md, EIPS/eip-code-merkleization.md
This EIP specifies a chunk-based approach to code merkleization with the goal of reducing block witness size in a stateless/partial-stateless ethereum.
=> Chunk-Based Code Merkleization

EIPS/eip-2935.md
Store historical block hashes in a contract, and modify the `BLOCKHASH (0x40)` opcode to read this contract.
=> Save historical block hashes in state

_includes/eiptable.html, _layouts/eip.html
Fixes #1147.
Before:
After:
---
And changes the EIP page render as well, though that commit can be removed.
Before:
After:
=> Include last call review-end-date in the rendered summary

.travis-ci.sh
Occasionally, people accidentally create EIP files in the root dir. This can be missed by editors very easily. This PR updates the CI script to check if any files in the root directory match the pattern `eip-*`. This should help reduce the number of accidental merges of EIP in the wrong location.
=> Check root for eip files

EIPS/eip-1123.md
=> Deprecate ERC 1123

EIPS/eip-2718.md
Removes RLP from the envelope, instead preferring single byte type prefix.
Changes type 0 transactions to type 6 transactions.
Changes encoding of type 6 transactions to LEB128.
=> Removes RLP.

EIPS/eip-695.md
EIP-695 still listed EIP-1474 as a dependency when it was finalized. This was an oversight on the part of the authors. 695 never required 1474. Rather, 1474 could be said to require 695. I'm author of both, and 1474 is still in draft.
Apologies to @axic and @Arachnid for missing this.
=> 695: Errata: remove EIP-1474 from dependencies

EIPS/eip-1319.md
Added the specification for ethPM uris. They've been an effective solution for handling packages so far - and are already implemented in the `ethpm-cli` and `Brownie`, and are also outlined in the [documentation](https://docs.ethpm.com/uris#registry-uris).
=> Update username in EIP-1319

EIPS/eip-2937.md
Add a `SET_INDESTRUCTIBLE` opcode that prevents the contract from calling `SELFDESTRUCT`.
=> SET_INDESTRUCTIBLE opcode

EIPS/eip-2718.md
This change removes all of the stuff not explicitly related to the new envelope.  The removed material will likely show up in future EIPs.
=> 2718: Cuts out everything except new transaction type.

EIPS/eip-2390.md, EIPS/eip-geoens.md
=> GeoENS pull request - initial revision

EIPS/eip-2970.md
Add a `IS_STATIC (0x4A)` opcode that pushes `1` if the current context is static (ie. the execution is in a `STATICCALL` or a descendant thereof, so state-changing operations are not possible), and `0` if it is not.
=> Add IS_STATIC opcode

EIPS/eip-2938.md
Account abstraction (AA) allows a contract to be the top-level account that pays fees and starts transaction execution.
=> Account abstraction EIP

EIPS/eip-1363.md
=> ERC-1363: Move to Last Call

EIPS/eip-2976.md
Adds support for transmission of typed transactions over devp2p.
=> 2976: eth/##: Typed Transactions over Gossip

EIPS/eip-2929.md
This PR clarifies the behaviours about subscope revertals in 2929
PTAL @vbuterin
=> EIP-2929: clarifications about scope revertals

EIPS/eip-2929.md
Contains a few clarifications
- Request from @shamatar  to be more clear in the abstract that some ops become cheaper, 
- Clarification (maybe unnecessary), due to an error that was present in geth, found by @shemnon  
- Finding by @shemnon that geth incorrectly had not updated a composite variable
=> EIP-2929: clarifications

.travis.yml
There was a breakage that caused eipv to fail to compile. The cause was that Cargo will happily replace a package dependency with the latest beta, unless specified differently. I've fixed the code to use beta 2 and updated the dependency requirement to used *exactly` beta 2. See the `eipv` PR here: https://github.com/lightclient/eipv/pull/24
=> Bump eipv to 0.0.6

EIPS/eip-2333.md
Test vector 0 was not updated in https://github.com/ethereum/EIPs/pull/2985
https://github.com/ethereum/EIPs/pull/2985/files#diff-8caacf51cadcfbe94a39cf606351c359R243
Test vector 0 is actually detailed with intermediate value at the bottom of the EIP so this merely copies that information over: https://github.com/ethereum/EIPs/pull/2985/files#diff-8caacf51cadcfbe94a39cf606351c359R294
The correction was checked against the reference implementation at eth2.0-deposits-cli which uses the correct vector:
https://github.com/ethereum/eth2.0-deposit-cli/pull/108/files#diff-909cbf3d1a7e55f1731e90bc1f9a7ad9R5
=> EIP2333 - ETH2 keygen: test vector 0 wasn't updated in #2985

EIPS/eip-3009.md
An EIP for `transferWithAuthorization`, as used by the USD Coin (USDC) smart contract, alongside [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612).
[Discussions](https://github.com/ethereum/EIPs/issues/3010)
=> EIP-3009: transferWithAuthorization - Gas-Abstracted ERC20 transactions

EIPS/eip-3009.md
I made a mistake on the previous review of EIP-3009, recommending @petejkim to replace links with relative versions. Although this is correct and appears to work on `eips.ethereum.org`, it doesn't work for linking within Github. As defined in EIP-1, relative links must be of the form `[EIP-XXXX](./eip-xxxx.md)`. I have fixed this in this PR.
=> Fix eip-3009 relative links

EIPS/eip-2474.md, EIPS/eip-coinbase-call.md
Allow contracts to be called directly by `block.coinbase` (block validator), without a transaction.
_In proof-of-work blockchains, validators are known as miners._
The validator might want to execute functions directly, without having to sign a transaction. Some examples might be presenting a proof in a contract for an change which also benefits the validator. 
A notable example would be when a validator want to act as an [EIP-1077] Gas Relayer, incentivized to pick up fees from meta transactions. 
Without this change, they can do so by signing from any address a `gasPrice = 0` transaction with the gas relayed call. 
However this brings an overhead of a signed transaction by validator that does nothing, as `msg.sender` is never used, and there is no gas cost to EVM charge. 
This proposal …
=> EIP: Coinbase Calls

EIPS/eip-1559.md
Rather than having two pools and a migration, we instead have a single transaction pool and legacy transactions are "upgraded" into 1559 transactions using a *very* naive strategy of just setting `fee_cap == gas_bribe == gas_price`.
While in here, I also made a few other minor changes since this is a consensus change and will require all clients update:
1. Renamed premium to bribe.  I think this makes it more clear what this is, it is a bribe for the miner to convince them to include your transaction.
2. Changed the gas target calculation to be a bit simpler (per prior conversation with @i-norden)
3. Added special handling for when the gas_used == gas_target (no change in target for next block).
4. Adds missing assertion that gas_used wasn't more than 2x the gas target.
5. Added clarity …
=> Changes 1559 to have a single shared pool for all transactions.

EIPS/eip-3000.md
=> ERC-3000: Optimistic enactment governance standard

EIPS/eip-2926.md
Simplified the spec. Modified tree structure to be consistent with the binary trie [proposal](https://hackmd.io/uCWOpSrUQaytBgcO0MVkTQ).
=> EIP-2926 revision 1

EIPS/eip-1102.md, EIPS/eip-1474.md
This PR replaces my email address with my GitHub username for EIPs 1102 and 1474, as suggested [here](https://github.com/ethereum/EIPs/pull/3048#issuecomment-711889333).
=> 1102, 1474: Replace author email with GitHub username

EIPS/eip-3030.md
Updates the API definition based on discussions at #3030.
- Instead of receiving `signingRoot`, the validator client must send to the remote signer `bls_domain`, object `data`, `fork`, and `genesis_validators_root`.
- Removes elements of rationale arguing in favor of not receiving the pre-image to be signed.
- Improves test cases.
- Adds the Remote Signing Wallet of Prysmatic Labs as an implementation.
- Adds an item to the threat model.
=> EIP-3030: Update API definition

EIPS/eip-3076.md
A JSON interchange format for Serenity (eth2) that contains the necessary slashing protection information required to safely migrate keys between clients.
=> EIP-3076: Validator client interchange format (slashing protection)

.travis.yml, EIPS/eip-1.md, EIPS/eip-1057.md, EIPS/eip-1123.md, EIPS/eip-1154.md, EIPS/eip-1240.md, EIPS/eip-1355.md, EIPS/eip-1538.md, EIPS/eip-158.md, EIPS/eip-1682.md, EIPS/eip-1706.md, EIPS/eip-3.md, EIPS/eip-4.md, EIPS/eip-5.md, EIPS/eip-820.md, EIPS/eip-875.md, EIPS/eip-908.md, EIPS/eip-999.md
I'm updating EIP statuses according to #2996. The mappings are as follows:
```
Draft => Draft
Last Call => Last Call
Accepted => Final
Final => Final
Superseded => Final
Abandoned => Withdrawn
Rejected => Withdrawn
Active => Living
```
=> Update EIP statuses

EIPS/eip-1057.md
EIPs have a new set of statuses, Accepted is no longer a status but we accidentally mass updated Accepted => Final, when it should have been Accepted => Review.
=> Correcting a mistake in a mass-update.

EIPS/eip-1.md
This has been discussed a few times. The main problem is that editors have a challenge finding EIP authors and getting their response, unless there is a clear GitHub username. This is blocking a lot of outstanding change requests.
Awaiting feedback, @Souptacular @nicksavers @MicahZoltu @lightclient
=> EIP-1: require at least one github username

EIPS/eip-2930.md
This change will deprecate EIP-155 behaviour for this transaction type. Many proposed EIP-2718 transactions already separate the chain id from the `v` value, so I believe there is demand for this modification.
=> Add chain id to 2930

README.md
I am reviewing a NIST paper that will be citing a lot of our work here.
They, and nearly everyone, are confused by thinking that once something has an issue number here it is a final publication.
This PR helps to dispel that myth.
=> Clarify that drafts are drafts

EIPS/eip-2016.md, EIPS/eip-3085.md
Rendered file: https://github.com/rekmarks/EIPs/blob/2016/EIPS/eip-3085.md
This PR adds EIP-3085, which introduces the `wallet_addEthereumChain` RPC method. It's basically [EIP-2015](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2015.md), without requiring the network to be switched.
I think 2015 is a great idea, but wallets may desire an RPC method that only adds a chain, without requiring that the network is changed. For example, allowing dapps to request network changes is bound to cause UX issues, especially as we see dapps moving to different layer 2 chains.
2015 and 3085 can proceed independently of each other.
Co-author credits go to @pedrouid
=> EIP-3085: wallet_addEthereumChain

EIPS/eip-2972.md
=> EIP-2972: Deprecateds legacy transactions in blocks.

EIPS/eip-2972.md
Since we are using SSZ in the receipt, we might as well use SSZ in the transaction as well and just show the non-SSZ version as a note.
=> EIP-2972: Embraces SSZ

EIPS/eip-2930.md
2718 has the first byte of every transaction be the transaction type, and the remaining bytes are interpreted however this EIP wants. This is the minimal change required to get it in line with 2718 so I think we should merge this ASAP and then continue discussion on whether we think this is the optimal format or not.
=> EIP-2930: Updates transaction format to match EIP-2718

EIPS/eip-3074.md
To hopefully clear up some of the confusion when discussing this EIP,
I've renamed what I originally referred to as a "relayer" to the
"invoker", which I think is more clear.
The established vocabulary seems to agree that relayer is actually the
actor who _sends_ the transaction, and conflating that with some
optional intermediary contract is just a bad idea.
=> Add rationale for precompile; s/relayer/invoker/ [EIP-3074]

EIPS/eip-725.md
This PR adjust 725 to the latest discussion version found here: https://github.com/ethereum/EIPs/issues/725
=> Update eip-725 to adhere to the last definition

EIPS/eip-2681.md
I made a couple minor updates to this EIP. The highest account nonce was found by querying the Google `crypto_ethereum` dataset.
I would like to bring this EIP up at [ACD 101](https://github.com/ethereum/pm/issues/224) for feedback, so I also went ahead and moved this EIP to review.
=> 2681: Few minor updates + move to review

EIPS/eip-2930.md
`chainId` was missing from abstract.
Discussion in Discord landed on switching over to `yParity` instead of `v` since `chainId` so now part of the payload explicitly and the `+27` stuff is tech debt from Bitcoin.
=> Adds chainId and yParity; removes senderV

EIPS/eip-1193.md
This PR fixes two errata in the EIP-1193 examples section, special thanks to @enolan for noting in https://github.com/ethereum/EIPs/issues/2319#issuecomment-734159349 and https://github.com/ethereum/EIPs/issues/2319#issuecomment-734169215.
=> 1193: Fix example errata

EIPS/eip-695.md
[JSON-RPC](https://www.jsonrpc.org/specification) specifies that when a client sends an `id`, the _Server MUST reply with the same value in the Response object_.
In [EIP-695](./EIPs/eip-695.md) example, the client sent `id: 1` and the server replied `id: 83`.
This commit updates Client's request to send `id: 83` instead.
Changes:
+ Update eip-695 example to conform JSON-RPC specification
- Your GitHub username or email address is listed in the 'author' header of all …
=> Fix EIP-695 example `id` mismatch

EIPS/Exclusive_Claimable_Token.md, EIPS/eip-3135.md
Change to a simpler example, because mail counts is clearly defined while bits going through VPN is a little ambiguous ( have to decide whether control signals and payment messages are counted as service bits, which is not important in this EIP).
=> change example in eip-3135

EIPS/eip-2481.md
I was asked to move this EIP to "Last Call" to draw attention to the EIP with the intention to move it to final in two weeks.
I'm a bit out of touch with the issue at hand (because I have changed roles and am currently no longer active in client development. For the curious, I'm working on [ethereum/fe](https://github.com/ethereum/fe) now)
I did a quick check on the latest development on the issue and my impression is that:
1. All client teams are on board to implement this
2. Most are waiting on Geth to move first
3. @karalabe from Geth said they would implement it before the Berlin fork (Citing from discord)
>Option A: We roll out 66 (request id), 67 (typed tx in blocks, tx-announce etc)
>- Drawback: Everyone must implement 65 (tx hashes), 66 and 67 before Berlin. - The entire network …
=> Moved EIP 2481 to last call

EIPS/eip-55.md
This EIP was written in a time when we were using EIPs for hardfork coordination and we weren't worried too much about link rot.  However, times have changed and maintaining EIPs like this is becoming more and more of a burden.  In this case, the specification is what is important, not who implements it.  Also, editors do not want to maintain external links to things that don't add *significant* value.
=> Cleans up EIP-55

eip-template.md
EIPs are technical documents, not part of the hard fork coordination process aside from being an asset in that process.  Consensus and politics are not relevant to EIPs.
=> Removes the community consensus from rationale in template.

EIPS/eip-1.md
Let the change control system do what the change control system was designed to do.  It is entirely redundant to store change history in the EIP itself and it just adds an ever growing clutter to an already too long (IMO) process description.  If anyone wants to see the history they easily can.  Also, the history section said to see the history button in the top right of this EIP but that only works if you view this EIP from GitHub, not from any other interface.
=> EIP-1: Removes history and updated list.

eip-template.md
In reality, the `Implementation` section almost always involves someone linking out to a personal or company repository when they create an EIP from the template.  External repositories cause problems because:
1. Links move/change over time and eventually the link will be dead.
2. The implementation likely isn't CC0 as the EIP is, and naive users may follow the link not realizing it is GPL and they are screwing themselves legally.
3. People are using EIPs for advertising their project, and they look for any opportunity they can to link out to their project in the body of the EIP.
4. People often link to some monolithic repository (e.g., go-ethereum) as the "implementation" which is less than useful.
Also, the description was written back when EIPs were part of the hard fork coordination …
=> Implementation => Reference Implementation

eip-template.md
While this section is more clear to EIP authors than most, it still requires coaching.  Also, the wording was written back when EIPs were tightly coupled with hard fork coordination, which is no longer the case.
=> Rewords Motivation section of template.

EIPS/eip-165.md
This is an attempt to get this EIP to render correctly on the EIPs site.
Current rendering:
=> Removes extraneous spaces.

EIPS/eip-2976.md
* Adds hashing mechanism for typed transactions.
* Changes the way legacy transactions are encoded for backward compatibility.
* Adds assertion that clients must not send new typed transactions until their fork block.
=> 2976: Adjustments after latest round of iteration

EIPS/eip-3102.md
There is a typo on the type of an account's balance: it is `uint256`, not `uint32`.
=> eip-3102: account balance is a u256

EIPS/eip-3085.md
Adds the `iconUrl` param and changes existing URL params from type `string` to `string[]`, per #3086.
=> 3085: Update params

EIPS/eip-3156.md
Fixed the discussions-to link.
Added a new section to the Security Considerations, on how to trust that the `onFlashLoan` arguments are genuine.
=> Expanded ERC-3156 with more security considerations

EIPS/eip-3198.md, EIPS/eip-x.md
=> Create BASEFEE opcode EIP

assets/css/style.scss
Uses a highly specific CSS selector to ensure that it overrides the minima selector of `.wrapper` which sets the max-width to 740px.
=> Changes the max width of EIPs site to be something reasonable.

EIPS/eip-2930.md
We forgot to define the receipt structure for this transaction (required by 2718).  I went with a mirror of legacy transaction receipts, though I am open to some alternative structure.
Some of the stuff we were defining here is already defined in 2718, and I believe redefining it was adding confusion and making iteration on this spec more challenging than it needed to be.
=> 2930: Adds receipt and non-normative change to improve readability.

EIPS/eip-3156.md
Updated the reference implementations [to actually run](https://github.com/albertocuestacanada/ERC3156), fixing some things along the way:
- Added natspec to interfaces
- Used `amount` instead of `value` throughout the code
- Corrected argument type on `onFlashLoan`
- Minor descriptive edits
- Added rationale on choosing `pull` over `push` repayment behaviour
- Expanded reference implementation of flash borrower
- Bug fixing on reference implementations
- Better comments on reference implementations
=> Erc3156 review

EIPS/eip-1559.md
Integrates 2718 (Typed Transactions) into EIP-1559.  Overall a pretty simple/small change, mostly with just some adjustments to pre-processing.
I took the opportunity to also rename some of the variables both to improve clarity and to reduce conflict in the community (bribe vs inclusion fee).  If someone feels strongly about it, I can split out the 2718 changes and the variable name changes.
=> 1559: Adds dependency on 2718

EIPS/eip-1559.md
=> 1559: Adds backward compatability section about the change in blockhash.

EIPS/eip-1559.md
Original spec had the starting base fee (at fork block) as 1 nanoeth, but this was unintentionally lost along the way. I believe current clients have implemented it the original way so this change shouldn't require any client changes.
Also fixed a bug in the spec that allowed the base fee to go negative by just flooring it to 0.
=> 1559: Changes starting base fee to 1 nanoeth and floors base fee at 0.

EIPS/eip-3156.md
BoringCrypto from SushiSwap revealed a vulnerability in the standard, that we are solving but requiring that `onFlashLoan` returns `true`, and requiring that the `lender` verifies that `true` was returned.
Aave v2 [already does this](https://github.com/aave/protocol-v2/blob/29448c19c1e9b8aa87dccd70b716d15cdf4128f6/contracts/protocol/lendingpool/LendingPool.sol#L507), thankfully.
=> erc3156: added return types to avoid vulnerability

EIPS/eip-2771.md
address is the last 20 bytes of the msg.data, not past the msg.data
also, use a simplified method to avoid copying entire msg.data just to read the last 20 bytes)
=> fix sample implementation, to match description

EIPS/eip-1186.md
Implementation tracking is part of the hard fork coordination process which now lives at https://github.com/ethereum/eth1.0-specs/.  Removing this section to avoid causing confusion since it likely won't be maintained or represent a full view of reality.  Also, it isn't really appropriate for EIPs anymore.
=> 1186: Removes Implementation section

EIPS/eip-634.md
Adding some updates to EIP-634
- use reverse dot notation instead of vendor keys
- Several recommendations from the discussions-to URL
=> Updates to EIP-634

EIPS/eip-3085.md
This PR changes the `iconUrl: string` parameter to `iconUrls: string[]` and updates all descriptions thereof.
=> 3085: Update iconUrl parameter

EIPS/eip-3156.md
- One instance of `IERC20` used as the type for `token` instead of `address`.
- Missing specification of what the `fee` is.
- Added checks for sentinel value on code excerpts.
- Corrected specification to check for sentinel, and not `true`
- Removed batch flash loan functionality.
=> Fixed typos on sentinels, and removed batch flash loans

EIPS/eip-3157.md, EIPS/eip-3234.md
I've segregated the batch flash loan functionality from ERC3156, to allow lenders to support single-asset, multiple asset, or both kinds of flash loans.
I've taken the liberty to assign the 3157 number to the Batch Flash Loan ERC, as I think everyone will find it easier to deal with two very similar ERCs if they have consecutive numbers. Apologies if this can't be done.
=> Initial draft for ERC3234 batch flash loans

EIPS/eip-3156.md
=> Erc3156: Rename `maxFlashAmount` as `maxFlashLoan`

EIPS/eip-3156.md
After two months of intense developement and consultation, I'd like to move ERC-3156 to Last Call.
In its development we have discussed it with members of Aave, Uniswap, Sushiswap, Yearn, Yield, DefiSaver, OpenZeppelin, and StakeDAO. It's been discussed on Ethereum Magicians, Twitter, ETHSecurity and FlashF*ck Researchers. The feedback has been very positive.
=> ERC-3156: Move to Last Call

EIPS/eip-3156.md
Ether cannot be pulled as when using `transferFrom`, so ERC3156 Ether flash loans are not possible. Therefore, references to sentinel values for Ether have been removed.
=> erc3156: removed sentinel values for ether

EIPS/eip-3234.md
Ether cannot be pulled as when using transferFrom, so Ether as part of an ERC3234 batch flash loan is not possible. Therefore, references to sentinel values for Ether have been removed.
=> erc3234: removed sentinel values for Ether

EIPS/eip-2612.md
As per eip-712, the encodeData function corresponds to abi.encode, not abi.encodePacked in solidity. See:
https://eips.ethereum.org/EIPS/eip-712#definition-of-encodedata.
Existing implementations already conform to this.
=> use abi.encode instead of abi.encodePacked in permit (EIP-2612)

EIPS/eip-2930.md
This is a security requirement of EIP-2718.
=> Makes signature have type as the first byte.

EIPS/eip-3076.md
With EIP-3076 (slashing protection interchange) now implemented by the 4 major Eth2 clients (Lighthouse, Nimbus, Prysm, Teku), I would like to nominate it for review.
There are a few tweaks to the security recommendations that I would like to make before moving to Final Call, but the substance of the EIP has been stable for several months now and is unlikely to change.
=> Move EIP-3076 to Review status

EIPS/eip-2930.md
Also removed empty optional sections while here.  They can be added back if/when tests/implementations are added, but they are otherwise optional.
I also moved this to review, since that is a much more appropriate state for an EIP that is going into a soon-to-be-scheduled hard fork, and there are no major changes planned to this EIP by the authors that I know of.
=> 2930: Changes 1 to 0x01 for clarity and moved to Review.

EIPS/eip-1559.md
This PR updates the signature specification to match the format used in EIP-2930, and also adds the transaction format to the abstract.
=> EIP-1559: update signature specification to match EIP-2930

EIPS/eip-681.md
Fixed the spelling of ether as a unit and added a required header linking to the discussion of ERC-681 at FEM's forum.
=> ERC-681 back to Review

EIPS/eip-1559.md
This EIP was originally written quite a while ago, this change just brings it in line with modern EIP editing standards.
EIPs are technical documents, not repositories for general information about a particular change.  Generally speaking, people should not be linking to EIPs directly when talking with the general public.  The time you would link a human to an EIP is when you want to discuss the technical aspects of it or implementation details.  In most other cases (such as governance discussions), a higher level document should be linked to and the EIP should just be a footnote in the references, meant only for implementors and people interested in understanding the EIP at a technical level.
@timbeiko has created this Hack MD document (https://hackmd.io/@timbeiko/1559-resources) that …
=> Removes Resources section.

EIPS/eip-2678.md
Adds an empty header row to tables enable table formatting with github flavored markdown.
=> Add header row to support gfm for table formatting

EIPS/eip-3297.md
Remove gas refunds for SSTORE and SELFDESTRUCT.
=> Removal of refunds

EIPS/eip-3074.md
As much as I *hate* ORIGIN with a burning passion and would love to have it broken/removed, I don't think sneaking it in with this EIP is the right way to go.  ORIGIN references the transaction that initiated the transaction, and that doesn't change by adding a new `CALL` opcode.  I would 100% support a separate EIP that removes `ORIGIN` or otherwise breaks it, just not embedded in a new opcode.
=> 3074: Removes change to ORIGIN.

EIPS/eip-2315.md
Remove outdated Appendix.  Solidity team has improved code generation, so example is obsolete.
=> remove appendix

EIPS/eip-3085.md
This changes the discussions-to link to Ethereum Magicians instead of #3086.
=> 3085: Move discussion to Ethereum Magicians

EIPS/eip-1102.md
At the request of the Catherders, we should keep the discussion at Ethereum Magicians. (cc: @poojaranjan :) )
=> 1102: Revert discussions-to URL to Ethereum Magicians

EIPS/eip-3085.md
- Various copy edits / fixes and specification language simplifications
- Unrequire EIP-3091
- If 3091 becomes standardized, wallets are free to choose to mandate that block explorers are compatible with it, but we shouldn't hold up this EIP on 3091.
- Do **not** mandate that requests for chains that were already added should be treated as successful
- This amounts to changing a "**MUST**" to a "**SHOULD**".
- See new subsection of Security Considerations, "Preserving User Privacy", for details.
=> 3085: Minor specification change, unrequire EIP-3091, copy edits

EIPS/eip-3322.md, EIPS/eip-draft-gas-storage.md
Specs out efficient gas refunds that would supplant wasteful alternatives.
Reviewers @MicahZoltu
=> EIP 3322: Efficient Gas Storage

EIPS/eip-196.md, EIPS/eip-2645.md, EIPS/eip-2678.md, EIPS/eip-2680.md, EIPS/eip-615.md
I am currently extending the DIP-Checker to also check EIPs and will submit a PR soon that adds it as a github action.
So far most things are very clean in here (so the github action will only replace the manual work of checking it for future PRs) - but there have been some inconsistencies in the author header. This PR is fixing them.
=> Unify author header values

EIPS/eip-3085.md
Updates the status of EIP-3085 to "Review".
=> 3085: Move to Review

EIPS/eip-3074.md
Removes `type` from stack;
Adds `depthLeft` to stack;
Adds two checks to the `valid` preconditions;
Expands security considerations for invokers.
=> Add depthLeft [EIP-3074]

EIPS/eip-2228.md
=> EIP-2228: Promote to Review

EIPS/eip-2929.md
EIP-2929: fix typo "SELFEDESTRUCT" to "SELFDESTRUCT"
=> fix typo: "SELFEDESTRUCT" to "SELFDESTRUCT" for EIP-2929

EIPS/eip-2315.md
This version is updated to specify rules for safe execution and amenability to static analysis.
=> EIP-2315: Simple Subroutines for the EVM

EIPS/eip-2981.md
@VexyCats 
- Fixed issues in precision of the percentages. In some places 4 decimals were used, but we want 5 (0.00001) was the intention.
- tokenId was added to functions but inconsistently
- You can't emit an event on the NFT contract directly, you must wrap it in a function. Having this function requires adding it to the interface
- Interface ERC165 calculation was incorrect (didn't update it for the uint256 tokenId when it was added) plus I had to add in the new function for emitting the event
- Added `_tokenPaid` field to the `RoyaltiesReceived` event to support ERC20 payments
- Removed the 4th index in the event - events can only have 3 indexed parameters. ERC20 and ERC721 both don't index the amount, so not indexing the `_tokenPaid` and the `_amount` is consistent with the …
=> EIP 2981 improvements

EIPS/eip-3322.md
This updates the draft so that the opcode specifications would be compatible with EIP-3198: BASEFEE opcode.
=> Update EIP-3322 Opcodes to be compatible with EIP-3198

EIPS/eip-3402.md, EIPS/eip-3403.md
Alternative to EIP 3298 that makes a more limited change.
=> EIP 3403: Partial removal of refunds

EIPS/eip-3074.md
=> Fail on invalid extvalue instead of throw

EIPS/eip-1559.md
The EIP had one spelling error and still the outdated reference implementation is in the EIP. If there is any new reference implementation, then this should be added.
=> EIP1559: remove spelling error / remove wrong reference implemenation

EIPS/eip-1363.md
Just update the interface id in comments by linking all in one instead of having them separate.
EIP says that they MUST be all implemented so there is no reason to keep them separate.
=> Update interface id in ERC1363

EIPS/eip-681.md
As there were no more change requests while ERC-681 was in Review, it can move on to Last Call
=> EIP-681: move to Last Call

EIPS/eip-3436.md, EIPS/eip-cliquechoice.md
Adds fork choice rules to clique aimed to prevent deadlocks.
Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>
=> Clique Block Choice Rule

EIPS/eip-3234.md
- pluralize function arguments
- IERC3234FlashBorrower -> IERC3234BatchFlashBorrower
- change success condition of example implementation
=> Fix some typos on EIP3234

EIPS/eip-3416.md
Removed dynamic BLOCK_GAS_TARGET altogether to focus on the following:
* Median premium fee.
* Dynamic Base Fee with Additive updates.
Also removing the clamp for BASE_FEE border conditions that was redundant or useless.
=> Removed dynamic BLOCK_GAS_TARGET and BASE_FEE clamp

EIPS/eip-1559.md
I don't believe this extra field is useful in a consensus structure. Each field in the receipt can currently *only* be determined by reexecuting the transaction. `effectiveGasPrice` does not require reexecution, only the transaction's `feeCap` and `tip` in addition to the block's `baseFee`. This generally requires 1 additional RPC call to get the block `baseFee`, on top of what is done today (just `eth.getTransaction` today). Client could optimize this further by indexing transaction in relation to the block `baseFee`.
=> Remove effective gas price from EIP-1559 receipt

.codespell-whitelist
Failure: https://travis-ci.org/github/ethereum/EIPs/jobs/766589226
=> Apparently codespell doesn't know `sting` is a word?

.github/workflows/auto-merge-bot.yml
This new version has a lot of refactoring and also now mentions the authors if a given EIP has no errors
changes in question: https://github.com/alita-moore/EIP-Bot/commit/01abc40143277dec9c669c2a757ebfbeec04cfd3
=> fix not mentioning authors

EIPS/eip-3156.md
It was not clear enough that receivers can't give automatic approvals to lenders unless they verify the initiator is trusted in each execution of `onFlashLoan`.
=> erc3156: made security around automatic approvals clearer

EIPS/eip-2565.md
Updates the status of EIP2565 after the Berlin hard fork
=> EIP2565: Move from 'Last Call' to 'Final'

EIPS/eip-1559.md
Feedback suggests that "inclusion fee" may not be immediately obvious since you have to pay the base fee to be included.  The idea with priority fee is "this is the number you need to increase in order to have higher priority over other people trying to transact on Ethereum during times of congestion".
=> 1559: Rename inclusion fee to priority fee.

EIPS/eip-3529.md
An alternative way to reduce refunds to deal with the issues addressed in EIPs 3298 and 3403.
=> EIP 3529: alternative refund reduction

EIPS/eip-3091.md
Currently it renders suboptimal like this:
=> Fix markdown for routes

EIPS/eip-1559.md
Per @karalabe's [document](https://gist.github.com/karalabe/1565e0bc1be6895ad85e2a0116367ba6) and [proposal](https://discord.com/channels/595666850260713488/749160974506000444/839548707859070996), this PR will remove the notion of `gasTarget` in the block structure. It will revert to the current status quo of `gasLimit`. The `gasTarget` will continue to be an integral part of EIP-1559, but it will be computed each block with the formula `gasLimit // ELASTICITY_MULTIPLIER`. On the fork block, the gas target will be interpreted as the parent block's gas limit to avoid unduly halving the gas target.
=> Remove gas_target from block structure

EIPS/eip-3554, EIPS/eip-3554.md
Targeting 0.1 second effect on the first week of December 2021 with a delay of 9.5 million blocks.
=> Create EIP-3554 for delaying the difficulty bomb until Shanghai and/or Merge.

EIPS/eip-1559.md
As discussed on the infrastructure call, we are going to update the spec to align with client implementations. Previously, the spec defined the base fee for all blocks *before* the fork block to be `1_000_000_000`. Clients ended up implementing this as *the fork block* base fee is set to `1_000_000_000`. There is very little difference in the two, and since clients have already implemented the latter, we're just going to make it official via the spec.
It's important to note that while the base fee calculation doesn't require a different interpretation of the parent blocks gas limit, the gas target adjustment does. So before calculating the allowed range in which the gas target can be adjusted, clients should not divide out the `ELASTICITY_PARAMETER`.
=> Start with default base fee on fork block

EIPS/eip-1559.md
This reverts `gasLimit` checks to use the same validation as was used previously.
=> eip-1559: revert to old gaslimit checks

EIPS/eip-1559.md
Current spec seems to indicate we remove the min gas limit (see Yellow Paper reference):
This PR fixes this as removing the min gas limit is not desired.
=> EIP1559: import original min gas limit

EIPS/eip-3554.md
I made mistake in the date calculations. Updated to be more accurate and the Proposal is ready for Review.
=> Updated months to be more accurate for the iceage

EIPS/eip-3529.md
Rename `NEW_MAX_REFUND_QUOTIENT` to `MAX_REFUND_QUOTIENT` and explain what this constant refers to in Yellow Paper.
=> EIP-3529: Rename NEW_MAX_REFUND_QUOTIENT to MAX_REFUND_QUOTIENT

EIPS/eip-1559.md, EIPS/eip-3198.md, EIPS/eip-3529.md, EIPS/eip-3541.md, EIPS/eip-3554.md
Suggested on ACD by @timbeiko, with the end-date set to the date of mainnet fork.
=> Mark all London EIPs as Last Call

EIPS/eip-3561.md, EIPS/eip-3651.md
Additional storage slots to decrease trust in interaction with upgradeable smart contracts.
Removing trust from upgradeability proxy is required for anonymous developers. To achieve that, disallowing sudden, potentially malicious upgrades is required. This EIP introduces a time lock, a period of one month, before defined by proxy admin implementation becomes active implementation.
=> EIP3561: Trust Minimized Upgradeability Proxy

EIPS/eip-3384.md, EIPS/eip-3386.md
Introduces a standard interface for wrapping ERC-721 and ERC-1155 tokens with derivative ERC-20 tokens.
=> Create EIP for a ERC-721, ERC-1155 to ERC-20 Wrapper (#3386)

EIPS/eip-2981.md
- Rename to `NFT Royalty Standard` to imply both 721 and 1155 compatibility
- Explain that it could potentially be a universal royalty standard, not just for NFTs
- Fix the 165 function calculation
- Rename the interface to _INTERFACE_ID_ERC2981
- Remove invalid return value from the constructor
- Use `supportsInterface()` for determining support in the example
=> EIP-2981 review comments

EIPS/eip-2930.md
There has been some desire to get some consistency across these EIPs in terms of naming.  Also, `access_list` is snake case while the rest are `camelCase` so I fixed it to align with the rest (and also match casing style of 1559).
=> 2930: Non-normative changes to variable names to match 1559.

assets/css/style.scss
If you don't like full-width pages, you can resize your browser window.  When looking at code, having artificial width limits can lead to unnecessary scroll bars.
=> Makes the EIPs site maximally responsive.

EIPS/eip-627.md
=> Fix typo in eip-627.md

EIPS/eip-3607.md, assets/eip-3607/geth.diff
Updates 3607 to use pseudocode instead of go.
Adds a git diff instead of a link to the implementation.
=> 3607: updated pseudocode, added diff

EIPS/eip-2981.md
- _value is now _salePrice
- royaltyInfo() return values no longer have underscore prefix
- checkRoyalties function uses IERC165 interface instead of IERC2981 interface
- fixed-percentage wording revised 
- caveats added around percentage calculation
- conversation with artist and marketplace cleaned up
- ERC165 was being imported instead of IERC165
Also, I've removed parts where we repeated ourselves unnecessarily.
=> EIP2981 content revised ✍️

EIPS/eip-3607.md, assets/eip-3607/geth.diff
As discussed on last ACD, we'd rather use the empty code hash instead of the code size cc @dankrad
=> 3607: update to use empty code hash instead of codesize

EIPS/eip-3541.md
The info in the eip is wrong, see https://gist.github.com/holiman/466cf6598e4a967620b9833b5ce49a23. The actual block number where the state was based on, for some reason, got lost, and the number in the eip is something else (right now, the EIP-blocknumber the analysis was based on won't be mined for a few years yet).
=> EIP-3541: fix erroneous comment

EIPS/eip-2981.md
fix: updating eip-2981 status from 'Review' to 'Last Call'.
=> EIP2981 status changed to 'Last Call'. ✍️ 

EIPS/eip-3541.md
It was pointing to a comment and not the topic starter.
=> Fix discussions-to url of EIP-3541

EIPS/eip-3651.md, EIPS/eip-draft-warm-coinbase.md
Introduces EIP to initialize COINBASE address as warm.
Reviewer @lightclient
=> EIP 3651: Warm COINBASE

EIPS/eip-1559.md
Also noticed that the RLP section uses camelcase, while the python spec uses snakecase.
Furthermore other fields are also not matching, like `value` vs `amount`.
Basically asking for guidance, before I do more changes.
=> Use consistent naming for to/destination in 1559

EIPS/eip-3436.md
As per author, the proposal is ready to be moved to "Review" status.
Feedbacks are requested at eth-magicians. - https://ethereum-magicians.org/t/eip-3436-expanded-clique-block-choice-rule/5809/5
=> Promote EIP-3436 to Review

EIPS/eip-2535.md
EIP-2535 has had feedback and been reviewed for many months. It is ready to move to Last Call.
Here is a link to a list of projects that are already using EIP-2535: https://eip2535diamonds.substack.com/p/list-of-projects-using-eip-2535-diamonds
Here is a link to a list of smart contract security audits that have been done that include the EIP-2535 reference implementations: https://eip2535diamonds.substack.com/p/smart-contract-security-audits-for
=> Move eip-2535 to Review

EIPS/eip-1559.md
We can prove that the `parent_base_fee_per_gas - base_fee_per_gas_delta > 0`, so flooring to 0 is unnecessary.
=> 1559: Removes unnecessary max

EIPS/eip-1559.md
After the [Ropsten consensus issue](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/retrospectives/london.md) it was noted that the ordering of the `assert` statements made it unclear that the `signer.balance` field in `assert signer.balance >= transaction.gas_limit * transaction.max_fee_per_gas` had already had `transaction.amount` deducted from it (L207). This change simply bring up this `assert` statement closer to other assertions for `signer.balance` to increase clarity.
=> 1559: Change signer.balance assertion location

EIPS/eip-2535.md
[EIP-2535](https://eips.ethereum.org/EIPS/eip-2535) is ready to move to Last Call.
EIP-2535 is a standard for building modular smart contract systems that can be extended in production.
An introduction to it is here: https://eip2535diamonds.substack.com/p/introduction-to-the-diamond-standard
EIP-2535 was released in February 2020. The standard has gotten a lot of feedback and much experience has been gained with it by implementing diamonds and using them in production. Feedback and experience started in 2018 when [EIP-1538](https://eips.ethereum.org/EIPS/eip-1538) was released. EIP-2535 is an improvement upon EIP-1538.
More than 20 projects are using EIP-2535.  Here is a link to a list of projects that are using EIP-2535: https://eip2535diamonds.substack.com/p/list-of-projects-using-eip-25 …
=> Move eip-2535 to Last Call

EIPS/eip-1155.md
Fixed `ERC-165 Standard Interface Detection` link which is invalid because of typo.
=> EIP 1155: fix invalid link

EIPS/eip-1271.md
The industry standard is to encode signatures as `(bytes32 r, bytes32 s, uint8 v)` in 65 bytes, which is evident here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/d3c5bdf4def690228b08e0ac431437288a50e64a/contracts/utils/cryptography/ECDSA.sol#L32
But also in the implementation code which reads the first 32 bytes as r, then the next as s, and the last byte as v
However, it checks if the signature is 66 bytes long, rather than the 65 which it reads. As such I believe this is an error in the example.
----
- The PR …
=> EIP 1271: fix implementation example signature validation

EIPS/eip-3198.md
EIP-3198 deployed on the mainnet with the London upgrade.
=> Promote EIP-3198 to Final.

EIPS/eip-3554.md
EIP-3554 deployed on the mainnet with London upgrade.
=> Promote EIP-3554 to Final.

EIPS/eip-3541.md
EIP-3541 deployed on the mainnet with the London upgrade.
=> Promote EIP-3541 to Final.

EIPS/eip-1559.md
The comment is deprecated after https://github.com/ethereum/EIPs/pull/3681 was merged
=> 1559: Remove deprecated comment

EIPS/eip-3541.md
Recently on Twitter it seems a common misunderstanding is that the rejection is for the contract address. This clarifies it.
=> 3541: clarify the title

EIPS/eip-3675.md
See https://ethereum-magicians.org/t/eip-3675-upgrade-consensus-to-proof-of-stake/6706/2 for details
=> EIP-3675: update Network section

EIPS/eip-1155.md, EIPS/eip-1363.md, EIPS/eip-1504.md, EIPS/eip-1616.md, EIPS/eip-1620.md, EIPS/eip-165.md, EIPS/eip-1761.md, EIPS/eip-20.md, EIPS/eip-721.md, EIPS/eip-725.md, EIPS/eip-777.md, EIPS/eip-801.md, EIPS/eip-897.md
As we discussed on EIPIP, I have removed the "ERC" prefix from ERC titles.
=> Remove ERC prefix from title

EIPS/eip-3675.md
This EIP provides events from the consensus client which indicate various validation meanings to the execution client.
Some of the language around these events is confusing or needs to be updated:
`POS_CONSENSUS_VALIDATED` should indicate that the referred block and any *ancestors* are considered valid, as a valid block implies all blocks reachable by `block.parent_root` are also valid.
`POS_CHAINHEAD_SET` has the same issue although as I understand this event, there will always be a single block referenced (even in the `FINALIZED` variant) that should be the unique head.
=> Clarify validation conditions in EIP 3675 "The Merge"

.travis.yml
This adds support for the `description` field in the preamble. It enforces a maximum length of 140 characters (just like in the good old days on twitter!).
`eipv` PR: https://github.com/lightclient/eipv/pull/28
=> Bump eipv to v0.2

EIPS/eip-1.md, EIPS/eip-2718.md, _includes/head.html, _layouts/eip.html, eip-template.md
Implementation of https://github.com/ethereum/EIPs/pull/3564#issuecomment-837367526.
The header:
Twitter before:
Twitter after:
**Could also render the `description` prominently after the header.**
=> Add description field to the EIP header

EIPS/eip-3014.md
Came across this problem (jekyll complains about it). Picked from #3599.
=> 3014: Avoid using special characters in title

_config.yml
Not sure whether it is useful. The Youtube channel has ACD, Eth2.0 calls, Eth1.x calls, which have relevance here.
=> Remove social media links from the page (but keep Github)

EIPS/eip-2315.md
Ethereum object format allows immediate data, which https://github.com/ethereum/evmone/pull/351 uses to provide static, relative jumps.  This allows for static, validated subroutines.
=> Validate static JUMPSUB using immediate data

EIPS/eip-3074.md
EIPs shouldn't have external links.  I also removed the TODO section since it was empty (and it is optional anyway).
=> Removes implementation section.

EIPS/eip-2315.md
There are three substantive changes to this proposal since the prior Last Call, made possible by other recent EVM work.
* Work on the Ethereum Object Format can make it possible to have immediate arguments for static operations.
* A static `JUMPSUB`, Static Relative Jumps, and deprecating dynamic jumps can support EIP-615-level safety guarantees against invalid instructions, stack underflow, and many stack overflows.
* A distinct contract-creation phase allows for validity checking to enforce those guarantees and eliminate the need for (and DOS vulnerability of) jumpdest-analysis.
The proposal has been expanded to:
* Demonstrate claimed efficiency gains.
* Provide safety rules and a validation algorithm for enforcing them.
=> EIP-2315 pre-review copyediting.

EIPS/eip-3675.md
- Unifies `POS_CHAINHEAD_SET` and `POS_BLOCK_FINALIZED` into `POS_FORKCHOICE_UPDATED`
- Adds more details to the PoS events description for the sake of clarity
- Introduces a small fix to the Block validity section, related to the PoS events
=> 3675: Update PoS events

EIPS/eip-2981.md
* Removed supportsInterface from the IERC2981 interface
* Added a separate definition of the IERC165 interface with the original comment language
* For more details about this change, see; https://github.com/ethereum/EIPs/issues/2907#issuecomment-903283402
=> Update interface definition code section

EIPS/eip-170.md
Name the `0x6000` constant in EIP-170 as `MAX_CODE_SIZE`.
=> EIP-170: Name the MAX_CODE_SIZE constant

EIPS/eip-1.md
I believe we decided in a previous EIPs meeting to just have Living stay living.  Having it toggle to review doesn't make sense, because then it means there is no living EIP-1 while it is in review.
cc @poojaranjan
=> Removes Living toggling between review and living.

EIPS/eip-3675.md
Notes that `TERMINAL_TOTAL_DIFFICULTY` parameter must be hardcoded into client software distribution. See the corresponding change in the consensus layer for additional details and rationale https://github.com/ethereum/consensus-specs/pull/2605.
=> EIP-3675: Hardcode terminal total difficulty

EIPS/eip-3675.md
Removes the deprecation of **`extraData`** block field.
The **`extraData`** field is pretty handy during investigation into various network incidents as the default usage of this field is to express the client software version that has been used to create a block.
=> EIP-3675: Bring back extraData

EIPS/eip-1202.md
=> Major draft content update for eip-1202.md

EIPS/eip-3436.md
Even though this isn't ethash, it is a consensus change so it is a core EIP, not a networking EIP.
=> 3436: Changes to Core from Networking.

EIPS/eip-3675.md
PoS events signalling validity of the block with respect to the proof-of-stake consensus rules are simplified in the following way:
- After this change `POS_CONSENSUS_VALIDATED` event relates to the block it has a reference to, the requirement to affect ancestors of this block is removed
- Additional semantics of signalling the block is valid wrt the consensus rules is removed from  `POS_FORKCHOICE_UPDATED` event
Simplifies the spec and reduces implementation complexity. It adds a restriction on the events order which is gonna be satisfied by synchronous event processing in the Merge Interop implementations. Production ready solution for preserving the order of events is TBD.
=> EIP-3675: Simplify PoS events signalling the consensus validity

EIPS/eip-2309.md
type uint256 has 256 bits, which should allow for 2^256 items (from 0 to (2^256)-1). Similar to how uint8 should allow for 2^8 (256) items (from 0 to 255 aka (2^8) - 1).
=> Update docs to use maximum number of 2^256 items

EIPS/eip-4337.md
@vbuterin ,
this PR adds the create2 deployer refernce to the EIP
the code is updated in https://github.com/eth-infinitism/account-abstraction/pull/14
(can't PR to the EIP-4337 itself, since it is not public,
=> reference EIP-2470 (create2 deployer)

EIPS/eip-725.md
- Add 2 more arguments to `contractCreated` event: `operation` and `value`.
=> Update EIP-725: contractCreated Event

EIPS/eip-3675.md
Alter the terminal PoW block logic and `TRANSITION_POW_BLOCK` logic to be less strict on EL to allow for a simpler override mechanism in the event of attacks and other emergency overrides.
The details of the override mechanism and why this supports it can be found here -- https://github.com/ethereum/consensus-specs/issues/2643#issuecomment-953250363
=> Alter 3675 terminal block logic to account for overrides

EIPS/eip-4398.md, EIPS/eip-4399.md
A proposal to supplant the `DIFFICULTY` opcode with the `RANDOM` opcode during the upgrade to PoS (a.k.a. the Merge):
- enshrine the output of the beacon chain randomness beacon into the block header structure by supplanting the value of the deprecated `mixHash` field
- make the instruction with the number of the `DIFFICULTY` opcode return the value of the `mixHash` field
- rename the `mixHash` field and the `DIFFICULTY` opcode to `random` field and `RANDOM` opcode respectively
=> EIP-4399: Supplant DIFFICULTY opcode with RANDOM

EIPS/eip-4399.md
* minor language cleanups
* add discussion about why this is tightly coupled to 3675
* make clear that this change is backwards incompatible
=> minor cleanups to 4399

EIPS/eip-3675.md
Concerning EIP-3675:
During the Amphora interop, it became clear we needed to agree on a value for `FORK_NEXT` as it pertains to EIP-2124.
This PR suggests a value of `0` and adds a short rationale for the decision.
=> Add note about `FORK_NEXT` value re: EIP-2124

EIPS/eip-3569.md
Per EIP-1, `discussions-to` cannot point to Github pull requests. Unfortunately I missed this during review and accidentally merged the EIP before it had a Ethereum Magicians discussion thread. I've created one here: https://ethereum-magicians.org/t/eip-3569-sealed-nft-metadata-standard/7130
=> Add fem link for 3569

EIPS/eip-2364.md, EIPS/eip-2464.md, EIPS/eip-4345.md
Combines the updates from https://github.com/ethereum/EIPs/pull/4367 and https://github.com/ethereum/EIPs/pull/4366, and addresses most comments from @MicahZoltu in a way which hopefully makes him happy, but recognizes the fact that these EIPs are already "ancient". Addressed all comments which were related to formatting/sections, but links are still present, and the specification has been left as is. 
Hopefully we can get a soft +1 on these before requiring Péter to review & approve.
=> Updates to EIPs 2464 and 2364.

EIPS/eip-3675.md
Addressing PR feedback in #4411:
- Update link to EIP
- Specify what happens to the EIP-2124 values *after* the transition.
=> Update specificiation on handling EIP-2124 during the consensus upgrade

README.md
Link is still pointing to the old EIP validator.
=> Link to active eip validator

.github/workflows/stale.yml
See https://github.com/actions/stale#exempt-issue-labels
After this change, if an issue is labeled `discussion-url`, it will be exempt from closure.  We should reopen the actual discussion URLs which have been closed recently and label them too.
=> Make the stale bot ignore discussion urls

EIPS/eip-1.md
The `discussion-url` is not an optional field.
=> `discussion-url` required

EIPS/eip-2681.md
Based on https://github.com/ethereum/go-ethereum/pull/23853.
=> 2681: Clarify that 2^64-1 is invalid as a transaction nonce

EIPS/eip-4444.md
Clients must stop serving historical blocks/receipts that are older than a year on the p2p layer. Clients may prune such historical data.
=> Bound history size

EIPS/eip-1967.md
- Add inline reference implementation
- Change simple summary section to description header field
- Move extraneous Beacon section to within the Specification
- Add new Security Considerations section
- Update some outdated links
cc @axic
=> Reformat EIP1967 to match requirements from EIP1

EIPS/eip-3675.md
Add a section to the security consideration about meaning of ancient blocks to the core of the PoS protocol
=> EIP-3675: Ancient blocks are no longer a requisite for a network security

EIPS/eip-4399.md
Add a note that the changes introduce by 4399 allows for smart contracts to distinguish PoS blocks from PoW blocks
=> EIP-4399: note that smart contracts may distinguish PoS blocks

assets/eip-722/eip-722.md
Hi, I see, I see almost NFT applications are using ERC721, so after the NFT start-up trend, there will be many companies that run out of capital and dissolve. At that time they will shutdown their servers and many of the images associated with the NFT will be inaccessible. Should we need create a contract that allows the holder to update the image URI.
=> EIP-722: Allow everyone migrate token URI

EIPS/eip-3675.md
Make it clear that the various 0 values in the EIP can be overridden by subsequent EIPs.
=> Add note about PoW constant validation.

EIPS/eip-3675.md
Adds `TERMINAL_BLOCK_HASH` parameter and describes scenarios when it may be used.
Additionally, covers scenario when `TERMINAL_TOTAL_DIFFICULTY` is considered to be overridden.
=> EIP-3675: introduce TERMINAL_BLOCK_HASH parameter

EIPS/eip-1.md
- Update "discussion to" place, to highly recommend starting a discussion thread at [Fellowship of Ethereum Magicians](https://ethereum-magicians.org/)
- Update status to reflect status documenting uniformly throughout the EIP-1
eg. `DRAFT` - > `Draft`
=> Update "discussion to" place & status case

EIPS/eip-1.md
Updated texts to add web links wherever required to remove the "Bibliography" section. 
eg.  
[formal specification] -> [formal specification](https://github.com/ethereum/yellowpaper)
Some of the links were redundant and hence couldn't be added to the current version of EIP-1.
=> Update weblink to text(s) and remove Bibliography from EIP-1

EIPS/eip-1153.md
IMO passing revert information from inner call frames is not as useful as being able to rely on the data written to transient storage as if it were regular storage
It can also be supported by not reverting and instead returning an error code
Tried to flesh out some of the time complexity stuff and it seems like it justifies a gas cost more similar to hot `SLOAD`/`SSTORE`
=> fix: edit eip-1153.md to treat transient storage the same as persistent storage with regards to reverts

EIPS/eip-4361.md
This is the draft PR for [Sign-In with Ethereum](https://notes.ethereum.org/@djrtwo/sign-in-with-ethereum-RFP). Development is happening in the open on [community calls](https://forms.gle/bJX99EJqExq66J2c7). 
Latest updates about the project can be found at https://login.xyz
TODO:
=> Create EIP-4361: Sign-In with Ethereum

EIPS/eip-1.md
https://eips.ethereum.org/EIPS/eip-1#eip-header-preamble
I have no idea why it is rendering that way, this is a feeble attempt to fix it.
=> Attempt to fix rendering of header preamble.

EIPS/eip-1.md
Update EIP-1 to discourage use of Issues for "discussion-to" and "EIP number"
=> Update EIP-1 to not use Issues for EIP number

.github/workflows/auto-merge-bot.yml, .github/workflows/auto-stagnate-bot.yml, .github/workflows/greetings.yml, .github/workflows/manual-bot-rerun.yml, .github/workflows/rerun-bot-pull-request-review.yml, .github/workflows/rerun-bot-workflow-run.yml, .github/workflows/stale.yml
This patch adds a condition to check and skip if the repository isn't 'ethereum/eips', solving the problem for forked branches.
Issue Ref: https://github.com/ethereum/EIPs/issues/4526
Sample test run: https://github.com/mryalamanchi/EIPs/runs/4579216649?check_suite_focus=true
Kindly review and merge
Note: The `if` checks don't allow for case-insensitive, as mentioned in the docs. 
So will have to keep an eye out if this can cause any problems later.
=> Patch for preventing GH actions/bots to run on the forked branches

EIPS/eip-4337.md
The logic on the snippet is wrong (i.e. having opsSeen > 0 and opsIncluded = 0 would return "OK" every time).
=> Fix pseudocode on EIP-4337 paymaster reputation status

EIPS/eip-4626.md
Replaced the `calculateShares` and `calculateUnderlying` requirements for a longer description that includes which function behaviour should they match, with an explanation on the rationale section.
=> calculate* requirements and rationale

EIPS/eip-4626.md
Descriptions rewritten for clarity
=> Rewrite the `calculate*` descriptions

EIPS/eip-4361.md
The spec's ABNF and the ABNF in the reference implementation all mandate `domain` and `chainId` to be required fields in a message, so we add them to the specification text for completeness as well.
Comment on Ethereum Magicians is here: https://ethereum-magicians.org/t/eip-4361-sign-in-with-ethereum/7263/11
=> EIP-4361: fix mandatory fields (domain & chainId)

EIPS/eip-4626.md
The functions re now described in more precise language, covering all parameters and return values. The `skimbatch` mention has been replaced by an actual description.
=> Tighter function descriptions

EIPS/eip-4626.md
Mention of exact parameters, and more clarity between `calculate*` and other functions
=> Exact parameters, `calculate*` descriptions

EIPS/eip-4573.md
=> No LaTex :(

EIPS/eip-3978.md
Adding gas refunds for reverted LOGs since the blockchain database was never modified.
=> [EIP-3978] Add LOGs gas refunds

EIPS/eip-4626.md
After an intense internal discussion, we have decided that 4 preview functions are needed, one for each of the 4 mutable functions. Significant use cases would either not be possible or would be not compliant if using a single `exchangeRate` function.
On the other hand, to allow easier integration of the simpler use cases, `exchangeRate()` has been kept as an alias for `redeemPreview(10**decimals())`
=> EIP-4626: Preview functions

EIPS/eip-4626.md
Update to add `caller` context to `max*` methods.
This changes context so that implementors can return discretionary values in case of a whitelist or deposit limit use case, or if there is some withdrawal limit or timelock in place that a given `caller` must use external means to configure prior to calling the mutable methods.
=> refactor: add caller context variable to `max*` view methods

EIPS/eip-4626.md
The function name is `totalAssets` and uses a name return value of `totalAssets`. If this YAML is used to auto-generate Solidity, it will result in a shadowing warning/error.
=> 4626: Tiny clarification for ABI

EIPS/eip-2930.md
I cannot find any reference to why the non-zero call-data byte cost should be `12` and not `16` and didn't get any response on the Forum; so I assume it is a bug?
https://ethereum-magicians.org/t/eip-2930-optional-access-lists/4561/41
Was there any other proposal after EIP-2028 that change this?
=> EIP-2930: bump calldata costs to 16

EIPS/eip-3668.md
The following issues were raised during the last call process and addressed:
- Optional (for gateways) support for POST requests because of the 2k limit on URL length.
- Additional notes in the security section about fingerprinting risks and how to mitigate them.
- Additional notes on how CCIP read aware contracts should handle nested calls.
With these addressed I do not believe there is any further barrier to moving this EIP to Final status.
=> Move EIP 3668 to Final

EIPS/eip-2612.md
This PR moves EIP-2612 to Review. EIP-2612 enjoys widespread adoption, and imho should be moved forward in the EIP process. I have spoked with the EIP's author, @MrChico , and has told me that he is content with the specification as-is, and would be interested and it seeing it move forward.
=> move 2612 to Review

README.md
Related to EIPIP meeting https://github.com/ethereum-cat-herders/EIPIP/issues/101#issuecomment-1011094223
---
Please accept this PR and also update the repository description from:
> The Ethereum Improvement Proposal repository
to 
> This repository tracks the ongoing improvements to Ethereum
---
This PR takes inspiration from https://github.com/apple/swift-evolution
=> Spell out mission statement, fixes #1128

EIPS/eip-4361.md
EIP 4361 states that 
> address is the Ethereum address performing the signing conformant to capitalization encoded checksum specified in EIP-55 where applicable.
But the example does not use EIP-55 checksum encoding. This PR fixes that.
=> eip-4361: apply capitalization checksum

EIPS/eip-4803.md, EIPS/eip-draft-gaslimit.md
This is a follow up of [ACD#120](https://github.com/ethereum/pm/blob/master/AllCoreDevs-Meetings/Meeting%20120.md#limiting-account-nonce-eip-2681-vs-3338) where it was agreed to follow up the EIP-2681 and split more of EIP-1985 content into individual EIPs.
=> EIP-4803: Transaction gas limit field

EIPS/eip-4626.md
`assetsPerShare` was removed in a previous PR, and is now being replaces by `convertToAssets` and `convertToShares`.
These two functions allow to implement robust price oracles from the Vault, since the `preview` methods are manipulable due to their exact nature. They are partially applied manipulations for the reasons explained in [this article](https://hackernoon.com/getting-prices-right).
=> EIP 4626 - Add `convert` methods to provide price data

EIPS/eip-4626.md
- Use `owner` and `receiver` consistently, and rework the sentences where they appear for better grammatical flow and precision.
- Talk about vault shares in lowercase
- Introduce a couple of missing "exactly" remarks.
=> EIP 4626 - Fix parameter names

EIPS/eip-4626.md
The reasons for `preview*` and `convert*` functions can now be easily inferred from the security considerations.
=> EIP 4626 - Removed outdated info from rationale

EIPS/eip-2681.md
Unfortunately we have to update the spec of this retroactive EIP, because there was misunderstanding regarding how CREATE/CREATE2 instructions report nonce overflow error.
It makes much more sense to return 0 rather than abort entire execution in this case, because this is like all other create-specific errors are reported (e.g. insufficient balance for transfer, account already exists, code size above limit, code starts with 0xEF)
And in fact I assumed that 0 result is the expected behavior both in [go-ethereum implementation](https://github.com/ethereum/go-ethereum/pull/23853) and in [tests](https://github.com/ethereum/tests/pull/934), and these are already merged and released.
cc @axic @holiman
=> EIP-2681: Fix CREATE/CREATE2 max nonce error reporting rule

EIPS/eip-4399.md
* Renames the EIP, opcode and block header field
* Adjusts specification and other sections accordingly
* A bit of polishing here and there
=> EIP-4399: Rename RANDOM to PREVRANDAO

EIPS/eip-1.md
Currently the list does not format as an unordered list, as I believe is the intent of the author.
=> Remove line breaks in list to properly format as unordered list

.gitignore
This allows for GitPod (https://gitpod.io/) to be used for editing, without polluting the repository with a `.gitpod.yml` file. It is currently not possible to disable this feature, so the alternative to adding it to the gitignore is manually deleting the file every other commit.
=> Add .gitpod.yml to gitignore

EIPS/eip-1.md
External links aren't durable, and may not necessarily permit redistribution. Some links _may_ be durable and permit redistribution, but determining which links are/do is a subjective and onerous task for editors.
That said, I've chosen `SHOULD NOT` over `MUST NOT` to allow for special cases.
**Note to editors**: Signal approval with a comment, just in case the bot auto-merges on approval.
=> Advise against external links & add myself as an active editor

EIPS/eip-4844.md
This PR moves the consensus-layer part of EIP 4844 to the github.com/ethereum/consensus-specs repository.
See PR https://github.com/ethereum/consensus-specs/pull/2850
During the move various issues were also corrected in the consensus part:
- Fix missing argument to a function call
- A few renames to fit consensus specs patterns
- Define `shard` field for forward compatibility in `BlobsSidecar`
- Expand p2p specs
- Define new `SignedBlobsSidecar` for DoS protection during initial gossip
- Misc integration (primarily things to define a consensus-layer feature fork)
=> EIP-4844: Move consensus layer part to consensus specs repository

EIPS/eip-4881.md
Sub-section headings should be bold and image shouldn't take up the whole page on high-res screens.
=> Improve Rendering of EIP-4881 on eips.ethereum.org

EIPS/eip-4844.md
- `v` is now encoded as `y_parity`, like EIP-1559 (and the AL tx type also) does.
- intrinsic gas now adds `Gtxcreate` (yellow paper gas cost for contract creation by tx) and access-list intrinsic gas.
Thanks to [yperbasis](https://ethereum-magicians.org/u/yperbasis) on eth-magicians for reporting these two issues.
This PR is getting auto-merged, but happy to adjust again if anything is wrong/missing.
The `21000` -> `20000` intrinsic gas cost reduction was already there since the original blob-transactions proposal by Vitalik ([here](https://notes.ethereum.org/@vbuterin/blob_transactions)). I realize we may need to add an explanation, I asked the other authors for clarification. In general it should encourage usage of the new SSZ-encoded transaction type.
=> EIP-4844: v -> y_parity like EIP-1559, and fix intrinsic gas

EIPS/eip-725.md
- Remove `SupportedStandards:ERC725Account` dataKeys section, as per [PR#64 in ERC725Alliance/ERC725 repository.](https://github.com/ERC725Alliance/ERC725/pull/64/commits/6daac48fd9b0820a34b27de804c31fdd1f922c6e)
- Prettify Markdown with prettier
=> EIP725 - remove 'SupportedStandards:ERC725Account

EIPS/eip-3540.md
PR fixes a small typo referencing a wrong EIP in the EIP specification.
=> Small reference typo correction in EIP-3540 (EVM Object Format)

assets/eip-712/Example.js
fixes the eip 712 javascript example (keccak on strings)
using ethereumjs-util `7.1.3` and node `16.10.0`
ref https://github.com/ethereumjs/ethereumjs-monorepo/commit/438b859d0184430ae22ce516c4f7f3b23fd10ac8
=> EIP 712 assets: fix example.js (cosmetic)

EIPS/eip-4760.md
Deactivate SELFDESTRUCT by changing it to SENDALL, which does recover all funds to the caller but does not delete any contract code or storage. In order to give applications good time to switch to new constructions, do this via a stage of exponential gas cost increases.
=> EIP-4760: SELFDESTRUCT bomb

EIPS/eip-4762.md
This EIP introduces changes in the gas schedule to reflect the costs of creating a witness. It requires clients to update their database layout to match this, so as to avoid potential DoS attacks.
=> EIP-4762: Statelessness gas cost changes

EIPS/eip-4758.md
This EIP deactivates the `SELFDESTRUCT` opcode, and instead renames it to `SENDALL`, with the only renaming functionality being to move all funds to the caller.
=> EIP-4758: Deactivate selfdestruct

EIPS/eip-4895.md
This point came up on ACD today to not nest the RLP encoding. This PR updates the EIP to reflect that.
=> Update EIP-4895: do not nest RLP encoding

EIPS/eip-721.md
Fixing typo for function name.
Actually I'm not sure if it is intended or just a typo, but there is no function with this name even though it is wrapped with backquotes.
=> Fixed typo on eip-721.md

EIPS/eip-4881.md
Since this is the first version of this endpoint, it should be `v1`.
=> Fixed Deposit Snapshot Endpoint

EIPS/eip-4931.md, EIPS/eip_generic_token_upgrade_standard.md
Create a standard interface for upgrading ERC20 token contracts.
=> EIP-4931 - Generic Token Upgrade Standard

EIPS/eip-2929.md, EIPS/eip-2930.md
Both EIP-2929 and EIP-2930 have been added in the Berlin hard fork.
=> Set FORK_BLOCK in EIP-2929 and EIP-2930

.github/workflows/auto-merge-bot.yml
This is a test PR. I would like exactly one EIP editor to approve this, and NOT manually merge.
From the EIP bot logs, it appears that only one EIP editor approval is required to make changes to the editor list: https://github.com/ethereum/EIP-Bot/issues/79. This PR tests that by making a normal change to the workflow (which should probably then be reverted if it merges).
If exactly one editor approves this and this is merged, then https://github.com/ethereum/EIP-Bot/issues/79 is a real issue. Otherwise, it's a false alarm.
CC @MicahZoltu @lightclient @SamWilsn
=> [EIP EDITOR NEEDED TO] Debug the EIP bot

EIPS/eip-5065.md
Add a new instruction that transfers ether to a destination address without handing over the flow of execution to it. It should work similarly to how `SELFDESTRUCT` transfers ether to the destination without making a call to it.
=> EIP-5065 - Instruction to transfer Ether

EIPS/eip-3540.md
This implementation variant does not handle some of the cases we
currently care about. E.g. section size should never be 0.
=> EIP-3540: Remove Simplified Implementation section

EIPS/eip-4400.md
Signed-off-by: Daniel Ivanov <daniel.k.ivanov95@gmail.com>
Updating the restriction on changing the address of the consumer after transfer based on the following [feedback](https://ethereum-magicians.org/t/erc-4400-erc-721-consumer-extension/7371/21?u=daniel-k-ivanov).
=> Update EIP4400 based on community feedback

EIPS/eip-4906.md
This standard is an extension of ERC-721. It proposes adding a `MetadataUpdate` event to ERC-721 tokens.
=> EIP4906: ERC-721 Metadata Update Extension

assets/eip-5027/0001-unlimit-code-size.patch
I was hoping that this file would fail once, not every time someone submits a PR.  Unfortunately I was wrong.  I have no idea if this will invalidate the patch, but I'm optimistic that the diff is lenient on line lengths and having a few more characters than the diff's default line length won't break anything.  😬
=> Fixes "spelling error" in diff

EIPS/eip-4844.md
In the `validate_blob_transaction_wrapper` function, it uses `blob_commmitments` which doesn't make sense. It makes more sense when it uses `blob_versioned_hashes` instead.
=> EIP-4844: Change to versioned hashes

EIPS/eip-4400.md
1. Change paragraphs to one line. The markdown renderer will add the newlines automatically.
2. Add a space before and after the slash makes text easier to read.  Reference: https://www.grammarly.com/blog/slash/
=> EIP-4400: Text format optimization

EIPS/eip-5007.md, EIPS/eip-TimeNFT.md, assets/eip-5007/.gitignore, assets/eip-5007/README.md, assets/eip-5007/contracts/ERC5007.sol, assets/eip-5007/contracts/ERC5007Demo.sol, assets/eip-5007/contracts/IERC5007.sol, assets/eip-5007/migrations/1_initial_migration.js, assets/eip-5007/package.json, assets/eip-5007/test/test.js, assets/eip-5007/truffle-config.js
This standard is an extension of ERC-721. It proposes some additional property(`startTime`, `endTime`,`originalTokenId`) to help with the on-chain time management.
=> EIP5007: TimeNFT, ERC-721 Time Extension

EIPS/eip-3156.md
Fixed comment in code example.
The fee is in bps units (see in `_flashFee`, division by 10,000) -> hence 1 unit of fee is 0.01%
@alcueca
=> EIP3156: small fix in code example

EIPS/eip-2364.md
CC: @karalabe, @timbeiko
Closes #2365
=> Finalize EIP-2364

EIPS/eip-4844.md
Both (interactive) optimistic rollups and zk rollups can use the point-evaluation precompile, so we can drop the blob-verification precompile to reduce complexity.
=> EIP-4844: remove blob-verification precompile in favor of point-evaluation precompile

EIPS/eip-4626.md
The language on reusing the `transferFrom` pattern in `withdraw` and `redeem` has been updated to make clear that both flows must be implemented.
=> fix: Split `transferFrom` flows

EIPS/eip-4626.md
CALLER is a solidity OPCODEs, in vyper [OPCODES](https://github.com/vyperlang/vyper/blob/efe1dbef873af6995833d1220a3d56978dfb9de0/vyper/evm/opcodes.py#L69) are not [allowed](https://github.com/vyperlang/vyper/blob/48e326f0685723e24c9d8daa8d13a4011099483b/vyper/semantics/namespace.py#L109) to be used.
I suggest replacing caller by `sender`
=> 4626 -> fix`caller` is a reserved keyword in vyper

.github/workflows/auto-merge-bot.yml
Fixes https://github.com/ethereum/EIP-Bot/issues/48 (probably)
I am making this a draft PR so it doesn't auto-merge. Please provide feedback if there's something that I've missed that might cause an issue!
Explanation: Always runs the EIP Bot (even with drafts). This will also (once some copyediting features are put in place) help users get their EIPs up to spec before requesting a review. It then disables the auto-merge step when the PR is in the draft state.
=> Run EIP bot on draft PRs

EIPS/eip-1.md, EIPS/eip-5069.md, EIPS/eip-apprentice-handbook.md, README.md
CC: @poojaranjan
I've heavily modified https://hackmd.io/@poojaranjan/EIP-ERC-Editor-handbook to suit the EIP format and to make the document more formal, specific, inclusive, and easier to understand.
Notes to EIP-1 and the README are added to increase awareness.
Items that need discussion:
Fixes https://github.com/ethereum/EIPs/issues/5048
=> EIP-5069: EIP editor handbook in EIP form

assets/eip-4973/ERC-4973.sol
A compile error occurs because the ownerOf function is overridden but there is no "override" keyword
=> fix: Added "override" keyword to the ownerOf function in the ERC-4973 contract

EIPS/eip-5006.md
EIP5006: Change Status to Last Call
=> EIP5006: Change Status to Last Call

EIPS/eip-5131.md, EIPS/eip-603.md
=> Add EIP-5131: ENS Subdomain Authentication

EIPS/eip-5189.md
`master` is currently broken due to these typos: https://github.com/ethereum/EIPs/runs/7322877908?check_suite_focus=true
Not sure how #5189 was merged.
=> Fix typos in EIP-5189

.github/workflows/auto-merge-bot.yml, .kodiak.toml
This fixes the "pull request unstable" bug.
~~**The `EIP Auto-Merge Bot` check MUST be added to the branch protection required checks before this can be safely merged.**~~
Never mind, it already is. Yay!
=> Fix eth-bot automerging & configure kodiak

EIPS/eip-5313.md, EIPS/eip-xxx.md
=> EIP-5313 Light Contract Ownership

EIPS/eip-712.md
There have been no substantial changes to this EIP in over a year.
This PR also includes non-normative changes to adapt the EIP to new formatting requirements. A mention of "EIP-719" was removed because said EIP doesn't exist. The "Implementation" section was removed as it consisted of an implementation log that doesn't belong in the EIP format.
=> Move EIP-712 to Last Call

.github/workflows/stale.yml
- Massively reduces the time required for an issue or PR to become stale or be closed because of it
- Reduces the verbosity of the message
- Reduces the frequency that the bot is run at
- Adds a "long-term" label that can be applied to PRs or issues that are awaiting e.g. author approval (will need to manually be created).
- Other stuff
=> Update Stale Bot

.github/workflows/stale.yml
Reverts a couple behavior changes in the bot introduces in #5365.  In the future, please do not merge changes to non-EIPs without getting feedback/review/approval from other editors.
=> Reverting behavior changes that didn't get editor approval.

.github/workflows/auto-merge-bot.yml
The current EIP Bot version is out of date. This PR bumps it to the most recent version.
Blocker: https://github.com/ethereum/EIP-Bot/pull/105
=> Update EIP Bot

_layouts/eip.html
We want to minimize the number of users that use non-final standards, so we have `[DRAFT]` noted in a few places on the rendered page.  Unfortunately, We forgot to update with `Review`, `Stagnant`, and `Withdrawn` so those won't get the appropriate tag.
=> Adds DRAFT tag to items in review/stagnant/withdrawn when rendered.

EIPS/eip-4987.md, assets/eip-4987/Consumer.sol, assets/eip-4987/IERC1155Holder.sol, assets/eip-4987/IERC20Holder.sol, assets/eip-4987/IERC721Holder.sol, assets/eip-4987/Vault.sol
This moves EIP-4987 into `Review` and also cleans up the example assets.
See ongoing discussion here
https://ethereum-magicians.org/t/erc-standard-for-held-non-fungible-token-nfts-defi/7117
=> Move EIP-4987 to Review

EIPS/eip-5192.md, EIPS/eip-5555.md
- I was looking at many of the current Soulbound token implementations and it upset me that they all revert upon transfer
- At least it'd be nice if developers would allow wallets to understand that a token is permanently non-transferrable
- With my previous attempt at Soulbound tokens (EIP-4973), we got a bit lost in the details
- This attempt is much cleaner: Yes, it still permanently binds a token to an account. But that's fine: Users are doing this and it'd be dogmatic to make that a taboo around here
- Rather, with this change, I think, if implementers adopt it, it'll actually make the life of wallet implementers easier.
- I put status: Review right away. I think this EIP is done and can be peer-reviewed
=> Add EIP-5192 - Minimal Soulbound NFTs

.github/workflows/stale.yml
Reverts ethereum/EIPs#5360
cc @Pandapip1 I'm reverting this, even though I think it is a good change, in an effort to disincentivize editors from merging changes to the process without getting approval from any other editors or waiting a sufficient amount of time for review.  This isn't the first time someone has merged without acquiring approval/waiting, and I want to make sure that it is clear to everyone that just merging anyway and saying "oops"/"sorry" afterward isn't a viable strategy for forcing changes through.
=> Revert "Change Stale Thresholds"

EIPS/eip-831.md
This EIP was stagnant but used - was contacted by @3esmit to resurrect it and add a eth shorthand as alternative to the verbose "ethereum" scheme.
Resurrecting is a no-brainer - the shortcut could use some discussion as it might be problematic e.g. when registering the scheme - so this might need a check.
Let's discuss it here when there is time: https://github.com/ethereum-cat-herders/EIPIP/issues/159
=> Resurrect EIP-831 and add "eth" shorhand

.github/workflows/auto-merge-bot.yml, EIPS/eip-1.md
**Context**: We now have other editors who are relatively active so the response time for authors isn't as bad as it used to be (a week vs a year).  It also sounds like the process for consensus changes will be moving over to the executable specs repository in the near future and since that is the piece I care most about, I am less concerned now than I used to be about the EIP process remaining credibly neutral.
I also will be unsubscribing from this repository, so someone should probably take up the the task of making sure stuff doesn't get lost in the cracks.
**Note**: I also reordered the Emeritus editors list to be alphabetical rather than what appeared to be random order.
=> Removes MicahZoltu as EIP editor.

EIPS/eip-5375.md
There is currently no standardized way to determine the author of an NFT, and common techniques (custom methods and using the minter’s address) have serious drawbacks. This standard provides a standardized JSON field for author information, in addition to Author Consent Proofs (ACPs), which prove that an address agreed to be named as the author.
[Ethereum Magicians Discussion Thread](https://ethereum-magicians.org/t/eip-5375-nft-authorship/10182)
=> EIP-5375 - NFT Authorship.md

.github/workflows/auto-label-bot.yml
All this does is add a name to the only job that for some reason doesn't have one.
=> Add Name to Label Bot

EIPS/eip-4750.md
Type section in the container spec should better be optional in order to maintain backwards-compatibility with EOF1 spec.
=> EIP-4750: Make type section optional

EIPS/eip-712.md
There have been no comments since [Last Call was announced](https://ethereum-magicians.org/t/eip-712-eth-signtypeddata-as-a-standard-for-machine-verifiable-and-human-readable-typed-data-signing/397/35?u=frangio).
=> Move EIP-712 to Final

EIPS/eip-5192.md
Add `event LockingStatusChanged(uint256 tokenId, bool status)`
So the locking status of the NFT could be updated  off-chain.
=> EIP-5192: add event LockingStatusChanged(uint256 tokenId, bool status)

.github/workflows/auto-label-bot.yml
Fix: Doesn't remove all the labels now.
=> Update label bot

.github/workflows/auto-review-trigger.yml
Fixes https://github.com/ethereum/EIP-Bot/issues/49
=> Add EIP-Bot retrigger functionality

.codespell-whitelist
It thinks the user meant "compiles".
=> Add complies to whitelist

.github/workflows/post-ci.yml
Apparently it uses non-standard naming
=> Fix CI error label adding

.github/workflows/ci.yml
`eipw-action` now publishes the compiled output to a different branch.
=> Switch to `dist` branch of `eipw-action`
