ethereum/EIPs

- EIPS/eip-5.md
> EIP 5 for a change in gas and memory semantics for CALL and CALLCODE.

- EIPS/eip-1.mediawiki
> Fix formatting in EIP 1

- README.md
For https://github.com/ethereum/EIPs/issues/163
> Catalog EIP 150 as accepted

- README.md
> HF2 update of README.md

- README.md
Add EIP170 (Contract code size limit)
> Add EIP170

- EIPS/eip-1.md
remove duplicate section
This is the suggested template for new EIPs.
Note that an EIP number will be assigned by an editor. When opening a pull request to submit your EIP, please use an abbreviated title in the filename, `eip-draft_title_abbrev.md`.
EIP: <to be assigned>
Title: <EIP title>
Author: <list of authors' names and optionally, email addresses>
Type: <Standard Track | Informational | Meta>
Category (*only required for Standard Track): <Core | Networking | Interface | ERC> 
Status: Draft
Created: <date created on, in ISO 8601 (yyyy-mm-dd) format>
Requires (*optional): <EIP number(s)>
Replaces (*optional): <EIP number(s)>
"If you can't explain it simply, you don't understand it well enough." Provide a simplified and layman-accessible explanation of the EIP.
A short (~200 word) …
> remove duplicate section eip-1.md

- EIPS/eip-184.md
This EIP introduces new EVM opcodes and conditions on EVM code to support subroutines and static jumps...
> Subroutines and Static Jumps for the EVM

- README.md
Redo the table of EIPs, and define terms for EIP Statuses
> redo table of EIPs in README

- EIPS/eip-6.md
> status is Final

- EIPS/eip-141.md
- README.md
Adds EIP141 and includes it in the accepted list.
Finalises #141.
> Adds EIP141 (invalid instruction)

- README.md
Since every EIP in the table is of type "Standard", the Type column is redundant.
> add EIP-186 to consideration table, remove Type column

- EIPS/eip-181.md
If nobody objects, given this is already widely deployed and has been open for discussion as an issue for some time, I would like to fast-track this to final status.
> ERC: Ethereum Name Service reverse resolution support

- EIPS/eip-137.md
If nobody objects, given this is already widely deployed and has been open for discussion as [an issue](https://github.com/ethereum/eips/issues/137) for some time, I would like to fast-track this to final status.
> ERC: Ethereum Name Service

- EIPS/eip-ens-initial-registrar.md
> Clearer explanation of revealing a bid late

- EIPS/eip-158.md
- EIPS/eip-161.md
create files for https://github.com/ethereum/EIPs/issues/158 and https://github.com/ethereum/EIPs/issues/161.
> create files for EIPs 158 and 161

- EIPS/eip-170.md
create file for https://github.com/ethereum/EIPs/issues/170
> create file for EIP-170

- EIPS/eip-55.md
Creates a file for https://github.com/ethereum/EIPs/issues/55
Also includes a wallet/exchange adoption table.
> create file for EIP-55 (mixed-case address checksums)

- README.md
> fix link to EIP-2 in docs

- EIPS/eip-162.md
As implemented:
https://github.com/ethereum/ens/blob/mainnet/contracts/HashRegistrarSimplified.sol#L379
> Revert to more closely describe implementation

- EIPS/eip-55.md
Adds Etherwall 2.0.1+ to the supported wallets list
> * add Etherwall 2.0.1 to supported list

- EIPS/eip-606.md
- EIPS/eip-draft_hfmeta_homestead.md
> Add meta EIP for Homestead

- README.md
> Add EIP-658 to the list of accepted EIPs

- EIPS/eip-160.md
add file for https://github.com/ethereum/EIPs/issues/160
> add file for EIP 160 (EXP cost increase)

- EIPS/eip-1.md
> whisper link fixed

- EIPS/eip-1.md
This PR puts `eip-1.md` under public domain.
@Souptacular @cdetrio please approve as the copyright holders.
> Put eip-1.md under public domain

- EIPS/eip-609.md
It's marked as final on the README.md but still hows as draft in its own EIP md
> Update EIP609 (Byzantium) status to final

- EIPS/EIP-draft-getLogs-by-block-hash.md
- EIPS/eip-234.md
> Adds an EIP for getting logs by a block hash.

- EIPS/eip-779.md
This completes the HF table https://github.com/ethereum/EIPs/pull/676
> add informational EIP for DAO HF

- EIPS/eip-141.md
The EIP has been considered Final and is included in all major clients.
Updated the document to reflect this.
> Update status EIP-141 to Final

- EIPS/eip-1.md
As mentioned in EIP-1 itself 
> Some Informational and Process EIPs may also have a status of “Active” if they are never meant to be completed. E.g. EIP 1 (this EIP).
> Update status EIP-1 according to own specification

- EIPS/eip-155.md
Acquired from https://github.com/ethereum/EIPs/blob/master/EIPS/eip-607.md
> Adds fork block number.

- README.md
> Add EIP-1 to the Finalized EIPs list

- EIPS/eip-150.md
> Add links to issues 90 and 114.

- EIPS/eip-170.md
> EIP-170: Add parameters, capitalize Ethereum and use an em dash.

- EIPs/eip-4.md
- README.md
Clarify authorship and reformat to markdown.
> clarify EIP 4 author

- EIPS/eip-55.md
Added EIP55 Swift implementation link.
> Add EIP55 Swift implementation link

- EIPS/eip-20.md
> Fixed a typo

- EIPS/eip-721.md
I spent at least 2 minutes trying to figure out where the final version of this was, until I realized this line just needed to be updated.
> Update preamble to indicate final status

- EIPS/eip-145.md
> Update eip-145.md test links

- EIPS/eip-162.md
I'm adding myself as an co-author of this EIP.  Nick and Maurelian can vouch that I wrote a large part of this text and helped design the initial mechanisms
> Updating authors of ENS registrar

- EIPS/eip-198.md
Due to the copyright assignment, only @vbuterin may review and merge this PR.
> Rename bigint_modexp.md to eip-198.md, add new prologue and copyrigt notice

- EIPS/eip-86.md
Due to the copyright assignment, only @vbuterin may merge this PR.
> Rename abstraction.md to eip-86.md, add copyright clause, fix header.

- README.md
- _data/statuses.yaml
- _includes/eiptable.html
Also adds an explicit list of EIP statuses and outputs in the same order on each page.
> Update README, make table widths consistent

- EIPS/eip-3.md
> eip-3.md --> Status: Deferred

- EIPS/eip-609.md
> Updated Category to Meta

- EIPS/eip-721.md
> Fixed a few spelling errors

- EIPS/eip-778.md
> Revert "EIP-778: fix type field"

- EIPS/eip-616.md
> Fix email address on eip-616.md

- EIPS/eip-867.md
Fix links to e-mail addresses for site generation
> Update eip-867.md to fix author links

- EIPS/eip-884.md
Matches up verbage of both `VerifiedAddressAdded` and `VerifiedAddressRemoved`.
> Replaced "its" with "and".

- EIPS/eip-1011.md
Add link to PoW reward reduction analysis:
https://gist.github.com/djrtwo/bc864c0d0a275170183803814b207b9a
> EIP 1011 - add link to pow reward reduction analysis

- EIPS/eip-908.md
https://ethereum-magicians.org/t/eip-908-reward-full-nodes-and-clients/241
> EIP-908: change discussions-to

- EIPS/eip-926.md
- EIPS/eip-927.md
These drafts should not have been merged as-is. Sorry!
> Rename and fix EIP-X-nickjohnson drafts

- EIPS/eip-1077.md
* 191 compatibility
* removes timestamp/nonce duality
* adds Transaction Type
> Updates based on feedback

- EIPS/eip-1078.md
> 10XX -> 1077

- EIPS/eip-1077.md
> increases backwards and forwards compatibility

- EIPS/eip-721.md
Thank you @spalladino for bringing this up.
We have seen zero opposition to thing change during our review period.
> Remove requirement of 50,000 gas

- EIPS/eip-20.md
> Fix typo, releated->related

- EIPS/eip-1066.md
> Fix typos on eip-1066

- EIPS/eip-721.md
> Fix description of _from parameter in onERC721Receiver.

- EIPS/eip-721.md
Thank you @shrugs.
This supersedes https://github.com/ethereum/EIPs/pull/1151
> Fix 721 approve approval

- EIPS/eip-1155.md
> eip-1155 Crypto Item Standard

- EIPS/eip-1102.md
This PR updates the verbiage around provider exposure in EIP-1102.
> EIP-1102: update provider exposure verbiage

- EIPS/eip-1102.md
This PR updates pseudocode indentation in EIP-1102 for consistency.
> EIP-1102: update formatting

- EIPS/eip-1203.md
Discussion thread for [ERC-1203](https://github.com/ethereum/EIPs/issues/1203)
> ERC-1203 Multi-Class Token Standard (ERC-20 Extension)

- EIPS/eip-1052.md
> EIP-1052: Add missing parts of the specification

- EIPS/eip-649.md
- add author's handle
- add discussion-to link
> EIP-649: update to correct header format

- EIPS/eip-777.md
- Clarifications of ambiguous aspects
- Rephrasing to improve clarity and be more explicit
- Define default operators
- Add standard burn functions
> ERC777: Update and clean the specs

- EIPS/eip-1193.md
Updates to EIP 1193 including its title
> Update EIP 1193

- EIPS/eip-1240.md
> Minor changes from feedback.

- eip-X.md
> Correct discussions-to destination

- EIPS/eip-1234.md
https://github.com/paritytech/parity-ethereum/pull/9187
> Add implementation for EIP-1234

- EIPS/eip-234.md
> Checks Geth implementation box for EIP 234..

- EIPS/eip-1202.md
- EIPS/eip-998.md
* Adds a section to the EIP for bottom-up ERC20 composable tokens.
---
> Add ERC20 Bottom-Up Composables to ERC998

- EIPS/eip-1167.md
> Moving EIP-1167 to Last Call status

- EIPS/eip-1193.md
Add missing comma in code example. Thx @nivida
> Add missing comma in eip-1193.md code example

- EIPS/eip-926.md
- EIPS/eip-927.md
> Fix capitalisation of "standards track"

- EIPS/eip-1167.md
> Added ContractProbe to Ropsten

- EIPS/eip-1102.md
This pull request includes syntactical updates to the example provider detection code in EIP-1102.
> EIP-1102: Update example provider request code

- EIPS/eip-1285.md
Updated specification section with more detailed specification along with an implementation example of the EIP in the Geth client. Improved the rational section. Added copyright notice.
> EIP-1285 Updated specification section. Added copyright.

- EIPS/eip-820.md
- Cleanup of the code and tests
- Consistent compilation and metadata
- Nice address for the registry
> ERC820: Cleanup

- EIPS/eip-777.md
ERC #777: Update granularity/decimals and minting specs
> EERC777: Update to granularity/decimals and minting specs

- EIPS/eip-1109.md
As discussed in the core DEV meeting, this EIP is changed to add a specific PRECOMPILEDCALL.
> PRECOMPILEDCALL defined

- EIPS/eip-1234.md
- change EIP-1234 status to accepted as per https://github.com/ethereum/pm/issues/55
- change the effective delay to 12 months as per https://github.com/ethereum/pm/issues/55
> Move EIP-1234 to accepted; change delay to 12 months

- EIPS/eip-1102.md
This pull request updates EIP-1102 so that the Promise resolved after user approval is resolved with the public keys associated of the current user's accounts.
> 1102: Return accounts upon user approval

- EIPS/eip-1154.md
> 1154 edits

- EIPS/eip-1193.md
Special thanks to all the collaboration with the MetaMask team
> Updates eip-1193.md with latest revisions

- EIPS/eip-725.md
Fix some spelling and other tiny grammar mistakes for 'eip-725.md'.
> Update eip-725.md (fix typos)

- EIPS/eip-918.md
Added supporting for optional Merged Mining, Delegated Mint, and Mineable Token Metadata extensions. 
Provided a mechanism to support backwards compatibility of previous mint() method signature for interoperability with mining and pool software.
> ERC918 Extension updates

- EIPS/eip-918.md
> Fixed several typos

- EIPS/eip-725.md
> Grammar and spelling fixes in eip-725

- EIPS/eip-918.md
Updated sample code for ERC918 Delegated Mint Extension to use standard out of box web3 message signing with OpenZeppelin ECDSA contract
> ERC918 Delegated Mint Extension updates

- EIPS/eip-1102.md
This pull request updates the verbiage used throughout EIP-1102 to match [RFC-2119](https://www.ietf.org/rfc/rfc2119.txt).
> EIP-1102: Update RFC-2119 verbiage

- EIPS/eip-616.md
Need to delay this long enough be sure this is compatible with Wasm facility, and to bring it up to current formatting standards.
> Change status to deferred.

- EIPS/eip-20.md
I created a new PR, as I broke my old branch.
> Fix OpenZeppelin ERC20 Standard Token link.

- EIPS/eip-20.md
New PR due to name change of the file.
See https://github.com/ethereum/EIPs/pull/789 for the original PR
> Remove link to force 0 implementation (updated)

- EIPS/eip-875.md
A simple non fungible standard with inbuilt atomic swaps.
Unlike 721, it is easy to: 
- Query balance
- Transfer in bulk
- More efficiently make calls to enquire from nodes
For #875
> added eip875

- EIPS/eip-155.md
Added Ubiq mainnet and testnet chain ID's.
> Added Ubiq chain ID's

- EIPS/eip-1283.md
Add formal proof for EIP-1283 and refactored motivation/rationale section.
> EIP-1283: Add a formal proof

- EIPS/eip-1155.md
> ERC-1155 latest revisions

- EIPS/eip-820.md
This is the new two weeks last call
> ERC820: Last call fixes

- EIPS/eip-1193.md
> Update Ethereum Provider

- EIPS/eip-1155.md
> Revisions to Multi-Token ERC; Event-based enumeration and further improvements

- EIPS/eip-1102.md
This pull request updates EIP-1102 by detailing a new RPC method used to request account access.
cc @ryanio @marcgarreau
> EIP-1102: request accounts using an RPC method

- EIPS/eip-1155.md
> updates to scope approval

- EIPS/eip-1155.md
> Removing scoped approval in favor of generalized concept

- EIPS/eip-1450.md
Revised descriptions to:
- remove implication that tokens minted pursuant to the standard inherently 'comply with SEC regulations'; 
- capture that the code establishes a framework within which compliance with SEC regulations may be achieved
- make legal description more accurate (e.g., Regulation D is not 'new" (adopted in 1982!))
- If matching on email …
> Revised regulatory descriptions in EIP 

- EIPS/eip-1588.md
Proposal for a new hardfork meta to implement a new Proof-of-Work algorithm that is tuned for commodity hardware to minimize optimizations available for specialized ASICs
cc @Arachnid
> EIP-1588: Proposal for a new hardfork meta to implement a new Proof-of-Work algorithm

- EIPS/eip-1155.md
> Updates to ERC-1155

- EIPS/eip-1057.md
- Swap order of inner loop to make SIMD nature more apparent
- remove #define's
> EIP-1057 algorithm clarifications

- EIPS/eip-1155.md
> Tweaks to transfer events

- EIPS/eip-1271.md
- Rename `smart account` to `smart wallet`
- Change bool return to magicValue
> ERC-1271 : Add STATICCALL requirement

- EIPS/eip-1588.md
> edit eip-1588

- EIPS/eip-1155.md
> Last changes to ERC-1155, and fixed comments

- EIPS/eip-1155.md
>  ERC-165 signature

- EIPS/eip-1155.md
> Finalizing ERC-1155, improve readability

- EIPS/eip-1057.md
Update EIP to match latest version of the spec
> Update EIP-1057 to v0.9.2 spec

- EIPS/eip-820.md
After a discussion between @Arachnid and @jbaylina, a new last call for ERC820 has been requested.
> ERC820: Last Call

- EIPS/eip-1613.md
renamed may_relay to accept_relayed_call
returns zero on success, and error code on failure.
added post_relayed_call
> Update RelayRecipient API

- EIPS/eip-1155.md
> ERC-1155 status update to Last Call

- EIPS/eip-165.md
> EIP-165 requires EIP-214 due to its use of staticcall

- EIPS/eip-155.md
Based on information from http://progtest.net/#geth
> Add Gangnam chainid to EIP-155

- EIPS/eip-627.md
EIP 627 has been effectively final for a bit. The status of Draft confuses people (including, maybe exclusively, me). Propose to move to Final.
> Mark EIP 627 final

- EIPS/eip-55.md
> Add Trust Wallet to EIP-55 supported wallets

- EIPS/eip-1193.md
* Adds author credits
* Adds error code for "Unsupported Method"
* Clarifies addresses instead of public keys
> Updates EIP 1193

- EIPS/eip-1155.md
> Scoped-approval and expanding Rationale content

- EIPS/eip-615.md
> Gcolvin patch 1

- EIPS/eip-1193.md
Updates based on latest discussions
> EIP 1193 updates

- EIPS/eip-1767.md
@Arachnid  No material changes made to the EIP. Just addressed some typos.
> Fixed some typos on EIP-1767

- EIPS/eip-615.md
> Failed attempt to beat markdown into submission.

- EIPS/eip-615.md
> Beat on markdown harder.

- EIPS/eip-615.md
> Fix Brooke's address, some other stuff

- EIPS/eip-615.md
> Get Brooke's email right this time

- EIPS/eip-1081.md
> Fix header of EIP1081

- EIPS/eip-777.md
> ERC777: Update email

- EIPS/eip-777.md
Add `data` field to burn/operatorBurn functions
> Add `data` field to burn/operatorBurn functions

- EIPS/eip-777.md
- Add data to Burned event (Sorry I forgot that one.)
- Update Interface
> ERC777: Add data to Burned event & update interface

- EIPS/eip-777.md
Clarifications on data/operatorData
> ERC777: Clarifications on data/operatorData

- EIPS/eip-777.md
ERC777: Use external for hooks too
> ERC777: Use external for hooks too

- EIPS/eip-1155.md
> EIP-1155 Updated, scoped approval extension removed

- ISSUE_TEMPLATE.md
This updates to use the preferred citation format as per https://github.com/ethereum/EIPs#preferred-citation-format
Done for today
> Update to preferred citation format

- EIPS/eip-777.md
- Update links
- Update refs from 820 to 1820
> ERC777: Update links and refs from 820 to 1820

- EIPS/eip-721.md
Reference: https://github.com/ethereum/EIPs#preferred-citation-format
> Correct URLs to preferred citation format

- EIPS/eip-1485.md
- EIPS/eip-1488.md
EIP-1485 TethashV1 , rename EIP-1488 cause by pr conflicts
ETH ASIC Obsolete algorithm , TEthashV1
> EIP-1485 TethashV1, Obsolete ETH-Asic Machine

- EIPS/eip-1822.md
> Update the discussion link and references section

- EIPS/eip-1620.md
This PR simply adds the [ERC-1620](https://github.com/ethereum/EIPs/issues/1620) as a markdown file in the EIPs folder.
> EIP-1620: Money Streaming

- EIPS/eip-1761.md
> First draft of ERC-1761 Scoped Approval Interface

- _layouts/eip.html
> Show review end date on website

- EIPS/eip-1418.md
> EIP-1418 Blockchain Storage Rent Payment

- EIPS/EIP-draft-ens-interface-discovery.md
- EIPS/eip-1844.md
> Wrote ENS Interface discovery EIP

- EIPS/eip-1820.md
@mcdee @MicahZoltu Could you please reveiw ERC1820
@fulldecent You may want to take a look at the ERC165 part.
@nicksavers could you merge this PR please. Thanks.
> ERC1820: Last Call

- EIPS/eip-1015.md
1) Don't think it's such a great proposal anymore
2) Nobody else cared
3) Want to clean up the EIP lists
> Changing the status of this EIP to deferred

- EIPS/eip-1155.md
> Remove formatting tags from EIP-1155 markdown

- EIPS/eip-615.md
FTR, I haven't gone through the entire document.
> EIP-615: minor proof-reading, remove three unneeded words

- EIPS/eip-1155.md
This last call ended and no petition has been made to progress to Final status. Many outstanding issues remain. And now design decisions are being discussed.
This PR reverts the ERC to draft status.
> Recent ERC-1155 to draft

- EIPS/eip-1066.md
#1916 
https://github.com/ethereum/EIPs/pull/1916#issuecomment-480479797
> Revert 1066 status to Draft

- EIPS/eip-1922.md
> Post first draft for #1922

- EIPS/eip-1923.md
> Post first draft for #1923

- EIPS/eip-1344.md
Updates to EIP-1344 due to formatting comments [here](https://github.com/ethereum/EIPs/issues/1935#issuecomment-482399373)
> EIP-1344: Added missing sections

- EIPS/eip-777.md
@nicksavers Could you please merge this PR?
Thanks a lot.
> ERC777: Last Call

- EIPS/eip-1344.md
Also added @fubuloubu as an author due to previous work
> EIP-1344: Move to Last Call

- EIPS/eip-1344.md
Closes #901.
@Arachnid @fubuloubu what do you think? This EIP came out of a discussion from #901. Also it seems #901 doesn't carry any more usefulness and would be nice to close it.
> Add reference to EIP901 in EIP1344

- EIPS/eip-1679.md
As requested by @bmann rel https://github.com/ethereum-cat-herders/PM/pull/63 https://github.com/ethereum-cat-herders/PM/issues/53
Note that this PR is made with the assumption that EIP-615 will also be in the proposal list.
> Add EIP-1702 as a proposal for Istanbul hard fork

- EIPS/eip-1679.md
This adds 1884 as proposed for Istanbul
> add 1884 as proposed

- EIPS/eip-1344.md
> EIP-1344: Use present tense in the spec

- EIPS/eip-1679.md
Also, added a note about the pending audit.
> Propose EIP-1057 (ProgPow) for Istanbul

- EIPS/eip-777.md
Update last call by a week to deal with the last minute comments.
> ERC777: Update last call period

- EIPS/eip-4.md
- EIPS/eip-6.md
It seems this field is not present in EIP-1.
> Remove obsolete layer field

- EIPS/eip-1803.md
- EIPS/eip-draft_rename_opcodes.md
This change is similar to #42. Also addresses and closes #59.
> Rename opcodes for clarity

- EIPS/eip-1.md
> Add editors

- EIPS/eip-1155.md
> Updated the "Safe Transfer Rules" section to match feedback given in discussion thread. This introduces specific scenarios and rules to match.

- EIPS/eip-777.md
Move ERC777 to final. See #777 for further details.
> ERC777: Move to final

- EIPS/eip-1344.md
Noticed that the explicit dependency on EIP-155 was not documented for this proposal.
> EIP-1344: add dependency on EIP-155

- EIPS/eip-1108.md
No underlying algorithms are being changed!
> Typo fix in EIP-1108

- EIPS/eip-1155.md
> Additional rule clarity and potentially finalized updates after feedback.

- EIPS/eip-1155.md
> Added safe and batch transferFrom rules to also be explicit there and a few minor edits to match the rule(s) in the interface text.

- EIPS/eip-1679.md
- EIPS/eip-2028.md
- EIPS/eip-Calldata_gas_cost_reduction.md
Added a draft of EIP to reduce the gas cost of Calldata
> Calldata gas cost reduction

- EIPS/eip-100.md
- EIPS/eip-1077.md
- EIPS/eip-145.md
- EIPS/eip-1485.md
- EIPS/eip-150.md
- EIPS/eip-155.md
- EIPS/eip-160.md
- EIPS/eip-170.md
- EIPS/eip-4.md
- EIPS/eip-779.md
- EIPS/eip-86.md
This PR:
- adds Github usernames for EIPs which don't have any (enables those in Draft to make changes via automerge)
- fixes email formatting of EIP-1485
> Fix author fields (emails/usernames)

- EIPS/eip-1679.md
> Add more proposals to Istanbul

- EIPS/eip-1418.md
Fix per https://github.com/ethereum/EIPs/pull/1752#pullrequestreview-241668583
Thank you @axic
> Fix name formatting

- EIPS/eip-1155.md
> Last call for ERC-1155

- EIPS/eip-1803.md
- EIPS/eip-663.md
> Add discussions-to URL to EIP-663

- README.md
see: https://ell.stackexchange.com/a/31673
> fix typo: "as follows"

- EIPS/eip-1155.md
> Bump review-period-end +1 day for final checks

- EIPS/eip-1155.md
> Update Articles & Discussions with a new link

- EIPS/eip-1155.md
> ERC-1155 Final Status

- EIPS/eip-695.md
- Move to Last Call status and set the review period for 4 weeks.
- Add EIP-155 requirement.
cc @axic
> Move EIP-695 to Last Call status and add 155 requirement

- EIPS/eip-1202.md
> Update the minimized eip-1202 to get ready of publication

- EIPS/eip-823.md
The absolute link of the assets pointed to the png files of repository. They have been updated to relative paths that point to the assets in this repository.
> Updated the links of the assets

- EIPS/eip-158.md
Based on https://github.com/ethereum/EIPs/issues/158#issuecomment-324019788
> Mark EIP-158 properly: superseded and not replaced

- EIPS/eip-1702.md
> Add CC0 copyright for EIP-1702

- EIPS/eip-2028.md
Changing the name to clarify the porpuse of the EIP.
> Change EIP name and add author

- EIPS/eip-6.md
> Fix typo in EIP-6

- EIPS/eip-1761.md
> EIP-1761 update authors, minor tweaks

- EIPS/eip-2025.md
> Updated around feedback from the community

- EIPS/eip-1154.md
> Abandoned ERC 1154

- EIPS/eip-2028.md
> Set new price to 16 gas per byte

- EIPS/eip-2025.md
> Revert to original for history and withdrawing proposal.

- EIPS/eip-1056.md
Creates an actual draft EIP based on https://github.com/ethereum/EIPs/issues/1056
> EIP-1056 Ethereum Lightweight Identity implementation

- EIPS/eip-1344.md
Added:
- Updated link to reference implementation (which is WIP currently)
- Added implementation notes regarding where to obtain the value of chain ID from
> Updated EIP-1344 Implementation notes

- EIPS/eip-1767.md
> Updated current implementations

- EIPS/eip-1884.md
This PR adds more info about security considerations, and also info about testcases for 1884
> Update 1884 3

- EIPS/eip-1822.md
> Update eip-1822.md co-author email

- EIPS/eip-2159.md
Minor tweak to fix the grammar in the simple summary for EIP-2159.
> Fix wording of simple summary

- EIPS/eip-1344.md
Just updated some of the links so they appear in the autogenerated site, and also reference the correct locations.
> EIP-1344: Updated links

- EIPS/eip-1985.md
> Updates to EIP-1985

- _config.yml
- _includes/eiptable.html
- _layouts/eip.html
The section linking support is taken from #1297 and fixed by @fulldecent.
> Some Jekyll fixes

- EIPS/eip-1474.md
https://github.com/ethereum/go-ethereum/issues/20117
I found this issue and add error code -32005
> Eip-1474 add Error codes

- EIPS/eip-2266.md
https://github.com/ethereum/EIPs/issues/2266
> EIP-2266: Atomic Swap-based American Call Option Contract Standard

- EIPS/eip-2304.md
> Ens multichain

- EIPS/eip-2304.md
> Update EIP with new test vectors and better algorithm descriptions

- EIPS/eip-1191.md
Change status to Last Call and add reference to web3.js and ethereumjs-util implementations.
> EIP-1191: Change status to Last Call

- EIPS/eip-615.md
Last call passed. Bouncing to draft.
> Bounce EIP-615 to draft

- EIPS/eip-2330.md
> EIP-2330: Added Aleth pull request link

- EIPS/eip-152.md
Last call!
Via the ACD call, it looks like we're good. Let's do this thing :sunglasses:
> Update EIP-152 to reflect Final status

- EIPS/eip-1884.md
> make eip 1884 final

- EIPS/eip-1344.md
Tests are in progress of being added, created link to test case PR so readers can keep track of it.
> EIP-1344: Added link to test PR

- EIPS/eip-2330.md
> EIP-2330, Added Santiago Palladino to Authors

- EIPS/eip-1077.md
> Use Solidity highlighting in EIP-1077

- EIPS/eip-2364.md
Discussions to https://github.com/ethereum/EIPs/issues/2365.
> EIP-2364: eth/64: forkid-extended protocol handshake

- EIPS/eip-634.md
Just implementing this EIP client side and think it is not nice to have such a question in the standard. Would like to replace with  this suggestion (hence SHOULD not MUST) - for making it a MUST it might already be to late as people might already prefixed with an @. I think it is better to not have the @ as it is redundant and just bloates state.
> Replace question with suggestion

- EIPS/eip-2309.md
> Fix the username of @pizza-r0b in EIP-2309

- EIPS/eip-1679.md
> Add required EIPs as prerequisites

- EIPS/eip-2200.md
> Change EIP-2200 to last call

- EIPS/eip-2028.md
> Change EIP-2028 to last call

- EIPS/eip-1108.md
- EIPS/eip-1344.md
- EIPS/eip-152.md
- EIPS/eip-1679.md
- EIPS/eip-1884.md
This matches what was agreed on [ACD#76](https://github.com/ethereum/pm/issues/140)
> Change Istanbul EIPs to Last Call (152, 1108, 1679, 1884) – but not 1344 as that went through Last Call

- EIPS/eip-2384.md
- EIPS/eip-2387.md
> Updated Name, Block Number, Moved to Last Call 

- EIPS/eip-1080.md
> correct a sentence semantically, and a spelling mistake

- EIPS/eip-1108.md
- EIPS/eip-152.md
- EIPS/eip-1679.md
- EIPS/eip-1884.md
- EIPS/eip-2028.md
- EIPS/eip-2200.md
> Mark all Istanbul EIPs are Final

- EIPS/eip-1679.md
> Mark Istanbul final

- EIPS/eip-721.md
> Add discussion URL metadata to EIP-721

- last-call.xml
See https://validator.w3.org/feed/docs/rss2.html
> Two small RSS fixes to last-call.xml

- EIPS/eip-918.md
> Updated contact information in EIP-918

- EIPS/eip-2387.md
Updated to clarify there is no change in block reward, as requested in ACD Call 77. https://github.com/ethereum/pm
> Clarified - No change in block reward.

- EIPS/eip-1077.md
Just fixing some spec to work well with other EIPs.
> EIP-1077 - Add block.coinbase rule

- EIPS/eip-1202.md
> Add security considerations

- EIPS/eip-2387.md
Updated to clarify there is no change in block reward, as requested in ACD Call 77. https://github.com/ethereum/pm
> Updated To Final

- EIPS/eip-999.md
I'm no longer interested in restoring the contract code at `0x863DF6BFa4469f3ead0bE8f9F2AAE51c91A907b4`
> Withdraw EIP-999

- EIPS/eip-1102.md
Also fixes code sample syntax highlighter language to be correct (JS doesn't have types).
> Fixes code sample to be correct.

- EIPS/eip-2464.md
Discussions to https://github.com/ethereum/EIPs/issues/2465.
> EIP-2464: eth/65: transaction announcements and retrievals

- EIPS/eip-2309.md
> adding spec about not emitting transfer event, fixing typo, burn example

- EIPS/eip-2477.md
> Specify schemaIntegrity in JSON, add design

- EIPS/eip-1753.md
Update missed parameter in renaming.
> Update other function parameter

- EIPS/eip-1753.md
> Fix solidity errors

- EIPS/eip-2544.md
> Remove duplicate frontmatter

- EIPS/eip-1102.md
- EIPS/eip-1474.md
Adds @rekmarks as author to:
- 1102
- 1474
cc: @bitpshr
> Add author to 1102, 1474

- EIPS/eip-721.md
eip: 721
title: Fix broken links
author: Lucas Draichi (@Draichi)
discussions-to: https://github.com/ethereum/EIPs/issues/2554
status: Draft
type: Informational
created: 2020-03-09
> [hot-fix] - EIP 721 broken links

- EIPS/eip-2315.md
EIP 2315: another attempt at fixing the opcodes in the example
> Fix opcodes

- EIPS/eip-1193.md
This PR adds Erik Marks (@rekmarks) as an author to EIP-1193 as recognition and thanks for his contributions to the specification.
> 1193: Add author

- EIPS/eip-695.md
Updates links in 695 per @axic's recommendation: https://github.com/ethereum/EIPs/pull/2625#pullrequestreview-405611863
> 695: update links to eip 155

- EIPS/eip-1123.md
- EIPS/eip-1829.md
- EIPS/eip-2020.md
- EIPS/eip-2028.md
- EIPS/eip-205.md
- EIPS/eip-2098.md
- EIPS/eip-2477.md
Here are some fixes to use HTTPS when those links work instead of the HTTP links.
> Upgrade to https

- EIPS/eip-2335.md
> EIP-2335 Fix minor typo

- EIPS/eip-1057.md
> add Michael and Greg changes

- EIPS/eip-695.md
- `EIP n` -> `EIP-n`
- Format raw link
- Fix rekmarks author reference
> ERC-695: Fix EIP reference notation

- EIPS/eip-2315.md
This PR aims to resolve the gas-cost discussions about EIP-2315. 
Discussions here: https://github.com/ethereum/EIPs/pull/2669#discussion_r430053819
and here: https://ethereum-magicians.org/t/eip-2315-simple-subroutines-for-the-evm/3941/64?u=holiman
cc @gcolvin , @ordian (or @sorpaas , or @vorot93 ), @matkt , @axic
> 2315: changes in gascosts

- EIPS/eip-1193.md
File: https://github.com/rekmarks/EIPs/blob/1193-security-considerations/EIPS/eip-1193.md
Adds `Security Considerations` to EIP-1193.
Also includes some minor stylistic fixes/corrections.
> 1193: Add "Security Considerations"

- EIPS/eip-2334.md
> Clarify when eth2 specific paths should be used

- EIPS/eip-2718.md
Adds rational for hashing and signing inner transaction and adds recommendations for client behavior.
> 2718: Adds specification for hashing.

- EIPS/eip-1559.md
There was some confusion since the term was not formally defined.  I'm open to different wording for it!
> Adds definition for BLOCK_GAS_TARGET.

- EIPS/eip-2696.md
Includes one change that came up in discussion at https://github.com/ethereum/EIPs/issues/2319#issuecomment-654338478 during the Last Call phase.
> Move 2696 to final.

- EIPS/eip-2780.md
- EIPS/eip-lower-intrinsic-gas.md
rendered: https://github.com/lightclient/EIPs/blob/reduce-intrinsic-cost/EIPS/eip-2780.md
> Intial draft of eip to reduce intrinsic gas cost of transactions

- EIPS/eip-2700.md
Non-normative change to final EIP. This EIP was extracted from 1193 and @remarks indicated that adding their name as author was acceptable.
> 2700: Adds an author

- EIPS/eip-1.md
As [discussed](https://gitter.im/ethereum/EIPs?at=5f0ece4d15779f6fdca82a82) on Gitter, this will add @MicahZoltu  to the EIP editor list.
> Add Micah Zoltu as an EIP editor

- EIPS/eip-165.md
This simply changes my old private email to my current public one.
> Updated outdated email

- EIPS/eip-2711.md
Also cleans up some inconsistencies in wording, typos, errors, etc.
> Adds receipts and makes child transactions an array.

- EIPS/eip-2746.md
Changed the Discussions-To URL.
> Changed URL

- EIPS/eip-173.md
Adding more links to implementations of eip-173
> Update eip-173.md, adding links

- EIPS/eip-2569.md
Try to make it seperate from another EIP.
> Make EIP-2569 seperate from EIP-2794

- EIPS/eip-234.md
This has been implemented and live in multiple clients for quite some time now, I just lost track of it.
> EIP-234: Moves to Last Call

- EIPS/eip-2746.md
> Updated URL for EIP-2535

- EIPS/eip-2831.md
Fixes a typo error from Proider to Provider.
> fix: fixes a typo error

- EIPS/eip-1820.md
> Fix typo of EIP1820

- EIPS/eip-2848.md
> EIP-2848: Fixed some typos

- EIPS/eip-2848.md
Now MOM is separated in two sets of features: core and extended. Core features MUST be implemented, extended features SHOULD be implemented.
> EIP-2848: features are now in two sets, core and extended

- EIPS/eip-2848.md
Improved descriptions to be clearer.
> EIP-2848: Improved descriptions to be clearer

- EIPS/eip-2771.md
> refer receipient eip discussion to ethereum-magicians

- EIPS/eip-2876.md
This is fixing the comments brought up when the draft was merged.
> Fix comments from @MicahZoltu

- EIPS/eip-2771.md
>  EIP 2771: fixed broken discussion link

- EIPS/eip-2831.md
This PR cleans up some language around [EIP-2831](https://eips.ethereum.org/EIPS/eip-2831)
> EIP-2831: Add more explicit events

- .codespell-whitelist
- .travis-ci.sh
I started pushing out a lot of old pending changes I did locally, this is the first one.
> Run codespell on everything

- EIPS/eip-2583.md
This PR updates the (abandoned) penalty-eip 2583 with some of the comments from @MicahZoltu
> shape up 2583

- EIPS/eip-875.md
Per comment from author in https://github.com/ethereum/EIPs/pull/2357#issuecomment-686876074
> Moves 875 to Abandoned.

- EIPS/eip-908.md
This EIP hasn't been touched for over 2 years.  As an author on the EIP, I don't even remember what it is at this point and after reviewing it I no longer hold any opinions I may have held on the topic two years ago.  Unless @jamesray1 plans on pushing for this, I am recommending we mark it as withdrawn.
If someone later decides to pick it up again, we can always bring it back to DRAFT.
> EIP-908: Marking as withdrawn

- EIPS/eip-1240.md
My stance on this has changed over the years since I created this EIP and while I still am not outright against this change, I better appreciate why the bomb exists and am no longer interested in fighting for its removal.  If someone else wants to take over this EIP let me know and we can change the author and move it back into DRAFT.
> EIP-1240: Changes status to Withdrawn

- EIPS/eip-2831.md
> create replacement event

- EIPS/eip-2733.md
> Make updates to EIP-2733 based on FEM feedback

- .github/workflows/stale.yml
- _config.yml
> Fix "stale" github action

- EIPS/eip-2266.md
> EIP-2266: change status from draft to last call

- EIPS/eip-2266.md
fix https://github.com/ethereum/EIPs/pull/2308#issuecomment-689422758
> EIP-2266: change status from draft to last call 

- EIPS/eip-2309.md
Review period has ended. Moving this EIP to Final! This EIP was originally proposed in October of 2019. It has been refined and tested in production environments. It recently helped facilitate the creation of 20,000 NFT vouchers where 500 of these vouchers were sold in a pre-sale. By including the event mentioned in this EIP we are able to effectively track the creation and distribution of these vouchers. Vouchers could be purchased in bulk and tracked effectively - saving consumers massive gas costs for bulk purchases.
> 2309 to Final

- EIPS/eip-2266.md
- assets/eip-2266/Example.sol
re: https://github.com/ethereum/EIPs/issues/2266#issuecomment-689996097
> add EIP-2266 example

- EIPS/eip-2972.md
Two new transaction types for wrapping legacy transactions with and without a chain ID.
> Wrapped Legacy Transactions

- EIPS/eip-1559.md
add Abdelhamid Bakhta as author
> add Abdelhamid Bakhta as author

- EIPS/eip-3014.md
suggested here https://github.com/ethereum/EIPs/pull/3014#discussion_r499106461
> eip-3014: shorten title

- EIPS/eip-2733.md
> replace byte with u8

- EIPS/eip-2733.md
> add gas calc to 2733

- EIPS/eip-2733.md
> Add atomicity to children

- EIPS/eip-712.md
> Eip 712 domain separator order

- EIPS/eip-3045.md
Add basefee field to `eth_getUncleByBlockHashAndIndex`.
> Add basefee to eth_getUncleByBlockHashAndIndex

- EIPS/eip-3046.md
Add basefee field to `eth_getUncleByBlockNumberAndIndex`.
> Add basefee to eth_getUncleByBlockNumberAndIndex

- EIPS/eip-2929.md
This PR adds a clarification, requested by @karalabe, concerning "what if someone does a cold read on a cold account?"
> EIP-2929: additional clarification

- EIPS/eip-2929.md
Some more clarifications requested by @karalabe 
@vbuterin lgty?
> EIP-2929: clarifications

- EIPS/eip-1363.md
> ERC-1363: Move to Final

- EIPS/eip-2844.md
Some updates to EIP2844 based on the discussion https://github.com/ethereum/EIPs/issues/2845
> chore: update eip2844

- EIPS/eip-3009.md
> Update EIP-3009 draft

- EIPS/eip-2935.md
> adjusted block numbers borders for the new blockhash

- EIPS/eip-2015.md
Fixes the spelling of my last name in the EIP-2015 header.
> EIP-2015: Fix author name

- EIPS/eip-1155.md
> fixed JSON parse errors

- EIPS/eip-3102.md
* Remove external links
* Replace latex identifiers with their programmatic-style equivalents
* Simpler summary
> Update EIP 3102 to include review feedback

- EIPS/eip-3102.md
* Mention the possibility to reserve an extra address bit for future account extensions
* Fix the prototype branch reference
> update eip-3102 after geth team feedback

- EIPS/eip-2844.md
Edits based on the discussion around EIP2844.
> chore: additional 2844 udates

- EIPS/Exclusive_Claimable_Token.md
- EIPS/eip-3135.md
---
eip: 3135
title: Exclusive Claimable Token
author: Zhenyu Sun (@Ungigdu)
discussions-to: https://github.com/ethereum/EIPs/issues/3132
status: Draft
type: Standards Track
category: ERC
created: 2020-08-10
requires: 20
---
This standard defines a token which can be claimed only by token issuer with payer's signature.
This EIP defines a set of additions to the default token standard such as ERC-20, that allows online/offline service providers establish micropayment channels with any number of users by signing and verifying messages about the consumption of token off chain. Using this mechanism will reduce interactions with blockchain to minimal for both participants, thus saving gas and improve performance.
There are two main purposes of this EIP, one is to reduce interactions with …
> Exclusive Claimable Token

- eip-template.md
I have to type this to basically every EIP author, figured it was time to just integrated the advice directly into the template.
> Adds clarification to Simple Summary.

- eip-template.md
I have to coach almost every EIP author on what the abstract is, integrating into the template will hopefully help with that process.
> Adds words to abstract definition.

- EIPS/eip-681.md
I no longer have the replaced email address. No other changes.
> Change in author's email address.

- EIPS/eip-2678.md
> Actually bump 2678 to review

- EIPS/eip-681.md
ERC 681 has been implemented for a while by several wallet applications: WallETH, MyCrypto, Q-Wallet, MetaMask (partial), Status (partial) and possibly others. I believe that it is a de-facto standard and therefore it is time to finalize it as such.
> Request peer review for ERC-681

- EIPS/eip-1271.md
> EIP-1271 - Update comment for _hash argument

- EIPS/eip-2255.md
Spelling error -- not sure if EIPs can be modified easily after their creation, but worth a try
> Spelling Error -- Update eip-2255.md

- EIPS/eip-681.md
There have been no objections for two weeks while the status was "Review", so it is time to move on to "Last Call".
> After two weeks in "Review", change status of ERC-681 to "Last Call"

- EIPS/eip-3156.md
Line formatting, and incorrect parameter type on `onBatchFlashLoan` function signature.
> Erc3156 - typos

- EIPS/eip-1890.md
"EIP no longer active" as suggested by Kevin Owocki
> EIP-1890 : Status changed to 'Withdrawn'. 

- EIPS/eip-2982.md
> Change EIP-2982 status from "Draft" to "Review"

- EIPS/eip-2718.md
> Change EIP-2718 status from "Draft" to "Review"

- EIPS/eip-3156.md
- Shorter summary.
- `initiator` instead of `sender`
- Better description on trusting `data`
> erc3156: minor improvements

- EIPS/eip-2929.md
> Change EIP-2929 status from "Draft" to "Review"

- EIPS/eip-3234.md
- 3157 -> 3234
- Discussions page
- maxFlashAmount -> maxFlashLoan
- flashLoan -> batchFlashLoan
- onFlashLoan -> onBatchFlashLoan
> erc3234: Multiple renamings

- EIPS/eip-2678.md
> Relax requirements for source checksums

- EIPS/eip-1102.md
This moves the 1102 discussions link to a newly created issue.
> EIP-1102: Update discussions link

- EIPS/eip-1185.md
As per request from @MicahZoltu
> Add github username to EIP-1185

- EIPS/eip-1559.md
> Change EIP-1559 status from "Draft" to "Review"

- EIPS/eip-2718.md
> fix typo: "signatureses" to "signatures"

- EIPS/eip-3156.md
After extensive consultation and collaboration, and after receiving no further feedback for the two weeks this EIP has been in Last Call status, I would like to propose to make it Final.
> erc3156: Final Status

- EIPS/eip-2935.md
> Change EIP-2935 status from "Draft" to "Review"

- EIPS/eip-2972.md
May resume in future, but not now.
> 2972: Withdrawn

- EIPS/eip-1559.md
Just some small PEP-8 style changes.
https://www.youtube.com/watch?v=hgI0p1zf31k
> add whitespace after comma

- EIPS/eip-2678.md
Changes in this pr are related to the discussion in https://github.com/ethereum/EIPs/pull/3269#pullrequestreview-591995056
> 2678: Convert html tables to markdown

- EIPS/eip-3220.md
- EIPS/eip-crosschain-id.md
This document was created by EEA (Enterprise Ethereum Alliance) Crosschain Interoperablitty Task Force and is submitted as a EIP proposal.  The document was shared with Hudson Jameson for EIP editor's feedback.
> EIP-crosschain-id proposal

- EIPS/eip-2678.md
> Convert headerless tables to lists for better formatting

- .travis.yml
> Bump eipv to v0.1.1

- EIPS/eip-2678.md
> Move 2678 to Last Call

- EIPS/eip-3074.md
Remove `chainid` and `depthLeft`.
> Remove depthLeft [EIP-3074]

- EIPS/eip-2780.md
> Change status of EIP-2780 from "Draft" to "Withdrawn"

- EIPS/eip-3074.md
> [EIP-3074] Move to AUTHCALL version

- EIPS/eip-3382.md
> Simplify EIP-3382

- EIPS/eip-1559.md
The cost of an eip-1559 tx is not currently specified.
> Explicitly state intrinsic cost of eip-1559 txs

- EIPS/eip-3074.md
> add impl for eip3074

- EIPS/eip-3074.md
We're happy with the current specification and ready for the EIP to be reviewed more widely.
> Move 3074 to review

- EIPS/eip-3074.md
> Revamp motivation

- EIPS/eip-3074.md
as decided by the many hours of discord discussions
> 3074 two value operands

- EIPS/eip-3382.md
This is being discussed in the next ACD. I believe it is ready for review.
> Move EIP-3382 to review

- EIPS/eip-3369.md
- EIPS/eip-3372.md
This pull request adds ~EIP-3369~ EIP-3372.
> EIP-3372 - Apply minor modifications to the Ethash algorithm to break current ASIC implementations (EIP-969 resubmission)

- EIPS/eip-3238.md
> 3238: be more neutral about the time of year

- EIPS/eip-3416.md
Goals:
- Improve & shorten redaction.
- Possibly adding convex formula by @mtefagh to avoid attacks of senders sending BASEFEE to zero (Article and Simulation : [Designed an attack for EIP-1559 and proposed an alternative transaction fee pricing protocol based on the Almgren–Chriss framework and median price auctions](https://mtefagh.github.io/fee/)).
- Review block elasticity delta (1/1024) and base fee elasticity (8).
> Redaction fixes

- EIPS/eip-3416.md
Is adding improvements on the base fee update and over-all fan of the Median approach.
> Adding @mtefagh as co-author.

- EIPS/eip-2535.md
> EIP-2535 Improvements

- EIPS/eip-2315.md
Not ready for London review, cleaned up for further consideration, if any.
> Return 2315 to draft status

- EIPS/eip-2315.md
> 2315 formatting

- EIPS/eip-2929.md
- EIPS/eip-2930.md
Moving 2929 and 2090 to last call
> eip2929 and eip2930: move to last call

- EIPS/eip-3074.md
EIP-3074: Minor clarifications for gas costs
Gas attempt [EIP-3074]
More gas refinements
More gas tweaks
EIP-3074: Unrestrict self-sponsoring
Some final touches before ACD [EIP-3074]
> EIP-3074: Move to strict AUTHCALL rules

- EIPS/eip-3416.md
> EIP-3416.md minor change

- EIPS/eip-3436.md
updates based on eip editor comments
> update based on editors comments

- EIPS/eip-2981.md
- Fixed several spelling and grammatical errors in addition to simplifying and clarifying content
- Added more detail to the Abstract
- Added more to the rationale section to make things crystal clear
- Made the Solidity function comments match the same form as ERC-721 format (`///` instead of `/* * */`)
- Renamed `receivedRoyalties()` to `onRoyaltiesReceived()` to match the standard Ethereum pattern per EIP comment thread
- Only major functional change was adding a `bytes32 _metadata` to the `RoyaltiesReceived` event to help future-proof this EIP and become more of a building block to build more EIPs off of
> [EIP-2981] Royalty Payments - Many improvements, reformatting, error fixes, edits

- EIPS/eip-2981.md
> [EIP-2981] Fix return value of comment

- EIPS/eip-2678.md
> Finalize 2678

- EIPS/eip-191.md
Seems like we can start inching this one to final? @holiman @Arachnid
> Move EIP-191 to review

- EIPS/eip-191.md
Hi again @holiman @Arachnid, just once more after this.
> Move EIP-191 to last call

- EIPS/eip-2929.md
> EIP 2929 -> final

- EIPS/eip-2930.md
> EIP 2930 -> Final

- .github/workflows/auto-merge-bot.yml
> only run on pull_request_target and add that as a valid event (bot)

- .github/workflows/auto-merge-bot.yml
> re-run bot on review

- .github/workflows/auto-merge-bot.yml
The secondary actions are on a branch in https://github.com/alita-moore/EIP-Bot
> await ci on bot and remove old failed runs to keep things clean

- EIPS/eip-2930-updates.md
- EIPS/eip-3521.md
> Modify eip-2930 gas accounting

- EIPS/eip-3520.md
- EIPS/eip-draft_transaction_destination_opcode.md
Hello,
This PR is meant to introduce a new EIP for accessing a transaction's original recipient to allow advanced forms of introspection to manifest.
Feedback is welcome on all points.
> EIP-3520: Transaction Destination Opcode

- EIPS/eip-3508.md
- EIPS/eip-3520.md
Hello,
This PR is meant to merge some editorial changes to the 3508 and 3520 EIPs that have already been merged as "Draft".
> EIP 3508, EIP 3520: Incorporation of Feedback

- EIPS/eip-681.md
The Last Call review period ended without any requested changes or objections.
> ERC681 change status to Final

- EIPS/eip-2981.md
- Removed the `onRoyaltiesReceived()` function and `RoyaltiesReceived` event
- Updated `royaltyInfo()` function and docstring based on EIP discussion
- Updated the copy based on these changes
- Added more information to the Rationale section
> Reworked EIP-2981 based on feedback

- EIPS/eip-3554.md
> Fixing typos

- EIPS/eip-2938.md
> Minor proofreading of EIP-2938 for readability

- EIPS/eip-3529.md
Addresses https://github.com/ethereum/EIPs/pull/3538#issuecomment-840668341
> Mark dependencies properly for EIP-3529

- EIPS/eip-3554.md
> EIP:3554 updated title to be more accurate

- EIPS/eip-191.md
- EIPS/eip-234.md
While I don't want to require these old EIPs to be properly formatted to move them to final when they are effectively final already, in this case it was trivial to include the URLs while moving the EIPs to final.
> Make 191 and 234 final

- EIPS/eip-3584.md
- EIPS/eip-block_access_list.md
a proposal to build a block access list and include its fingerprint in block header
https://ethresear.ch/t/block-access-list-v0-1/9505
> block access list

- EIPS/eip-2681.md
Moving this to last call since there was no dissent in ACD 101.
> EIP-2681: move to last call

- EIPS/eip-1559.md
Follow-up from the discussions on https://github.com/ethereum/pm/issues/321#issuecomment-850230251 
cc @MicahZoltu @vbuterin
> eip-1559: add more constraints to the tx validation

- EIPS/eip-3448.md
> Fix formatting in eip-3448

- EIPS/eip-2981.md
@VexyCats @jamesmorgan @seibelj can I get an approval?
> EIP:2981 Update to grammar and clarity around ecosystem conversation 🖋️

- EIPS/eip-2228.md
> Be less prescriptive in copyright note

- EIPS/eip-2098.md
Updated with the changes suggested on the `discussions-to` and moved to Review.
> Updated EIP-2098 w/ suggestions and move to Review

- EIPS/eip-1271.md
Updates based on comments by @MicahZoltu ; https://github.com/ethereum/EIPs/pull/2857#pullrequestreview-462265956
> EIP-1271 content update, no specification change

- EIPS/eip-1271.md
> EIP-1271; Add additional implementation example

- EIPS/eip-1271.md
> EIP-1271 update solidity code

- EIPS/eip-2981.md
fix: Grammar, typos and general clarity of ideas.
>  EIP2981 general revisions ✍️  

- EIPS/eip-1271.md
Closed #3628 as per @lightclient's request and moving ERC-1271 to Review status first.
> Set ERC-1271 to Review status

- EIPS/eip-1271.md
Fix error with magic value returned
> Update implementation error in ERC-1271

- EIPS/eip-2228.md
Passed Last Call period without any changes
> Promote EIP to final

- _layouts/eip.html
- assets/css/style.scss
This PR fulfills a request to add a warning to EIPs which are not finalized.
Open to recommendations on changes to language, color scheme, etc.
Requested in: https://github.com/ethereum-cat-herders/PM/issues/214
> Add clear warning to EIPs which are not Living or Final

- EIPS/eip-3651.md
Change EIP link: absolute to relative.
> Update 3651: Relative Links

- EIPS/eip-2981.md
> EIP2981 status changed to 'Final' ✍️

- EIPS/eip-3554.md
> fix misprint eip-3554.md

- EIPS/eip-778.md
Last call ended on 2020-09-18.
> Promote EIP-778 to Final.

- EIPS/eip-868.md
Last call ended on 2020-09-18.
> Promote EIP-868 to Final

- EIPS/eip-2124.md
> Promote EIP-2124 to Final

- EIPS/eip-1559.md
Follow up of https://github.com/ethereum/EIPs/pull/3600#issuecomment-883735026.
> 1559: change value field to amount in RLP, as the spec uses that

- EIPS/eip-2481.md
The author is ready to move the proposal to the next status.
> Move EIP-2481 to "Last Call"

- EIPS/eip-3670.md
Change unassigned to undefined.
> 3670: clarifications and test cases

- EIPS/eip-1559.md
Follow up of https://github.com/ethereum/EIPs/pull/3600#issuecomment-883735026.
Here only the last commit matters, as this should be merged after #3682.
> 1559: Use snakecase throughout the spec

- EIPS/eip-1559.md
EIP deployed on the mainnet with the London upgrade.
> Promote EIP-1559 to Final

- EIPS/eip-3529.md
EIP-3529 deployed with the London upgrade.
> Promote EIP-3529 to Final

- EIPS/eip-3675.md
- Removes TBDs
- Makes various statements more clear
> Polish EIP-3675 specification

- EIPS/eip-1.md
- eip-template.md
As agreed in the [EIPIP meeting 39](https://youtu.be/eo90AIGv3jw), added a suggestion in the EIP template to not repeat the EIP number in the EIP title.
> Update EIP template

- EIPS/eip-2315.md
> JUMPSUB improvements.

- EIPS/eip-1.md
This was bugging me for so long:
> 1: fix rendering preamble description

- EIPS/eip-3756.md
> EIP-3756: Fix typo

- EIPS/eip-.md
- EIPS/eip-3788.md
> Strict enforcement of chainId

- EIPS/eip-2135.md
> Update draft for eip-2135

- EIPS/TODO.md
- EIPS/eip-3709.md
> Deprecate type1 transactions

- EIPS/eip-2711.md
I still think this is a good idea, but I'm no longer actively championing it.  If anyone wants to take up ownership of this EIP or something similar to it please do so!
> 2711: Withdrawing

- EIPS/eip-721.md
This removes deprecated language
> Remove racist language

- index.html
Removed extra word "the" at line 32.
> Update index.html - remove duplicate word

- EIPS/eip-1581.md
Move EIP-1581 to Review.
EIP-1581 is used in the [Status client](https://status.im) to derive chat and encryption keys.
> Move EIP-1581 to Review

- EIPS/eip-4345.md
> Add "review-period-end"

- README.md
Addresses https://github.com/ethereum/EIPs/pull/3849#issuecomment-913859076
> Drop duplicate info from the README

- EIPS/eip-4345.md
> Add @tjayrush as author

- .github/workflows/stale.yml
> add issues to stale PR bot

- EIPS/eip-4399.md
Fixes spelling and improves on clarity as per @MicahZoltu's review feedback
> EIP-4399: fix spelling

- .github/workflows/auto-merge-bot.yml
Networking is *basically* Core.
> I shouldn't have removed myself from networking.

- EIPS/eip-1.md
> Strengthen the discussion-url rules

- EIPS/eip-1.md
- eip-template.md
> Add RFC 2119 recommendation to EIP-1

- EIPS/eip-3074.md
Should bring some info from these discussions into the EIP:
* https://ethereum-magicians.org/t/we-should-be-moving-beyond-eoas-not-enshrining-them-even-further-eip-3074-related/6538
* https://ethereum-magicians.org/t/validation-focused-smart-contract-wallets/6603
> Add note on future compatibility

- EIPS/eip-1.md
```console
$ rg "updated: " . | wc -l
0
```
Doesn't look like anyone uses the updated field.
> Remove `updated` field

- EIPS/eip-3675.md
Addressing PR feedback from this PR https://github.com/ethereum/EIPs/pull/4415 that was auto-merged a bit too early
> 3675: refactor the rationale

- .travis.yml
- EIPS/eip-1.md
- EIPS/eip-1191.md
- EIPS/eip-1271.md
- EIPS/eip-173.md
- EIPS/eip-2266.md
- EIPS/eip-2481.md
- EIPS/eip-2535.md
- EIPS/eip-2678.md
- EIPS/eip-2786.md
- EIPS/eip-2976.md
- EIPS/eip-2982.md
- EIPS/eip-3076.md
- EIPS/eip-875.md
- _includes/eiptable.html
- _layouts/eip.html
- index.html
> Rename review-period-end to last-call-deadline

- EIPS/eip-4444.md
> Clear up a few things

- EIPS/eip-4444.md
> Add note about eip pronunciation

- EIPS/eip-3675.md
Reverts https://github.com/ethereum/EIPs/pull/4397
> EIP-3675: Revert "TRANSITION_BLOCK is not defined as being a child of a te..."

- assets/eip-722/eip-722.md
> EIP-722: Allow everyone migrate token URI update

- assets/eip-722/eip-722.md
> EIP-722: update introduction

- assets/eip-722/eip-722.md
> EIP-722: update implementation

- EIPS/eip-4399.md
Aligns name of transition block with that defined in EIP-3675
Signed-off-by: Justin Florentine <justin+github@florentine.us>
> updates name of block to change behavior on to TRANSITION_BLOCK

- .github/workflows/greetings.yml
YAML syntax suggests using multiline string with pipe character (|).
It will be best to NOT use single/double quotes, especially when it's multi-line and Markdown string.
More about multi-line string value in YAML: https://yaml-multiline.info
Try it out here: https://yamlvalidator.com/ with example:
```
issue-message: |
Since this is your first issue, we kindly remind you to check out [EIP-1](https://eips.ethereum.org/EIPS/eip-1) for guidance.
If this issue was created as a “discussions-to” for an EIP or to discuss an idea for an EIP, please close it and create a thread at [Fellowship of Ethereum Magicians](https://ethereum-magicians.org/).
pr-message: |
Since this is your first pull request, we kindly remind you to check out [EIP-1](https://eips.ethereum.org/EIPS/eip-1) for guidance.
If …
```
> The issue was in the YAML syntax with multi-line strings.

- EIPS/eip-4345.md
Signed-off-by: Tim Beiko <t.beiko23@gmail.com>
> Move 4345 to Last Call

- EIPS/eip-3779.md
Fixes https://github.com/ethereum/EIPs/pull/4330/files#r743323700
> 3779: Fix rendering

- EIPS/eip-2569.md
- Move EIP-2569 from "stagnant" to "draft" to continue the review process
- Add new author to follow up the review process
> EIP-2569: move from "stagnant" to "draft"

- EIPS/eip-1716.md
Ping authors: @5chdn @MariusVanDerWijden / please approve
> Update EIP to refer to Ethereum Mainnet, wording as per EIP-2228

- EIPS/eip-1153.md
some suggested updates from @MicahZoltu
> fix(eip-1153): update rationale section

- EIPS/eip-4520.md
> Fix typo `0xED`. Changed to `0xEC`

- EIPS/eip-3668.md
> Updates to 3668

- EIPS/eip-101.md
- EIPS/eip-198.md
- EIPS/eip-2.md
- EIPS/eip-7.md
Updating EIPs from this author to use preferred author citation format.
REFERENCES:
- EIP template (uses name + GitHub username) https://github.com/ethereum/EIPs/blob/master/eip-template.md
- Invitation for PR from editor @axic  https://github.com/ethereum/EIPs/pull/4530#issuecomment-988406258
> Update author format to preferred name + GitHub username format, Vitalik

- EIPS/eip-161.md
Updating EIPs from this author to use preferred author citation format.
REFERENCES:
- EIP template (uses name + GitHub username) https://github.com/ethereum/EIPs/blob/master/eip-template.md
- Invitation for PR from editor @axic  https://github.com/ethereum/EIPs/pull/4530#issuecomment-988406258
> Update author format to preferred name + GitHub username format, Gavin

- EIPS/eip-3978.md
> [EIP-3978] Update specification

- EIPS/eip-2228.md
Based on progress of updating those EIPs
> Reduce list of references to non-complaint EIPs

- EIPS/eip-3668.md
> More improvements to 3668

- EIPS/eip-1.md
> Fix a typo in eip-1.md

- EIPS/eip-3668.md
I believe EIP 3668 is now ready to move to review and then last-call. I'd appreciate it if you're able to merge this PR to move it to last-call status!
> Move 3668 to Review

- EIPS/eip-3668.md
> Make URL a substitution string

- EIPS/eip-2098.md
> Revert "EIP-2098 stagnant (2021-Dec-26th@01.13.15)"

- EIPS/eip-3607.md
Has been implemented by all teams.
> Move 3607 to Last Call

- EIPS/eip-1011.md
> Fix a typo in eip-1011.md

- EIPS/eip-4521.md
adds suggestion and references for 721/20-compatible transfer
> EIP-4521: 721/20-compatible transfer

- EIPS/eip-3448.md
> Move 3448 to Last Call

- EIPS/eip-2315.md
- EIPS/eip-3779.md
- EIPS/eip-4573.md
> Procs safe subs again

- EIPS/eip-4337.md
> Update ERC-4337 RPC methods

- EIPS/eip-191.md
I noticed a typo in eip-191, so I thought I would fix it.  I couldn't find any contributing guidelines so I hope this is ok.
> Typo in eip-191

- EIPS/eip-4626.md
https://github.com/ethereum/EIPs/pull/4705 isn't getting automerged, duping here
> EIP-4626: Preview functions

- EIPS/eip-1052.md
> docs: fix a typo in eip-1052.md

- EIPS/eip-4337.md
> update EIP4337: authors

- EIPS/eip-2980.md
Review status for eip-2980
ref: #2980
> EIP-2980: Review status

- eip-template.md
> Add an optional Reference section.

- eip-template.md
This reverts commit 518fe4f3cdb4ffa7114298dc7193a360952c6ac3.
Reverts #4724, which should not have been auto-merged.
> Revert "Add an optional Reference section. (#4724)"

- EIPS/eip-2315.md
> Move EIP-2315 to Review

- EIPS/eip-4626.md
changes discussed with @joeysantoro, @transmissions11, @JetJadej, and @alcueca
> refactor: redesign from independent Peer Review

- EIPS/eip-663.md
> Revert "663: Update SWAP/DUP to use EIP-3540"

- EIPS/eip-4200.md
Co-authored-by: Andrei Maiboroda <andrei@ethereum.org>
> EIP-4200: Add reference implementation

- EIPS/eip-4626.md
> EIP-4626: Remove 165, 712 and add 2612

- EIPS/eip-3779.md
> Clarifications and bug fixes

- EIPS/eip-3779.md
Add one empty line so code displays properly  at eips.ethereum.org
> minor formatting

- EIPS/eip-3779.md
> misnamed functions

- EIPS/eip-3779.md
> get max stack right

- EIPS/eip-4527.md
- EIPS/eip_draft_qr_code_data_transmission_protocol.md
> EIP-4527: QR Code data transmission protocol for the Ethereum wallets

- EIPS/eip-4337.md
> 4337: Fix typos

- EIPS/eip-3675.md
Change EIP-3675 status to Review
> EIP-3675: Move to Review

- EIPS/eip-4747.md
- EIPS/eip-simplify-161.md
Currently doesn't have a number or an Ethereum magicians thread. I will create a Ethereum magicians thread as soon as I have an number.
> EIP-4747: Simplify EIP-161

- EIPS/eip-4626.md
> 4626 updates

- EIPS/eip-1153.md
> EIP-1153: Introduce cheaper implementation, clarify semantics

- EIPS/eip-4626.md
> Clarify Max logic

- EIPS/eip-4626.md
> EIP-4626 Clarify Preview Function Behavior

- EIPS/eip-158.md
This is in a similar vein to #4559 and #4560. It will help getting https://github.com/ethereum/eipv/pull/39 fixed.
> EIP-158: Update author field to contain handle

- EIPS/eip-4399.md
Refines Security Consideration section of the EIP by describing in more details properties of randomness produced by the beacon chain RANDAO implementation, and provides tips for application developers that allow to rely their apps on less biasable and less predictable randomness.
> EIP-4399: refine Security Considerations

- EIPS/eip-1967.md
Adding @frangio, who has been collaborating on this EIP, so he can take over and try to get it finalized.
> Add @frangio as author of EIP1967

- EIPS/eip-4626.md
`Deposit(caller, receiver, assets, shares)` -> `Deposit(caller, owner, assets, shares)`
`Withdraw(caller, receiver, assets, shares)` -> `Withdraw(caller, receiver, owner, assets, shares)`
> Changes to event fields

- EIPS/eip-3779.md
Debugging reference implementation.
> validate()

- EIPS/eip-4626.md
> chore: move EIP-4626 to Last Call

- EIPS/eip-4626.md
> 4626: link fix

- EIPS/eip-3978.md
Reviewer @k06a
I believe I preserved your specification.
* Shorter abstract, moved rest to Motivation
* some spelling
* some grammar
* Explicit reference to WARM_STORAGE_READ_COST from EIP-2929
* Explicit reference to callframe
> EIP-3978 modifications

- EIPS/eip-4881.md
Addressing some of the [comments made in initial PR](https://github.com/ethereum/EIPs/pull/4881#pullrequestreview-905212133)
> Addressed @lightclient's Comments

- EIPS/eip-4626.md
> 4626: clear up max functions & remove decimals clause

- EIPS/eip-4626.md
> 4626: decimals recommendation

- EIPS/eip-4863.md
Reflect latest consensus changes (including engine API) in #4863.
> Updates to EIP-4863

- EIPS/eip-4626.md
> ERC-4626: Clarify maxDeposit/maxMind

- EIPS/eip-4626.md
> ERC-4626: Clarify Preview Revert behavior

- EIPS/eip-4626.md
> Clarify ERC-4626 flows

- EIPS/eip-4626.md
> Move EIP-4626 to Final 🎉

- EIPS/eip-3651.md
3651 is being considered for inclusion in Shanghai.
Changes EIP-3651 from Stagnant to Review
> Eip 3651: Stagnant -> Review

- EIPS/eip-2309.md
In comparing 2309 and 1155 contracts section the author points to undefined 2039 contract.
> Fix typo in contract reference number

- EIPS/eip-4400.md
Marking this EIP for review. Since the inception of this EIP, there have been 2 implementations and there was no feedback on changing the spec.
> EIP-4400: Mark for review; Update motivation

- EIPS/eip-3651.md
Reviewer @MicahZoltu
Moves Simple Summary to Description
> EIP-3651 Description

- EIPS/eip-1153.md
Since it's not possible to review stuff in a PR that hasn't been changed, I've made this PR as a review of EIP-1153 to unblock #4942.
> EIP-1153 Review

- EIPS/eip-725.md
- Adding function overloading to `getData(...)` and `setData(...)` to be backward compatible and provide a more efficient way to get and set single data from/to a smart contract.
- Will be cheaper by **2k~3k** gas unit.
> docs: add function overloading

- EIPS/eip-4337.md
Set of changes following the security audit by OpenZeppelin.
(copy from https://github.com/eth-infinitism/account-abstraction/blob/PEEPanEIP/eip/EIPS/eip-4337.md)
> post-audit changes

- EIPS/eip-2098.md
Last Call deadline passed on Feb 23, I'm not aware of any arguments against finalizing
> move 2098 to Final

- EIPS/eip-3779.md
> Validation algorithm is work in progress

- EIPS/eip-4907.md
> EIP4907:update title and test code

- EIPS/eip-4527.md
> EIP-4527: add origin field for indentify different key provider

- EIPS/eip-4527.md
> EIP-4527: update the origin to note

- EIPS/eip-4399.md
> EIP-4399: add test cases

- EIPS/eip-3675.md
> EIP-3675: add test cases

- EIPS/eip-1967.md
Hey @spalladino, @frangio, and @Amxx!
@Amxx opened a PR to move this EIP into the final state, but there were a couple blocking issues. I've taken the liberty of applying the changes, but since these go beyond just fixing typos, I'm opening this PR (and extending the last call deadline.)
I've:
- Removed external links;
- Moved paragraphs from "Specification" into "Rationale" as appropriate; and
- Removed references to non-final EIPs.
If these changes are acceptable, one of the authors (@spalladino or @frangio) will need to approve.
Thanks,
Your friendly neighbourhood EIP editor.
> EIP-1967: Editor revisions before Final

- EIPS/eip-4907.md
> Mark ERC-4907 for Review

- EIPS/eip-4799.md
> Mark ERC-4799 for Review

- EIPS/eip-3074.md
@jochem-brouwer hopefully this clarifies the wording a bit!
> EIP-3074: Clarify that ignored bytes still cost gas

- EIPS/eip-4804.md
> Add support for EIP-3770 chain-specific address

- EIPS/eip-4400.md
Signed-off-by: Daniel Ivanov <daniel.k.ivanov95@gmail.com>
Updating this EIP to final since `Last Call` time has passed
> EIP4400: Update status to Final

- EIPS/eip-4906.md
EIP-4906: Change status to Review
> EIP-4906: Change status to Review

- EIPS/eip-4200.md
This brings reference code in sync with the code in EIP-3670.
> EIP-4200: Update reference code

- EIPS/eip-2464.md
CC: @karalabe, @timbeiko
Closes https://github.com/ethereum/EIPs/issues/2465
> Finalize EIP-2464

- EIPS/eip-5133.md
> remove "If it is not ready by then..."

- EIPS/eip-5133.md
> Changed Prediction Script

- .github/workflows/auto-merge-bot.yml
I don't think there's anything special I need to put here, so I'm writing this sentence because it feels incorrect to leave a form field blank.
EDIT: I do have something to put here. EIP Editors - do NOT approve this, signal approval with a comment instead. @eth-bot _will_ auto-merge this with only one approval.
> Add myself (@Pandapip1) as an editor

- assets/eip-4973/src/ERC4973.sol
- assets/eip-4973/src/ERC4973.t.sol
- assets/eip-4973/src/interfaces/IERC4973.sol
adds `function burn` from #5136 change into reference implementation
> EIP-4973: Add `function burn` to reference impl.

- EIPS/eip-2976.md
This moves EIP-2976 to final status.
> Move EIP-2976 to final

- EIPS/eip-5133.md
> Status to Review

- EIPS/eip-5133.md
> Status to Last Call

- EIPS/eip-4907.md
- assets/eip-4907/README.md
- assets/eip-4907/contracts/ERC4907.sol
- assets/eip-4907/contracts/ERC4907Demo.sol
- assets/eip-4907/contracts/IERC4907.sol
- assets/eip-4907/package.json
EIP4907: Change Status to Final
> EIP4907: Change Status to Final

- EIPS/eip-3525.md
1. remove the unnecessary TOC
2. revise the description for id-to-address transfer function
> Minor update and clean-ups

- EIPS/eip-4353.md
@aug2uag here you go, sorry about that.
> Fix section order for EIP-4353

- EIPS/eip-5005.md
This PR adds events that were missing from the spec.
> add missing events

- EIPS/eip-173.md
> Move EIP-173 to final with minor (normal) changes

- EIPS/eip-4834.md
> Move EIP-4834 from Draft to Review

- EIPS/eip-4671.md
- assets/eip-4671/ERC4671.sol
- assets/eip-4671/ERC4671Consensus.sol
- assets/eip-4671/ERC4671Delegate.sol
- assets/eip-4671/ERC4671Pull.sol
- assets/eip-4671/ERC4671Store.sol
- assets/eip-4671/IERC4671.sol
- assets/eip-4671/IERC4671Consensus.sol
- assets/eip-4671/IERC4671Delegate.sol
- assets/eip-4671/IERC4671Enumerable.sol
- assets/eip-4671/IERC4671Metadata.sol
- assets/eip-4671/IERC4671Pull.sol
- assets/eip-4671/IERC4671Store.sol
> Fix SPDX license identifier in EIP-4671

- EIPS/eip-3475.md
- assets/eip-3475/IERC3475.sol
> Fix SPDX license identifier in EIP-3475

- .github/workflows/ci.yml
This adds [`eipw`](https://github.com/SamWilsn/eipw) as a step in CI.
> Add trial run of eipw

- .github/workflows/ci.yml
I promise this is the last of the micro-PRs*
\* Unless it isn't
> Remove defunct option in HTMLProofer CI

- EIPS/eip-3448.md
- assets/eip-3448/MetaProxyFactory.sol
- assets/eip-3448/MetaProxyTest.sol
> Add SPDX License Identifier to EIP-3448

- EIPS/eip-2266.md
- assets/eip-2266/Example.sol
> Add SPDX License Identifier to EIP-2266

- .github/workflows/ci.yml
Reverts ethereum/EIPs#5249
It didn't work 😢
> Revert "Small fix for when the Gemfile is updated"

- EIPS/eip-4200.md
Add `Test Cases` section to EIP-4200: Static relative jumps
> EIP-4200: Add test cases

- .github/workflows/ci.yml
- .github/workflows/vercel.yml
> Fix vercel

- .github/workflows/vercel.yml
> Fix vercel... again

- .github/workflows/auto-merge-bot.yml
- .github/workflows/ci.yml
This reverts commit 0d48e94ea22db8d756592899ddedb1dd33189709.
> Revert "Move EIPW into a pull_request_target workflow instead (#5277)"

- .github/workflows/ci-comment.yml
- .github/workflows/ci.yml
This is, unfortunately, what the docs suggest. I think.
> Use a workflow_run trigger to make the `eipw` comment

- EIPS/eip-4519.md
The title exceeded the maximum number of characters. We fixed it to less than 44 characters.
> EIP-4519 - Tittle fixed to less than 44 characters.

- .github/workflows/ci-comment.yml
Deletes the previous comment before posting a new one.
> Make the CI Commenting Cleaner

- EIPS/eip-4906.md
EIP-4906: Change status to Last Call
> EIP-4906: Change status to Last Call

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
This will allow us to point the issue toward the correct repository.
> Update the issue forms

- EIPS/eip-5006.md
- assets/eip-5006/contracts/ERC5006.sol
ERC-5006  Implementation Bugfix
> ERC-5006  Implementation Bugfix

- EIPS/eip-4400.md
- assets/eip-4400/LICENSE
- assets/eip-4400/README.md
- assets/eip-4400/contracts/ERC721Consumable.sol
- assets/eip-4400/contracts/ExampleToken.sol
- assets/eip-4400/contracts/IERC721Consumable.sol
> Fix SPDX license identifier in EIP-4400

- EIPS/eip-4834.md
> Move EIP-4834 to Last Call

- EIPS/eip-5313.md
I have no changes left to make here.
Requesting last call status to raise visibility here and see if anybody objects here.
> Move to last call

- EIPS/eip-3475.md
#﻿When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md
#We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:
changing the ERC to EIP (EIP-1) along with some changes in the rendering issue of md that is bloking the DRAFT
> wip: minor changes about ERC -> EIP and spaces

- .github/workflows/rerun-bot-pull-request-review.yml
> Remove an unnoticed single quote

- .github/workflows/auto-merge-bot.yml
- .github/workflows/auto-stagnate-bot.yml
- .github/workflows/ci-comment.yml
- .github/workflows/ci.yml
- .github/workflows/manual-bot-rerun.yml
- .github/workflows/rerun-bot-workflow-run.yml
- .github/workflows/stale.yml
This reverts commit 213ef960cfc1904a197064a2e249fc96af08e0c3.
> Revert "Improvify GitHub Action (#5312)"

- EIPS/eip-4804.md
> Add schemas "ethereum-web3://" and "eth-web3://"

- EIPS/eip-4844.md
This should appease `eipw`. uwu
> Fix formatting eip refs

- .github/workflows/auto-label-bot.yml
- .jekyll-labels.yml
Adds labels to PRs that, well, need labels. Uses 100% pre-existing but unused labels.
> Add relevant labels to PRs automagically

- .github/workflows/stale.yml
Reverts ethereum/EIPs#5342
Reverting since the PR in question didn't go through the multi-editor approval process and contained functional changes.
> Revert "Update Stale Bot"

- EIPS/eip-5267.md
As suggested in the [discussion forum](https://ethereum-magicians.org/t/eip-5267-retrieval-of-eip-712-domain/9951/5?u=frangio).
> Add a word to clarify meaning in EIP-5267

- .github/workflows/stale.yml
- Uses a single invocation of the action
> Update Stale Bot Formatting

- .github/workflows/ci.yml
This appears to just be a typo, fixing.
> Corrects the name of EIPW.

- .github/workflows/auto-label-bot.yml
Fixes a few bugs. I can't see any possible reason not to merge this immediately but @MicahZoltu will almost certainly have other ideas.
> Update Label Action

- EIPS/eip-831.md
- EIP-4804 is blocked by EIP-831 (as the dependency of 4804) for review status :)
> Update EIP-831 to Review

- .github/workflows/auto-review-bot.yml
See https://github.com/Pandapip1/EIPs-clone/pull/3 for testing PR.
Implements the long-awaited "2 editors needed to merge an unknown file".
> Update EIP Bot

- config/.jekyll-labels.yml
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️
> Fix "waiting: EIP number" label

- EIPS/eip-2330.md
- assets/eip-2330/Extsload.sol
- Update gas costs.
- Add EIP-2929 access list warm/cold address/slot.
- Make changes required to pass EIP Validator checks e.g. add missing fields, remove external links, etc.
cc: @dominicletz @spalladino
> Move EIP-2330 to Draft status

- config/.jekyll-labels.yml
@SamWilsn
Yea. Turns out that files that aren't EIPs don't have valid EIP numbers. Oops.
> Fix the waiting on EIP number label again

- config/.jekyll-labels.yml
So apparently `isNaN(null) != isNan(undefined)`.
> Fix waiting for EIP number label again again

- EIPS/eip-4400.md
fix typo, change ConsumEIPhanged to ConsumerChanged
> EIP-4400, fix typo, change ConsumEIPhanged to ConsumerChanged

- .github/workflows/auto-review-bot.yml
> Re-removes Micah from editor list.

- .github/workflows/ci.yml
Not sure why it started to randomly error, but this fixes it.
> Fix Codespell

- .github/workflows/ci.yml
Reverts ethereum/EIPs#5483
It didn't work.
> Revert "Fix Codespell"

- .github/workflows/post-ci.yml
> Fix Label Adding

- EIPS/eip-5485.md
1. Add mention to SEC and CFTC as use-cases
> Revisions to EIP-5485

- EIPS/eip-5375.md
This PR changes the status of EIP-5375 from "Draft" to "Review".
[Ethereum Magicians discussion](https://ethereum-magicians.org/t/eip-5375-nft-authorship/10182)
[Previous PR](https://github.com/ethereum/EIPs/pull/5375)
Previous reviewer(s): @Pandapip1, @SamWilsn
> Change EIP-5375 (NFT Author Information and Consent) status to "Review"

- EIPS/eip-3525.md
> Revise of preamble

- EIPS/eip-1.md
- eip-template.md
See the EIP-1 changes for description.
Changes needed:
Closes https://github.com/ethereum/EIPs/issues/5245
> Add adoptable field

- .github/workflows/post-ci.yml
- .github/workflows/stale.yml
- config/.jekyll-labels.yml
> Use new label format

- .github/workflows/ci-rerun-trigger.yml
I made a typo that means that this currently doesn't work.
> Fix rerun CI trigger

- EIPS/eip-5007.md
EIP-5007: Move Status to Last Call
> Update EIP-5007: Move Status to Last Call

- EIPS/eip-5437.md
- EIPS/eip-sc.md
> Add EIP-5437: Interface for Security Contact

- EIPS/eip-5192.md
hey,
is it fine if we move this to last call? I don't see us making any other significant edits anymore.
> Update EIP-5192: Move to Last Call

- EIPS/eip-5516.md
- assets/eip-5516/ERC5516.sol
- assets/eip-5516/IERC5516.sol
**CO-Authored by @MatiArazi** 
---
> Move EIP-5516 to Review

- EIPS/eip-5289.md
> Update EIP-5289: Use Base 64

- EIPS/eip-2315.md
> no external links

- EIPS/eip-2315.md
> Incorporate @xinbenlv review

- EIPS/eip-5516.md
- assets/eip-5516/IERC5516.sol
Our bad!
Co-Authored-By: Matias Arazi <71347020+MatiArazi@users.noreply.github.com>
> Error that passed the review stage.

- EIPS/eip-5484.md
> Update EIP-5484: Move to Review

- EIPS/eip-5528.md
> Update EIP-5528: Move to Review

- EIPS/eip-5516.md
- assets/eip-5516/IERC5516.sol
> Fix eip5516 error

- EIPS/eip-5643.md
> Add EIP-5643: Subscription NFTs

- EIPS/eip-5643.md
These functions can be made public or external, not pure or view.
> fix(5643): typo in specification

- EIPS/eip-5643.md
> fix(4563): missing parameter natspec

- EIPS/eip-2315.md
> Update EIP-2315: Ready for Review

- EIPS/eip-4844.md
This PR adds @Inphi as co-author: Mofi has been contributing significant specification feedback and is a core contributor in testing and implementation.
> Update EIP-4844: Add @Inphi to author list

- EIPS/eip-5625.md
- EIPS/eip-draft_nft_metadata_json_schema_dstorage_extension.md
> Add EIP-5625: NFT Metadata JSON Schema dStorage Extension

- EIPS/eip-5289.md
> Update EIP-5289: Fix false positive codespell error

- EIPS/eip-1.md
> Update EIP-1: Fix that stupid Jekyll/Markdown bug

- EIPS/eip-5615.md
- EIPS/eip-XXXX.md
Apparently this isn't actually standardized yet?!?
> Add EIP-5615: EIP-1155 Supply Extension

- EIPS/eip-5528.md
Can we move EIP-5528 to Last-Call?
We do not have significant changes anymore.
> Update EIP-5528: Move to Last Call

- EIPS/eip-2315.md
> eip-2315.md formatting nits

- EIPS/eip-5081.md
> Update EIP-5081: Add Kevin as a co-author

- .gitignore
Blocking https://github.com/ethereum/EIPs/pull/5606
> Configuration: Add .DS_Store to .gitignore

- .github/workflows/auto-review-bot.yml
Reverting #5502 for more discussion.
> Revert "Adds @xinbenlv as an EIP Editor (#5502)"

- EIPS/eip-2135.md
> Update EIP-2135: Move to Review

- EIPS/eip-4883.md
Remove reference to requirement that the caller needs to have rights to use the NFT
> EIP-4883: remove rights requirement

- EIPS/eip-5679.md
> Update EIP-5679: Move to Review
