ethereum/EIPs

- EIPS/eip-4750.md
Unfortunately the current one does not render well:
> EIP-4750: Change bullet point list for markdown rendering

- config/.jekyll-labels.yml
There were some trailing `"`, this PR removes them. In addition, I forgot to re-include some of the old labels.
> CI: Fix typo in labels & add missing labels

- EIPS/eip-4906.md
EIP-4906: Move Status to Final
> Update EIP-4906: Move Status to Final

- EIPS/eip-5375.md
This PR clarifies that all addresses must be written following [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) casing.
> Clarify address casing for EIP-5375

- EIPS/eip-5216.md
- assets/eip-5216/ERC1155ApprovalByAmount.sol
Move EIP-5216 to review and changed OZ msgSender context function to native msg.sender.
Furthermore, I'd like to add some test cases how @MicahZoltu told me here: https://github.com/ethereum/EIPs/pull/5216#pullrequestreview-1048632814. There are some example of this?
> Update EIP-5216: Move to Review

- .codespell-whitelist
Add someone else's name to CodeSpell
> Configuration: Add "furter" to whitelist

- EIPS/eip-1418.md
> Update EIP-1418: More progress // and formatting

- EIPS/eip-4844.md
This PR removes the "system contract" concept from EIP-4844. Although the approach has several pros, it tends to be a sticking point in the discussions around EIP-4844 due to the fact that we don't currently have the concept of a system contract with storage and that concept would need to be implemented into clients - whereas the header extension approach has already been performed to add `baseFee` to the header in EIP-1559.
Additionally, it resolves an issue in the original draft that conflated blobs and blob txs.
Will leave in draft until some consensus among authors is reached.
> Update EIP-4844: Remove system contract concept

- EIPS/eip-4844.md
Renamed the header field a few times and left an outdated reference. (h/t @axic)
> EIP-4844: fix typo

- EIPS/eip-4844.md
This EIP changed the intrinsic `G_transaction ` to 20k, as maybe an incentive for people to use this new transaction type.
If we want to make this change, it should happen in a separate EIP that explains the motivation & solution like every other gas cost change.
[As discussed in Discord]
> fix(4844): leave G_transaction at 21000

- .github/workflows/stale.yml
There was a relevant edge case that meant that the stale bot didn't work properly that got fixed: https://github.com/actions/stale/pull/816
> CI: Update Stale Bot

- EIPS/eip-4844.md
the EIP was refactored in a previous PR to keep the fee state in the block header but references to its prior location in the state remain. this PR fixes the outdated references
> fix signature to use `Header` rather than `ExecState`

- EIPS/eip-2718.md
Change the word _transcation_ to _transaction_
> Update EIP-2718: Fix the spelling of transaction

- EIPS/eip-3670.md
Also add `EOF1 Forward compatibility` subsection to `Motivation`.
> Update EIP-3670: Use exceptions with error messages in reference code

- EIPS/eip-4844.md
The existing text uses the name `max_basefee_per_gas` which suggests the maximum base fee value a transaction would be willing to pay.
This value actually refers to the maximum fee per gas the transaction would be willing to pay (base fee + priority fee) and this change reflects this with what I consider a clearer name.
> Update 4844: use clearer name for max fee value

- EIPS/eip-4844.md
So... at some point back in June [we updated](https://github.com/ethereum/consensus-specs/pull/2901) the consensus side of 4844 to be executable. This resulted in various fixes and improvements for the cryptographic parts of the consensus code.
These updates were never ported back to EIP land because the code was quite unstable and we wanted to minimize any duplicate overhead between EIP and consensus review processes. This means that the EIP was out of date for the past months...
These days, the 4844 cryptographic code seems relatively stable, so this commit updates the EIP. Also, with the merge coming up, more devs will start looking at 4844 code, and hence having the code be up to date is imperative.
Note that instead of updating the cryptographic functions we instead link to the …
> Synchronize EIP-4844 cryptography with consensus specs

- .github/workflows/auto-review-bot.yml
Hi all, unfortunately have not been able to contribute much to ERC editing lately and my inbox if overflowing with notifications. I will be more effective if I focus on the other EIP areas and helping with the process.
@Pandapip1 and @SamWilsn have been doing a great job staying on top of ERCs. If we get to a point again where ERCs are not reviewed in a timely manner I can return to editing them.
Thanks for understanding.
> Remove @lightclient as ERC editor

- _layouts/eip.html
Allows using LaTeX in EIPs (yay!)
> Website: Add MathJax

- EIPS/eip-5643.md
Instead of passing in an `expiration` date, I found it easier to pass in a `duration`. This allows contracts to calculate the price of renewal easier instead of having to derive the duration from the existing expiration.
> Update EIP-5643 interface

- .github/workflows/stale.yml
These labels mean that the PR is waiting on some other person in order to be merged, and the author may still be responsive.
> CI: Disable certain labels from becoming stale

- EIPS/eip-2771.md
CC other authors: Ronan Sandford (@wighawag), Liraz Siri (@lirazsiri), Dror Tirosh (@drortirosh), Yoav Weiss (@yoavw), Alex Forshtat (@forshtat), Hadrien Croubois (@Amxx), Sachin Tomar (@tomarsachin2271), Patrick McCorry (@stonecoldpat), Nicolas Venturo (@nventuro), Fabian Vogelsteller (@frozeman)
> Update EIP-2771: Add myself as an author and bring it up to date

- EIPS/eip-5023.md
- EIPS/eip-shareable-nft.md
PR for comments. Shareable NFT EIP draft.
> Add EIP-5023: Shareable non-transferable non-fungible token

- EIPS/eip-2315.md
> Update EIP-2315: Catch up to latest Yellow Paper

- .github/workflows/auto-stagnate-bot.yml
- .github/workflows/ci-rerun-trigger.yml
- .github/workflows/ci.yml
> CI: Pin hashes

- .github/workflows/auto-label-bot.yml
- .github/workflows/auto-review-bot.yml
- .github/workflows/auto-review-trigger.yml
- .github/workflows/ci.yml
Stops outdated CI runs from hogging the CI queue. Cancels the previous run on push.
Also provides protection against @eth-bot approving PRs that have been changed.
> CI: Add concurrency

- .github/workflows/ci.yml
Now that the CodeSpell issue is fixed, we can now re-enable CI failures.
> CI: Re-enable CodeSpell

- EIPS/eip-5528.md
Update content based on Final review recommends.
First, Thanks for the PR on https://github.com/StartfundInc/EIPs-5528-review/pull/1
And updated based on latest recommend from @SamWilsn : https://github.com/ethereum/EIPs/pull/5790#pullrequestreview-1146519906
> EIP-5528 update MD contents in review state

- EIPS/eip-4895.md
address some feedback from eth-magicians
and reflect latest changes to CL specs around withdrawal object
> Update EIP-4895: `validator_index` and more info around `index`

- EIPS/eip-3525.md
This PR fixes several typos and offers grammatical and verbiage improvements to help improve clarity.
> Update EIP-3525: verbiage improvements, typos

- EIPS/eip-5791.md
The payload input argument should be of type `bytes calldata` because it doesn't make sense to limit the length of a payload that a chip can sign. This payload can be of arbitrary length.
> Update EIP-5791: Change payload to be type bytes

- .github/workflows/ci.yml
Currently, the detection of the changed file detects out-of-date branches as changing files. This fixes it.
> CI: Fix changed files detection

- EIPS/eip-4844.md
Update to the EIP-4844 fee market design. List of changes:
Potential remaining todos:
> Update EIP-4844: Fee Market Update

- EIPS/eip-2612.md
Two non-normative changes are included here in addition to the move to Final:
1. The title is slightly changed because the previous title looked awkward (was "**EIP-2612: EIP-20** Permit Extension ...")
2. The spec is changed to more explicitly say the contract "must" implement the 3 functions as suggested by @xinbenlv in https://github.com/ethereum/EIPs/pull/5506#issuecomment-1267523134. (Note: I didn't use all caps "MUST" because the RFC 2119 clause is not present and I don't want to add it to minimize changes.)
> Update EIP-2612: Move to Final

- EIPS/eip-5568.md
- EIPS/eip-signal.md
Apparently, descriptions are highly recommended. I suggest that you look at [the files tab](https://github.com/ethereum/EIPs/pull/5568/files) instead.
> Add EIP-5568: Required Action Signals Using Revert Reasons

- EIPS/eip-4844.md
Removed the dots behind two sentences because every other bullet point is punctuated this way, too.
> EIP-4844.md: Fixed punctuation inconsistency

- EIPS/eip-3540.md
Fix data-only contract example, currently it has the terminator byte (00) instead of code_section byte (01), and code_section byte instead of data_section byte (02).
> Fix data-only contract example

- EIPS/eip-4844.md
Revise 4844 to include 4895 as a dependency; including reflecting that EIP's effects on the header format
> EIP-4844: declare withdrawals in 4895 as a dependency

- EIPS/eip-5732.md
Clean up some lengthy reference implementations
> Update EIP-5732 Clean up

- EIPS/eip-5489.md
This PR contains following modifications:
1. MOD: eip-5489 to review status
2. ADD: detailed description of EIP-5489 JSON Metadata
> Update EIP-5489: Move to review

- EIPS/eip-4844.md
During discussions at and after Devcon VI, it became clear that there is a desire to lower the initial blob throughput to ensure network stability. This PR reduces the max throughput from 2 MB to 0.5 MB per block, as well as the target from 1 MB to 0.25 MB per block.
The expectation would be to increase the throughput over the next few hardforks back to its original value. In case the EIP is not included into Shanghai, higher initial values might be appropriate, as there will be more lead time for network stress testing and CL client hardening.
> [EIP-4844] Reduce Throughput

- EIPS/eip-4519.md
Can we move eip-4519 to last call?
> Update EIP-4519: Move to last call

- README.md
They're over half a year out-of-date.
> Update README: Update automatic check descriptions

- EIPS/eip-2535.md
Removed incorrect words that describe Loupe functions.
> Update EIP-2535: fix typos (unnecessary/incorrect words)

- EIPS/eip-1.md
As discussed in [EIPIP Meeting #64](https://github.com/ethereum-cat-herders/EIPIP/issues/174), here's a PR with my proposal for updating the `requires` text.
> Update EIP-1: Clarify when to use `requires`

- EIPS/eip-3670.md
- EIPS/eip-4200.md
- EIPS/eip-4750.md
We assume one definition in EIP-3540 code is enough and other EIPs' codes reuse it.
> Remove redundant ValidationException definition from EOF EIPs

- .github/workflows/ci.yml
The latest version of `eipw` will report warnings instead of errors for EIPs with a Stagnant status. This should let the stagnant bot work properly.
> CI: Grab latest `eipw`, which won't block stagnant bot

- EIPS/eip-1898.md
Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>
It is supported by Geth 1.9.6 ([PR](https://github.com/ethereum/go-ethereum/pull/19491)).
It is supported by Besu 20.10.4 ([PR](https://github.com/hyperledger/besu/pull/1784)).
> Update EIP-1898: Move to draft

- EIPS/eip-3540.md
- EIPS/eip-3670.md
Move detailed rules from EIP-3670 to clarify contract behavior in context of EOF validation.
> EIP-3540: Clarify contract creation rules

- EIPS/eip-4844.md
Clarifies how to interpret `parent.excess_data_gas` for the first post-fork block, where that field is not defined for the parent.
> Update EIP-4844: Clarify Fork Block Behavior

- EIPS/eip-4844.md
This PR does two things (split into corresponding commits):
- Simplifies the implementation of the point evaluation precompile by using the bytes-based `verify_kzg_proof()` from https://github.com/ethereum/consensus-specs/pull/3097 . This way the client developers don't need to understand what field elements are, and can just pass bytes to the KZG library.
- Syncs `validate_blob_transaction_wrapper()` to the latest high-level crypto API of the consensus specs introduced in https://github.com/ethereum/consensus-specs/pull/3038
> EIP4844: Update crypto API (simplify precompile / sync with consensus-specs)

- EIPS/eip-4844.md
Specifies that blob transactions should not be broadcast to peers, but only announced (so that they can then be manually retrieved).
Adds a reference to https://github.com/ethereum/EIPs/pull/5793 which will give peers more fine-grained control by making it possible to identify blob transactions (and their size) from announcement messages.
> Update EIP-4844: Disable Blob Transaction Broadcast

- EIPS/eip-4844.md
Clarify that the precompile return values follow the usual EVM big endian encoding.
> Update EIP-4844: Clarify Precompile Return Data Endianness

- EIPS/eip-5920.md
- EIPS/eip-pay-opcode.md
Adds a new opcode to do simple ether transfers.
discussions-to: https://ethereum-magicians.org/t/eip-5920-pay-opcode/11717
> Add EIP-5920: PAY opcode

- EIPS/eip-4844.md
This PR includes two clarifications:
- Remove deprecated gas price of blobs (simplified version)
- Remove outdated gas-advantage consideration
> Update EIP-4844: small clarification

- EIPS/eip-5749.md
please refer to https://github.com/ethereum/EIPs/pull/5912#issuecomment-1314247015 to comments regarding title and the reason for `evmproviders`
> Update EIP-5749: Move to last call

- EIPS/eip-5007.md
- assets/eip-5007/contracts/ERC5007.sol
- assets/eip-5007/contracts/ERC5007Composable.sol
- assets/eip-5007/contracts/ERC5007ComposableTest.sol
- assets/eip-5007/contracts/ERC5007Demo.sol
- assets/eip-5007/contracts/IERC5007.sol
- assets/eip-5007/contracts/IERC5007Composable.sol
- assets/eip-5007/test/test.js
EIP-5007: Change uint64 to int64
The max value of `int64` is 9,223,372,036,854,775,807. As a timestamp, 9,223,372,036,854,775,807 is about year 292,471,210,648. `uint256` is too big for C, C++, Java, Go, etc, and `int64` is natively supported by mainstream programming languages.
> EIP-5007: Change uint64 to int64

- EIPS/eip-191.md
- Updating the example to be more comprehensive + more updated. 
- Simplifying the EIP191 Standard, by providing more explanation of the different versions.
- Re-ordering the text so we start by:
- The formula for the standard
- Why we have 0x19
- What are the different bytes version we have
- Explicitly mentioning that `E` is version `0x45`and `thereum Signed Message:\n" + len(message)` is version specific data.
> Update EIP-191: Improve Comprehensibility

- EIPS/eip-1.md
This add the Ethereum networking specs (devp2p) as an accepted resource to EIP-1.
> Update EIP-1: add devp2p repo as accepted external resource

- EIPS/eip-4750.md
Clarify that data stack limit of 1024 items still applies.
Also make CALLF fail immediately if it would result in stack overflow.
> Update EIP-4750: Clarify stack overflow rules

- EIPS/eip-3540.md
Forbid EOF → legacy contract creation.
> Update EIP-3540: Restrict EOF version in create

- EIPS/eip-4200.md
1.  Reject `RJUMPV` with empty jump table at validation.
2. Fix off-by-one bug in reference code when reading jump table size.
3. Update reference code to disallow CALLCODE ad SELFDESTRUCT according to current spec of EIP-3670.
> Update-4200: disallow empty jump table

- EIPS/eip-4750.md
Exception if not exactly `types[i].output` items on stack at `RETF`.
(This runtime check is superseded by deploy-time validation of EIP-5450)
> Update EIP-4750: Clarify RETF not cleaning the stack automatically

- EIPS/eip-4844.md
Clarify that the precompile will reject non-canonical inputs. Also update the consensus-specs git reference to point to the latest version.
> EIP4844: Be explicit about precompile accepting canonical inputs

- EIPS/eip-4895.md
incorrect typo from #6089 and @eth-bot merged a little too quickly
thanks to @yperbasis for catching the error!
> EIP-4895: fix typo from #6089 to use correct type for withdrawal `amount`

- .github/workflows/ci.yml
Recently, Github updated its `ubuntu-latest` to a new version `ubuntu-22.04` so ruby 2.6 is no longer supported, resulting [this kind of failure](https://github.com/ethereum/EIPs/actions/runs/3654459792/jobs/6174903582)
```
Error: Error: Unknown version 2.6.0 for ruby on ubuntu-22.04
available versions for ruby on ubuntu-22.04: 3.1.0, 3.1.1, 3.1.2, 3.2.0-preview1, head, debug
Make sure you use the latest version of the action with - uses: ruby/setup-ruby@v1
```
Here is the fix steps tried:
1. Update the ruby to `3.1.2` which is latest stable release available. result: https://github.com/ethereum/EIPs/actions/runs/3654483141/jobs/6174948461 yields `minitest-5.14.1 requires ruby version ~> 2.2, which is incompatible with the`
2. Revert the `ubuntu-latest` to `ubuntu-20.04`, passed
> Update ci.yml for ubuntu version fixing HTMLProofer

- EIPS/eip-3540.md
- EIPS/eip-3670.md
Drop the requirement that the last instruction in code is "terminating". The change requires adding explicit rule about immediate data.
> Update EIP-3670: Drop "terminating" instruction restriction

- EIPS/eip-5375.md
Unlike stated in the specifications, the example in line 193 did not escape the non-ASCII character "à". This PR fixes our mistake.
> Update EIP-5375: Fix typo in JSON

- .github/workflows/ci.yml
Reapplies #6091 with an additional fix for `ahash`.
> Grab latest eipw... again

- EIPS/eip-5807.md
- EIPS/eip-5850.md
> Add EIP-5850: Complex Numbers stored in Bytes32 types

- EIPS/eip-2481.md
EIP has been in last call for ~6 months. Eth/66 has long been implemented by all clients, so this should be final already
> Update EIP-2481: Move to final

- EIPS/eip-4750.md
> Remove terminating instructions validation

- EIPS/eip-6059.md
The note about EIP-6059 being able to support inter-operation between multiple NFT collections was added.
> EIP-6059: Add a note about inter-contract compatibility of EIP-6059

- EIPS/eip-5773.md
- assets/eip-5773/contracts/MultiAssetToken.sol
- assets/eip-5773/test/multiasset.ts
A test which failed before fixing the bug was included.
> Fixes bug when replacing asset on sample implementation of 5773

- EIPS/eip-6206.md
- EIPS/jumpf.md
This is a follow up from #6205 which removed `JUMPF` specification from EIP-4750. We have reintroduced it with a direct dependency to EIP-5450 to avoid specifying any runtime validation semantics (which would ultimately be discarded with EIP-5450).
> Add EIP-6206: EOF - JUMPF instruction

- EIPS/eip-5115.md
Minor correction on the interface removing the unused AssetType enum.
> Update EIP-5115: Minor correction on interface

- EIPS/eip-4337.md
Fixes typo: 'desribed' -> 'described'
> Update EIP-4337: fix typo desribed -> described

- EIPS/eip-3540.md
There was a comment on discord to clarify the order of operations w.r.t. failed initcode validation and metering.
> Clarify that initcode which fails validation still pays 3860 `initcode_cost`

- EIPS/eip-3670.md
- EIPS/eip-4200.md
- EIPS/eip-4750.md
It seems like after the decision was made to add back `pc` instruction, people are [leaning more](https://discord.com/channels/595666850260713488/706868829900505180/1055540534883651697) again towards removing it from EOF. This PR accomplishes that.
> Remove `pc` instruction from eof

- EIPS/eip-5606.md
> Update EIP-5606: Move to Last Call

- .gitignore
- EIPS/eip-3540.md
- EIPS/eip-3670.md
- EIPS/eip-4200.md
- EIPS/eip-4337.md
- EIPS/eip-4750.md
- EIPS/eip-5115.md
- EIPS/eip-5219.md
- EIPS/eip-5380.md
- EIPS/eip-5450.md
- EIPS/eip-5507.md
- EIPS/eip-5568.md
- EIPS/eip-5606.md
- EIPS/eip-5773.md
- EIPS/eip-6110.md
- EIPS/eip-6170.md
- EIPS/eip-6206.md
- assets/eip-5773/contracts/MultiAssetToken.sol
- assets/eip-5773/test/multiasset.ts
> Merge master into eip-5380-review

- EIPS/eip-3540.md
Also, fixed the minimum (0003 -> 0004) and maximum (FFFF -> FFFC) because it has to be divisible by four
> Explained typesize in the v.1 header

- EIPS/eip-4337.md
Update EIP-4337 to the working version from
https://github.com/eth-infinitism/account-abstraction/blob/develop/eip/EIPS/eip-4337.md
Changes:
AA-94 update keccak rules.
AA-93 Adding debug RPC APIs for the Bundler to use (#153)
AA 92 simulate execution (#152)
AA 73 unify reputation (#144)
AA-68 rpc calls (#132)
AA-61 rename wallet to account (#134)
AA-69 wallet support for simulation without signing (#133)
AA-70 rename requestId to userOpHash (#138)
AA-67 relax storage rules in opcode banning (#121)
AA-63 remove paymaster stake value from EntryPoint (#119)
AA-51 simpler simulation api, including aggregation
AA-60 validate timestamp (#117)
Clarify wallet factory behavior when the wallet already exists (#118)
> Update EIP-4337 to latest working version

- EIPS/eip-5630.md
add material on encrypting to a contract. remove the HKDF. expand on rationale.
> add material to EIP-5630

- EIPS/eip-3540.md
This makes explicit when contract creation fails even if initcode is valid.
> Test cases: specify when contract creation fails in Valid initcode

- EIPS/eip-3540.md
Now that data section is allowed to be 0, we should all expand the overall range.
> 3540: type size range should start at 0

- EIPS/eip-725.md
- assets/eip-725/ERC725.sol
- Adding function selector for ERC725 functions
- Add an example to use specific notations when calling ERC725 overloaded functions
- Mark standard as Draft instead of Stagnant
- Change the terms keys and values to dataKeys and dataValues.
- Change the term key/value store to data key/value store. (Use key/value store instead of key-value store)
- Edit `Executed` event to use bytes4 instead of bytes
- Overload `execute` function in ERC725X
- Modify `ContractCreated` event to include a `bytes32 salt`
- Add a simple implementation of ERC725
> Update EIP-725: Improvements

- assets/css/style.scss
This pull request centers layout of the EIP website.
The current layout is very hard to read on bigger screens. For example, an ultrawide monitor of 2560x1080 resolution displayed the website as the following:
The proposed change fixes the maximum width of the content to 960px and centers the layout on all screen sizes:
> Center layout

- EIPS/eip-4337.md
Fixing small typos:
"To avoid confusion, it is **not** named "transaction".
"unlike **a** transaction, it contains several other fields, described below"
"A node/bundler SHOULD drop (~~not~~ add to the mempool) a `UserOperation`"
> Update EIP-4337: fix miscellaneous typos

- EIPS/eip-3540.md
This bound already exists in 4750, just propagating it up to 3540.
> 3540: restrict number of code sections to 1024

- .github/workflows/auto-label-bot.yml
Fixes a minor issue with labeling
> CI: Only run label bot on PRs to master

- EIPS/eip-5570.md
Although forcing signatures upon the vendors would be useful, allowing third parties and users to create their own receipts that are valid (but ultimately not legal receipts) does offer some opportunities for projects.
> Make signature of signature optional

- EIPS/eip-3860.md
Change the failure in case of exceeding the initcode size limit for CREATE instructions to be OOG (same as the other check and many others).
See https://ethereum-magicians.org/t/eip-3860-limit-and-meter-initcode/7018/15.
> EIP-3860: Change the failure to OOG

- EIPS/eip-4844.md
this makes the tx hashing for the purposes of tx signing more consistent with computing the hash of a signed blob transaction, and should be more efficient.  Sister PR to https://github.com/ethereum/EIPs/pull/6238
> change blob tx_hash to use serialize instead of hash_tree_root

- EIPS/eip-6147.md
- EIPS/eip-draft_tittle_GONS.md
> Add EIP-6147: Guard of NFT/SBT, an Extension of EIP-721

- EIPS/eip-4895.md
Following discussion from here https://github.com/ethereum/pm/issues/702, protocol devs want to explore harmonization in the withdrawals format from CL to EL.
This PR updates EIP-4895 with the first part of this change to use the same units (`Gwei`) for the `amount` in each withdrawal.
> EIP-4895: CL-EL withdrawals harmonization: using units of Gwei

- EIPS/eip-4844.md
This clarifies how the `DATAHASH` opcode return value is pushed back onto the stack in the previous place of the popped input, essentially replacing it. Also clarifies it's the top value of the stack, and the input `index` is interpreted as big-endian `uint256`.
No functionality changes.
Thanks to the EthereumJS team for reporting this.
> Update EIP-4844: clarify datahash return value

- EIPS/eip-4200.md
Fixing typo when comparing RJUMP/RJUMPI to JUMP/JUMPI sequences.
> EIP-4200: fix RJUMPI -> JUMPI

- EIPS/eip-6372.md
- EIPS/eip-XXXX.md
Following discussion on EIP-5805, we decided to spin of clock part of the interface as its own EIP.
EIP-5805 will add a dependency on this once merged.
> Add EIP-6372: Contract clock

- EIPS/eip-4736.md
The CLWP GitHub repository and website https://clwp.xyz has launched, and we intend to move from an EIP-4736 from Stagnant status back to Draft status for further review. 
This change has:
- updated the status from stagnant to Draft
- Removed pre-loading deposit address information into clients, as we intend to instead rely upon social consensus for reviewing any contentions (which may include signatures from the deposit address)
- Changed wording from "Change withdrawal address" in favor of "set withdrawal address" to align with other "set address" operations, and emphasize that the set withdrawal address action is a one time event 
We welcome any feedback and further modifications. Beacon client teams are still making final implementations and some have indicated (prysm, lighthouse) an …
> Update EIP-4736: Move to Draft

- .github/workflows/auto-review-bot.yml
- .github/workflows/post-ci.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> CI: Use environment files

- EIPS/eip-6120.md
Changes:
* Using `mode` for input tokens and `flags` for action for better visibility
* add `IN_TX_PAYMENT` input token mode for payment-in-callback style contracts (e.g. Uniswap/v3)
* add `ALLOWANCE_BRIDGE` as a compatibility input token mode for contracts that directly called `transferFrom` for pull payment
* add more Sample Usages for Uniswap/v3 swap and liquidity functionalities.
> Update new design for better compatibility

- EIPS/eip-6093.md
Several language corrections and improvements for EIP-6093.
Most edits proposed in this PR should be uncontroversial, but I want to share the rationale behind my suggestion to say "greater than or equal to" instead of "equal or greater than". There are two reasons:
1. This is the formal definition ([reference](https://www.cuemath.com/numbers/greater-than-or-equal-to/)).
2. Closer to the actual mathematical sign `>=` (the sign starts with "greater than")
Cc @ernestognw.
> Update: EIP-6093: improve wording

- EIPS/eip-5018.md
> Update EIP-5018: Move to Review

- EIPS/eip-6465.md
> Add EIP-6465: SSZ withdrawals root

- EIPS/eip-5793.md
This PR changes EIP-5793 (`eth/68`) to Review status, on request of @MariusVanDerWijden.
The EIP is a soft-dependency of EIP-4844 (the EIP will work without, but propagation of larger transactions is derisked with the functionality of this EIP) and ready to move to Review status.
> Update EIP-5793: update EIP to Review status (eth/68)

- EIPS/eip-6206.md
This replaces two requirements on `stack_height` at JUMPF (inequality + equality) with equivalent combination of JUMPF instruction validation requirement and `stack_height` equality requirement.
> EIP-6206: Simplify JUMPF validation

- EIPS/eip-6404.md
- EIPS/eip-6465.md
- EIPS/eip-6466.md
> Add EIP-6466: SSZ receipts root

- EIPS/eip-4844.md
These limits allow growth to up to `2**12` blobs per transaction, which is up to `512 MB` of blob data at the current blob size (4096 field elements) and `4 GB` of blob data at the maximum blob size currently supported by the trusted setup (`2**15` field elements).
- If matching on email address, the email address is the one publicly listed on your …
> More sane limits on blobs per transactions

- EIPS/eip-6059.md
The interface Id changed in a previous iteration.
The rename from EIP to ERC on the document was made to follow new rules.
> Updates interface Id and renames EIP references to ERC.

- .github/workflows/auto-review-bot.yml
- README.md
Uses `ethereum/eip-review-bot` instead of `Pandapip1/eip-review-bot`.
> CI: Update eip-review-bot username

- EIPS/eip-5114.md
Mostly just switching "token" for "badge", except in the description (to make it more... descriptive.)
> ERC-5114: Some wording changes regarding badge vs. token

- EIPS/eip-4361.md
Update EIP-4361 back to `Review` from `Stagnant`.
> Update EIP-4361: Move to Review

- EIPS/eip-4750.md
Change runtime checks to asserts coming from EOF verification.
> EIP-4750: Change checks to asserts

- EIPS/eip-5507.md
`smallest divisible unit` -> `indivisible unit`
> Update EIP-5507: Fix small typo

- EIPS/eip-6467.md
- EIPS/eip-6538.md
The stealth meta-address registry will provide a central place for users to store their stealth-meta address as defined in [EIP-5564](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-5564.md).
Its a light-weight contract that can be called to (programmatically) retrieve the stealth meta-address of a users to then engage in more private interactions through a stealth address.
> Add Stealth Meta-Address Registry 

- EIPS/eip-6492.md
This PR adds an EIP that extends EIP-1271 with an addition that allows counterfactual contracts to sign messages and get them verified. It was initially inspired by this thread in the EIP-4337 implementation: https://github.com/eth-infinitism/account-abstraction/issues/188
btw sorry for assigning a number, I read that this is the editor responsibility later on but figured I'd leave it in as it should make life easier
> Add EIP: Signature Validation for Pre-Deploy Contracts

- EIPS/eip-6047.md
- EIPS/eip-xxx.md
> Add EIP-6047: Extend ERC-721 to Support balance counting via Transfer event

- EIPS/eip-5807.md
- EIPS/eip-5883.md
title: Token Transfer by Social Recovery
description: This EIP describes a token recovery by a transfer from an identity which is not accessible anymore to another newly created identity by social interaction.
Looking forward to feedback!
> Add EIP-5883: Token Transfer by Social Recovery

- EIPS/eip-6120.md
An address in the form of `0x6120...6120` is added for the deployed UTR contract. Update text, and authors.
> EIP-6120: add the UTR contract address

- EIPS/eip-223.md
Transfer event description does not match the reference implementation code. This needs to be fixed.
> Update EIP-223: update the event specification code

- EIPS/eip-5773.md
- assets/eip-5773/contracts/IERC5773.sol
- assets/eip-5773/contracts/MultiAssetToken.sol
- assets/eip-5773/test/multiasset.ts
The interface was renamed to IERC5773 and the MultiAssetToken contract was updated to use the new interface.
> Update EIP-5773: Update interface

- EIPS/eip-6220.md
- assets/eip-6220/contracts/EquippableToken.sol
- assets/eip-6220/contracts/IERC6220.sol
- assets/eip-6220/package.json
- assets/eip-6220/test/equippableSlotParts.ts
The interface was renamed to IERC5773 and the MultiAssetToken contract was updated to use the new interface.
> Update ERC-6220 interface

- EIPS/eip-6059.md
As the discussion on the EIP-6059 seems to have been concluded, we are proposing to upgrade the EIP to Last Call.
> Update ERC-6059: Move to Last Call

- EIPS/eip-6404.md
- assets/eip-6404/tests/normalized/convert_transactions.py
- assets/eip-6404/tests/normalized/create_proofs.py
- assets/eip-6404/tests/normalized/ssz_proof_types.py
- assets/eip-6404/tests/normalized/ssz_tx_types.py
- assets/eip-6404/tests/normalized/verify_proofs.c
- assets/eip-6404/tests/normalized/verify_proofs.py
- assets/eip-6404/tests/union/create_proofs.py
- assets/eip-6404/tests/union/verify_proofs.c
Chain ID is already mixed into each transaction signature, no need to replicate it as part of the transactions list.
> Update EIP-6404: rm `chain_id` from txs wrapper

- _includes/head.html
The documentation was out of date and that loader no longer exists.
> Website: Fix MathJax

- EIPS/eip-3651.md
This EIP has been in review without changes for between one and two years.
Several times I have had to un-stagnant it.
Because of its [inclusion in Shanghai](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md#eips-considered-for-inclusion), and because it was implemented by all recognized clients without sprouting ambiguity, I wish to begin the transition to Final.
Changes status to last-call
Sets a last-call-deadline two weeks from today.
> Move EIP-3651 to Last Call

- EIPS/eip-6506.md
- EIPS/jhweintraub_eip.md
> Add EIP: P2P Escrowed Governance Incentives

- EIPS/eip-6110.md
Fixed Typo in the following file :
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-6110.md
- All builds' were passed
- OmkarK97 -<omkar139797@gmail.com>
- Changed typo error of responsibliity -> responsibility (line 15)
> Update EIP-6110: Fixed typo in eip-6110.md

- EIPS/eip-6110.md
Reverts ethereum/EIPs#6779 due to spam, the original change is proposed here https://github.com/ethereum/EIPs/pull/6778
> Update EIP-6110: Fixed typo in eip-6110.md"

- EIPS/eip-5773.md
- assets/eip-5773/contracts/IERC5773.sol
- assets/eip-5773/contracts/MultiAssetToken.sol
- assets/eip-5773/contracts/utils/MultiAssetRenderUtils.sol
- assets/eip-5773/test/multiasset.ts
- assets/eip-5773/test/renderUtils.ts
Upon detailed examination we have concluded that priorities should be expressed in `uint64` instead of `uint16` as this consumes less gas upon implementation of the proposal.
> Update EIP-5773: Modify specification to consume less gas

- EIPS/eip-4895.md
replace `TBD` timestamp with `mainnet` value
> Update EIP-4895: add `mainnet` timestamp for shanghai fork

- EIPS/eip-6810.md
- EIPS/eip-draft-oops.md
Introduces a new EIP to solve all of Ethereum's top challenges with user experience and legal compliance.
[My previous attempt](https://github.com/ethereum/EIPs/pull/3455) was rejected despite having no security issues, but this one will be easier to use, as it does not require deploying a smart contract.
> Add EIP: Ex Post Facto Cascading Revert

- assets/css/style.scss
Add a media query that automatically hides the header and the footer when printing an EIP.
> Website: 💄 hide header/footer on print

- EIPS/eip-6823.md
This proposal suggests an approach to improving the accuracy of off-chain transaction simulations that involve contracts that comply with the `ERC-20`/`ERC-721`/`ERC-1155` standards. The proposal provides a standardized entry point to obtain the reserved storage slot of a mapping responsible for tracking ownership of tokens in a contract. This approach not only helps capture state changes more precisely but also enables external tools and services to do so without requiring expertise in specific implementation details.
Due to the unique storage layout for different contracts, it is challenging to simulate transactions that involve smart contracts, specifically due to the use of mappings. The storage location of a value in a mapping depends on a specific storage slot, which can only be …
> Add EIP: Token Mapping Slot Retrieval Extension

- EIPS/eip-5564.md
By introducing a staking mechanism similar to eip-4337, we can handle DoS by filtering spamming senders within the parsing process. Parsing providers can either entirely filter the announcements of known spammer or de-prioritize them.
> Update EIP-5564: update eip-5564 - add staking mechanism

- EIPS/eip-1.md
This PR adds the [Ethereum Execution Client Specifications](https://github.com/ethereum/execution-specs) as well as the [Ethereum Yellow Paper](https://github.com/ethereum/yellowpaper) as permitted links to EIP-1. The related draft EIP triggering this PR is https://github.com/ethereum/EIPs/pull/6269.
> Update EIP-1: Permit links to Execution Specs

- EIPS/eip-3860.md
This PR promote EIP-3860 to `Last call`.
> Update EIP-3860: Move to Last Call

- EIPS/eip-4844.md
Different precompiles treat non-canonical input lengths differently (ECREC pads & truncates, BLAKE2F fails). A.t.m. EIP-4844 is mute on the matter. This change stipulates that inputs with incorrect lengths to the point evaluation precompile result in failure.
> Update EIP-4844: check input length of the precompile

- EIPS/eip-4844.md
This PR changes the blob tx type from 0x05 to 0x03. 
The types 0x03 and 0x04 are not set on mainnet. We should not create the expectation that we will care about transaction types on other chains. i think the expectation should be that at least the first 32 transaction types are reserved for mainnet use.
> Update EIP-4844: change blob transaction type to 0x03

- EIPS/eip-4788.md
- additional author
- use block roots instead of state roots
- key by slot
- use of ring buffer in state
- use header timestamps to derive slot numbers, rather than consume additional header space
also relevant: https://github.com/ethereum/consensus-specs/pull/3319
> Update EIP-4788: Move to Draft

- EIPS/eip-4881.md
> Update EIP-4881: Move to Review

- EIPS/eip-3690.md
Fixes typo: 'contact' -> 'contract'
> Update EIP-3690: Fix typo

- EIPS/eip-1444.md
Fixes typo: 'contact' -> 'contract'
> Update EIP-1444: Fix typo

- EIPS/eip-6049.md
Changes "udpates" to "updates"
> Update EIP-6049: fix (small) typo

- .github/renovate.json
Renovate will try to update ethereum/eip-review-bot to the default branch, while the built action is in the `dist` branch.
> Config: Add ethereum/eip-review-bot to renovate ignorelist

- assets/eip-5219/IDecentralizedApp.sol
When I had written this, I had a brainfart and thought that `uint8` was 8 *bytes*, and not 8 *bits*.
As the specification references that any status code is allowed, the EIP-712 "that specification doesn't work" rule applies.
> Update EIP-5219: Fix major brainfart

- EIPS/eip-6120.md
Greatly simplify the standard by focusing on token allowance only:
* remove `action.flags` and its usages
* remove `amountInSource` and its usages
* rename `amountInMax` to `amountIn`
* remove `ALLOWANCE` and `*_FROM_ROUTER` modes
* input mode now only have 2 values: `PAYMENT`, `TRANSFER`, and `CALL_VALUE`
* add `UTR.discard` function to discard a portion of pending payment
Tokens should not be transferred to the UTR, in the new standard.
> Update EIP-6120: simplify the standard

- EIPS/eip-6913.md
- EIPS/eip-draft-setcode.md
SETCODE allows contracts to replace their code without clearing their internal state.
I hope SETCODE will be adopted at the same time that SELFDESTRUCT is broken, in order to preserve in-place code replacement.
Create EIP introducing SETCODE
> Add EIP: SETCODE instruction

- .github/workflows/ci.yml
eipw-lint-js 0.4.5 fixes the unicode issue causing panics on #6916
> CI: Bump eipw to 0.4.5

- EIPS/eip-5639.md
The first commit section is missing the initial forward slash.
> Update EIP-5639: Add missing forward slash

- EIPS/eip-6493.md
Simplify the SSZ transaction signature scheme by removing some elements:
- `tx_type_fork_version` is not needed, as transaction signatures do not expire. On consensus messages, certain messages are constrained in validity to a single fork, which we won't need here.
- `DomainType` is not needed, as execution signatures use ECDSA and consensus signatures use BLS, so there is no harm done by reusing domain types across layers.
- `genesis_hash` is not needed, as the `chain_id` already uniquely identifies an individual chain. Malicious actors setting up custom networks can deliberately introduce both `genesis_hash` and `chain_id` conflicts with the same effort, so there is no security benefit in including both of these values.
- The EIP-2718 transaction type already encodes the type of message …
> Update EIP-6493: Drop `DomainType`, `fork_version`, `genesis_hash`

- EIPS/eip-4788.md
Avoid conflict with `Basefee` opcode (`0x48`) and `Datahash` opcode (`0x49`)
> Update EIP-4788: Update eip-4788.md

- EIPS/eip-6066.md
- EIPS/eip-6493.md
- Added interface detection support
- Fixed a wrong interface ID (magic value)
- Revised wording slightly
> Update EIP-6066: Added ERC165 support, fixed interface ID

- EIPS/eip-5564.md
Add link to EIP-6538 to make the section on stealth meta-addresses more clear.
> Update EIP-5564: add link to eip-6538

- EIPS/eip-1271.md
Change `an` to `a` in ERC 1271, as it precedes `signed`. I believe this was just a typo.
I also noticed the clause:
> considering that an *authorized* signers providing proper signatures for a given data would see their signature as "valid" by the signing contract
And think "signers" may be a typo, or I may just be misinterpreting the sentence.
> Update EIP-1271: Change `an` to `a` in ERC 1271, as it precedes `signed`

- EIPS/eip-6821.md
- EIPS/eip-xxx.md
> Add EIP: Support ENS Name for Web3 URL

- EIPS/eip-5573.md
to prevent a conflict with the erc-4631 statement abnf definition, which only allows single quotes ', not double quotes ". This pr also adds more description of the meaning of the NB objects and their requirements (e.g. an empty [{}] object in the array implies no restrictions, while an empty array [] implies no options to apply when using a capability, i.e. it is not available). this grammar is [defined in the ucan spec v0.10 section 3.2.6.3](https://github.com/ucan-wg/spec/blob/0.10/README.md#3263-caveat-array)
> Update EIP-5573: ERC-5573 update

- EIPS/eip-4844.md
The second argument of `calc_data_fee` is `parent` rather than `header`.
> Update EIP-4844: amend inconsistency in calc_data_fee

- EIPS/eip-4844.md
I'd like to propose removing SSZ entirely from the EL side of 4844.
The only real value in blob transactions being SSZ encoded (as specified) is that the CL is able to parse the transaction and easily access `blob_versioned_hashes`. I don't have a great solution to this if they aren't SSZ encoded. Ultimately it seems that either i) one of the layers implements the other layer's serialization scheme or ii) the engine api is extended to resolve blob hashes given a blob tx (may not even be efficient enough).
I think adding RLP into the CL requires much less decision making than supporting SSZ in the EL. It's already clear how to lay transactions out, calculate their sig hashes and standard hashes, etc. CLs simply need to search through the opaque blobs, find the blob txs, then RLP decode …
> Update EIP-4844: de-sszify spec

- EIPS/eip-4844.md
Right now `DATAHASH` sort of conflicts with the EOF data section concept (which will want to have things like `DATALOAD`, `DATACOPY`, etc for). So I propose we change the mnemonic for blob hashes to `BLOBHASH` instead.
> Update EIP-4844: change op to `BLOBHASH`

- EIPS/eip-6093.md
While implementing the standard, we realized there are some extra cases considered in ERC721 to take account of, rewording `ERC721InvalidOwner` into `ERC721IncorrectOwner` to avoid conflicting with a new `ERC721InvalidOwner` error that asserts the validity of an address as an owner (EIP-721 explicitly invalidates `address(0)` as an owner).
Additionally, errors for querying `ownerOf` and token existence were added.
> Update EIP-6093: EIP6093 Corrections for ERC721

- EIPS/eip-6093.md
After further working in implementing the EIP, we realized that there's no other way of approval in ERC1155 than approving for all. Therefor, the `ERC1155InsufficientApproval` can't be applied to a particular `tokenId`.
> EIP-6093 Adjustment to ERC155 error

- EIPS/eip-4788.md
reflecting recent discussion on ACDC, favor a stateful precompile for the 4788 implementation, rather than a new opcode
> Update EIP-4788: favor stateful precompile over opcode

- EIPS/eip-6913.md
* Clarify that nonce is not updated
* Clarify how parent execution of updated code continues
* Clarify interaction with `CODECOPY`, `CODESIZE`, `EXTCODECOPY`, `EXTCODESIZE`
> Update EIP-6913: Clarify Parent Execution Scopes, and add to Rationale

- EIPS/eip-6913.md
By not deferring the update, the updating scope can perform validations without relying on a parent scope.
I had designed it with deferral because previously I was worried about `EXTCODE`- and `CODE`- operations but these are already well-defined in such situations due to `DELEGATECALL` and `CREATE`.
* `SETCODE` takes effect immediately
* Specify the behavior of `CODECOPY`, `CODESIZE`, `EXTCODECOPY`, and `EXTCODESIZE` to match `CREATE` and `DELEGATECALL`.
* Clarify that `SETCODE` violates the read-only rules of `STATICCALL`
> Update EIP-6913: Remove Deferral and Clarify Staticcall

- EIPS/eip-4844.md
Add a separate execution-layer validation section with the block validity rule changes.
Detailed list of changes:
- use data gas for all accounting (instead of number of blobs)
- add block validation section
There is still an open question as to how to handle the relationship between data gas limit and CL max blobs per block limit, however this is considered out of scope for this PR.
> Update EIP-4844: Refactor Validity Conditions

- EIPS/eip-7045.md
- EIPS/eip-X.md
Increases attestation inclusion range to aid security proofs and confirmation rule of LMD-GHOST. Note, this is planned for inclusion in CL deneb fork
accompanying CL spec changes -- https://github.com/ethereum/consensus-specs/pull/3360
> Add EIP: Increase max attestation inclusion slot

- EIPS/eip-4788.md
Presents a simplification to 4788 that keys the precompile's storage by the root itself, mapping to the timestamp in the corresponding execution payload.
> Update EIP-4788: key beacon roots by root

- EIPS/eip-4844.md
At the moment, EIP-4844 uses the `excess_data_gas` from a block's parent header in order to determine the data gas price of transactions in the current block. This is a bit different than EIP-1559 which first ensures the header's `base_fee` is correctly derived from the parent header, then proceeds to use that value for further gas price calculation.
tldr; `excess_data_gas` is pricing for _next_ block, while `base_fee` is pricing for _current_ block -- this PR aligns them so that both represent pricing information for the current block
> Update EIP-4844: add `data_gas_used` to header

- EIPS/eip-4844.md
@karalabe raised a concern that the current transaction type spec in 4844 is not clear on whether a `nil` `to` field is allowed. This PR aims at clarifying any confusion around the correct representation of blob txs.
> Update EIP-4844: clarify to must be non-nil

- EIPS/eip-6953.md
Replaces https://github.com/ethereum/EIPs/pull/6991, based on the comments from @xinbenlv @SamWilsn and @g11tech in https://github.com/ethereum-cat-herders/EIPIP/issues/232.
> Update EIP-6953: Move to Review

- EIPS/eip-4844.md
It seems like an oversight on my part in #5353 to make `excess_blobs` a 256 bit unsigned integer and it has propagated through the various changes until now. @karalabe noticed that `excess_data_gas` will never even need more than a 64 bit unsigned integer. After 1500 blocks, the data fee ends up being around `2**256`, which is obviously much larger than could possibly be paid. `log2(1500*(MAX_DATA_GAS_PER_BLOCK - TARGET_DATA_GAS_PER_BLOCK)) = 28.5`, so 64 bit is fine.
> Update EIP-4844: reduce size of `excess_data_gas` to 64 bit

- EIPS/eip-6093.md
Updating `ERC721InexistentToken` to `ERC721NonexistentToken`
> Update EIP-6093: Rename `ERC721InexistentToken` to `ERC721NonexistentToken`

- EIPS/eip-6963.md
Just some editorial updates mainly so far, still making changes as I go. Wanted to get this published so others can provide feedback as I'm finishing up.
> Update EIP-6963: Editorial changes

- EIPS/eip-3540.md
Originally proposed in https://github.com/ethereum/EIPs/pull/6359 by @ritzdorf.
The changes here in the spec are:
- `DELEGATECALL` returns 0 instead of "exceptionally halting" the execution,
- not all gas is consumed by `DELEGATECALL` in case it fails of this reason.
Also @ritzdorf removed from the EIP authors list. I believed I requested this some time ago but I cannot find it now so maybe the comment were never properly sent.
> Update EIP-3540: EOF1 contracts can only DELEGATECALL EOF1 contracts

- EIPS/eip-5564.md
We decided to remove the staking mechanism (that was supposed to mitigate DoS attacks, or at least provide some additional measure agains them) for the sake of simplicity of the ERC.
We add another indexed keyword to the Announcement event to enable parsing providers to easily filter certain "caller" (msg.sender) for mitigating spam more effectively.
> Update EIP-5564: ERC-5564 - remove staking and add indexed caller

- EIPS/eip-4844.md
Adjusts the throughput section to the updated 3/6 blobs case. This section was missed in the main update in https://github.com/ethereum/EIPs/pull/7154.
> Update EIP-4844: Adjust Throughput Section

- EIPS/eip-6963.md
The [wagmi](https://github.com/wagmi-dev) core team proposes to add `walletId` back into the design of EIP-6963.
Decided not to use an `rdns` (Reverse DNS) for the said deterministic identifier to keep the objective clear, focused and simple, without having to deal with the complexities of potential side-effects of an rDNS in the future.
> Update EIP-6963: Add walletId back into the design

- EIPS/eip-4788.md
I moved the 4844 precompile to the next available address in #7172 
and this PR updates the precompile address for 4788 to be right after that
> Update EIP-4788: Update the precompile address for 4788

- EIPS/eip-6900.md
Made adaptations to respect this generally accepted terminology:
- `account` = address + chain, the onchain object that holds user funds.
- `wallet` = account + secret, the client software that manages private keys and signs transactions.
> Update EIP-6900: More precise usage of words `account` and `wallet`

- EIPS/eip-1.md
Originally from #6691 by @kdenhartog.
Splitting out so it can be discussed separately.
Changed slightly with my review feedback.
> Update EIP-1: Add W3C as a permissible origin

- EIPS/eip-1.md
Originally from https://github.com/ethereum/EIPs/pull/6691 by @kdenhartog.
Splitting out so it can be discussed separately.
Changed slightly with my review feedback.
> Update EIP-1: Add WHATWG as a permissible origin

- EIPS/eip-6093.md
Updated the use of `MUST` for each error and clarify its usage guidelines.
Also, updated the titles for `ERC721InvalidOwner(address owner)` and `ERC721NonexistentToken(uint256 tokenId)` so they don't show up in the table of contents
> Update EIP-6093: Improve specification clarity

- EIPS/eip-1.md
Originally from https://github.com/ethereum/EIPs/pull/6691 by @kdenhartog.
Splitting out so it can be discussed separately.
Changed slightly with my review feedback.
> Update EIP-1: Add IETF as a permissible origin

- EIPS/eip-3076.md
To assist with merging https://github.com/ethereum/EIPs/pull/7184, this PR reformats EIP-3076 to satisfy the linter.
> Update EIP-3076: Conform EIP-3076 to linting policy

- EIPS/eip-3076.md
Fix ordered list rendering issue
Adding blank line after `4. Refuse to sign...` to comply with the markdown linter seems to reset the HTML ordered list...
This PR removes the blank line. (The markdown linter will complain, but at least the HTML rendering will be OK.)
> Update EIP-3076: Update eip-3076.md

- EIPS/eip-2537.md
puts 2537 precompiles after the latest mainnet precompiles in #4788
> Update EIP-2537: update precompile addresses to avoid collision with latest precompile set

- EIPS/eip-7044.md
> Add EIP: Perpetually Valid Signed Voluntary Exits

- EIPS/eip-5564.md
By changing the name of the contract, we aim to make it more aligned with the function name and avoid confusion with "text messaging" services that could potentially be built on top of the proposed standard.
> Update EIP-5564: update contract name

- EIPS/eip-6381.md
The newly recalculated address that was required to be added after the changes to the proposal were added.
Some additional typos were fixed.
> Update EIP-6381: Add recalculated address and fix typos

- EIPS/eip-6909.md
The author being "jtriley" renders to https://github.com/jtriley on the EIPs website, when in reality the author is "jtriley-eth" --> https://github.com/jtriley-eth
> Update EIP-6909: Author's github not being correctly rendered

- EIPS/eip-6492.md
Extends EIP-6492 to also handle the case of a wallet being deployed but not ready to sign using EIP-1271.
See: https://ethereum-magicians.org/t/eip-6492-signature-validation-for-pre-deploy-contracts/12903/44?u=agusx1211
> Update EIP-6492: Handle non-ready deployed wallet

- EIPS/eip-4361.md
This update contains a few **non-breaking** updates to the EIP-4361 specification to scope the responsibility of wallets further, and make changes to the `domain` field. Through implementation in major wallets, we have received feedback that it would be beneficial to support schemes other than `https`, such as using `http` for localhost to facilitate local development, and is generally aligned with the tenets of decentralization and protocol-agnosticism. Therefore we are introducing a non-breaking change to the specification that allows for non-https schemes to be explicitly specified while retaining the default scheme as `https` as the top suggestion for implementers. 
- Various updates to the Overview section around how Sign-In with Ethereum messages are generated by relying parties, …
> Update EIP-4361: Various Updates to EIP-4361 - Sign-In with Ethereum

- EIPS/eip-725.md
- assets/eip-725/ERC725.sol
Function overloading is not supported in many blockchain programming languages (vyper, cairo), which can create interoperability issues. To ensure language independence and promote interoperability, it was decided to remove function overloading and simply rename the functions to include the word "batch" when taking an array.
> Update EIP-725: Remove overloading from ERC725

- EIPS/eip-4750.md
Update opcodes according to https://github.com/ethereum/execution-specs/blob/master/lists/evm/pending-opcodes.md.
> Update EIP-4750: Update opcodes for CALLF and RETF

- EIPS/eip-6206.md
Update opcode according to https://github.com/ethereum/execution-specs/blob/master/lists/evm/pending-opcodes.md.
> Update EIP-6206: Update opcode for JUMPF

- EIPS/eip-4844.md
I think "data gas" is problematic because we already have the concept of "data" in transaction -> calldata. To uninitiated, things like `excess_data_gas` seems to refer to calldata. Of course this isn't the case though. We should improve the naming to be clear what "data gas" is and that it actually refers to "blob data". 
Ultimately I decided to drop "data" almost entirely and refer to gas for blobs as "blob gas". The idea here is that it is gas for paying for blobs. One argument might be that this conflates the idea that a blob might cost a lot (2**17) "blob gas". I think this isn't the case. The "blob" adjective is just a discriminator to note that this gas is typed for blob payment. `GAS_PER_BLOB` further clarifies the unit of gas being a fraction of the total cost of a blob. This is …
> Update EIP-4844: Rename "data gas" to "blob gas"

- EIPS/eip-7329.md
The Specialized Editors link doesn't work as intended, and there is not a great description of that alternative.
> Update EIP-7329: Remove unnecesary link and elaborate

- EIPS/eip-5169.md
events should not contain `memory` keyword
> Update EIP-5169: Fix uncompilable memory in event

- EIPS/eip-7377.md
While reading this EIP, I noticed a few mistakes I would like to fix:
* Minor typo in sentence.
* Minor table formatting issue.
* Unnecessary comma in sentence.
* `storageTuples` should be `storage` to match table of fields.
* An "it's" v.s. "its" problem.
* A duplicate word in "migration transaction transaction."
* I think "MigrationTransaction" should be "migration transaction."
By the way, the transaction type format in the abstract uses `storage` instead of `storageTuples` too:
https://github.com/ethereum/EIPs/blob/bf74be7bd9e11082e3fb1a73cf31aa19b2287b57/EIPS/eip-7377.md?plain=1#L16
> Update EIP-7377: Fix some nits

- EIPS/eip-4844.md
Address https://github.com/ethereum/consensus-specs/issues/3462
1. Rename `BLOB_COMMITMENT_VERSION_KZG` to `VERSIONED_HASH_VERSION_KZG`
2. Use CL-specs defined `Blob: ByteVector[BYTES_PER_FIELD_ELEMENT * FIELD_ELEMENTS_PER_BLOB]` format.
- Add `BYTES_PER_FIELD_ELEMENT` to EIP
- Simplify the `blobs` field description in networking
3. **[New]** Fix `KZGCommitment` description: `0x00..00` is not the serialized format of G1 point at infinity. This PR copied [the CL spec defined `KZGCommitment` validation](https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/polynomial-commitments.md#custom-types) to EIP-4844.
> Update EIP-4844: Align names and fix `KZGCommitment` description

- EIPS/eip-4788.md
This just came up in a discussion on how to populate the new beacon block root header field for the case where Cancun starts at genesis and there is no beacon block root present for the genesis block.
> Update EIP-4788: Mention genesis block with no existing beacon block root case

- EIPS/eip-6963.md
Spec was updated to specify that `icon` must be data URI in [32fbcd8d7422958a9afe51f6ef02e96044af8594](https://github.com/ethereum/EIPs/commit/32fbcd8d7422958a9afe51f6ef02e96044af8594)
This updates the Wallet Provider implementation example to use a data uri for its `icon` value
> Update EIP-6963: use data URI for icon value in Wallet Provider implementation example

- EIPS/eip-6551.md
> Update EIP-6551: Move to Review

- EIPS/eip-5793.md
changes the type of the size to P which implies non-leading zeros as discussed with @tbenr
> Update EIP-5793: change size type to prevent leading zeros

- EIPS/eip-7303.md
- EIPS/eip-draft-token-controlled-token-circulation.md
> Add EIP: Token-Controlled Token Circulation

- EIPS/eip-7201.md
The spec definition is missing abi encoding so it cannot be compiled as is. Fixed by simply wrapping with  `abi.encode` before keccak256 hashing.
The reference implementation correctly includes the abi encoding, as seen in line 66- this edit simply updates the spec definition to reflect that code.
- If matching on email address, the email address is …
> Update EIP-7201: eip-7201.md

- EIPS/eip-7329.md
Revises EIP to only call for structural changes to the repository, explicitly pointing out process changes are out of scope.
Also add objection to process/structure bundling, and add scope for where split maps to potential process changes.
> Update EIP-7329: Move to Review

- EIPS/eip-6909.md
- fix incorrect types in `Transfer` event
- add a `bool` return value for `transfer`, `transferFrom`, `approve`, `setOperator` because it makes calls from contracts cheaper
> Update EIP-6909: update eip-6909

- EIPS/eip-6909.md
- Fixes `preceed` spelling with `precede`
- Removes trailing `and`
> Update EIP-6909: fix spelling mistakes

- EIPS/eip-6909.md
This updates the reference implementation to match the recent change to return boolean values from state-modifying methods.
Additionally, it conforms to the "should" statement relating to allowance deduction on infinite approvals.
> Update EIP-6909: Update reference implementation to specification

- EIPS/eip-820.md
The creative commons CC0 link, since it was contained in an HTML code block instead of a markdown one, was interpreted as an HTML tag instead of raw text.
> Update EIP-820: Fix accidental tag

- EIPS/eip-4844.md
Many constants that were introduced for older SSZ flavor of EIP-4844 are no longer used. Remove references to them.
> Update EIP-4844: Remove unused constants

- EIPS/eip-1822.md
ToC is automatically generated, so removed the manual ToC.
https://eips.ethereum.org/EIPS/eip-1822
> Update EIP-1822: remove unnecessary toc

- EIPS/eip-7213.md
- EIPS/eip-7432.md
This standard introduces role management for NFTs. Each role assignment is associated with a single NFT and expires
automatically at a given timestamp. Inspired by `ERC-5982` roles are defined as `bytes32` and feature a
custom `_data` field of arbitrary size to allow customization.
The NFT Roles interface aims to establish a standard for role management in NFTs. Tracking on-chain roles enables
decentralized applications (dApps) to implement access control for privileged actions, e.g., minting tokens with a role
(airdrop claim rights).
NFT roles can be deeply integrated with dApps to create a utility-sharing mechanism. A good example is in digital real
estate. A user can create a digital property NFT and grant a `keccak256("PROPERTY_MANAGER")` role to another user,
allowing them to …
> Add EIP: Non-Fungible Token Roles

- EIPS/eip-6120.md
Changes:
- Change the `pay` and `discard` interface to accept `bytes` payload for extensibility
- Add a Security Consideration for `discard`
> Update EIP-6120: Update to payload interface

- EIPS/eip-1.md
This obviously makes changes to the EIP numbering process.
> Update EIP-1: Add numbering guidelines

- EIPS/eip-7412.md
* Renames `fulfillOracleData` to `fulfillOracleQuery`. This feels more appropriate, as the _query_ is being fulfilled, moreso than the data.
* Renames `OracleFeeRequired` to `FeeRequired`. There is nothing oracle-specific about this revert.
> Update EIP-7412: Rename Parts of Interface

- .github/workflows/ci.yml
This version of `eipw` introduces support for f u l l y c o n f i g u r i n g from a TOML file.
For example:
```toml
[lints.banana]
kind = "preamble-regex"
name = "title"
mode = "includes"
pattern = "banana"
message = "`title` preamble field must include `banana`"
[[modifiers]]
kind = "set-default-annotation"
name = "eip"
value = "7444"
annotation_type = "info"
```
This would replace _all_ default lints with just `banana`, and replaces _all_ modifiers to just one that downgrades all messages for EIP-7444 to info.
To enable a configuration file, you need to specify a path in the workflow with `options-file`.
> CI: New `eipw` version

- EIPS/eip-3026.md
Update Proposed addresses table, followed by EIP-2537 and [EIP-2539](https://github.com/ethereum/EIPs/pull/7535).
> Update EIP-3026: Update addresses table

- EIPS/eip-6900.md
- Corrects the usage of "initializes" to "initialize"
> Update EIP-6900: Correct phrasing

- _includes/head.html
- assets/css/override.css
closes #7549 
- Updates to newer bootstrap.
- Uses a media query to change the theme.
<details><summary>Screenshots</summary>
</details>
> Website: Support a dark mode (closes ethereum#7549)

- EIPS/eip-6551.md
In the Tokenbound Working Group Telegram channel, Jayden Windle mentioned seed was renamed to salt.
"Are you using the most up to date version of the contracts here? Seed was renamed to salt, and allows you to have multiple accounts per NFT."
> Update EIP-6551: Update eip-6551.md to fix typo

- EIPS/eip-7511.md
- EIPS/eip-minimal-proxy-push0.md
Simple Summary
With the newly introduced `PUSH0` opcode ([eip-3855](https://eips.ethereum.org/EIPS/eip-3855)) at Shanghai Upgrade, we optimized the previous Minimal Proxy Contract ([eip-1167](https://eips.ethereum.org/EIPS/eip-1167)) from 55 bytes to 54 bytes, which saves 200 gas at deployment and 5 gas at runtime, while remain the same functionalities.
discussion: https://ethereum-magicians.org/t/proposal-for-a-new-eip-minimal-proxy-contract-with-push0/15662
implementation: https://github.com/AmazingAng/Minimal-Proxy-PUSH0
> Add EIP: Minimal Proxy Contract with PUSH0

- EIPS/eip-6900.md
- `bytes4 executionSelector` was missing as a member of the `ManifestStandardExecutionHook` struct. This is required for the plugin to differentiate between applying hooks over `execute` vs. `executeBatch` as hooks for these will have different parameters.
- Corrected a comment on `pluginManifest()`.
- Corrected a statement in the installation flow that stated that installation should continue if encountering conflicts.
> Update EIP-6900: add missing members to IPlugin structs, correct install step statement

- EIPS/eip-5585.md
Since there is no ongoing discussion on the EIP, we propose that it be moved to Last Call.
> Update EIP-5585: Move to Last Call

- EIPS/eip-5453.md
> Update EIP-5453: Move to Review

- EIPS/eip-721.md
Change the spelling of "collectable" to "collectible", to match the spelling in the rest of this and all other EIPs.
This is consistent with definitions that differentiate between items to be collected (like "collectable payments") and items of value worth collecting (like "collectible cards"). The latter is the intended meaning of NFTs.
> Update EIP-721: Spell collectible consistently

- EIPS/eip-7516.md
As @smartprogrammer93 pointed out in #7714, there is an opcode conflict with `BLOBHASH` with `0x49`. #7714 fixed this by changing `BLOBBASEFEE` to `0x4a`, but they missed a few references, this PR fixes them.
> Update EIP-7516: removes remaning references to 0x49

- EIPS/eip-6982.md
> Update EIP-6982: Minor Improvements EIP6982

- EIPS/eip-5920.md
pinging @Pandapip1, @xinbenlv for comment
> Update EIP-5920: expand the motivation a bit

- EIPS/eip-6963.md
This update adds a section to provide requirements and motivation for the `rdns` property.
I was originally planning to add example UI flows where a DApp would use this value, but I'm not sure this belongs in the spec. I'm thinking that saying that the DApps can rely on this property being stable might be enough.
> Update EIP-6963: Add RDNS section for motivation and requirements

- EIPS/eip-4788.md
- EIPS/eip-7508.md
*repost from https://github.com/lightclient/4788asm/pull/16*
We've had a few really nice audits done on this code and things have generally been positive. There are a few pieces of feedback that I think are worth addressing before we settle on the final code though. Here is a list, ordered by priority:
1. Verify timestamp is non-zero -- currently the implementation allows an input of zero to return a zero root. This is because the current mainnet timestamp is not perfectly divisible by our modulus. Although no proof could be authenticated against the zero root, it's still an ugly correctness edge case that I think should be addressed.
2. ~~Update `buflen` to `93600` -- this value will share 500-1000[^1] more remainders if the slot time were to change versus the current modulus, decreasing …
> Update EIP-4788: post audit tweaks

- EIPS/eip-4788.md
Forgot to update rationale after ring buffer size update in #7672.
> Update EIP-4788: update ring buffer size rationale for new ring buffer size

- EIPS/eip-6780.md
The current version of eip6780 specified that a contract created and selfdestructed in the same transaction, should write 0s after the verkle fork to mark that it was created and deleted.
This has no impact on EVM execution, but does create a special case in the codebase of clients. As a result, we have decided to remove this requirement during ACDE 171.
Another remark has been made that it makes little sense to specify a future-proof behavior in an EIP, and that the specific future behavior should be specified in the verkle EIP. As a result, this PR drops the paragraph regarding the behavior after the verkle fork.
> Update EIP-6780: remove mention of verkle tree behavior

- EIPS/eip-7480.md
`PUSH` costs 3, there is no reason for `DATALOADN` to cost less.
> Update EIP-7480: Change prices of DATALOAD and DATALOADN to be consistent with price of PUSH

- EIPS/eip-1559.md
This PR clarifies the language by replacing the term 'transaction' with 'senders' to explicitly identifies who pays the base and priority fee. Makes the fee payment process more understandable for new readers.
> Update EIP-1559: Clarify who pays gas fees

- EIPS/eip-6963.md
Noticed this inconsistency with `SHOULD` and `MUST` for the icon aspect ratio and resolution. I believe this should be `SHOULD`
> Update EIP-6963: make icon requirement wording consistent

- EIPS/eip-1046.md
1. `ERC1155TokenMetadataInterop` was missing a `tokenId` parameter.
2. Those metadata functions aren't always optional (specifically, in the case of ERC-721).
3. Decimals is `18` by default -- only for ERC-20.
> Update EIP-1046: Fix some issues

- EIPS/eip-7201.md
Superceding #7519 which was blocked by old requested changes. The requested change was the addition of a Security Considerations section which has already been added.
Regarding the Last Call deadline: I recognize this is sooner than would normally be required. The move to Last Call was requested over a month ago and approved 2 weeks ago, and unfortunately it wasn't merged earlier. I believe there has already been plenty of time and active discussion about the ERC, including various comments that have been addressed. The authors are likely not going to accept normative changes after Oct 1st, so this deadline is the best way to represent that.
> Update EIP-7201: Move to Last Call

- EIPS/eip-6093.md
Added an offchain security consideration when decoding errors for user action prompting.
> Update EIP-6093: Include error-decoded operations in the Security Considerations

- EIPS/eip-6120.md
Allow only contracts with ERC-165 interface ID `0x61206120` to be called in action code.
> Update EIP-6120: ERC-165 interface

- .github/PULL_REQUEST_TEMPLATE.md
Now that the repos are split we should make it very clear in case people continue to try and open PRs.
> Config: update pr template with ercs moved notice

- EIPS/eip-4844.md
Use latest function name for batched blob verification
> Update EIP-4844: fix typo on blob batch verification function name

- EIPS/eip-6780.md
I was reading EIP-6780, and I noticed that the title and the first paragraph mention "caller", whereas the rest of the EIP refers to the account being sent the self-destruct ETH as the "target".
I think that the latter is correct.
Cc @gballet.
> Update EIP-6780: say "target" instead of "caller"

- EIPS/eip-7549.md
- EIPS/eip-75XX.md
> Add EIP: Move committee index outside Attestation

- EIPS/eip-1153.md
`TLOAD` is expected to push the value it read from the transient storage to the stack, not pop it.
> Update EIP-1153: fix typo

- EIPS/eip-7549.md
fix EIP-7549 typo , `tupple` ->  `tuple`
> Update EIP-7549: fix typo

- EIPS/eip-3074.md
This moves 3074 back to review status from stagnant and it updates the `v` value of the signature input to `AUTH` to be only a single byte since it already can only be either `0` or `1`.
> Update EIP-3074: Move to Review

- EIPS/eip-3074.md
per [this comment](https://ethereum-magicians.org/t/eip-3074-auth-and-authcall-opcodes/4880/133?u=anna-carroll), EIP-4844 blob transactions use `0x03` as the EIP-2718 TransactionType prefix. it was suggested that EIP-3074 `MAGIC` byte should choose a different prefix to avoid any possibility of collision.
> Update EIP-3074: update 3074 MAGIC byte

- EIPS/eip-7549.md
fixed minor typos:
to -> the
sign -> signed
identify -> identifies
> Update EIP-7549: fix typo #8015

- EIPS/eip-7545.md
The previous text of the EIP was quite confusing (and sometimes downright incorrect) regarding how the parameters are to be passed to the precompile. This PR updates it to specify that all parameters are passed, concatenated, via the regular `input` interface. The precompile no longer reads memory.
> Update EIP-7545: clarify precompile interface

- EIPS/eip-3074.md
This is one of the longest request features of 3074. Thanks to @yoavw and @shemnon for more recent discussions on the topic and inspiration for this adaptation.
--
This PR modifies the `AUTH` message to now include `nonce`. The full message, over which the signature is constructed, is now as follows:
```
keccak256(MAGIC || chainId || nonce || invokerAddress || commit)
```
This places `nonce` within the protocol-definition of the `AUTH` message, so no matter the security of the invoker it is possible for the user to revoke any and all outstanding `AUTH` signatures they've created.
Using the message *does not* increment the EOA's nonce. This allows the user to reuse the same `AUTH` signature as much as they like (until their EOA originates a tx), which provides a similar experience to the …
> Update EIP-3074: add nonce to auth msg to provide revocation

- EIPS/eip-6690.md
1. fix typo: implict->implicit
2. fix linter error in CI
> Update EIP-6690: fix typo & linter error

- EIPS/eip-3540.md
Terminating instruction requirement was a feature of EIP-3670 from the early days of EOF, not relevant with current stack validation proposal
> Update EIP-3540: Remove mention of terminating instruction requirement

- EIPS/eip-6916.md
fix a typo: infrastracture -> infrastructure
> Update EIP-6916: fix typo

- EIPS/eip-7516.md
Opcode is just the number the instruction is assigned to.
> Update EIP-7516: Use "instruction" term

- EIPS/eip-4788.md
This PR makes the block header specification consistent with the changes introduced in EIP-4844. The change is necessary because the current terms are ambiguous.
> Update EIP-4788: Use "blob" term consistent with EIP-4844

- EIPS/eip-7480.md
Sync with [megaspec](https://github.com/ipsilon/eof/blob/main/spec/eof.md)
1. update opcodes to not conflict with `EXCHANGE`
2. DATALOADN is validated against the "static data" section only
3. include rationale for not having `EXTDATACOPY` (will be linked to from the "Data-only contracts" section in EIP-3540
4. DATACOPY gas rule was missing the static 3 gas
> Update EIP-7480: match to EOF Megaspec

- EIPS/eip-7569.md
On [ACDC#127](https://github.com/ethereum/pm/issues/951) we agreed to schedule Dencun's mainnet activation for epoch `269568`. I used https://slots.symphonious.net to confirm that the epoch's starting slot is `8626176`, which is an historical accumulator boundary (8626176 % 8192 = 0), and the corresponding timestamp is `1710338135`. At least one person should independently validate those numbers before we merge this 😄
> Update EIP-7569: Add Dencun mainnet epoch & time

- EIPS/eip-6122.md
> Update EIP-6122: Fix typo in EIP-6122

- EIPS/eip-4844.md
Type 2 transactions already use the "base fee" nomenclature.  This change makes 4844 transactions consistent with that naming scheme.
> Update EIP-4844: Rename gasPrice to baseFee

- EIPS/eip-7587.md
I realized this EIP should be a `Meta` type, not `Informational` as this EIP blocks an address range for precompiles. From [EIP-1](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md): "[Meta EIPs] often require community consensus; unlike Informational EIPs, they are more than recommendations, and users are typically not free to ignore them."
> Update EIP-7587: Moves 7587 from info to meta type

- EIPS/eip-7609.md
- EIPS/transient-pricing.md
> Add EIP: Decrease base cost of TLOAD/TSTORE

- EIPS/eip-7623.md
On the html page, there is a strange errer with whitespace symbols in the second python codeblock in the EIP. Not sure what causes it to be malformated.
> Update EIP-7623: remove formating error

- assets/css/override.css
The before-and-after screenshots:
> Website: Small fix for mobile navigation

- EIPS/eip-7623.md
Based on @MariusVanDerWijden 's input at ethmagicians [here](https://ethereum-magicians.org/t/eip-7623-increase-calldata-cost/18647/3?u=nerolation), this PR incorporates the costs for init code into the formula to clarify that it is NOT part of the conditional max() part.
> Update EIP-7623: EIP-7623 - Incorporate Init Code

- EIPS/eip-7623.md
This change makes sure that calldata heavy contract creations have lower threshold for getting the standard token price.
> Update EIP-7623: EIP-7623 - Move CREATE inside max

- config/eipw.toml
As per https://github.com/ethcatherders/EIPIP/issues/275 the Yellow Paper should be allowed.
_reported by @pdobacz (hopefully correct username) on discord_
> Config: Allow yellow paper

- EIPS/eip-3074.md
As discussed on [ACD 182](https://github.com/ethereum/pm/issues/961), I am updating the authorization message in this EIP to only be valid for an account's _current_ nonce.
> Update EIP-3074: allow only current nonce in auth msg

- EIPS/eip-6800.md
Replace a TODO in the "Access Events" section, with a link to the EIP where they are described.
> Update EIP-6800: refer to eip 4762 for the state access costs

- EIPS/eip-663.md
> Update EIP-663: Move to Draft

- EIPS/eip-6800.md
This PR clarifies some important details:
How 16-bytes chunks used in the trie-key hashing should be interpreted when mapping them to scalar-field elements.
How points are transformed into scalar-field elements. This is in the context of mapping points to vector elements in the tree nodes.
> Update EIP-6800: pedersen hash endianness and group to field fixes

- EIPS/eip-3670.md
Updates the language of the EIP-3670, to align with [EOF Megaspec](https://github.com/ipsilon/eof/blob/main/spec/eof.md) and other changes in EOF EIPs. Mainly makes independent from the exact spec of EOF contract creation.
The gist of the EIP should remain the same.
> Update EIP-3670: Align with EOF Megaspec and other EIPs

- EIPS/eip-7569.md
Fixed a typo regarding EIP numbers:
EIPs 1153, 4788, 4844, 5656, 6780 and 7516(instead of 7526) require changes to Ethereum’s execution layer.
--
> Update EIP-7569: Update eip-7569.md

- EIPS/eip-7645.md
- EIPS/eip-draft_alias_origin_to_sender.md
This has been part of the discussion around account abstraction.
> Add EIP: Alias ORIGIN to SENDER

- EIPS/eip-1.md
This PR proposes adding links to `ethereum/execution-spec-tests` to the allowed list. These are very useful for core EIPs as they can reference the canonical tests written for core eips by the testing team.
> Update EIP-1: add exec spec tests to allowed links

- EIPS/eip-7547.md
Change so that the `payload_attributes` SSE event output includes the inclusion list summary.
(I believe that this is what is meant, feel free to close this if not.)
> Update EIP-7547: Change modification to payload attribute SSE event

- EIPS/eip-3074.md
The authors have gone back and forth about allowing this behavior in the first iteration of the EIP. The limitation was originally added to de-risk 3074. Over time, we've come to find that the concern around sending value was overblown.
Yes, it breaks a protocol invariant which exists today (e.g. you can statically determine if a list of txs are valid). However, the cost of breaking this is minimal.
In the rationale we outline an attack which is possible today and how 3074 decreases the cost and difficulty.
> Currently an attacker can queue many transactions in the tx pool, across many accounts, and invalidate them all at once with a block where each of the queued accounts send a tx moving their entire balance. This attack will become easier and cheaper after this EIP, because it will no …
> Update EIP-3074: allow authorized to send value

- EIPS/eip-1.md
Looks like there was a typo in the example url.
> Update EIP-1: fix typo in exec spec tests link

- EIPS/eip-7002.md
First stab at converting 7002 to a system contract. A few notable changes:
* Instead of directly reading storage to compute the exits in the block, this has be combined in the system call to the contract. The exits are returned as normal return data. They should be packed in 68 byte chunks.
* The contract now allows for callers to read the current `excess_exits` count by calling the contract with no calldata.
* The contract does not return an over payment of the fee. Instead, callers should use the aforementioned getter to compute the exact fee before calling the contract.
The bytecode is created from the following repo: https://github.com/lightclient/7002asm
> Update EIP-7002: convert to system contract

- EIPS/eip-4844.md
* The `blob base fee `refereed in the EIP is actually  `base fee per blob gas`, and seems to have confused quite a number of readers.
* changes data fee references to blob fee (`calc_data_fee` => `calc_bob_fee`) going with the previous reasoning of renaming data => bob to not conflict with any future other "data" objects that can be added
This EIP updates the same since it doesn't has any material change since no header fields are affected (and hence doesn't affect consensus), just internal helper functions and constants which clients can update at their own pace
> Update EIP-4844: Update blob base fee to base fee per blob gas

- EIPS/eip-4844.md
- EIPS/eip-4938.md
- EIPS/eip-5793.md
Also moves dependencies to Final: 4844 -> 5793 -> 4938
> Update EIP-4844: Move to Final

- EIPS/eip-1153.md
- EIPS/eip-5656.md
- EIPS/eip-7516.md
- EIPS/eip-7568.md
Moves EIPs 1153, 7516 and 7568 to Final. 
Edit: will move 5656 to a separate PR due to the test changes required.
> Update EIP-1153: Move to Final

- EIPS/eip-7666.md
Corrects the number of the EIP merged in #8366 with the next available number, 7666.
> Add EIP: EVM-ify the identity precompile

- EIPS/eip-7652.md
- EIPS/eip-7667.md
Raise the gas costs of opcodes and precompiles that involve hash functions.
> Add EIP: Raise gas costs of hash functions

- EIPS/eip-7623.md
Adjust Token from 16 to 12 in consideration of:
* ** Access list costs**
* Impact on Merkle Proofs
* Imapct on certain cryptographic tools such as STARKs
> Update EIP-7623: Adjust Token from 16 to 12

- EIPS/eip-7002.md
Link to CL spec had an extra `>` on it (thanks James He for reporting it on Discord)
Also removed some extra spaces that are not needed.
> Update EIP-7002: Fix typo on link to CL specs

- EIPS/eip-2537.md
Discussion: https://ethereum-magicians.org/t/eip-2537-bls12-precompile-discussion-thread/4187/63
The spec is inconsistent and uses both additive notation (G!ADD and G1MUL) and multiplicative notation (G!MULTIEXP) for the elliptic curve group law.
Blockchain, cryptography and ZK research has settled in using the additive notation.
And previous BN254 EIPs (EIP196) already uses the additive notation.
> Update EIP-2537: Rename multiexponentiation to MSM

- EIPS/eip-5792.md
- add back `wallet_showCallsStatus`. this is a method that requests a wallet shows information about a call bundle. this was part of the original EIP-5792.
- added semicolons throughout ts
- add an address param to `wallet_getCapabilities`. capabilities can differ per address. also noted that apps should have an already-approved connection to this provided address.
> Update EIP-5792: Add showCallsStatus

- EIPS/eip-6913.md
This simplification has the same properties as the belongs-to spec but is clearer and combines separate rules into a general rule.
The general rule is now to allow when the currently executing code equals the code of the executing account.
This encapsulates the relevant cases of `DELEGATECALL` and `CREATE`, while keeping the same security properties as the more-complex belongs-to.
> Update EIP-6913: Move to Draft

- EIPS/eip-1193.md
updated username in 2022; airdrop farmer registered the old one a few weeks ago.
> Update EIP-1193: author username

- EIPS/eip-1015.md
fix a typo: `eficient`->`efficient `
> Update EIP-1015: Fix typo

- EIPS/eip-3074.md
Some housekeeping that we meant to add ages ago. This retains the properties set forth by EIP-3607.
> Update EIP-3074: fail if account has code

- EIPS/eip-2537.md
EIP-2537 currently lists two conflicting gas formulas for the pairing precompile, one in section [Pairing operation](https://eips.ethereum.org/EIPS/eip-2537#pairing-operation), and a different one in [Gas schedule clarifications for pairing](https://eips.ethereum.org/EIPS/eip-2537#gas-schedule-clarifications-for-pairing).
Geth currently implements "43000*k + 65000" and it's cause of failing tests. 
This PR fixes that by using only "23000*k + 115000", but let me know if this is not correct.
> Update EIP-2537: Fix conflicting gas formula

- EIPS/eip-2537.md
Rollbacks change in https://github.com/ethereum/EIPs/pull/8414 and actually fixes the conflicting formula.
After speaking with @MariusVanDerWijden, it seems like the duplicated formula to fix was `23000*k + 115000` -> `43000*k + 65000`, not the other way around as the previous PR implemented.
> Update EIP-2537: Rollback and fix formula

- EIPS/eip-5450.md
Stack validation algorithm is updated to be less restrictive.
> Update EIP-5450: Align with EOF megaspec

- EIPS/eip-7685.md
- EIPS/eip-requests.md
This EIP introduces the generic notion of an EL triggered requests. This is intended to encapsulate many of the request types which are being considered in Prague (and beyond). For example, instead of having individual types in the header, body, execution payload, etc. we can have a single generic `Request` that encompasses several different types.
> Add EIP: General purpose execution layer requests

- EIPS/eip-7685.md
Remove requirement for processing requests in the CL function `process_execution_payload(..)`.
> Update EIP-7685: simplify cl behavior

- _config.yml
Client API's are in their own repo and now that ERC's are separate as well, the description should reflect that.
Also added timezone and language to config.
> chore(config): Update _config.yml to reflect repo split

- EIPS/eip-7669.md
- EIPS/eip-7686.md
Add a hard memory limit equal to the gas limit of the current context. Make the maximum gas cost of a sub-call depend on the memory used in the current context. The two rules together ensure that a transaction with N gas can use at most N bytes of memory.
> Add EIP: Linear EVM memory limits

- EIPS/eip-7623.md
Add one sentence to clarify on implentation (deduction of floor before execution)
Remove focus from nonzero bytes
> Update EIP-7623: Add further clarification

- EIPS/eip-6110.md
Based on @lightclient’s work in https://github.com/ethereum/EIPs/pull/8440, makes adjustment to the python part of the spec
> Update EIP-6110: put deposits into request struct, take 2

- EIPS/eip-6110.md
Simplifies python code by removing `Deposit` structure
> Update EIP-6110: get rid of Deposit struct definition

- EIPS/eip-2935.md
This heretofore stagnant eip is now necessary for stateless clients to be able to execute the `BLOCKHASH` opcode. This PR:
* moves the eip from a stagnant status to a draft status
* change how the PR is activated since forks are now timestamp-based
* adds additional history persist step on fork activation so that new retrieval logic can be transitioned to from first block itself
> Update EIP-2935: Move to Draft

- EIPS/eip-5000.md
The abstract says
> Introduce a new instruction, `MULDIV(x, y, z)`, to perform `((x * y) / z) % 2**256` in 512-bit precision. `z = 0` is a special case for `(x * y) % 2**256`.
The specification says
> If `z == 0`, `r = (uint512(x) * y) / 2**256`.
and in plain text
> `muldiv(x, y, 0)` computes the higher order 256 bits.
Hence fix the abstract to match the spec
> Update EIP-5000: Fix abstract for 0 special case

- EIPS/eip-698.md
> Update EIP-698: fix comment

- EIPS/eip-698.md
- eip-template.md
> Update EIP-698: Remove repetitive words

- EIPS/eip-7600.md
Updates from [ACDE#186](https://github.com/ethereum/pm/issues/1016): 
- Include EIP-7685
- CFI EIP-7212
- CFI EIP-7623, which actually was previously CFI'd, so no changes in this PR.
> Update EIP-7600: Move to Review

- EIPS/eip-3074.md
The wording "invalid" can be confused with throwing "execution invalid", which is not what should happen. The signature should be considered invalid and the operation should terminate gracefully and unsuccessfully.
> Update EIP-3074: clarify handling of incorrect nonce

- EIPS/eip-2935.md
addresses the issue raised in:
- https://github.com/ethereum/EIPs/pull/8488/files
> Update EIP-2935: restrict contract input to 8 bytes to prevent overflow in checks

- EIPS/eip-2935.md
realized that the contract uses calldataload which pads right with zeros so previous 8 byte check was incorrect (https://github.com/ethereum/EIPs/pull/8514)
now changes to direct compare against the max 8 byte val as the simplest option
> Update EIP-2935: fix the input validation as 32 byte calldataload

- EIPS/eip-5283.md
Hi, just a few typos I found. Also I'm pretty sure "transaction execution parallelization" (line 24) should be remplaced with "parallelized transaction execution", but I'm not sure. Let me know if you wish me to correct that aswell. Have a nice day
> Update EIP-5283: few grammatical corrections

- EIPS/eip-7664.md
I have decided to withdraw the Access-Key opcode EIP.
The use-case is quite niche, and with EIP-7702 there is so much flexibility that the gap (static declaration of data in a tx) that was created by EIP-3074 is now being addressed. While 7702 is not as far as 3074 yet, solutions like that should be pursued.
> Update EIP-7664: Move to Withdrawn

- EIPS/eip-7069.md
Add a step in EXT*CALL to validate no high bytes are set when executing a call, halting when set.  This preserves essential room for Address Space Expansion.
> Update EIP-7069: EIP-7069 - Add Address Space Extension check

- EIPS/eip-6206.md
This aligns the EIP with https://github.com/ipsilon/eof/blob/main/spec/eof.md. Also `evmone` implementation has it like this, and `CALLF` also is like that, so I'm assuming the fix makes sense and the discrepancy was just by omission. 
Credit to @jochem-brouwer for reporting this.
> Update EIP-6206: fix discrepancy in stack height check JUMPF

- EIPS/eip-7620.md
Aligns with https://github.com/ipsilon/eof/pull/78 and https://github.com/ipsilon/eof/pull/76
Anticipates the [EIP-7698](https://eips.ethereum.org/EIPS/eip-7698) being there to cover introducing EOF code to the state.
> Update EIP-7620: Remove TXCREATE, InitcodeTransaction and the Creator Contract

- EIPS/eip-7495.md
- assets/eip-7495/stable_container.py
- assets/eip-7495/tests.py
- Rename `MerkleizeAs` to `Profile`
- Remove field reordering from `Profile`
- Add all-optional to `StableContainer`
- Clean up descriptions
- Formatting
> Update EIP-7495: simplify design, renaming, formatting

- EIPS/eip-2935.md
This PR makes the following changes to the EIP:
- Reverts changes to the BLOCKHASH opcode so it retains its prior behavior. I.e. gas cost of 20 stays and it will not read from the contract state anymore. The idea is we should change the implementation of BLOCKHASH at the transition to Verkle tries.
- Backfilling logic is removed. It will take roughly 1 day for the contract storage to fill up with 8192 block hashes.
- EIP-2929 rules clarified w.r.t history contract
> Update EIP-2935: update for Prague devnet1

- EIPS/eip-4200.md
The `RJUMP` is valid as a final instruction.
> Update EIP-4200: Fix validation test cases

- EIPS/eip-7600.md
Decided on [ACDE#188](https://github.com/ethereum/pm/issues/1043)
> Update EIP-7600: Add 7702, remove 3074

- EIPS/eip-7620.md
- EIPS/eip-7698.md
Aligning with https://github.com/ipsilon/eof/pull/86 + https://github.com/ipsilon/eof/pull/122
> Update EIP-7620: Initcode mode validation

- EIPS/eip-7069.md
Align with https://github.com/ipsilon/eof/pull/90
> Update EIP-7069: Padding oob behavior of RETURNDATA*

- EIPS/eip-1.md
- config/eipw.toml
This PR adds support for Chain Agnostic Improvement Proposals (CAIPs) as valid external links. Chain Agnostic Improvement Proposals (CAIPs) describe standards for blockchain projects that are not specific to a single chain.
Namely, one of the most important CAIPs is [CAIP-2](https://chainagnostic.org/CAIPs/caip-2) and [CAIP-10](https://chainagnostic.org/CAIPs/caip-10) which allow for deeply specified address from various different blockchians. 
The current limitation of not having CAIPs specified is we get half baked proposals such as [ERC-3770](https://eips.ethereum.org/EIPS/eip-3770) which take us half-way to the full solution, but stop short. For reference, 3770 was heavily inspired by CAIP-10, and has notably prevented users from pasting incorrect address across networks. …
> Update EIP-1: Feat/add caip

- EIPS/eip-7643.md
The hash_tree_root result of `0xec8e040fd6c557b41ca8ddd38f7e9d58a9281918dc92bdb72342a38fb085e701`  is with an SSZ List limit of `2048`.
> Update EIP-7643: Fix MAX_HISTORICAL_EPOCHS for provided root

- EIPS/eip-2537.md
While reviewing this EIP I noticed some minor nits. This PR will:
* Fix a few minor typos.
* Reformat the constants table.
* Delete excess blank lines.
* Replace "the Pippenger algorithm" with "Pippenger's algorithm" which is how it's commonly referred.
* Remove unnecessary indentation & blank lines from pseudocode.
> Update EIP-2537: Fix some nits

- EIPS/eip-7591.md
Introduces a new transaction type instead of reusing `BLOB_TX_TYPE`.
> Update EIP-7591: fix eip 7591 typo

- EIPS/eip-7600.md
Adds PeerDAS to the list of Pectra EIPs in the Meta EIP. I want to discuss this on https://github.com/ethereum/pm/issues/1069 before merging, as this EIP is a bit unique for two reasons. First, it's not a Core EIP, but "only" a networking change. Second, it's not if the special activation pattern for PeerDAS should be mentioned in this EIP. 
Nevertheless, given the overall consensus is "PeerDAS is in Pectra", the Meta EIP should reflect it.
> Update EIP-7600: Add PeerDAS

- EIPS/eip-7702.md
> Update EIP-7702: Move to Review

- EIPS/eip-7716.md
> Update EIP-7716: fix typos

- EIPS/eip-7698.md
> Update EIP-7698: Clarify relation to 3541

- EIPS/eip-2982.md
> Update EIP-2982: fix table displaying error

- EIPS/eip-3540.md
https://github.com/ipsilon/eof/pull/125
and https://github.com/ipsilon/eof/pull/128
> Update EIP-3540: align with recent clarifications and updates

- EIPS/eip-7702.md
Currently items in the authorization list are ordered:
- Chain ID
- Address
- (Optional) nonce
but in order to recover the authority, we need to reorder the fields to
- Chain ID
- (Optional) Nonce
- Address
which in some cases necessitates a secondary type to encode the authorization for recovery. Using the same order for the fields simplifies implementation slightly.
> Update EIP-7702: Reorder authorization fields for authority recovery

- EIPS/eip-7702.md
clarify behavior of invalid nonce format
> Update EIP-7702: note tx is invalid if nonce is not formatted correctly

- EIPS/eip-7620.md
This was missed in #8586, where the EOF validation checking initcode-mode was actually introduced, contrary to what this paragraph says
> Update EIP-7620: remove obsolete Rationale paragraph

- EIPS/eip-4762.md
- EIPS/eip-6800.md
For reference: https://notes.ethereum.org/EHXrhQ8-QdeqnqLH3-KBuw?view
> Update EIP-4762: reworked gas schedule from interop

- EIPS/eip-4750.md
Otherwise the value 0x80 of `outputs` may come off as invalid in EOFv1
> Update EIP-4750: ensure visibility of non-returning functions

- EIPS/eip-7620.md
- EIPS/eip-7698.md
Align with https://github.com/ipsilon/eof/pull/136. Justification of the removal of definitions (from the Megaspec PR):
>  proposed removing the "initcode container" and "runtime container" definitions, as I think they are unwieldy and suggest a particular implementation (the so-called inside-out determination of container kind). Also, these definitions cross paths with those used in the context of initcontainer_index and deploy_container_index of opcodes
The Megaspec PR isn't yet merged, so if anyone feels strongly about keeping the definitions in, please let know
> Update EIP-7620: Remove initcode/runtime container definitions

- EIPS/eip-3540.md
The text itself has this text: 
> the number of container sections must not exceed `256`. The number of container sections may not be `0`, if declared in the header
To encode 255 container sections, `0x0100` should thus be used, since `0` is disallowed. See also https://github.com/ipsilon/eof/pull/141
> Update EIP-3540: Ensure num_container_sections is correct

- EIPS/eip-7702.md
_This is an idea originally proposed by @vbuterin._
One aspect of 7702 that hasn't sat right with many involved is the fact that some types of 7702 authorizations do not expire. For delegations that are ephemeral, it's important to have a type of authorization that is replayable (which often means irrevocable), because it allows users to distance their activity from the master key of the account, e.g. delegate control to a smart wallet which can have subkeys with different privileges.
Because previous attempts at account delegation have relied on just-in-time provision of authorizations, the only way to make the authorizations replayable has been to make them irrevocable (or revocation impractical, see `maxNonce` mechanism). If we took a step back and thought about what we *really* want …
> Update EIP-7702: add delegation designation

- EIPS/eip-2935.md
The EIP currently points to EIP-158, which was never deployed, and should point to EIP-161.
> Update EIP-2935: Point to correct EIP-161

- EIPS/eip-7742.md
> Add EIP: Uncouple blob count between CL and EL

- EIPS/eip-2935.md
Declare that the behavior of 2935 is the same as 4788, and warns that said behavior will change with verkle.
> Update EIP-2935: use 4788 method + future-proofiness warning

- EIPS/eip-7610.md
The EIP currently points to EIP-158, which was never deployed, and should point to EIP-161.
> Update EIP-7610: Point to correct EIP-161

- EIPS/eip-3540.md
Removes duplicate formulation of the container format size constraints, mirroring the recent https://github.com/ipsilon/eof/pull/143
> Update EIP-3540: remove duplicate size constraints

- EIPS/eip-7620.md
Mirrors https://github.com/ipsilon/eof/pull/145
> Update EIP-7620: Clarify `CREATE2` rules upheld in `EOFCREATE`

- EIPS/eip-7610.md
Currently blocking https://github.com/ethereum/EIPs/pull/8749, and also agreed upon already, so it should probably be moved all the way to final.
> Update EIP-7610: Move to Review

- EIPS/eip-6800.md
This PR proposes:
- Updates the name of the code hash field to be aligned with the latest EIP-4762.
- Clarify that packing in `BASIC_DATA` is done using big-endian. This is required for one of the reserved bytes to extend `code_size` to 4 bytes in the future.
> Update EIP-6800: Clarify BASIC_DATA layout and update naming

- EIPS/eip-7702.md
This PR makes a few changes:
* disallows contract creation via 7702 tx, like the restriction on 4844 txs
* bans zero length authorization lists in 7702 tx
* charges the regular 25k gas in case an account doesn't exist before placing the delegation designator
* charges an additional `COLD_ACCOUNT_READ` gas during delegate resolution if the account hasn't been warmed yet
h/t @gumb0 for most of these
> Update EIP-7702: various updates

- EIPS/eip-7748.md
- EIPS/eip-x.md
This PR creates a new EIP for the state conversion to Verkle Tree.
> Add EIP: State conversion to Verkle Tree

- EIPS/eip-7702.md
Small change, it inserts step 8. `Add authority to accessed_addresses (as defined in [EIP-2929](./eip-2929.md).)` . to become step 3. (Before nonce and bytecode checks)
This is a better order as we load the account first and add authority to the access list before checking if the nonce is equal or if acc is empty/delegated.
> Update EIP-7702: Switch order of authority warm access

- EIPS/eip-6914.md
- EIPS/eip-7702.md
Fields inside the Authorization List are accessed (validated) differently than items inside the Transaction. A very big nonce will invalidate the transaction while if the nonce is big in AuthorizationList (By current spec) tx will still be valid. This makes decoding a special case.
Introducing expected limits on items invalidates this edge case.
> Update EIP-7702: Add decoding limits for AuthList items

- EIPS/eip-7702.md
Making some clarifications based on some discussions on discord. h/t @jochem-brouwer @rakita
> Update EIP-7702: add a few clarifications

- EIPS/eip-3155.md
Move EIP-3155 to last call and some minor edits.
Normative: move memSize position
Normative: Remove implementation links (per current linking policy)
Non-normative: update sample test case
Non-normative: formatting and minor verbiage edits
> Update EIP-3155: Move to Draft

- EIPS/eip-7637.md
> Update EIP-7637: Move to Review

- EIPS/eip-7745.md
- EIPS/eip-template.md
An efficient and light client friendly replacement for bloom filters. This EIP proposes a new data structure that adds a moderate amount of consensus data that is optional to store long term, has limited processing and memory requirements and allows searching for log events with 2-3 orders of magnitude less bandwidth than what bloom filters allowed back when they were not rendered useless by over-utilization. It also inherently adapts to changing block utilization and maintains a constantly low average false positive ratio.
https://ethereum-magicians.org/t/eip-7745-two-dimensional-log-filter-data-structure/20580
> Add EIP: Two dimensional log filter data structure

- EIPS/eip-7748.md
This PR fixes:
- A phase naming which was referring to a phase that doesn't exist (in the final proposed version of the EIP).
- A rename of the `BasicDataPhase`, since as mentioned by @gabrocheleau it might create some confusion since the semantics of `BasicData` are different in VKT.
> Update EIP-7748: fix namings

- EIPS/eip-7749.md
- EIPS/eip-x.md
- Add wallet_signIntendedValidatorData JSON-RPC method
to discuss and to know more with non standardized sections here: [PatronumLabs/wallet_signIntendedValidatorData](https://github.com/Patronum-Labs/wallet_signIntendedValidatorData)
> Add EIP: Add wallet_signIntendedValidatorData method

- EIPS/eip-152.md
The solidity example with the reference test of https://datatracker.ietf.org/doc/html/rfc7693#appendix-A is at least confusing because it declares values of type `bytes8` using a literal of length of 4 bytes.
> Update EIP-152: Fix reference test

- EIPS/eip-2935.md
- EIPS/eip-3155.md
Based on the discussion here: https://github.com/ethereum/go-ethereum/pull/29465#issuecomment-2296819860. I took the liberty to expand on block processing and the set/get functions.
> Update EIP-2935: update mechanism via system call

- EIPS/eip-7756.md
- EIPS/eip-eof-tracing.md
Expand EIP-3155 to include features for EOF.
> Add EIP: EOF/EVM Trace Specification

- EIPS/eip-7742.md
> Update EIP-7742: Uncouple blob count between CL and EL

- EIPS/eip-7675.md
> Update EIP-7675: Move to Review

- EIPS/eip-663.md
For [EIP-663 Specification](https://eips.ethereum.org/EIPS/eip-663#specification), there is a mistake in the description that includes only 2 instructions.
This PR makes corrections to the descriptions, indicating that there are actually three instructions.
> Update EIP-663: Modify specification section for EIP-663

- EIPS/eip-7702.md
The past few weeks we've been discussing validity conditions for 7702 transactions. Originally @rakita added the decoding limits for auth list items in #8746. Now we're looking at further constraining validity in #8833 to disallow chain ids other than zero or the current chain's id.
My philosophy here is 1) tx validity should be as simple as possible to ascertain and 2) we should retain as much similarity across tx types as possible.
The motivation for 1) is that tx originators are incentivized to not send junk authorizations with their txs, therefore they won't. What's the point of adding more constraints into the protocol when they aren't necessary?
For 2), I believe it's extremely important to follow existing conventions when possible. If every single tx type is designed as an ornate …
> Update EIP-7702: adjust tx validity

- EIPS/eip-6800.md
Since EIP-6780 was included in the Cancun fork, and that fork is deployed on mainnet, removal of SELFDESTRUCT is no longer a backwards-compatibility breaking change.
> Update EIP-6800: remove text around SELFDESTRUCT deprecation

- EIPS/eip-6493.md
- assets/eip-6493/ssz_types.py
In `EcdsaTransactionSignature`, both `from` and `ecdsa_signature` fields are required.
> Update EIP-6493: Fix `Optional` specification for signature profile

- EIPS/eip-7620.md
This PR fixes a typo/formatting issue and adds some EIP linking that was probably not known at the time the EIP was created.
> Update EIP-7620: Fix typo, formatting, and add EIP references

- EIPS/eip-7742.md
> Update EIP-7742: Move to Review

- EIPS/eip-7620.md
Align with https://github.com/ipsilon/eof/pull/160. This rule is already tested in EEST tests (either recent or upcoming release).
> Update EIP-7620: Clarify EOFCREATE in static mode

- _includes/head.html
The `polyfill.io` domain was taken over by a malicious actor, and now injects code that redirects to unrelated websites.
References:
<https://sansec.io/research/polyfill-supply-chain-attack>
<https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet/>
Closes #8853
> Website: Remove polyfill.

- EIPS/eip-7702.md
Prior versions of the EIP called for deleting the set code at the end of the transaction. This PR removes some dangling references to that deletion. 
@lightclient - following up from your comment on #8869.
> Update EIP-7702: Remove reference to post-tx code deletion

- EIPS/eip-7761.md
- EIPS/eip-is-contract.md
Allow EOF contracts to discriminate between EOA (Externally Owned Accounts) and smart contract accounts by introducing an `IS_CONTRACT` instruction.
This EIP responds to a community request to keep a way to distinguish between EOA and smart contract accounts in EOF, c.f. [ACDE \#195](https://github.com/ethereum/pm/issues/1142)
> Add EIP: HASCODE instruction

- EIPS/eip-4762.md
In the current state of the spec, there are a few instances where the basic leaf can be created but not the code hash leaf.
This unconditionally write-touch all leaves upon contract initialization, as this will result in an account no matter what happens. The only difference is that the value of the code hash will either be the hash of the contract code, or the empty hash, but that does not impact the gas costs.
> Update EIP-4762: unconditionnal account write during contract init

- EIPS/eip-7761.md
> Update EIP-7761: reference 3540 explicitly

- EIPS/eip-7702.md
Repost from #8840 as it should not have automatically merged.
> The past few weeks we've been discussing validity conditions for 7702 transactions. Originally @rakita added the decoding limits for auth list items in #8746. Now we're looking at further constraining validity in #8833 to disallow chain ids other than zero or the current chain's id.
> My philosophy here is 1) tx validity should be as simple as possible to ascertain and 2) we should retain as much similarity across tx types as possible.
> The motivation for 1) is that tx originators are incentivized to not send junk authorizations with their txs, therefore they won't. What's the point of adding more constraints into the protocol when they aren't necessary?
> For 2), I believe it's extremely important to follow existing …
> Update EIP-7702: 7702 validity

- EIPS/eip-7623.md
This orders the clauses in the calculation s.th. it matches the other calculation better
> Update EIP-7623: homogenize calculation examples

- EIPS/eip-7688.md
`deposit_requests`, `withdrawal_requests` and `consolidation_requests` were moved from `ExecutionPayload` to `ExecutionRequests`.
> Update EIP-7688: Adjustments for `v1.5.0-alpha.6` specs

- EIPS/eip-712.md
The current byte counts are plainly wrong and easy to fix. The first commit fixes it. The second gets the linter to be quiet - excepting a couple spurious errors.
The example signature only has 65 bytes, but is said to 129 bytes:
```
$ echo -n "0x4355c47d63924e8a72e509b65029052eb6c299d53a04e167c5775fd466751c9d07299936d304c153f6443dfa05f40ff007d72911b6f72307f996231605b915621c" | wc -c
132
```
Removing 2 characters for the `0x` prefix leaves 130 characters of hex, which encodes only 65 bytes.
(Oddly, the "last byte" on top of 128 bytes is counted as 1 character instead of 2)
Appendix F of the yellow paper and the function signature in EIP-191 (`signatureBasedExecution(address target, uint256 nonce, bytes memory payload, uint8 v, bytes32 r, bytes32 s) public payable`) reaffirm that these …
> Update EIP-712: Fix incorrect byte counts

- EIPS/eip-7685.md
There is no need to create a tree hash over the requests, since proofs related to requests will be made over the CL block. The EL block body stores unvalidated requests and will never be used for proofs. Removing the tree hash simplifies things.
> Update EIP-7685: change requests hash to flat hash

- EIPS/eip-7251.md
I am proposing to change the encoding of consolidation requests to be exactly equal to how they are returned by the contract. The extra layer of RLP encoding is not necessary, and by removing it, we can avoid defining the structure of these requests in the execution layer client implementation.
> Update EIP-7251: change request to flat encoding

- EIPS/eip-7702.md
I was reviewing the updated semantics of EIP-7702 after #8677, which now sets the account code permanently in the trie. One of the forward compatibility notes refers to the earlier version of this EIP and seems confusing / no longer relevant.
> Update EIP-7702: remove outdated note on forward compatibility

- EIPS/eip-7600.md
- EIPS/eip-7607.md
- EIPS/eip-7773.md
- EIPS/eip-amsterdam.md
This PR formalizes the changes to Pectra agreed to in [ACDE#197](https://github.com/ethereum/pm/issues/1153), namely: 
* Reducing the set of SFI'd Pectra EIPs to those which were already part of [devnet-3](https://notes.ethereum.org/@ethpandaops/pectra-devnet-3)
* CFI'ing EIPs 7742 and 7762 (note that we also agreed to "CFI" a blob count (or target) increase, but don't have an EIP for this yet)
* Moving EOF and PeerDAS from being SFI'd in Pectra to being SFI'd in Fusaka, as well as other Pectra CFI'd EIPs (7212) to CFI'd in Fusaka. 
* Moving Verkle EIPs from being CFI'd in Fusaka to CFI'd for Amsterdam (CL "G" star name TBD)
The PR also adds a pointer to [EIP-7723](https://eips.ethereum.org/EIPS/eip-7723), which defines `Proposed`, `Considered` and `Scheduled for Inclusion`. It supersedes …
> Add EIP: Hardfork Meta - Amsterdam

- EIPS/eip-6110.md
I am proposing to change the encoding of deposit requests to be a flat concatenation of the fields returned by the contract. The extra layer of RLP encoding is not necessary, and by removing it, we can avoid defining the structure of these requests in the execution layer client implementation.
> Update EIP-6110: change request to flat encoding

- EIPS/eip-7002.md
- EIPS/eip-7251.md
This updates 7002 and 7251 to account for the sys-asm PR https://github.com/lightclient/sys-asm/pull/26. This method is not fragile to gas cost / gas limit changes.
> Update EIP-7002: add updated excess inhibitor logic

- EIPS/eip-7685.md
Hopefully this encapsulates the discussion on discord and in #8916.
Essentially, we now refer to `request_data` as the opaque data output by the system contract instead of a request's individual fields and we modify the `request_hash` calculation to be the following:
```
sha256(sha256(0x00 || request_data_00) || sha256(0x01 || request_data_01) || ...)
```
> Update EIP-7685: group requests into request-data

- EIPS/eip-7702.md
rebased copy of #8905, didn't have write access to the branch
repost:
It is important to not allow `authorization.nonce == 2**64 - 1`, because in this case incrementing authority nonce will result in nonce overflowing 64 bit, which is not allowed since [EIP-2681](https://eips.ethereum.org/EIPS/eip-2681)
~~Alternative to adding this to the transaction validity rules could be additional check during delegation setting, but it is simpler this way (fewer checks) and more aligned with existing transaction types validity.~~ It is checked at authorization list processing now.
> Update EIP-7702: 8905 copy

- EIPS/eip-7702.md
replaces #8906 so i can fix some merge conflicts
> Update EIP-7702: 8906 copy

- EIPS/eip-7702.md
placeholder for further devnet changes.
outstanding clarifications to make (from my notes):
* authorization should be invalid is nonce == 2^64 - 1 
* This case (add tx-level delegated account to warm)
* Precompiles will not be run once delegated to (treated as empty accounts)
* EXTCODEHASH puts 0 on stack if the 7702-delegated account it is delegates to does not exist in trie (as opposed to empty hash keccak256("") of accounts which exists in trie, but have no code, i.e. EOAs (non-delegated to))
* delegations are not reverted in case transaction fails
* if delegation target account does not exist, nonce is checked to be 0
* is the price correct at 2500? is there incentive to use as alternative contract deployment?
* limit chain id to uint64 and y_parity to uint8
> Update EIP-7702: restrict field sizes

- EIPS/eip-2537.md
Fully replace "multiexponentiation" with "multi-scalar-multiplication".
> Update EIP-2537: Replace "multiexponentiation"

- EIPS/eip-7702.md
h/t @jochem-brouwer for suggestions in #8929
> Update EIP-7702: fixup gas costs and empty code hash

- EIPS/eip-7781.md
- EIPS/eip-7782.md
Reduce Ethereum's slot time from 12 seconds to 8 seconds
1. reduce based rollup latency
2. increase transaction throughput by approximately 33% without increasing individual block or blob counts
3. distributing bandwidth usage over time to lower peak bandwidth requirements and maintain network efficiency.
This would be equivalent to increasing blob count from 6 to 8 or gas limit from 30M to 40M; however this approach does not increase peak bandwidth.
> Add EIP: Reduce Slot Time for Lower Peak Bandwidth

- EIPS/eip-4762.md
This PR downgrades a generic reference to `*CALL` instructions to only `CALL`.
> Update EIP-4762: value-bearing clarification

- EIPS/eip-7702.md
adding back since it was removed by mistake.
> Update EIP-7702: add s value check

- EIPS/eip-6110.md
- EIPS/eip-7002.md
- EIPS/eip-7251.md
This cleans up 6110, 7002, and 7251 with respect to the modifications to 7685. Specifically, `request_data` now refers to the output of the system call to the contracts, not an individual request object's data.
> Update EIP-6110: harmonize request eips with 7685 changes

- EIPS/eip-4762.md
This PR clarifies in the spec how implementations should treat OOG situations on write/read events.
We found a disagreement on this aspect in `execution-spec-tests`, so it's worth clarifying.
cc @gballet @tanishqjasoria @g11tech
> Update EIP-4762: add clarification regarding OOG behavior

- EIPS/eip-7002.md
- EIPS/eip-7251.md
This PR should make it clearer that it is the system contract's responsibility to do the ssz serialization and not the caller (i.e. the execution layer client).
> Update EIP-7002: move ssz serialization into system call

- EIPS/eip-7702.md
Makes the description clear that the EIP updates the EOAs code permanently.
> Update EIP-7702: update description

- EIPS/eip-7775.md
- EIPS/eip-7xxx.md
> Add EIP: BURN opcode

- EIPS/eip-7069.md
As title + redacted some hard-coded constants (they're in the constants table)
> Update EIP-7069: emphasis - `value` rules are EXTCALL only

- EIPS/eip-7600.md
Adds EIP-7742 to the SFI list, as agreed on [ACDE#199](https://github.com/ethereum/pm/issues/1177), also removes CFI'd EIPs from `requires` line, let's see if the bot lets me 😄
> Update EIP-7600: Update eip-7600.md

- EIPS/eip-7742.md
Rename these vars for consistency with other spec constants, eg:
* `MAX_BLOBS_PER_BLOCK`
* `TARGET_BLOB_GAS_PER_BLOCK`
Note: this PR also renames "maximum" to "max".
--
- If matching on email address, the email address is the one publicly listed on …
> Update EIP-7742: Rename *_blob_count to *_blobs_per_block

- EIPS/eip-7745.md
Added log_entries to the hashing scheme in order to simplify the proof generation and verification process; now everything needed to validate log search results is hashed into a single tree. Also added necessary corrections and clarifications and removed some unnecessary parts.
> Update EIP-7745: improve hashing scheme, simplify proving process

- EIPS/eip-7702.md
Proposal to address latest point brought up in EthMagicians.
> Update EIP-7702: Remove delegation behavior of EXTCODE*

- EIPS/eip-7002.md
- EIPS/eip-7251.md
* add missing excess inhibitor logic to pseudocode
* update bytecode to latest
> Update EIP-7002: add excess inhibitor logic

- EIPS/eip-7685.md
Here I am proposing to change the `requests_hash` commitment so that empty items are excluded. The point of this is to ensure a stable empty requests hash which is independent of fork. Having such a hash makes testing a lot easier, and it mirrors how other execution-layer commitments behave.
There is also a corresponding engine API change: https://github.com/ethereum/execution-apis/pull/599
> Update EIP-7685: exclude empty requests data in commitment

- EIPS/eip-6206.md
`Update EIP-6206: clarify "JUMPF prepares the delta` raised in https://github.com/ethereum/solidity/pull/15550#issuecomment-2494801436
The other commit found when re-reading. The [megaspec](https://github.com/ipsilon/eof/blob/main/spec/eof.md?plain=1#L286) already has this "iff" formulation
> Update EIP-6206: clarify wording on JUMPF (EOF)

- EIPS/eip-7002.md
The get operation is meant to be used by contracts to compute the exact amount of ether required to add a withdrawal request. It does not return the fee directly though, but it returns the count of 'excess requests' instead. The caller has to compute the fee themselves by applying the fee formula.
I think this is not great. The fee logic, while reasonably straightforward, is an implementation detail of the contract. Duplicating it into caller contracts could lead to a mismatch in the computed values, and it's not necessary. I propose we change the system contract to return the fee directly. This contract change has also been submitted in this PR: https://github.com/lightclient/sys-asm/pull/33
The Rationale section of the EIP also had some outdated text about returning fee overage to the …
> Update EIP-7002: return fee from getter and add usage example

- EIPS/eip-7800.md
- EIPS/eip-7804.md
**Allow validators to update their withdrawal credentials via execution requests**
This proposal defines a mechanism to allow validators to update their withdrawal
credentials using a new execution request type (0x03). The request allows for
changing the execution address and the withdrawal credential prefix (0x01 or 0x02).
> Add EIP: Withdrawal Credential Update Request

- EIPS/eip-7639.md
Note that only bodies and receipts are dropped. Header chain remains intact.
> Update EIP-7639: format as new eth wire protocol

- EIPS/eip-7623.md
Add additional "backwards compatibilty" info regarding eth_estimateGas.
> Update EIP-7623: add additional backwards compatibility considerations

- EIPS/eip-7762.md
Reset the excess blob gas to 0, to avoid a blob basefee spike.
Todo (in followup PR): add rationale.
> Update EIP-7762: add excess gas reset

- EIPS/eip-7691.md
> Update EIP-7691: add update fraction specification

- EIPS/eip-7801.md
Update specification to use bitmask rather than an updating bitlist, so nodes will not need to update their ENR as the blockchain progresses across shard boundaries.  
Also change shard definition to 100k per 1M block span.  This makes data availability easy to reason about, and straightforward for a human to determine.
> Update EIP-7801: Eip 7801 bitmask

- EIPS/eip-7723.md
Introduces `Declined for Inclusion` after conversations at the L1 R&D workshop at Devcon. The purpose of this status is to signal that core devs with to explicitly exclude an EIP from a network upgrade and no longer discuss it as part of that upgrade's planning process. This already happens implicitly, where anything that isn't `CFI`'d or `SFI`'d is considered rejected from the upgrade. The `DFI` label makes this more explicit. 
This does **not** imply the EIP is "rejected forever": a DFI'd EIP can be proposed again for the next network upgrade.
> Update EIP-7723: Add "Declined for Inclusion"

- EIPS/eip-7639.md
> Update EIP-7639: Fix rendering of 7639 specification

- EIPS/eip-7639.md
Downgrade wire protocol version from 71 to 70.
> Update EIP-7639: protocol version should be 70

- EIPS/eip-5450.md
Fix some mis-spellings and note that `STOP` et.al. are relevant to the end of the call frame.
> Update EIP-5450: EIP-5450 - Speling corrections and on editorial change

- EIPS/eip-7251.md
Fixes the address.
Verified with: https://gist.github.com/protolambda/58f73421b91602a6a0f5104a9f0f5c89
The `CONSOLIDATION_REQUEST_PREDEPLOY_ADDRESS` now matches the address in the bytecode deployment section again.
> Update EIP-7251: fix CONSOLIDATION_REQUEST_PREDEPLOY_ADDRES

- EIPS/eip-7002.md
Fixes the address.
Verified with: https://gist.github.com/protolambda/abdf34f879398d1347578538a2aafb15
The `WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS` now matches the address in the bytecode deployment section again.
> Update EIP-7002: fix WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS

- EIPS/eip-7251.md
There is no `check_fee` defined in the EIP, the reference in the text was probably referring to older pseudo code.
This changes the reference to `msg.value >= get_fee()`, a short version of the pseudo code in the EIP, part of `add_consolidation_request`:
```
fee = get_fee()
require(msg.value >= fee, 'Insufficient value for fee')
```
> Update EIP-7251: replace check_fee with get_fee check

- EIPS/eip-7742.md
the EIP currently uses the target blob count of the current block, although closer inspection of this EIP surfaced the issue that really the excess blob gas computation should use the parent header
this is only really relevant at hard fork boundaries, but avoids weird edge cases with this calculation at hard fork boundaries
> Update EIP-7742: use parent target blob count for excess blob gas calculation

- EIPS/eip-7756.md
* change `gas`, `gasCost`, `gasUsed` to Number
* change `opcod` to Hex-Number
* Allow Numbers and Hex-Numbers to be used interchangeably.
* remove required column in favor of multiple sections
* editing cleanup
> Update EIP-7756: Eip7756/table layout

- EIPS/eip-7702.md
Also applies a minor suggestion posted in https://github.com/ethereum/EIPs/pull/8969 after it was merged.
> Update EIP-7702: Add security consideration about use of storage

- EIPS/eip-2537.md
Nethermind proposal of MUL and ADD operations. The speed of this precompile measured on Intel NUC 11 Intel Core i7-1165G7 and Nethermind client (EcRecover ~80 mgas/s). Full proposal: https://github.com/Marchhill/bls-precompile-benchmarks/blob/main/proposed-changes.md
```
g1add-1: 86.61 mgas/s (83.42-90.05)
g1mul-1: 86.90 mgas/s (83.24-90.89)
g2add-1: 82.34 mgas/s (78.50-86.58)
g2mul-1: 93.40 mgas/s (88.11-99.38)
mapfp-1: 89.96 mgas/s (85.91-94.40)
```
--
We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if …
> Update EIP-2537: Gas pricing MAP, MUL and ADD operations

- EIPS/eip-2537.md
**Update:** Changed numbers to Paweł's proposition, details here: https://gist.github.com/MarekM25/79982c313c1179cbfd68c9414f8925fa
--
> Update EIP-2537: Gas pricing pairing operations

- EIPS/eip-712.md
> Update EIP-712: Update eip-712.md

- EIPS/eip-7600.md
EIP-7691 was SFI'd on [ACDC#146](https://github.com/ethereum/pm/issues/1200) and EIP-7623 was SFI'd on [ACDE#201](https://github.com/ethereum/pm/issues/1197)
> Update EIP-7600: Add EIPs 7623 & 7691

- EIPS/eip-7723.md
This PR attempts to formally define the relationship between EIPs implementation progress in upgrade devnets and their CFI/SFI status for a network upgrade.
> Update EIP-7723: CFI/SFI & Devnets

- EIPS/eip-7002.md
> Update EIP-7002: Update eip-7002.md

- EIPS/eip-7702.md
There has been a comment that there are efforts which will expect chain id to be u256. I think we should make this change to 7702. https://ethereum-magicians.org/t/eip-7702-set-eoa-account-code/19923/326?u=matt
> Update EIP-7702: make chain id u256

- EIPS/eip-2537.md
This removes `BLS12_G1MUL` and `BLS12_G2MUL` precompiles because they are trivially replaceable by corresponding MSM precompiles.
This reduces the number of precompile's addresses defined in this EIP from 9 to 7. The addresses of remaining 7 precompiles are changed to be continues.
The Rationale entry describes why this change make sense. Additionally, the cost of MSM for single input (`k==1`) has been corrected to match the original MUL cost. The specification now suggests how this case should be implemented.
Moreover, because of the ABI compatibility between MUL and MSM all existing tests for MULs can be easily converted to tests for MSMs.
The PoC of MUL and MSM precompiles equivalence is provided in [evmone PR#1042](https://github.com/ethereum/evmone/pull/1042).
The adjustment of the …
> Update EIP-2537: Remove redundant MUL precompiles

- EIPS/eip-7607.md
We need to start having a pipeline to retire precompiles that are  outdated and underused, to reduce the protocol complexity and consensus risk over time.
The easiest precompile to start removing is the identity precompile. EIP-7666 removes the precompile, and replaces it with a piece of EVM code that has equivalent functionality (except naturally it costs more gas). If this approach works for this case, we can later start also applying it to other precompiles (eg. Blake, RIPEMD-160) that see very little usage.
> Update EIP-7607: Add EIP-7666 (EVM-ify the identity precompile) to proposed-for-inclusion in Fusaka

- EIPS/eip-7642.md
If `NewBlock` and `NewBlockHashes` are removed from the protocol, it makes it incompatible with other blockchains that haven't gone through The Merge, such as Polygon. For Ethereum, formally removing `NewBlock`(`Hashes`) is unnecessary since those are not sent anyway after The Merge (as [stipulated](https://eips.ethereum.org/EIPS/eip-3675#network) by EIP-3675).
> Update EIP-7642: don't remove NewBlock(Hashes)

- EIPS/eip-7691.md
Fix a typo: certainity -> certainty
> Update EIP-7691: fix typos

- EIPS/eip-7768.md
- EIPS/eip-8888.md
Discussing a new approach for third-party pay transactions
> Add EIP: No-Ether transactions with free-for-all tips

- EIPS/eip-4762.md
Fix a typo `targetting ` to `targeting`
Thank you very much!
> Update EIP-4762: fix typo

- EIPS/eip-5792.md
- Updated status codes as discussed in telegram chat:
- 1xx: Pending states
- 2xx: Confirmed states
- 4xx: Chain rules failures
- 5xx: Offchain failures
> Update EIP-5792: Add status codes

- EIPS/eip-7623.md
Previously, the `evm_gas_used` (now renamed to `execution_gas_used`) was not specified. This lead to two different interpretations whenever the `execution_gas_used` was the value after or before applying refunds.
We argue that the interpretation that `execution_gas_used` don't have refunds subtracted is incorrect because it would make the "current" formula for the `tx.gasUsed` incomplete and confusing as the total gas used by a transaction would actually be `tx.gasUsed - refunds`.
Using this reasoning, this change clarifies the specification by following the interpretation that the `execution_gas_used` is the value after the refunds are applied.
> Update EIP-7623: Clarify the gas refunds handling

- EIPS/eip-7851.md
This PR:
* makes the magician link consistent with the EIP title.
* fixes some fact errors, such as it mentions that the alternative smart contract approach "leaks" the design of a (widely used) programming language into the Ethereum core protocol. I later found it was wrong since the contract does not need to be written in any specific programming language.
* removes some unnecessary statements. e.g. Forwards compatibility for removing EOAs session. because (i) it's just a possible path to go. (ii) the statement is not very related to "forwards compatibility".
* statement and code refinements.
> Update EIP-7851: multiple fixes and refinements

- EIPS/eip-4762.md
I think the removal of CALLCODE cost for value transfer needs to be clarified and I didn't find any reference to it in the EIP. I remember that Besu bumped into this change and we actually applied the change to previous forks as well causing the CI pipeline to fail later on.
Even though it makes sense to not charge anything since CALLCODE transfers to itself, that's not the case with previous forks so this is a change in behaviour which IMO is worth documenting. 
cc @gballet @jsign
> Update EIP-4762: clarify change in behaviour for CALLCODE cost if value transfer

- EIPS/eip-4762.md
This is to correct a previous PR that was merged without applying these changes. I also found what I believe some missing references for CALLCODE since wildcarded `*CALL` does not cover this case.
> Update EIP-4762: Fix references to CALLCODE and wording around its value-transfer costs

- EIPS/eip-2537.md
This PR aligns recently updated gas cost for `BLS12_G1ADD`, `BLS12_G2ADD` and `BLS12_MAP_FP2_TO_G2` between different sections of the document.
> Update EIP-2537: Align gas cost in `Constants` section with `Gas schedule` section.

- EIPS/eip-7840.md
Already accepted in Pectra, this is currently blocking https://github.com/ethereum/EIPs/pull/9164
> Update EIP-7840: Move to Review

- EIPS/eip-7702.md
Hi, i think a closing parentheses has to go instead of a closing bracket to match the `ecrecover(` opening.
> Update EIP-7702: eip-7702.md

- EIPS/eip-7840.md
> Update EIP-7840: Add BaseFeeUpdateFraction

- EIPS/eip-7691.md
adds some text to clarify that the new values should be used within the fork activation block.
so that pre-fork, the old values are used, and at the first block of the new fork, the new values are used
> Update EIP-7691: clarify parameter handling at the fork boundary

- EIPS/eip-7702.md
Here are the proposed changes to `EXTCODE*` behavior over concerns brought up in this [post](https://hackmd.io/@otim/H1Q7yCHDyl) on HackMD. The proposed changes were discussed at ACD (1/16/25) and agreed upon by those present.
> Update EIP-7702: update `EXTCODE*` opcodes to act on full "delegation designator"

- EIPS/eip-7761.md
Change the EIP to return the type of the account (EOA, Legacy Code, EOFv1 code) instead of a boolean has/no code.
Expand upon these decisions in the rationale and motivation.
--
- If matching on email address, the email address is the one publicly …
> Update EIP-7761: Change HASCODE to EXTCODETYPE

- EIPS/eip-7607.md
See the motivation for more details:
1. Removes unused unbounded cases. Such cases are known to have caused numerous consensus bugs in the past.
2. Makes it easier for ZK systems to implement this precompile -- and many already have a similar limitation in place (like Polygon zkEVM).
3. Makes it easier to implement the precompile using EVMMAX.
> Update EIP-7607: Add EIP-7823 (Set upper bounds for MODEXP) to proposeed-for-inclusion in Fusaka

- EIPS/eip-7607.md
This EIP proposed keeping accessed addresses and storage keys "warm" throughout the duration of a block.
This aligns more closely with the caching practices used in clients and improves overall efficiency.
Additional info in this ethresearch post:
https://ethresear.ch/t/block-level-warming/21452/8
> Update EIP-7607: Propose EIP-7863 for Fusaka

- EIPS/eip-7549.md
> Update EIP-7549: Various spelling fixes of EIP 7549

- EIPS/eip-7862.md
- EIPS/eip-xxxx.md
This EIP implements a delayed state root. It is ready for draft status and discussion.
> Add EIP: Delayed Execution Layer State Root

- EIPS/eip-7251.md
This PR updates the final EIP-7251 system contract address to a "nicer" looking one:
`0x0000BBdDc7CE488642fb579F8B00f3a590007251`
The address follows the pattern `0x0000...00<eip-number>` as for other pectra system contracts to make them more recognizable. The sender address for the deployment has been updated accordingly. 
I've also tested the deployment of the contract on ephemery:
https://explorer.ephemery.dev/tx/0x379269d571beff3ed1d8eba3abb24076a7267b0eaf0cc66d728fb0544f5a690d
Some alternative addresses (in case someone has a strong preference for one of these):
```
0x00001d2782329781e501777e0789fcc904007251  (sig-s: 0x37a53e94f77471e75c1d45be0ee4f3bd59004d)
0x0000b7a00b397dd82c8dbb9aec324c5a10007251  (sig-s: 0x55ddb8b7a99563bd7ec192c6605c6ff7150028)
```
fun fact: these addresses …
> Update EIP-7251: Final system contract address

- .github/workflows/jekyll.yml
I've noticed the EIP website is outdated and doesn't get updated by the workflow anymore:
https://github.com/ethereum/EIPs/actions/workflows/jekyll.yml
Problem comes from the `actions/upload-pages-artifact@v2` action, which internally uses the deprecated `actions/upload-artifact@v3`.
I've updated the upload-pages-artifact action to v3. Following the [release notes](https://github.com/actions/upload-pages-artifact/releases/tag/v3.0.0) of upload-pages-artifact@v3, I've also updated the actions/deploy-pages to v4.
> fix: upgrade actions for github pages deployment

- .github/workflows/auto-review-trigger.yml
- .github/workflows/ci.yml
Don’t know for sure but this might help to resolve recent CI issues, [for example](https://github.com/ethereum/EIPs/actions/runs/13145370173/job/36682129698?pr=9319).
The commit of the `upload-artifact` which hash is currently used is from mid 2023. v1, v2, v3 versions have been deprecated last year, so the failure might be related to the deprecation.
> Switch to upload-artifact@v4

- EIPS/eip-7251.md
The EIP-7251 consolidation contract returns the consolidation fee when called without arguments.  This adjusts the text to match reality.
Note that the text is largely copied from EIP-7002, which has a similar contract structure.
> Update EIP-7251: fix outdated statement

- EIPS/eip-7623.md
Add a crossref to EIP-3860 to clarify the `INITCODE_WORD_COST` as suggested here:
https://github.com/ethereum/EIPs/pull/9350#issuecomment-2647826169
> Update EIP-7623: add reference to eip-3860

- EIPS/eip-7877.md
- EIPS/eip-tbd.md
EIP to replace `RETURN` with 4 more specific `RETURN` opcodes which allow defining where to return from explicitly instead of first requiring copying to memory.
> Add EIP: Enhanced RETURN opcodes

- EIPS/eip-7843.md
- Changed `8 byte ulong in big endian encoding` → `8-byte uint64 in big-endian encoding` for consistency and clarity.
The EIP-7843 specification already uses the `uint64` type, so replacing `ulong` with `uint64` ensures consistency in terminology. This helps avoid confusion and makes the description more precise in the context of Ethereum development.
> Update EIP-7843: specification update

- EIPS/eip-7702.md
Clarify that `CODE*` operate on the code being executed, and not on the delegation designator.
(Tests' expectations agree with this.)
This clarification is motivated by confusion observed in this document: https://hackmd.io/5kcrdKgaQHSjrQ9MtAlBfg?comment=37baf7a2-fd97-4e3a-9972-e4a86c92ce8b
> Update EIP-7702: Clarify CODE* operations behavior

- EIPS/eip-7873.md
- EIPS/eip-xxxx.md
See also corresponding EOF mega-spec change https://github.com/ipsilon/eof/pull/177
> Add EIP: EOF - TXCREATE and InitcodeTransaction type

- EIPS/eip-7251.md
* Provides a link to CL spec
* Updates Rationale and Security Considerations
* Moves to Last Call
> Update EIP-7251: Move to Last Call

- EIPS/eip-1898.md
Moving this EIP to Last Call. This eip has been widely supported by clients, devtools and libraries for multiple years, so no change is expected. Hence, the Last Call period could be short.
> Update EIP-1898: Move to Last Call

- EIPS/eip-7873.md
Rectifies two minor details I've found after reading the EIP post-merge
> Update EIP-7873: memory expansion of TXCREATE and remove 3860 charge mention

- EIPS/eip-7607.md
I want to cap Transaction gas limit ASAP before we increase Block limit too much so that we won't be nerfing it later. The actual limit (30mln) is up for debate.
> Update EIP-7607: Proposing 7825 for Fusaka

- EIPS/eip-7607.md
Reviewer @timbeiko
I think EOF needs the PAY opcode to maintain payment security, so I propose it will be considered for Osaka.
* add eip-5920 to proposed for inclusion
> Update EIP-7607: Propose EIP-5920 for inclusion in Osaka

- EIPS/eip-7880.md
- EIPS/eip-EXTCODEADDRESS.md
Add an instruction to EOF that reads code delegation designations from the account without requiring code introspection.
> Add EIP: EOF - EXTCODEADDRESS instruction

- EIPS/eip-7886.md
- EIPS/eip-xxxx.md
This PR proposes delayed execution as described in this ethresearch post:
https://ethresear.ch/t/delayed-execution-and-skipped-transactions/21677
Find Specs here:
https://github.com/ethereum/execution-specs/compare/master...fradamt:execution-specs:delayed-exec-basic
> Add EIP: Delayed execution

- EIPS/eip-5920.md
Reviewers @pandapip1 @SamWilsn @xinbenlv
I plan to champion EIP-5920 for inclusion in Osaka, else Amsterdam.
The current PAY opcode is likely to be used for `EXTDELEGATECALL`, of [EIP-7069](https://eips.ethereum.org/EIPS/eip-7069)
* Specification: change opcode to unused 0xFC
* Motivation: Mention EOF `EXTCALL`
* Rationale: Mention priority fees
> Update EIP-5920: Move to Draft

- EIPS/eip-7703.md
- EIPS/eip-7732.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `maximium` to `maximum`
Corrected `maximimum` to `maximum`
Corrected `latest_widthdrawals_root` to `latest_withdrawals_root` x2.
Corrected `Secutiry` to `Security`
Please review the changes and let me know if any additional changes are needed.
> Update EIP-7703: typos in documentation files

- EIPS/eip-7819.md
Hey there, 
I fix a typo: developpers -> developers
> Update EIP-7819: fix typos

- EIPS/eip-7864.md
eip-7864: Keep hash function as TBD with detailed analysis
This PR updates the hash function section of the unified binary tree state EIP to:
1. Keep the hash function selection as TBD while providing detailed analysis of the candidates:
- BLAKE3: Used in reference implementation for experimentation
- Keccak: Already used in Ethereum, well-studied security
- Poseidon2: Excellent for ZK proofs, pending security analysis
2. Make the specification hash-function agnostic by:
- Updating the node merkelization section to use a generic hash function H
- Clarifying that the reference implementation uses BLAKE3 temporarily
- Adding context about the ongoing EF cryptography initiative for Poseidon2
3. Update the TODO section to include finalizing the hash function selection
This approach allows EL …
> Update EIP-7864: Finalize hash function selection to Poseidon2

- EIPS/eip-5920.md
Reviewers @Pandapip1 @SamWilsn @xinbenlv
This future-proofs PAY for Address Space Extension, using the same method as `EXTCALL`.
* copy `extcall` address halting behavior
* define gas cost timing relative to exceptional halt
> Update EIP-5920: PAY Opcode Recipient Address

- EIPS/eip-7830.md
Now that the standard gas is 18/36 update the gas table to reflect the new maximum. Also, fix tpyos.
> Update EIP-7830: Update table to 36M gas

- EIPS/eip-7873.md
Updates to the Creator Contract as done in https://github.com/ipsilon/eof/pull/177 :
- remove `0xff` magic value from the `final_salt` calculation (CC @gumb0 @frangio)
- pass on as return data the entire revert return data (presumably revert reason) in case deployment fails (CC @frangio )
> Update EIP-7873: Creator Contract - revert reason & magic value

- EIPS/eip-3855.md
- EIPS/eip-7069.md
Corrected a couple of grammar mistakes:
- Replaced "exists" → "exist" in EIP-3855.
- Updated "explotation" → "exploitation" in EIP-7069.
No functional changes, just doc cleanup.
> docs: fix minor typos in EIP-3855 and EIP-7069

- EIPS/eip-7620.md
- EIPS/eip-7698.md
- EIPS/eip-7873.md
Makes note in all the EIPs concerning EOF contract creation, that whenever not explicitly stated, legacy rules should be had in mind.
> Update EIP-7620/7698/7873 - Defer EOF creation rules to legacy

- EIPS/eip-7896.md
- EIPS/eip-draft_abis_for_sendcalls.md
This EIP extends EIP-5792 with a new `interfaces` capability, whereby an application can attach the contract interface specifications (aka. ABIs) that the wallet needs to reliably decode the calldata in the request.
> Add EIP: ABI attachment in `wallet_sendCalls`

- EIPS/eip-1186.md
> Update EIP-1186: fix typo

- EIPS/eip-####.md
- EIPS/eip-7745.md
- EIPS/eip-7916.md
Move SSZ ProgressiveByteList to its own EIP so that it can be worked on independently of the eth_getLogs filter usage.
Plans are to work with @wemeetagain to generalize it beyond byte lists, and to simplify the parameters with `CAPACITY = unbounded` as well as `COMMON_RATIO = 4`. That way, in EIPs such as EIP-6404 and EIP-6466 it is no longer necessary to define arbitrary bounds to byte lists, and in consensus we can use such an `UnboundedList[T]` construct to replace proposer / attester slashing lists (with a shared maximum allowed len), and could use it for attestations list that keeps changing across forks.
First step is to move this out to its own EIP with Zsolt as author, then do the followup work with me and @wemeetagain in separate PRs.
> Add EIP: SSZ ProgressiveByteList

- EIPS/eip-7889.md
- EIPS/eip-xxxx.md
This PR proposes to emit a log containing the revert message for reverted transactions, making it accessible via standard RPC without the need for tracing.
> Add EIP: Emit log on revert

- EIPS/eip-663.md
Add a rationale for immediate arguments instead of arguments from the operand stack.
> Update EIP-663: Add rationale for immediate arguments

- EIPS/eip-6110.md
EIP-6110 currently does not specify how to parse the deposit event data. This PR adds the specific layout of the mainnet (and Sepolia) log data to the spec. If the deposit contract logs a DepositEvent but the layout is incorrect, the block will be marked as invalid, because the deposit contract does not adhere the deposit event layout.
Note that this approach does only spec the layout of the log: the actual bytecode of the contract is not specified. Therefore, mainnet, sepolia and holesky all match this spec. (Mainnet/Holesky bytecode is the same: Sepolia is however a "permissioned" ERC20-token contract (instead of accepting native Eth deposits) and thus has different bytecode. This thus allows any bytecode contract to be valid, given that the `DepositEvent` as being LOG-ed having the …
> Update EIP-6110: Spec `parse_deposit_data`

- EIPS/eip-7623.md
This PR adds an extra comment to mention bigger EL payload sizes that could happen for more adversarial constructions.
More details about the construction are in [this doc](https://hackmd.io/@jsign/eip-7623-big-el-payload), which builds a 1.05MB case. @nerolation pushed this idea further with a snappy inefficiency, leading to the mentioned 1.26MiB in this PR.
As mentioned in the doc linked above, this finding doesn't seem to justify a change in constants. Despite the worst case is updated, the constant also has a relationship with UX-impact. The doc references an Ethresearch post that can provide more insight into the rationale behind the current constant value.
> Update EIP-7623: add extra comment about worst case EL payload sizes

- EIPS/eip-7607.md
CFI & SFI changes made on [ACDE#208](https://github.com/ethereum/pm/issues/1374). [The EOF Meta EIP changes](https://github.com/ethereum/EIPs/pull/9557) cannot be merged yet due to status issues. The devnet specs referenced are from ["Option A" in this document](https://notes.ethereum.org/@ipsilon/eof_fusaka_options#A---Complete-EOF).
> Update EIP-7607: ACDE#208 Updates

- EIPS/eip-7873.md
We should not use 0x05 as tx type for the InitcodeTransaction, because this is used as MAGIC byte when signing EIP-7702 authorities: https://eips.ethereum.org/EIPS/eip-7702#parameters
As far as I am aware, 0x06 is not used as magic byte or "RLP escape byte".
> Update EIP-7873: set tx type to a currently unused (?) first RLP byte

- EIPS/eip-7873.md
Align argument order with planned order for EOFCREATE, see https://github.com/ethereum/EIPs/pull/9503
> Update EIP-7873: Align TXCREATE stack argument order with EOFCREATE

- EIPS/eip-7921.md
- EIPS/eip-draft-remove-jumpdest-push-check.md
I have long suggested this solution elsewhere but now I am making a formal proposal.
* add eip
> Add EIP: Skip `JUMPDEST` immediate argument check

- EIPS/eip-7557.md
Reopening the old PR that I did not realise was not previously merged (https://github.com/ethereum/EIPs/pull/7968)
This proposal is significantly different from EIP-7863 (https://github.com/ethereum/EIPs/pull/9246), arguably presents a more complete and fair solution that is worth the extra complexity, and precedes it for more than a year.
> Add EIP: Block-level Warming with fair cost savings

- EIPS/eip-7594.md
See [this doc](https://hackmd.io/@jimmygchen/HkUpFliYJx) for context
> Update EIP-7594: include cell proofs in network wrapper of blob txs

- EIPS/eip-4750.md
This was a loose end not updated after introduction of non-returning functions. Mega-spec has correct type, and it is additionally specified (correcrly) in EIP-6206.
> Update EIP-4750: Fix the definition of 0th code section type

- EIPS/eip-7873.md
Piggybacking on the updates to the EOFCREATE hashing scheme happening anyway, we align the TXCREATE scheme to be forward compatible with ASE (address space extension), by allowing a natural progression to 32-byte addresses
> Update EIP-7873: TXCREATE hashing scheme to EOFCREATE with ASE

- EIPS/eip-6206.md
- EIPS/eip-7620.md
- EIPS/eip-7873.md
It seems that 3 EIPs weren't explicit about new EOF opcodes being exclusive to EOF. The EOF megaspec fortunately was explicit about this https://github.com/ipsilon/eof/blob/main/spec/eof.md and I think it wasn't ever source of confusion, but we need to make it explicit regardless.
> Update EIP-6206: Ban the EOF-only opcodes in legacy

- EIPS/eip-7761.md
EOF requires this for eof-devnet-2, as well as the EIP-7607 Fusaka hard fork meta and EIP-7692 EOF Meta EIP.
> Update EIP-7761: Move to Review

- EIPS/eip-7873.md
EOF requires this for eof-devnet-1, as well as the EIP-7607 Fusaka hard fork meta and EIP-7692 EOF Meta EIP.
> Update EIP-7873: Move to Review

- EIPS/eip-7834.md
EOF requires this for eof-devnet-2, as well as the EIP-7607 Fusaka hard fork meta and EIP-7692 EOF Meta EIP.
> Update EIP-7834: Move to Review

- EIPS/eip-7620.md
Align with eof-devnet-1 planned change https://github.com/ipsilon/eof/pull/156 . Goes in hand with https://github.com/ethereum/execution-spec-tests/pull/1274
> Update EIP-7620: Align EOFCREATE stack args with EXTCALL

- EIPS/eip-7880.md
EOF requires this for eof-devnet-2, as well as the EIP-7607 Fusaka hard fork meta and EIP-7692 EOF Meta EIP.
> Update EIP-7880: Move to Review

- EIPS/eip-1898.md
Moving this EIP to Final. This eip has been widely supported by clients, devtools and libraries for multiple years, so no change or breakage is expected. I'm doing this mostly to clean up the ethereum ecosystem, especially with newcomers in mind.
Thanks @charles-cooper for creating the EIP and agreeing to go through this process.
> Update EIP-1898: Move to Final

- assets/eip-2537/fast_subgroup_checks.md
I noticed that in the description of the G2 group, the points are referred to as **(x', y')**, but later, the endomorphism check is described using **(x, y)**. This inconsistency could lead to confusion, so I updated the description to consistently use **(x', y')** for G2 points.
Now the description reads:
```
Group G2 is defined as a set of Fp2 pairs (points) `(x', y')` such that either `(x', y')` is `(0,0)` or `(x', y')` satisfy the curve Fp2 equation.
```
> docs: fix inconsistency in G2 group point notation

- EIPS/eip-7701.md
1. Fix broken **bold** markdown
2. Rename "PostTransaction" back to "PostOp"
3. Add "current transaction hash" and "nonce" to the "TXPARAM" table
4. Mark "time range validity" as "optional"
5. Fix using deprecated "callData" term instead of "senderExecutionData"
6. Provide pseudocode for "buy_gas" and "refund_gas"
7. Raise exception instead of skipping invalid AA tx in block pseudocode
8. Add security considerations
> Update EIP-7701: Minor fixes

- EIPS/eip-7642.md
Here I am updating the eth/69 proposal with two changes:
- Simplifying the receipts encoding. The original EIP proposed a new format for receipts with the bloom filter removed. It did that by mirroring the complex encoding for typed receipts which is also used by Ethereum consensus. Since the network protocol now introduces a deviation from the encoding used by consensus, there is no need to make it so complex. 
Ultimately all receipt types contain the same four fields. So with this update, I am changing the network encoding to be the same for all receipt types.
- I am adding a new field `earliestBlock` in the `Status` message. This is somewhat similar to EIP-7542, which proposed adding a `blockRange`.
> Update EIP-7642: Move to Draft

- EIPS/eip-7916.md
- https://github.com/ethereum/EIPs/pull/9542#pullrequestreview-2727849894
> Update EIP-7916: Address review feedback

- EIPS/eip-5920.md
EOF requires this for eof-devnet-2, as well as the EIP-7607 Fusaka hard fork meta and EIP-7692 EOF Meta EIP.
> Update EIP-5920: Move to Review

- EIPS/eip-6953.md
Historical summaries are updated once every **8192 slots**, not 7192 epochs. 
Capella's epoch, 194048, is not even divisible by 7192. The associated starting slot (194048 x 32 = 6209536) is divisible by 8192.
> Update EIP-6953: Update Historical Boundary Definitions

- EIPS/eip-1679.md
This pull request updates the EIPS/eip-1679.md file by fixing a broken GitHub link
> Update EIP-1679: Fixed Broken Link

- EIPS/eip-3860.md
Hi,
The word "effected" in 'Backwards Compatibility' section) seem to be incorrect in this context. The correct term is "affected".
I suggested a revision: "effected" to "affected".
Thanks.
> Update EIP-3860: Update eip-3860.md

- EIPS/eip-5450.md
This removes one redundant rule.
> Update EIP-5450: Simplify stack overflow checks

- EIPS/eip-7620.md
Fixes a quite unfortunate fail to copy-paste done in #9592 . Obviously, it is EOFCREATE and RETURNCODE which result in an exceptional halt **in legacy**, not CREATE and CREATE2. Sorry about that, hoping this has not led to any confusion
> Update EIP-7620: Fix failed copy-paste

- EIPS/eip-2935.md
The specs say:
> The ring buffer data structure is sized to hold 8191 hashes.
Also, https://github.com/ethereum/sys-asm/blob/f1c13e285b6aeef2b19793995e00861bf0f32c9a/src/execution_hash/main.eas#L17
```eas
;; BUFLEN returns the HISTORY_BUFFER_LENGTH as defined in the EIP.
#define BUFLEN = 8191
```
> Update EIP-2935: Fix Ring Buffer Size in Description

- EIPS/eip-7927.md
Remove the TODO item that was left in the EIP and is no longer needed.
> Update EIP-7927: EIP 7927 - remove leftover TODO item

- EIPS/eip-3540.md
- EIPS/eip-4200.md
- EIPS/eip-4750.md
- EIPS/eip-5450.md
- EIPS/eip-6206.md
- EIPS/eip-663.md
- EIPS/eip-7069.md
- EIPS/eip-7480.md
- EIPS/eip-7620.md
This PR improves and clarify spec of EOF EIPs. It also fills missing sections. Changes to each EIP has its separated commit.
> Update EIP-3540: Claify, improve and fill missing sections of EOF EIPs

- EIPS/eip-7607.md
On ["ACDT" 34](https://github.com/ethereum/pm/issues/1499), a decision was made to remove EOF from Fusaka. 
The process here was highly unusual. I encourage people to listen to the [full discussion](https://www.youtube.com/watch?v=M3DWaWbIB3s). Here are the reasons why I think this is the correct outcome, despite several client teams expressing support for EOF: 
1. **Risks to Fusaka timelines**: all client teams, ELs included, seem to agree that shipping PeerDAS ASAP is Ethereum's most important priority. While this wasn't a major topic of discussion on the call, it's worth acknowledging that debating variants of the EOF spec at this point affects our ability to ship. As we move towards Fusaka devnets, and coupling EL & CL changes, keeping EOF would increasingly become the default path. …
> Update EIP-7607: Remove EOF from Fusaka 

- EIPS/eip-7702.md
- Remove concept of trie from the EVM specification in EIP-7702 and replace it with "emptiness" for simplicity.
- I think it would be good to abstract the EVM from the trie implementation. The EVM should just know if an account is empty or not. This simplification has been done almost 9 years ago and we should stick to it. For clients that don't implement forks older than Tangerine Whistle it adds unnecessary complexity because they'd need to track if an account is empty but still exists in the trie, something that's not possible in these scenarios.
From [EIP-158](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-158.md)
"Whenever the EVM checks if an account exists, emptiness is treated as equivalent to nonexistence. Particularly, note that this implies that, once this change is …
> Update EIP-7702: Remove trie concept from the vm specification

- eip-7935.md
EIP to recommend a new gas limit by the time Fusaka is released and update EL default configs.
> Add gas limit increase EIP

- EIPS/eip-7762.md
Fixed spelling errors in EIP-7762:
- "apropriately" -> "appropriately"
- "aproach" -> "approach"
> Update EIP-7762: correct spelling errors in EIP-7762

- EIPS/eip-3220.md
This pull request fixes a typographical error in the EIP-3220 Crosschain Identifier Specification document. The phrase "block hash of of the block" contained a duplicate word "of" which has been removed to improve readability and correctness of the specification.
> Update EIP-3220: Correct wording in blockchain identifier documentation

- EIPS/eip-5792.md
Not normative changes, just editorial/bibliographical ones. The newer commits in these links should less confusing to implementers trying to implement 5792 with Wallet Connect and/or MetaMask SDKs, as CASA updated the examples on that side to match the newest changes to chainId-specific (and evm-wide) capability declaration from a few weeks back.
> Update EIP-5792: Update CAIP-25 links in eip-5792.md to newest commit

- EIPS/eip-7886.md
We've transitioned from the coinbase-fronted inclusion cost model to a mechanism where transaction senders are pre-charged for their declared gas usage upfront. If any transaction turns out to be invalid during execution, the entire EL payload is treated as a no-op, reverting to the pre-state. This avoids complex fork-choice changes and maintains compatibility with related protocol proposals such as FOCIL. It keeps the UX stable—gas refunds are still possible—while mitigating builder exploits around free DA. Critically, the declared gas usage must match actual gas used, or the block becomes invalid.
> Update EIP-7886: Move from "coinbase fronting" to "payload reversion" mechanism

- EIPS/eip-7702.md
**Typographical & Grammar Fixes**
- "formated" → "formatted" in the Abstract section.
- "reseting" → "resetting" in the Specification section.
- "sweeped" → "swept" in the Security Considerations (Transaction propagation) section.
- "maybe" → "may be" (space added) in the last paragraph under Transaction Propagation.
- "be able to" → "been able to" for proper tense in the Transaction Propagation section.
> Update EIP-7702: Fixing minor typos

- EIPS/eip-4444.md
This pull request corrects minor grammatical issues and a typo in the text of EIP-4444, specifically:
- Corrected “receipts that is older” to “receipts that are older”.
- Fixed a typo in the word “pronounciations” → “pronunciation”.
> Update EIP-4444: Fix typos in EIP-4444

- EIPS/draft-eip-multi-algorithm-pki.md
- EIPS/eip-7932.md
- assets/eip-7932/template-eip.md
This EIP introduces a new wrapper type transaction to allow for alternative signature algorithms to sign off on an ethereum transactions.
> Add EIP: Algorithmic Transaction Wrapper

- EIPS/eip-7002.md
This PR fixes a variable name inconsistency in the `dequeue_withdrawal_requests` function. The variable was assigned as `num_dequeued` but then referenced as `num_dequeue` in the for loop, which would cause an undefined variable reference.
- Changed `for i in range(num_dequeue):` to `for i in range(num_dequeued):` to correctly reference the previously defined variable
- This ensures the code correctly iterates through the intended number of withdrawal requests to be dequeued
The fix maintains the intended functionality of the withdrawal request system while preventing potential errors during execution.
> Update EIP-7002: fix variable name typo in withdrawal requests dequeue function

- EIPS/eip-7607.md
Moving the two EIPs included in `fusaka-devnet-0` from CFI to SFI as decided on [ACDT#36](https://ethereum-magicians.org/t/all-core-devs-testing-acdt-36-may-12-2025/24076)
> Update EIP-7607: Update eip-7607.md

- EIPS/eip-7702.md
@wjmelements noted that the current text is very confusing re: the gas costs of code reading instructions.
> Update EIP-7702: Clarify read ops

- EIPS/eip-7685.md
> Update EIP-7685: Move to Final

- EIPS/eip-7251.md
> Update EIP-7251: Move to Final

- EIPS/eip-6110.md
This change clarifies that the python `int.from_bytes` should use `signed=False`. Therefore, it will never return a negative number. Note, that `signed=False` is the default setting for `int.from_bytes`. This is thus a clarification to avoid decoding it as signed int. It is now thus decoded as `uint`.
> Update EIP-6110: ensure ints are decoded as uints

- assets/eip-3267/contracts/SalaryWithDAO.sol
- `assets/eip-3267/contracts/SalaryWithDAO.sol:69`: "exteremely" corrected to "extremely".
- Enhanced code accuracy and ensured professionalism by fixing the typo.
> typo-Update SalaryWithDAO.sol

- EIPS/eip-7607.md
I messed up the copy/paste in the [previous PR](https://github.com/ethereum/EIPs/pull/9772) 😅 
On [ACDT#36](https://ethereum-magicians.org/t/all-core-devs-testing-acdt-36-may-12-2025/24076), we SFI'd EIP 7883, to be included along with the other SFI'd EIPs in devnet-1. The Meta EIP now reflect this, and removes all SFI'd EIP from the CFI section.
> Update EIP-7607: Fix Fusaka SFI Changes

- EIPS/eip-225.md
- EIPS/eip-627.md
[EIP-225.md] fix from 'parcitular' -> 'particular'
[EIP-627.md] correct from 'excuding' -> 'excluding'
> Update EIP-225: fix typos

- EIPS/eip-7782.md
> Update EIP-7782: Move to Draft

- EIPS/eip-7805.md
- Add Engine API changes from https://github.com/ethereum/execution-apis/pull/609
- Clarify IL building process is unspecified in EL section
- Correct statements about block being invalid if IL not satisfied
- Clarify some details of EL / engine API changes
> Update EIP-7805: expand on EL changes

- EIPS/eip-7928.md
Unions are not present in the spec, and AFAICT they are not supported by production-grade SSZ implementations.  We can use a byte list here, with empty list signaling no code in the account.
> Update EIP-7928: convert contract code field from union type to list of bytes

- EIPS/eip-7917.md
Update EIP based on [latest specs](https://github.com/ethereum/consensus-specs/blob/dev/specs/fulu/beacon-chain.md#beaconstate).
> Update EIP-7917: Change proposer_lookahead type from List to Vector

- EIPS/eip-7928.md
Since code can only change once per tx/address, we can remove the list as suggested by @jochem-brouwer in this PR:
https://github.com/ethereum/EIPs/pull/9864#event-18019983159
> Update EIP-7928: Code change

- EIPS/eip-7600.md
With Pectra live on mainnet, the Meta EIP should be moved to Final. Note that this will require all included EIPs to be moved to final:
> Update EIP-7600: Move to Final

- EIPS/eip-7928.md
> make explicit that the BAL is its own field in the block
I think this was already assumed, so I'm making it explicit here.
> remove SSZ encoding as a requirement for BAL verification
Comparing the output of the ssz encoding of the computed BAL in verification incurs unnecessary overhead.  We can just compare the header BAL vs computed value directly (field-by-field).
> Update EIP-7928: make explicit that the BAL is its own field in the block, remove SSZ encoding as a requirement for BAL verification

- EIPS/eip-7934.md
As title.
From Pari:
> MARGIN needs to be atleast 890kib with todays validator set size. You likely want to set the value to 1mib or more to account for future validator set growth.
> Update EIP-7934: Bump safety margin to 2MiB.

- EIPS/eip-7762.md
This PR fixes two spelling errors in the Rationale section of EIP-7762:
- Corrects "aproach" to "approach"
- Corrects "apropriately" to "appropriately"
These changes improve the document's readability while maintaining its technical content.
> Update EIP-7762: Update eip-7762.md

- EIPS/eip-7883.md
From the performance analysis of the modexp precompile after EIP-7883, the increase minimal cost of 500 don't fully cover the worst case of small base/modulus. E.g. the case of the smallest base/modulus of 8 bytes the maximum exponent within the 500 gas cost budget has 880 bits. This case performs significantly worst than the average case (modulus 32 bytes).
We propose to eliminate the pathological cases of base/modulus smaller than 32 bytes by computing the gas cost as if they had 32 byte length. By the [Mainnet usage data of the modexp](https://github.com/hugo-dc/modexp_analysis/blob/master/modexp.ipynb), a modulus smaller than 32 bytes had never been used.
Additional context in the EIP discussion: https://ethereum-magicians.org/t/eip-7883-modexp-gas-cost-increase/22841/6.
The below …
> Update EIP-7883: Assume minimal base/mod length of 32

- EIPS/eip-7928.md
Fix inconsistencies in SSZ data structures.
`AccountCodeDiff.changes` -> `AccountCodeDiff.change` - as it represents a single code change
`NonceDiffs = List[AccountNonceDiff, MAX_TXS]` -> `NonceDiffs = List[AccountNonce, MAX_TXS]`
> Update EIP-7928: inconsistencies in SSZ structures

- EIPS/eip-7934.md
> Update EIP-7934: Set MAX_RECEIPTS_MESSAGE_SIZE for GetReceipts in devp2p

- assets/eip-7549/complexity_analysis.md
a few minor typos while reading through the complexity analysis and went ahead and fixed them:
- "aggregtes" → "aggregates"  
- "these numbers assumes" → "these numbers assume"  
- "respresented" → "represented"  
thanks!
> docs: fix typos in complexity analysis section

- EIPS/eip-7937.md
1. Corrected `noticable` → `noticeable`
2. Corrected `optmization` → `optimization`
3. Corrected `signficant` → `significant`
4. Corrected `seperate` → `separate`
> Update EIP-7937: Fix Typos and Improve Clarity in EIP-7937 Specification

- EIPS/eip-7928.md
In order to parallelize block transaction execution and state root calculation, we need post-tx nonce values for contract accounts which created other contracts.  If we only have prestate nonces, we would need to execute the final block transaction before being able to calculate the state root.
Also, I don't see a need to include the nonce values for contracts which invoked a `CREATE`/`CREATE2` that reverted.  It's not information that needs to be known in order to execute subsequent txs in the block.
> Update EIP-7928: specify nonce diffs as post-tx nonces for contract accounts which modified their nonce

- EIPS/eip-7898.md
**Description:**
This PR corrects a few typos in the EIP-7898 specification.
Changes:
*   `infact` → `in fact`
*   `augument` → `augment`
*   `annouce` → `announce`
> Update EIP-7898: Fix typos in EIP-7898

- EIPS/eip-1186.md
Replaced a deprecated GitHub Wiki link with the updated Merkle Tree documentation in the eth-wiki repo.
> Update EIP-1186: Fix broken Merkle Tree link in EIP-1186 abstract

- EIPS/eip-7928.md
This PR fixes two issues with BAL type definition:
1. `code_diffs` should be of type `CodeDiffs`.
2.  `NonceDiffs` is defined as `List[AccountNonceDiff, MAX_TXS]` but should be `List[AccountNonceDiff, MAX_ACCOUNTS]`
since it's tracking accounts, not transactions.
Additionally it fixes a small python syntax error:
1. `.push()` should be `.append()`
> Update EIP-7928: Fix BAL type definition

- EIPS/eip-7976.md
- EIPS/eip-xxxx.md
Raise calldata floor cost to 15/60 gas to reduce max block size
> Add EIP: Further increase calldata cost

- EIPS/eip-7749.md
Corrected a typo ("verfying" → "verifying") and improved the wording in the verifier address example section for clarity and accuracy.
> Update EIP-7749: fix typo in verifier address description

- EIPS/eip-7805.md
*Description*:
The max length of inclusion list transactions should be `MAX_TRANSACTIONS_PER_PAYLOAD`. The EIP was using `MAX_TRANSACTIONS_PER_INCLUSION_LIST` for historical reason and has to be updated.
Thanks to @GrapeBaBa for spotting this out.
Relevant discussion: https://discord.com/channels/595666850260713488/1210529202458071050/1332367822390693981
> Update EIP-7805: Use `MAX_TRANSACTIONS_PER_PAYLOAD` for the max length of IL transactions

- EIPS/eip-6466.md
- `logIndex` now based per receipt rather than entire block
- Switch to `ProgressiveContainer` / `CompatibleUnion` based design
> Update EIP-6466: Adopt `ProgressiveContainer`

- EIPS/eip-7607.md
EIPs 7907, 7934, 7939 and 7951 were SFI'd on [ACDE#214](https://github.com/ethereum/pm/issues/1569). 
This PR is blocked on https://github.com/ethereum/EIPs/pull/9833
> Update EIP-7607: ACDE#214 changes

- EIPS/eip-7807.md
- Use EIP-7495 ProgressiveContainer for latest forward compatibility changes
- Replicate changes to ExecutionPayload / Header to avoid separate `block_hash` field / use hash_tree_root everywhere
> Update EIP-7807: Adopt `ProgressiveContainer`

- EIPS/eip-7907.md
Clarify behavior when a large contract is the entry point of a transaction.
> Update EIP-7907: Account for large contracts as tx entry point

- EIPS/eip-7918.md
Update with the change agreed upon on [ACDE 214](https://ethereum-magicians.org/t/all-core-devs-execution-acde-214-june-19-2025/24508/2), i.e. finalize `BLOB_BASE_COST` to `2**13`. Figures to be updated in a separate PR later.
> Update EIP-7918: finalize BLOB_BASE_COST

- EIPS/eip-7939.md
Increases the gas cost of CLZ from 3 to 5. This gives us a very conservative upper bound that is very unlikely to be under priced and abused.
We could wait for benchmarking results over the next week to determine a more precise value or validate the current value, but personally as I lean on the side of finalizing Fusaka ASAP I'd rather increase now then re-assess in Glamsterdam.
> Update EIP-7939: Change gas cost from 3 to 5

- EIPS/eip-7910.md
Adds Fork Id as members `currentForkId` and `nextForkId` to the `eth_config` response, as specified in EIP-6122.
Note that EIP-6122 only mentions `FORK_HASH` as the current configured fork's Id, and the block/timestamp number as the sole piece of information for the next fork, but, in this PR, `FORK_HASH` is also calculated for the next fork in order to catch fork ID issues early.
BPO forks are now specified in the EIP.
Adds `last`, `lastHash` and `lastForkId` members to represent the last configured fork know by the client.
> Update EIP-7910: Add Fork Id to response, spec BPOs, add "last"

- EIPS/eip-7825.md
Based on [this new EIP](https://github.com/ethereum/EIPs/pull/9984#pullrequestreview-2994191824) and [discussions on ACDT](https://github.com/ethereum/pm/issues/1603), I created this PR to proposer lowering the tx gas limit cap.
> Update EIP-7825: Move to Draft

- EIPS/eip-2926.md
This PR revives eip 2926 based on a conversation that happened during the Berlin interop. The idea is to strip the verkle/binary/tree EIPs down to the most valuable piece for the medium-term Ethereum roadmap: code chunking.
There is a significant overhaul of this EIP:
* Code size and hash are stored at the account level, not in the tree. A new field for the code chunk root hash is added.
* Only the version is stored in the tree, alongside the code chunks
* Tree is expected to be MPT, to be later replaced with a single tree version, e.g. in eip-7864
* It doesn't restrict the depth of the tree, so that code length can go beyond 2MB
* It adapts the conversion from eip 7612 to this new version
> Update EIP-2926: Move to Draft

- EIPS/eip-7883.md
Fixing a typo in gas pricing of test case `modexp_nagydani_5_pow0x10001`
> Update EIP-7883: Fix typo in pricing of one test case

- EIPS/eip-7495.md
This pull request corrects two minor issues in EIP-7495:
- Fixes a typo: `chanages` is replaced with `changes`.
- Removes an extra parenthesis in the Merkleization specification link.
> Update EIP-7495: fix typos and link formatting

- EIPS/eip-7919.md
- Make motiviation clearer (no indexers for basic wallet use cases)
- Split ETH transfer emit logs and LOG reform sections
- Only keep multidimensional concept but don't introduce calldata fee
- Drop optional EIPs
> Update EIP-7919: Minimize scope

- EIPS/eip-7949.md
This PR corrects several typos and formatting issues in EIP-7949:
- **Header formatting**: Added proper markdown heading for "JSON Schema" section
- **Typo fix**: Corrected "Paramter" → "Parameter" in line 188  
- **JSON formatting**: Cleaned up spacing inconsistencies in schema definition
- Removed extra spaces in `pattern` properties
- Standardized spacing in `type` declarations
- Fixed `additionalProperties` formatting
- Improves document readability and consistency
- Ensures proper markdown rendering
- Maintains JSON schema validity
> Update EIP-7949: Fix typos and formatting

- EIPS/eip-8.md
there was a typo "incompatibel", fixed it to "incompatible"
> Update EIP-8: typo in reason=reasons.incompatibel_p2p_version

- EIPS/eip-7642.md
This pull request fixes several minor typos and grammatical errors in EIP-7642, including corrections for "transfered" → "transferred", "send" → "sent", and "pre merge" → "pre-merge".
> Update EIP-7642: Corrected Spelling and Grammar

- EIPS/eip-7910.md
follow up after https://github.com/ethereum/EIPs/pull/10039
there is a typo in `nextHash` - it should match the value of `lastHash` which has the correct value `0x0d82a81f`
@shemnon @rubo pls can you check
> Update EIP-7910: fix missing 0 in nextHash example

- EIPS/eip-7910.md
Some impls have good EIP-55 support, but that (a) breaks canonical form and (b) is hard to hand-edit. So all hex values must be lower case.
> Update EIP-7910: require addresses and forkids to be in lowecase hex.

- EIPS/eip-7966.md
- Add optional client-configured timeout parameter
- Define error codes for timeout and invalid parameter scenarios (following EIP-1474 and JSON error code standards)
- Change node-configured timeouts from MUST to SHOULD
- Improve specs
--
- If …
> Update EIP-7966: add client-configured timeout and improve specs

- EIPS/eip-2926.md
The EIP was meant to use 31-byte chunk size. That is, each chunk use 1 byte for push offset and 31 bytes of code, similar to the code chunking strategy in [EIP-6800](https://eips.ethereum.org/EIPS/eip-6800).
> Update EIP-2926: use 31-byte chunk size instead

- EIPS/eip-7937.md
Corrected a typo in the `Test Cases` section of EIP-7937:  
- Changed `orgnized` to `organized` for improved clarity and professionalism.
> Update EIP-7937: fix typo in test cases section

- EIPS/eip-1571.md
- `aknowledgement` → `acknowledgement`
- `an host` → `a host`
- `extranoce` → `extranonce`
> Update EIP-1571: fix typo

- EIPS/eip-7928.md
System contract must be mapped to tx_index `len(transactions)` instead of `len(transactions) +1`
> Update EIP-7928: Fix mistake in tx_index of system contracts

- EIPS/eip-7732.md
- Updates the links to the latest CL spec snapshot. 
- Removes mentions of payload boosts
- Adds bid payment processing mechanism by withdrawals
- Updates to latest structures
Still needs to update to dual deadline PTC and the rebase on Fulu.
> Update EIP-7732: update to latest CL-spec version

- EIPS/eip-7773.md
As requested in https://ethereum-magicians.org/t/eip-7773-glamsterdam-network-upgrade-meta-thread/21195, I am creating a PR to propose 2926 in Glamsterdam.
> Update EIP-7773: propose eip 2926 for inclusion in Glamsterdam

- EIPS/eip-7966.md
- Fallback to the default node-configured timeout when the client-configured timeout is invalid.
- Replace the negative error code `-32002` with a positive error code `4` when timeout.
> Update EIP-7966: remove client-configured timeout validation and change error code

- EIPS/eip-7807.md
Unnecessary 'to'
replaced with `ExecutionBlockHeader` - correct
> Update EIP-7807: correct grammar in Engine API section

- EIPS/eip-7917.md
According to https://github.com/linoscope/consensus-specs/commit/208f3687d2ae7662c9de4805772dbb2eeaf2d1ca there is an off by 1 in the EIP (see also https://github.com/ethereum/consensus-specs/blob/master/specs/fulu/beacon-chain.md#new-process_proposer_lookahead)
--
- Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside …
> Update EIP-7917: fix off-by-one error

- EIPS/eip-7981.md
This is the PR to the full specs:
https://github.com/ethereum/execution-specs/pull/1384
> Update EIP-7981: Add EELS spec implementation

- EIPS/eip-7773.md
This pull request corrects a typo in the EIP-7773 description, replacing "Gloas/Amsterdam" with the correct term "Glamsterdam" for clarity and consistency.
> Update EIP-7773: `Gloas/Amsterdam` → `Glamsterdam`

- EIPS/eip-2926.md
- Add hyphen to compound adjective `state-accessing opcodes`
- Fix missing closing parenthesis in chunk size explanation
- Correct number agreement: `field allows` instead of `fields allows`
> Update EIP-2926: correct grammar and punctuation errors

- eip-template.md
- Change RFC 8170 to RFC 8174 in the Specification section comment
- Aligns template with EIP-1 specification and existing EIP documents
- RFC 8174 is the correct standard for terminology alongside RFC 2119
- All existing EIPs use RFC 8174, making this consistent with the codebase
> fix: correct RFC reference from 8170 to 8174 in eip-template.md

- EIPS/eip-7980.md
Fix article usage: "Adds a EIP-7932" → "Adds an EIP-7932"
Add missing preposition: "discourages people attempting" → "discourages people from attempting"
> Update EIP-7980: fix issues

- EIPS/eip-7932.md
Without this return, the precompile fails to output the signer address on successful verification, breaking core functionality
> Update EIP-7932: add missing return statement in sigrecover_precompile function

- EIPS/eip-1702.md
https://specs.corepaper.org/40-unused/ - broken
https://corepaper.org/ethereum/compatibility/forward/ - correct
> Update EIP-1702: update broken link

- assets/eip-7825/analysis.md
Take a look at https://eips.ethereum.org/assets/eip-7825/analysis. The table does not render well.
In kramdown (used in Jekyll), a blank line is needed before the table. Otherwise, it will not render.
Though github renders it well, it shows a mess in the https://eips.ethereum.org/ website.
> Update EIP-7825: Fix broken table rendering

- EIPS/eip-7932.md
Take a look at https://eips.ethereum.org/EIPS/eip-7932. The table below `Algorithm specification` does not render well.
In kramdown (used in Jekyll), a blank line is needed before the table. Otherwise, it will not render.
Though github renders it well, it shows a mess in the https://eips.ethereum.org/ website.
> Update EIP-7932: Fix broken table rendering

- EIPS/eip-6404.md
Problem:
In EIP-6404’s EIP-7702 section, RlpSetCodeTransaction incorrectly declared payload: RlpAuthorization instead of payload: RlpSetCodeTransactionPayload. This contradicts the canonical SSZ type definitions used by the repo and leads to a type mismatch in the spec.
Evidence:
Canonical SSZ definition in the repo clearly shows the correct type:
assets/eip-6404/ssz_types.py
class RlpSetCodeTransaction(Container):
payload: RlpSetCodeTransactionPayload
signature: Secp256k1ExecutionSignature
The Markdown spec had the wrong type in the EIP-7702 section (now corrected):
class RlpSetCodeTransaction(Container):
payload: RlpSetCodeTransactionPayload
signature: Secp256k1ExecutionSignature
> Update EIP-6404: Fix RlpSetCodeTransaction payload type to RlpSetCodeTransactionPayload

- EIPS/eip-7723.md
This PR introduces a minimally invasive EIP Champion role for the duration of the EIPs lifecycle in a given network upgrade. In short, a Champion is the primary point of contact, but may delegate as much of the responsibility as needed.
The motivation is to establish clear communication channels out of the gate, so that call facilitators, client teams, and testers know exactly who to reach out to to progress an EIP through the upgrade. The lack of a Champion may also be healthy nudge early in the process to nominate one.
The change is backwards compatible, as a Champion is not a strict requirement.
Implementation considerations:
- If desirable, the Champion names could be displayed in the meta EIP for ease of reference.
- I've left it undefined, but rotating a Champion should be low fuss, …
> Update EIP-7723: Include primary point of contact in proposal

- EIPS/eip-2711.md
spotted a few small typos while going through EIP-2711:
* `recpient` → `recipient`
* `suitalbe` → `suitable`
> Update EIP-2711: fix minor typos

- EIPS/eip-7807.md
Remove redundant parentheses in ProgressiveContainer constructor call.
Changed `ProgressiveContainer((active_fields=[1, 1]))` to `ProgressiveContainer(active_fields=[1, 1])` to match the correct syntax used in ExecutionBlockHeader and ExecutionPayload classes.
> Update EIP-7807: Fix ProgressiveContainer syntax in GasAmounts

- EIPS/eip-1108.md
Fix grammatical error in EIP-1108.md
- Change "There protocols" to "These protocols" for proper grammar
> Update EIP-1108: correct typo in EIP-1108 rationale section

- EIPS/eip-7805.md
This PR reflects the change introduced to the engine APIs spec in this [commit](https://github.com/ethereum/execution-apis/pull/609/commits/ae719c0587a66e8d8196bfebfb7c4eaa6bc3f6fb).
> Update EIP-7805: reflect the latest engine APIs spec change
