EIPS/eip-5643.md
=> Update EIP-5643: Move to Review

EIPS/eip-5604.md
=> Add co-authors for EIP-5604

EIPS/eip-5027.md, assets/eip-5027/0001-unlimit-code-size.patch
=> Update EIP-5027 with cold/warm storage

EIPS/eip-5643.md
Forgot to update this section earlier. The interface id below is correct as I computed it after I changed the code.
=> Fix typo in EIP-5643

EIPS/eip-5643.md
Fix the example implementation
=> Final typo in EIP-5643

EIPS/eip-5528.md
=> Update EIP-5528: Move to final

index.html
http://xinbenlv.github.io/EIPs/
=> Add Discord link of Eth R&D to the EIP Website header.

README.md
"GitHub pages" should be updated to "GitHub Pages"
=> Update README: Capitalize "GitHub Pages"

EIPS/eip-2315.md
=> Catch up to Yellow Paper

index.html
=> Website: Add Ethereum Wallets Discord

EIPS/eip-2315.md
=> Update EIP-2315: Yellow Paper link

.github/workflows/ci.yml
This release adds:
* Bug fix for `requires:` header.
* Configurable allow/warn/deny levels per lint.
* No colons in title/description.
=> CI: Grab latest eipw-action

EIPS/eip-5216.md
Hey,
After a couple of months and a few of reviews from other devs in Solidity communities in Telegram (also avoiding fall into Stagnant), I move this EIP to Last Call awaiting for an editor response.
Thanks!
=> Update EIP-5216: Move to Last Call

.github/workflows/ci.yml
=> CI: Add EIP-5757 to unchecked list

EIPS/eip-5750.md
=> Update EIP-5750: Change the specification to suit more use cases, fix grammar and some formatting

EIPS/eip-5615.md
=> Update EIP-5615: Add short note about the function naming

EIPS/eip-2335.md
=> Update EIP-2335: Remove superfluous use of "verifies"

EIPS/eip-5507.md
=> Update EIP-5507: Add EIP-20 support

EIPS/eip-5732.md
=> Update EIP-5732: include @fulldecent's change

EIPS/eip-5679.md
=> Update EIP-5679: Fix ERC165 identifiers 

EIPS/eip-5000.md
I know there are a lot of contentious things about EIP-5000, but this particular error is horrifically egregious!
(/s, but the external link does need to be fixed)
=> Update EIP-5000: Fix external link

README.md
Makes a few changes (notably adding review & last call as incomplete stages) to the README.
=> Update README: Clarify incomplete draft behaviour

EIPS/eip-5202.md
=> Update EIP-5202: Move to review

config/.markdownlint.yaml
MD009 is buggy and triggers on newlines
=> Configuration: Fix Markdownlint configuration

EIPS/eip-5023.md
Update to interface hash id comment.
Update to function syntax on interface.
Updated the Draft status to Review.
=> Update EIP-5023: Move to Review, minor corrections to interface

EIPS/eip-1.md
If we're okay with this format, I'll update `eipw` and get the csl-json to render into a human readable citation.
=> Update EIP-1: Add first two external origins

EIPS/eip-5750.md
=> Move EIP-5750 to Final

EIPS/eip-5489.md
=> Update EIP-5489: Move to Last Call

EIPS/eip-4844.md
Add Ansgar Dietrichs (@adietrichs) as co-author to EIP-4844. Thank you for all your spec contributions to the fee-market design, precompile output and more!
=> EIP-4844: Add adietrichs as co-author

EIPS/eip-3540.md, EIPS/eip-4200.md
=> Add "EOF - " prefix to 3540, 4200

EIPS/eip-4987.md, assets/eip-4987/Consumer.sol
Changes
- more detailed revert specification
- harden example implementation
- add chained ownership lookup snippet
- misc cleanup
=> EIP-4987 hardening/cleanup

EIPS/eip-4987.md
direct links to important assets in the example implementation
=> EIP-4987: asset links

_layouts/eip.html
=> Configuration: Fix MathJax config

EIPS/eip-5753.md, EIPS/eip-draft_lockable_nft.md
Lockable EIP-721 tokens for better UX in DeFi.
=> Add EIP-5753: Lockable Extension for EIP-721

EIPS/eip-4527.md
Update some mirror change to the EIP and move it into review
=> Update EIP-4527: Move to draft

EIPS/eip-4527.md
=> Update EIP-4527: Move to review

EIPS/eip-6049.md, EIPS/eip-x-deprecate-selfdestruct.md
=> Add EIP-6049: Deprecate SELFDESTRUCT

EIPS/eip-5585.md
=> Introduce the getRights() interface;

EIPS/eip-5773.md
As the peer reviewer has been assigned to the EIP-5773 and is actively reviewing the proposal, the proposal is being upgraded to `Review` status.
=> Upgrade EIP-5773 to Review status

EIPS/eip-6049.md
At this point we are getting good discussion at https://ethereum-magicians.org/t/deprecate-selfdestruct/11907
Effectively this has already been in review. Just updating the status here.
=> Update EIP-6049: Move to review

EIPS/eip-5570.md
This allows for multiple sales taxes for jurisdictions such as the US.
=> Allows for multiple sales taxes

EIPS/eip-5247.md, assets/eip-5247/ProposalRegistry.sol, assets/eip-5247/testProposalRegistry.ts
=> Update EIP-5247 add assets

.github/workflows/ci.yml
Grabs https://github.com/ethereum/eipw/pull/56.
=> Pickup latest eipw version

.github/workflows/ci.yml
This reverts commit b4db14cf02d820f7bf417d2d1d0043573106d4d4.
=> Revert "Pickup latest eipw version (#6091)"

EIPS/eip-5023.md
=> Added security considerations and backwards compatibility texts for EIP-5023

EIPS/eip-5192.md
=> Update EIP-5192: Fix typo

EIPS/eip-5023.md
=> Update EIP-5023: Move to last call

EIPS/eip-4938.md
This PR was falsely moved to stagnant, move to last call instead
=> EIP-4938: Move to back to draft

EIPS/eip-5489.md
=> Update EIP-5489: Move to final

EIPS/eip-5757.md
Last call period ended on 16 Nov and we merged #5874 last week. I think this is good to go!
=> Update EIP-5757: Move to final

EIPS/eip-6093.md
=> Update EIP-6093: Fix typos

EIPS/eip-5615.md
=> Update EIP-5615: Change totalSupply behavior when exists is false

EIPS/eip-5219.md
=> Update EIP-5219: Fix small typo

EIPS/eip-5219.md, EIPS/eip-5507.md
=> Merge master into eip-5219-review

EIPS/eip-5380.md
=> Update EIP-5380: First update

EIPS/eip-6110.md
Initial draft of proposal to supply validator deposits on chain. This proposal allows for improving security and UX of validator deposits flow.
cc @djrtwo
=> Add EIP-6110: Supply validator deposits on chain

EIPS/eip-5507.md
=> Update EIP-5507: Fix typo (wei is a reserved name)

EIPS/eip-5115.md
Title rename, interface, and definition updates based on community feedback.
=> Update EIP-5115: Updates to interface based on community feedback

EIPS/eip-5568.md
=> Update EIP-5568: Move to review

EIPS/eip-5219.md, EIPS/eip-5507.md
This EIP is ready to be moved to review
=> Update EIP-5219: Move to review

EIPS/eip-6059.md
Yes, it's ugly. Yes, it's required to get the formatting you desire.
=> Update EIP-6059: Fix multi-line list elements

EIPS/eip-5630.md
additional line was wanted by the linter. fixed comment
=> EIP-5630: small additional fixes.

EIPS/eip-4337.md
=> EIP-4337 - AA-100: Change bundling rules to prevent any cross-op access

EIPS/eip-4337.md
=> EIP-4337 AA-99 account returns validAfter,validUntil

EIPS/eip-4337.md
=> update unstaked entity rules

EIPS/eip-5023.md
=> Update from last call to final

EIPS/eip-6059.md
As the EIP-6059 is ready for peer review, we are upgrading it to `Review` status to request it.
=> Update EIP-6059: Move to Review

EIPS/eip-5982.md, EIPS/eip-acl.md
=> Add EIP-5982: Role-based Access Control

EIPS/eip-5573.md
=> minor typos on EIP 5573

EIPS/eip-5630.md
=> another update to EIP-5630: only do ECDH

EIPS/eip-5630.md
=> very small follow-up edits to EIP-5630

EIPS/eip-6120.md
Add contents to the following sections:
* Motivation
* Backwards Compatibility
* Security Considerations
Update Specification and Reference Implementation to add token-transfer sub-action feature.
=> Update EIP-6120: more contents and token-transfer sub-action

EIPS/eip-5630.md
=> Added coauthor to EIP-5630 per discussion

EIPS/eip-1459.md
Let's get this started on the finalization train! It's been in production for a long time.
=> Update EIP-1459: unstagnate and add security consideration

EIPS/eip-2771.md
=> Update EIP-2771: Fix markdownlint issues

.github/workflows/auto-review-bot.yml
Was accidentally copy/pasted into the file when it shouldn't have been.
=> Update CI: Fix EIP bot sometimes not triggering

EIPS/eip-5507.md
=> Update EIP-5507: Fix file names

EIPS/eip-5507.md
=> Update EIP-5507: Final changes before last call

.github/workflows/auto-review-trigger.yml
The brute force method of bug squashing
=> CI: Make @eth-bot run on every PR action

EIPS/eip-4834.md
=> Update EIP-4834: Remove old links

EIPS/eip-2771.md
=> Update eip-2771.md: isTrustedForwarder gas limit

EIPS/eip-5568.md
Thanks @MicahZoltu for the suggestions!
Link to discussion: https://discord.com/channels/966361524547489873/966377683825094727/1061081115647021177 (on Ethereum Wallets discord)
=> Update EIP-5568: Micah's review

EIPS/eip-5920.md
=> Update EIP-5920: Prepare for Review

EIPS/eip-5920.md
=> Update EIP-5920: Update abstract

EIPS/eip-6188.md
=> Update EIP-6188: Fix minor typo

EIPS/eip-5267.md
Following suggestions from the discussions thread.
=> EIP-5267: Clarify use of extensions and add event

EIPS/eip-5630.md
=> more minor changes to 5630

EIPS/eip-5920.md
I would like to move this to review so it can be considered for future hard forks.
=> Update EIP-5920: Move to Review

.vscode/settings.json, EIPS/eip-5269.md
=> Update EIP-5269 EIP/ERC Detection and Discovery

EIPS/eip-6150.md, assets/eip-6150/contracts/ERC6150.sol, assets/eip-6150/contracts/ERC6150AccessControl.sol, assets/eip-6150/contracts/ERC6150Burnable.sol, assets/eip-6150/contracts/ERC6150Enumerable.sol, assets/eip-6150/contracts/ERC6150ParentTransferable.sol, assets/eip-6150/contracts/interfaces/IERC6150.sol, assets/eip-6150/contracts/interfaces/IERC6150AccessControl.sol, assets/eip-6150/contracts/interfaces/IERC6150Burnable.sol, assets/eip-6150/contracts/interfaces/IERC6150Enumerable.sol, assets/eip-6150/contracts/interfaces/IERC6150ParentTransferable.sol
=> Update EIP-6150: Optimize and add more implementation

EIPS/eip-6190.md
=> Update EIP-6190: Rename to verkle-compatible SELFDESTRUCT

EIPS/eip-5269.md, assets/eip-5269/contracts/ERC5269.sol, assets/eip-5269/contracts/IERC5269.sol, assets/eip-5269/contracts/testing/ERC721ForTesting.sol, assets/eip-5269/test/TestERC5269.ts
=> Add asset file for EIP-5269

EIPS/eip-5920.md
=> Update EIP-5920: Gas cost update and burning via zero address

EIPS/eip-6189.md
=> Update EIP-6189: Add support for EIP-5920

EIPS/eip-5269.md
=> Update EIP-5269: Move to Review

EIPS/eip-6224.md, EIPS/eip-xxxx.md
The EIP standardizes the management of smart contracts within the decentralized application ecosystem. It enables protocols to become upgradeable and reduces their maintenance threshold. This EIP additionally introduces a smart contract dependency injection mechanism to audit dependency usage, to aid larger composite projects.
=> Add EIP-6224: Contracts Dependencies Registry

EIPS/eip-5920.md
=> Update EIP-5920: Reduce account creation gas

EIPS/eip-6190.md
Although this was based on his proposal, I haven't checked whether or not he's okay with being listed.
CC @axic on whether or not you want authorship.
=> Update EIP-6190: Remove axic as an author

EIPS/eip-2135.md
=> Update EIP-2135: Move to Last Call

EIPS/eip-5982.md
=> Update EIP-5982: Move to Review

EIPS/eip-5604.md
=> Update EIP-5604: Move to Review

EIPS/eip-5805.md
=> Update to EIP-5805 

EIPS/eip-5298.md
=> Update EIP-5298: Move to Review

EIPS/eip-6150.md
Moving EIP-6150 to last call after adding demo implementation for default and optional interfaces.
=> Update EIP-6150: Move to Last Call

EIPS/eip-1898.md
* change status to Review
* remove dependency on EIP-1474
* add safe, finalized strings as options for block param
=> Update EIP-1898: Move to Review

README.md
The existing introduction is somewhat scattered and not easily understandable. This reorders some paragraphs and adds additional information that may be useful.
=> Update README: Add friendlier introduction

EIPS/eip-5805.md
=> Update EIP-5085: Fix typos

EIPS/eip-6220.md
The proposal is ready to move into Review stage, so we are marking it as such.
=> EIP-6220: Update status to Review

EIPS/eip-6384.md
=> added email address

EIPS/eip-6049.md
=> learn how to spell

EIPS/eip-2315.md
=> This proposal has been superceded by the EOF proposals.

EIPS/eip-5289.md
Moving to review to get a little more visibility
=> Update EIP-5289: Move to Review

EIPS/eip-4955.md
=> Update ERC-4955: Move to Final

EIPS/eip-6170.md
- Added an extra param called `data` in send message function which includes bridge-specific encoded params.
- Added unified events.
=> Update: relayer data + events added

EIPS/eip-6170.md
=> Fix: Typo fixes in EIP-6170

EIPS/eip-6150.md, assets/eip-6150/contracts/ERC6150.sol, assets/eip-6150/contracts/ERC6150AccessControl.sol, assets/eip-6150/contracts/ERC6150Burnable.sol, assets/eip-6150/contracts/ERC6150Enumerable.sol, assets/eip-6150/contracts/ERC6150ParentTransferable.sol
=> Update EIP-6150: update implementation

EIPS/eip-6188.md
This is a simple enough EIP. Let's move it to Review.
=> Update EIP-6188: Move to Review

EIPS/eip-4938.md
Change status to `Review`
On the suggestion of @MariusVanDerWijden creating this PR to move the proposal to `Review` status.
=> Update EIP-4938: Move to Review

EIPS/eip-4844.md
This PR updates the EIP to reflect the review status: the EIP is complete, targeted for EIP-4844 devnet-v3, and will be adjusted based on further external review and testnet results. Maybe long overdue, it's exactly 270 days (9 months) since the PR was first created, and a lot of progress has been made!
=> Update EIP-4844: update to Review status

EIPS/eip-2255.md
Will need review from either Dan Finlay (@danfinlay) or Erik Marks (@rekmarks)
Some more changes are necessary, but this is a reminder to self to do it.
=> Update EIP-2255: Add myself as an author and move back to review

EIPS/eip-5625.md
EIP-5625 is ready to move to Review stage.
BTW, the dStorage NFT metadata extension proposed by this EIP, is already supported by some products like W3Bucket. Here are some links for reference:
DAPP:  https://cloud3.cc/#/buckets
Documentation: https://docs.cloud3.cc/w3bucket/nftmetadata
Also as a real example, metadata URI of token 1000010 (https://opensea.io/assets/ethereum/0x587ad7a26c5acae69d683fe923fd3f5b0700f3ef/1000010) is: https://ipfs.io/ipfs/QmaErntVy9NUZBvZFRxvyrrvjFVSxvPkhoZ2z4h4dmjrVB :
```json
{
"name": "W3BKT (10 GB, syc6x3, 0)",
"image": "ipfs://QmSt7vra39Jk22kQxFACU89oSy6Txwwneu28YjR9pGjP47",
"dStorage": {
"platform": "Crust",
"consensus": "gpos",
"description": "Crust Network, the Incentive Layer of IPFS",
"dstorage_note": …
```
=> Update EIP-5625: Move to Review

.github/workflows/auto-review-trigger.yml
=> CI: Fix minor re-trigger bug

EIPS/eip-2255.md
=> Update EIP-2255: Make a few minor grammatical fixes

README.md
We're using eip-review-bot now!
=> Update README: Reference correct bot

EIPS/eip-6404.md
=> EIP-6404: Use `CHAIN_ID_LEGACY` instead of `tx_subtype`

EIPS/eip-1.md
=> Add myself to EIP-1 list

_layouts/eip.html
=> Fix jekyll build warnings

EIPS/eip-6475.md, assets/eip-6475/optional.py, assets/eip-6475/tests.py
=> Update EIP-6475: Add tests and implementation

EIPS/eip-998.md
Per author @mudgen approval, reviving ERC-998 and adding new author to drive the procedure.
=> Revive ERC-998

EIPS/eip-5069.md
Makes it a lot more readable and updates the files to use the new eip-review-bot config file.
=> Update EIP-5069: Minor changes & eip-review-bot update

config/eip-editors.yml
Add g11tech to core eip editors list
=> Config: Add g11tech to core eip editors list

EIPS/eip-747.md
Will need approval from one of Dan Finlay (@danfinlay) or Esteban Mino (@estebanmino)
More changes will likely be needed to bring this up to EIP-1
=> Update EIP-747: Add myself as an author and move back to Review

EIPS/eip-6404.md, EIPS/eip-6465.md, EIPS/eip-6466.md
=> Update EIP-6465/6466/6404: Mention correct type for LC use case

EIPS/eip-6381.md, assets/eip-6381/test/emotable.ts
A method name had changed it became outdated.
=> Updates interface Id for EIP6381

.github/workflows/ci.yml
Additional help links, and a few closed issues.
=> Pickup latest `eipw`

EIPS/eip-3770.md
Moving chain-specific addresses PR to Review. This becomes more critical with the account abstraction topic becoming more popular.
=> Update EIP-3770: Move to Review

EIPS/eip-1.md
=>  Update EIP-1: Add name to EIP Editors

EIPS/eip-5773.md
=> Update EIP-5773: Fix a typo

EIPS/eip-6381.md
=> Update 6381: Fix a typo

EIPS/eip-6454.md
=> Update 6454: Fix typos in the EIP-6454

EIPS/eip-6454.md
EIP-6454 is ready to be peer reviewed, so we are proposing it be moved to Review status.
=> Update 6454: Upgrade EIP-6454 to review status

EIPS/eip-6315.md, EIPS/eip-template.md
Uses EIP-2771 for account abstraction
=> Add EIP-6315: EIP-2771 Account Abstraction

EIPS/eip-5727.md
=> Update EIP-5727: update compatibility

EIPS/eip-5773.md, assets/eip-5773/contracts/IMultiAsset.sol, assets/eip-5773/contracts/MultiAssetToken.sol, assets/eip-5773/contracts/library/MultiAssetLib.sol, assets/eip-5773/contracts/mocks/MultiAssetTokenMock.sol, assets/eip-5773/contracts/utils/MultiAssetRenderUtils.sol, assets/eip-5773/hardhat.config.ts, assets/eip-5773/test/multiasset.ts, assets/eip-5773/test/renderUtils.ts
It can now receive multiple token IDs.
Also runs prettier on code.
=> Eip 5773 event improvement

EIPS/eip-6220.md, assets/eip-6220/contracts/EquippableToken.sol, assets/eip-6220/contracts/IERC5773.sol, assets/eip-6220/hardhat.config.ts, assets/eip-6220/test/catalog.ts, assets/eip-6220/test/equippableFixedParts.ts, assets/eip-6220/test/equippableSlotParts.ts, assets/eip-6220/test/multiasset.ts, assets/eip-6220/test/nestable.ts, assets/eip-6220/test/renderUtils.ts
Also updates readme with references from EIP-721 to ERC-721.
Runs prettier on code.
=> Updates event from ERC5573

EIPS/eip-5902.md
Fixed typos in specification document
=> Update EIP-5902: Smart Contract Event Hooks

EIPS/eip-5585.md
Remove staking functions and change the EIP status to Review.
=> Update EIP-5585: Remove staking functions and move to Review

EIPS/eip-6357.md, EIPS/eip-multicall.md
It's remarkable what you can find in OpenZeppelin that should really be standardized.
=> Add EIP-6357: Single-contract Multi-delegatecall

EIPS/eip-4804.md
=> Update EIP-4804: Move to Last Call

.github/workflows/auto-review-trigger.yml
Runs CI even when the review is a changes requested one.
CC @SamWilsn
=> CI: Fix w-response labeling issue

EIPS/eip-6170.md
=> Update: Interface upgrade

EIPS/eip-6066.md
=> Update EIP-6066: Move to Review

EIPS/eip-4804.md
=> Update EIP-4804: Move to final

EIPS/eip-1.md
Example:
```yaml
author: Random J. User (@username) <address@dom.ain>
```
=> Update EIP-1: Add option to use GitHub username and email at once

EIPS/eip-6551.md
=> Update ERC-6551: Reference implementation bugfixes + deployment transaction

EIPS/eip-6551.md
=> ERC-6551: Added event emission to reference implementation

EIPS/eip-5570.md
=> Adds Contract and Serial Number field to the schema

EIPS/eip-6147.md
=> Update EIP-6147: Move to Final

EIPS/eip-223.md
=> Update EIP-223: remove extra code from the example

EIPS/eip-6059.md, assets/eip-6059/contracts/IERC6059.sol, assets/eip-6059/contracts/NestableToken.sol, assets/eip-6059/package.json, assets/eip-6059/test/nestable.ts
The interface was renamed to IERC5773 and the MultiAssetToken contract was updated to use the new interface.
=> Update EIP-6059 interface

EIPS/eip-5773.md
As the discussion on the EIP-5773 seems to have been concluded, we are proposing to upgrade the EIP to Last Call.
=> Update ERC-5773: Move to Last Call

EIPS/eip-4944.md
=> Change status to draft

EIPS/eip-6105.md
=> Update eip-6105: Move to Review

EIPS/eip-5827.md, assets/eip-5827/ERC5827.sol, assets/eip-5827/IERC5827.sol
=> Update EIP-5827: add implementation

EIPS/eip-5252.md
=> set EIP-5252 into review

EIPS/eip-4910.md
=> Updating EIP-4910 Status to Last Call

EIPS/eip-6617.md
Fix solidity code to correctly define constants
=> EIP-6617: Fix solidity constant code

EIPS/eip-6366.md, assets/eip-6366/contracts/EIP6366Core.sol, assets/eip-6366/contracts/EIP6366Meta.sol, assets/eip-6366/contracts/interfaces/IEIP6366Core.sol, assets/eip-6366/contracts/interfaces/IEIP6366Meta.sol, assets/eip-6366/example/APermissionToken.sol, assets/eip-6366/example/APermissioned.sol
This a draft pull request, we will link to #6617 after a EIP number was assigned to **Bit Based Permission**.
=> Update the EIP-6366

EIPS/eip-4337.md
=> Audit-related changes (23-Feb-2023)

EIPS/eip-4337.md
=>   missing type update.

EIPS/eip-5485.md
=> EIP-5485 Move from Stagnant to Draft

assets/eip-6123/contracts/SDC.sol
- Store initial settlement data during trade inception
=> Improve trade inception in EIP-6123

config/.jekyll-labels.yml
It's handled by eip-review-bot now :)
=> Config: Remove e-number label

EIPS/eip-6780.md
=> Add EIP: SELFDESTRUCT only in same transaction

EIPS/eip-6358.md
=> Update EIP-6358: Move to Review

.github/workflows/auto-review-bot.yml
eip-review-bot now does it on it's own :D
=> CI: Remove redundant approve and auto merge actions

EIPS/eip-6059.md
This PR extends the security considerations section of ERC-6059. In addition to this it includes some minor typo fixes.
=> Update EIP-6059: Update ERC-6059 to extend the security considerations

EIPS/eip-6551.md
=> Update EIP-6551: Add missing EIP-1271 signature validation to reference implementation

EIPS/eip-6059.md
Security consideration section of the ERC-6059 was extended to be easier to understand.
=> Update EIP-6059: Update  security considerations

EIPS/eip-5006.md
=> Update EIP-5006: Move to Final

EIPS/eip-6220.md
As the debate on the EIP has been concluded, we are moving the EIP to Last Call.
=> Update EIP-6220: Move to Last Call

EIPS/eip-6105.md
=> Update EIP-6105: Move to Last Call

EIPS/eip-5639.md
=> Update EIP-5639: Move to Review

EIPS/eip-6357.md
=> Update EIP-6357: Move to Review

EIPS/eip-3525.md
1. One of the author (Will Wang) had changed his github account from will-edge to will42w
2. One of the author (Ethan Tsai) would like to use Chinese name and also add an email address
Sorry if there are any inconvenience caused.
=> Update EIP-3525: Revise information of some authors as well as modify the naming rules when referencing ERCs

EIPS/eip-1.md
Update EIP-1 to reflect policy decision documented in https://github.com/ethereum/EIPs/issues/6129#issuecomment-1494330848 and decided in https://github.com/ethereum-cat-herders/EIPIP/issues/198#issue-1490719895
=> Update EIP-1: Update EIP-1 to include wording about The Finalizing Pull Request

EIPS/eip-5773.md
The Metadata specification of EIP-5773 has been updated. Since this is an optional part of the specification, this shouldn't impact the proposal's progression to Final.
=> Update EIP-5773: Update EIP-5773s optional metadata specification

EIPS/eip-6059.md, assets/eip-6059/contracts/IERC6059.sol, assets/eip-6059/contracts/NestableToken.sol
The Metadata specification of EIP-5773 has been updated. Since this is an optional part of the specification, this shouldn't impact the proposal's progression to Final.
=> Update EIP-6059: Update EIP-6059 to optimize interface size

EIPS/eip-6381.md
The address of the EIP-6381 repository for Göerli, Sepolia, Mumbai and MoonbaseAlpha has been added.
=> Update EIP-6381: Add testnet address

EIPS/eip-3855.md
This PR is to promote EIP-3855 to `Last Call`.
=> Update EIP-3855: Move to Last Call

EIPS/eip-4895.md
This PR promotes EIP-4895 to `Last Call`
cc: @ralexstokes @djrtwo
=> Update EIP-4895: Move to Last Call

EIPS/eip-6551.md
=> Update EIP-6551: Modified proxy implementation, registry arguments, and deployment method

EIPS/eip-6551.md
=> Update EIP-6551: Update registry address to match deployment

EIPS/eip-4788.md
No substantive change. a few minor nits from the recent 4788 PR
=> Update EIP-4788: minor nits for 4788

EIPS/eip-5000.md
=> Update EIP-5000: typo

EIPS/eip-5773.md
As no issues arose during the last call period and since the deadline to move this proposal to final has passed, we are proposing to upgrade it to Final.
=> Update EIP-5773: Move to Final

EIPS/eip-6059.md
As no issues arose during the last call period and since the deadline to move this proposal to final has passed, we are proposing to upgrade it to Final.
=> Update EIP-6059: Move to Final

assets/eip-3267/contracts/BaseLock.sol, assets/eip-3267/contracts/BidOnAddresses.sol
Fixes Typo: 'contact' -> 'contract'
=> Update EIP-3267: Fixes typo

EIPS/eip-5008.md
EIP-5008: Change status from Stagnant to Review
=> Update EIP-5008: Move to Review

EIPS/eip-5164.md
Removed the Batch messaging and instead refactored SingleMessageDispatcher to MessageDispatcher as core part of EIP
=> Update EIP-5164: Updated EIP-5164 and simplified by removing batch

EIPS/eip-6220.md
As there have been no issues raised during the final call period and the final call deadline was reached, we are proposing the EIP-6220 be moved to Final.
=> Update EIP-6220: Move to Final

EIPS/eip-6381.md
As there have been no issues raised for the proposal for a while we propose to move it to Last Call.
=> Update EIP-6381: Move to Last Call

EIPS/eip-1185.md
Move 1185 back to draft, this has been used in real-world implementations so should be moved through the process to final.
=> Update EIP-1185: Move to Draft

EIPS/eip-3860.md
=> Update EIP-3860: Move to Final

EIPS/eip-4895.md
=> Update EIP-4895: Move to Final

EIPS/eip-3855.md
=> Update EIP-3855: Move to Final

EIPS/eip-5639.md, EIPS/eip-6551.md
update eip-5639 and eip-6551 author info. Fix typo in eip-6551
=> Update EIP-5639: update eip-5639 and eip-6551 author info. Fix typo in eip-6551

EIPS/eip-3651.md
=> Update EIP-3651: Move to Final

EIPS/eip-5007.md, assets/eip-5007/README.md, assets/eip-5007/contracts/ERC5007Composable.sol, assets/eip-5007/contracts/ERC5007ComposableTest.sol, assets/eip-5007/contracts/IERC5007Composable.sol, assets/eip-5007/test/test.js
EIP-5007:  update ERC5007Composable.sol , when split an old NFT, burn the old NFT and mint two new NFTs to avoid dynamic NFTs problem.
=> Update EIP-5007: update ERC5007Composable.sol

EIPS/eip-5656.md
=> Update EIP-5656: Fix typos

EIPS/eip-6551.md
=> Update EIP-6551: Returned to using ERC-1167 proxies for account creation

EIPS/eip-5564.md
Updating the metadata description and fixing a bunch of spelling/grammar mistakes.
=> Update EIP-5564: add metadata description to eip-5564

EIPS/eip-6120.md
=> Update EIP-6120: update desc and abstract

EIPS/eip-5007.md, assets/eip-5007/contracts/ERC5007.sol, assets/eip-5007/contracts/ERC5007Composable.sol, assets/eip-5007/contracts/ERC5007ComposableTest.sol, assets/eip-5007/contracts/ERC5007Demo.sol, assets/eip-5007/contracts/IERC5007.sol, assets/eip-5007/contracts/IERC5007Composable.sol, assets/eip-5007/test/test.js
Update EIP-5007: change int64 to uint64
=> Update EIP-5007: change int64 to uint64

EIPS/eip-5008.md
=> Update EIP-5008: Move to Last Call

EIPS/eip-6454.md
A note about the possibility to validate whether an initiator can transfer the token using the ERC-6454 interface has been added to the proposal.
=> Update EIP-6454: Update EIP-6454 with note about approvals

EIPS/eip-4788.md
=> Update EIP-4788: Fix typo

EIPS/eip-2015.md
Needs review from either Pedro Gomes (@pedrouid) or Erik Marks (@rekmarks).
There are also a few more changes I will need to make, particularly formatting/grammar-wise
=> Update EIP-2015: Move to Review

.github/workflows/ci.yml
This fixes the csl-json problem in #6963
=> CI: Bump eipw to 0.4.6

EIPS/eip-107.md
I was wondering why my vitepress builds were failing...
=> Update EIP-107: Use standardized markdown formatting

EIPS/eip-6551.md
=> Update EIP-6551: Removed accidentally included SPDX license identifier

EIPS/eip-4955.md
=> Update EIP-4955: Update eip-4955.md

EIPS/eip-4844.md
=> Update EIP-4844: Update eip-4844.md, fix typo

EIPS/eip-5202.md
=> Update EIP-5202: Move to Last Call

EIPS/eip-6913.md
0x49 is being used by BLOBHASH
Change opcode to 0xfc
=> Update EIP-6913: Setcode Opcode to 0xfc

EIPS/eip-6454.md
As the final call has been reached and no further comments have been made, this commit updates EIP6454 to Final.
=> Update EIP-6454: Move to Final

EIPS/eip-5007.md
=> Update EIP-5007: Move to Final

EIPS/eip-6122.md
needed by https://github.com/ethereum/EIPs/pull/7073#issuecomment-1563565999
cc @timbeiko
=> Update EIP-6122: Move to Review

EIPS/eip-6981.md
=> Update EIP-6981: Update Account Instance Signatures section

EIPS/eip-5169.md
Update EIP-5169: Move to Final
=> Update EIP-5169: Move to Final

EIPS/eip-6963.md
* Provide motivation for the design of Events Interfaces
* Better showcase symmetry of events on both sides
=> Update EIP-6963: Update Window Events section

EIPS/eip-6381.md, assets/eip-6381/contracts/EmotableRepository.sol, assets/eip-6381/contracts/IERC6381.sol, assets/eip-6381/test/emotableRepository.ts
The proposal has been updated to include bulk emoting and retrieving of emote data.
Additionally, the ECDSA pre signed emote support was added.
=> Update EIP-6381: Add bulk actions and presigned emotes

EIPS/eip-6381.md
With the latest updates, the last call deadline needs to be reset.
=> Update EIP-6381: Set new last call deadline

EIPS/eip-6551.md
missing ";" at line : 
bytes memory code = _creationCode(implementation, chainId, tokenContract, tokenId, salt)
=> Update EIP-6551: Update eip-6551.md

EIPS/eip-5656.md
Update MCOPY to `(0x5E)` per https://hackmd.io/@shemnon/CancunOpcodeAllocation
=> Update EIP-5656: update eip-5656 MCOPY opcode per cancun allocation

EIPS/eip-6492.md
=> Update EIP-6492: Fix typo in eip-6492.md

EIPS/eip-2015.md
=> Update EIP-2015: Use sam's wording

EIPS/eip-6963.md
Reverts ethereum/EIPs#7165 (was meant to open draft)
=> Update EIP-6963: Revert "Update EIP-6963: Add walletId back into the design"

EIPS/eip-6900.md
- Clarify conflicting function signatures for user operation validators
- Fix step numbering and minor typos
- Update execution struct field names to reflect usage
=> Update EIP-6900: Spec corrections

EIPS/eip-6093.md
=> Update EIP-6093: Move to Last Call

EIPS/eip-6239.md
=> Update EIP-6239: Move to Review

EIPS/eip-6997.md
=> Update EIP-6997: Move to Review

EIPS/eip-1.md
=> Update EIP-1: Update EIP-1 to allow link to BIPs

EIPS/eip-4337.md
=> Update EIP-4337: Some ERC-4337 changes

EIPS/eip-3607.md
"self desctruct" -> "self destruct"
=> Update EIP-3607: Fix typo in eip-3607.md

EIPS/eip-6381.md
As the last call deadline has passed and there are no open discussions we propose EIP-6381 be moved to Final status.
=> Update EIP-6381: Move to Final

EIPS/eip-7201.md
As pointed out in https://github.com/ethereum/EIPs/pull/7287#pullrequestreview-1517298075
=> Update EIP-7201: Simplify Solidity reference implementation

EIPS/eip-4844.md
As discussed with @adietrichs this PR attempts to provide a clearer description for the 2 new header fields introduced in EIP-4844.
=> Update EIP-4844: Clarify header fields

EIPS/eip-4788.md
=> Update EIP-4788: explicitly specify header schema for 4788

EIPS/eip-3643.md
- move the EIP to review status
=> Update EIP-3643: Move to Review

EIPS/eip-5202.md
=> Update EIP-5202: Move to Final

EIPS/eip-6239.md
=> Update EIP-6239: Move to Final

EIPS/eip-5585.md
Add a new interface 'transferUserRights()
=> Update EIP-5585: Add a new interface 'transferUserRights()'

EIPS/eip-7044.md
EIP-7044 is included for Deneb hard-fork
=> Update EIP-7044: Move to Review

EIPS/eip-7329.md, EIPS/eip-split.md
An EIP giving motivation, rational, alternatives, and objections to the EIP/ERC split proposal.
=> Add EIP: ERC/EIP Repository split

EIPS/eip-7329.md
=> Update EIP-7329: update discussion-to, tweak words.

EIPS/eip-7329.md
Move EIP-7329 (EIP/ERC split) to last call
=> Update EIP-7329: Move to Last Call

EIPS/eip-223.md
=> Update EIP-223: description

EIPS/eip-7045.md
Slated for Dencun, so bumping status
=> Update EIP-7045: Move to Review

EIPS/eip-6968.md
=> Update EIP-6968: Update eip-6968.md

EIPS/eip-5806.md
=> Update EIP-5806: refactor motivations

EIPS/eip-4520.md
=> Update EIP-4520: The typo double-whammy!

EIPS/eip-777.md
=> Update EIP-777: Small fix - add end tag

EIPS/eip-1175.md
EIP-1 mandates relative paths. Also my build system doesn't like it.
=> Update EIP-1175: Fix absolute pathing

EIPS/eip-210.md
Sorry Vitalik, but that's not actually valid markdown.
=> Update EIP-210: Make it not crash my build system

EIPS/eip-2612.md
This PR is supported by the Æternity Crypto Foundation
=> Update EIP-2612: Make consistent indents in json

EIPS/eip-3156.md
Small fix to my github handle in the EIP
=> Update EIP-3156: github handle

EIPS/eip-7377.md
Fixed small typo in tx definition.
=> Update EIP-7377: fix typo

EIPS/eip-223.md
=> Update EIP-223: Update eip-223.md

EIPS/eip-2135.md
=> Update EIP-2135: Fix errors from EIPWalidator

EIPS/eip-223.md
=> Update EIP-223: Move to Review

EIPS/eip-2135.md
=> Update EIP-2135: Move to Final

EIPS/eip-7444.md, EIPS/tbd.md
Add EIP: Timelock Maturity markdown file
=> Add EIP: Time Locks Maturity

EIPS/eip-1271.md
Very minor spelling correction.
=> Update EIP-1271: Update eip-1271.md

EIPS/eip-6982.md
The interface has been used in a few projects and no issues came out from there. So we think it is time to move to review
=> Update EIP-6982: Move to Review

EIPS/eip-5793.md
Following the spec change here: https://github.com/ethereum/devp2p/commit/6b259a7003b4bfb18365ba690f4b00ba8a26393b
=> Update EIP-5793: update for change to types

EIPS/eip-223.md
=> Update EIP-223: Move to Last Call

EIPS/eip-6120.md
* Add @h4l as an author
* Clarification for duplicated input behavior.
* Add usage example for Allowance Adapter
=> Update EIP-6120: Update ERC-6120

EIPS/eip-1820.md
See also https://github.com/ethereum/EIPs/pull/7397
=> Update EIP-1820: Fix same tagging issue

EIPS/eip-7432.md
We already have enough comments on Eth Magicians, and maturity of the interface to request review from the broader ethereum community. Looking forward for feedback!
=> Update EIP-7432: Move to Review

EIPS/eip-7303.md
Modified name of functions short
=> Update EIP-7303: Update eip-7303.md

EIPS/eip-4788.md
addressing https://github.com/ethereum/EIPs/pull/7456#issuecomment-1693308271
thanks @yperbasis for catching this!
=> Update EIP-4788: 4788 cleanups

EIPS/eip-6120.md
add Native Token Transfer section
=> Update EIP-6120: add Native Token Transfer section

.github/renovate.json, .github/workflows/auto-stagnate-bot.yml
=> CI: Fix stagnant bot

EIPS/eip-5568.md
=> Update EIP-5568: Use interface

EIPS/eip-5791.md
=> Update EIP-5791: Update eip-5791.md (adding contributor)

EIPS/eip-6900.md
- Correct wording around parameter types
- Fix a comment on hook applicability
=> Update EIP-6900: Fix parameter types

EIPS/eip-5115.md
Update to conform with latest EIP validator rules.
=> Update EIP-5115: Update to conform to new EIP validator rules

EIPS/eip-7401.md
This proposal introduces the ability to assign attributes to NFTs in a public non-gated repository smart contract that is accessible at the same address in all of the networks. The repository smart contract is designed to be a common-good repository, meaning that it can be used by any ERC-721 or ERC-1155 compatible token.
=> Update EIP-7401: Restructure Superseed message

EIPS/eip-7401.md
As there is no open discussion on the EIP, we propose its upgrade to Last Call.
=> Update EIP-7401: Move to Last Call

EIPS/eip-7160.md
Changes EIP-7160 to `Review` status
=> Update EIP-7160: Move to Review

EIPS/eip-4883.md
=> Update EIP-4883: Update eip-4883.md to use onchain

EIPS/eip-223.md
=> Update EIP-223: Move to Final

EIPS/eip-7508.md
The EIP-7508 description has been updated in order to represent the proposal better.
=> Update EIP-7508: Refine description

EIPS/eip-7053.md
After the conversations with the community and the industrial experts, we propose to change this EIP from Review to Last Call.
=> Update EIP-7053: Move to Last Call

EIPS/eip-7512.md
Update author affiliation of ERC-7512
=> Update EIP-7512: Fix Author

EIPS/eip-2535.md
=> Update EIP-2535: Fixed typo

EIPS/eip-7231.md
=> Update EIP-7231: Move to Review

EIPS/eip-7432.md
=> Update EIP-7432: Move to Last Call

EIPS/eip-5247.md
=> Update EIP-5247: Move to Review

EIPS/eip-5453.md
=> Update EIP-5453: Move to Last Call

EIPS/eip-4337.md
=> Update EIP-4337: Update eip-4337.md

EIPS/eip-6170.md
=> Update EIP-6170: Update eip-6170.md

EIPS/eip-7514.md
- Update constant value as decided in https://github.com/ethereum/pm/issues/857
=> Update EIP-7514: Update eip-7514.md

EIPS/eip-7514.md
Align EIP variable names to https://github.com/ethereum/consensus-specs/pull/3499
=> Update EIP-7514: Update eip-7514 constant name

EIPS/eip-3091.md
Polish and Resurrect EIP3091
This EIP is used and did a good job aligning block explorers to use the same routes - it should not be stagnant but move to Final finally.
=> Update EIP-3091: Move to Draft

EIPS/eip-7508.md, assets/eip-7508/contracts/AttributesRepository.sol
Added the repository's address to the specification.
Additionally, the parameters have been named in the example implementation to make it easier to understand.
=> Update EIP-7508: Add repository address

EIPS/eip-7401.md
Added the repository's address to the specification.
Additionally, the parameters have been named in the example implementation to make it easier to understand.
=> Update EIP-7401: Move to Final

EIPS/eip-7329.md
No substantive changes were made or requested, all changes from last call were minor to stylistic.
=> Update EIP-7329: Move to Final

EIPS/eip-7514.md
=> Update EIP-7514: Move to Review

EIPS/eip-1191.md
=> Update EIP-1191: Fix Implementation Table

EIPS/eip-6120.md
Changes:
* add the singleton deployed address
* add Payment Lifetime section
* add audit information
=> Update EIP-6120: update

EIPS/eip-663.md
Update opcodes according to https://github.com/ethereum/execution-specs/blob/master/lists/evm/pending-opcodes.md.
=> Update EIP-663: Update opcodes for SWAPN and DUPN

EIPS/eip-6963.md
This is based on discussion of the security considerations of wallets tampering with the window.ethereum properties and what the tradeoffs are for these mitigations.
=> Update EIP-6963: updates for object.freeze and other recommendations

EIPS/eip-7085.md
update EIP-7085
according to https://ethereum-magicians.org/t/introducing-new-eip-nft-relationship-enhancement/14468/2
=> Update EIP-7085: update EIP-7085

EIPS/eip-7542.md, EIPS/eip-????.md
Relevant outcomes from the p2p meeting discussing this EIP draft can be found here:
https://github.com/ethereum/pm/issues/858#issuecomment-1708403774
=> Add EIP: eth/69 - available-blocks-extended protocol

EIPS/eip-5564.md
The Review stage may signal:
* As the ERC requires an audited singleton contract, the the start of working on that
* Related stuff concerning adoption
* UX improvements
=> Update EIP-5564: Move to Review

README.md
Add some info about the split to the readme.
=> Update README: add notice about repo split in readme

EIPS/eip-7480.md
=> Update EIP-7480: fix typo

config/eip-editors.yml
Add g11tech (myself) to governance group
=> Config: Add g11tech to governance group

EIPS/eip-4788.md
=> Update EIP-4788: Move to Review

EIPS/eip-7549.md
Still an early stage EIP, merged directly as review by mistake. Thanks @poojaranjan for the notice
=> Update EIP-7549: Move to Draft

EIPS/eip-4844.md
- Use consensus constant
- Mention specific blob retention window
=> Update EIP-4844: Clarify blob retention window part

EIPS/eip-6122.md
cc: @MariusVanDerWijden, this is blocking https://github.com/ethereum/EIPs/pull/8000
=> Update EIP-6122: Move to Last Call

EIPS/eip-6780.md
cc: @dankrad @gballet, this removes the reference to EIP-6046, which was blocking the status change in https://github.com/ethereum/EIPs/pull/7451
=> Update EIP-6780: Move to Review

EIPS/eip-6475.md
update text: ideomatic -> idiomatic
=> Update EIP-6475: simple typo fix in 6475

EIPS/eip-3074.md
=> Update EIP-3074: fix misaligned memory description

EIPS/eip-684.md
fix a typo: `attemted`->`attempted`
=> Update EIP-684: Fix typo

EIPS/eip-225.md
=> Update EIP-225: Update eip-225.md to fix typo "singer"

config/eip-editors.yml
I haven't been active recently. I'd still like to review proposals as they come in, but I haven't been able to meet obligations for governing recently. If I can find the time, I'll request to be added back.
CC @lightclient @axic @gcolvin @SamWilsn @g11tech @xinbenlv
=> Config: Remove myself as governing editor

EIPS/eip-7002.md
fix storage slots, fix parentheses, SLOAD -> sload
=> Update EIP-7002: Fix typos

EIPS/eip-5806.md
=> Update EIP-5806: Update EIP-5806

EIPS/eip-5806.md
=> Update EIP-5806: use TX_TYPE for signature generation

EIPS/eip-7514.md
Dencun is going live on testnets!
=> Update EIP-7514: Move to Last Call

EIPS/eip-6122.md
Blocking https://github.com/ethereum/EIPs/pull/8132, cc: @MariusVanDerWijden
=> Update EIP-6122: Move to Final

EIPS/eip-6953.md
=> Update EIP-6953: Move to Final

EIPS/eip-4788.md
=> Update EIP-4788: Move to Last Call

EIPS/eip-4938.md
@MariusVanDerWijden it keeps going
=> Update EIP-4938: Move to Last Call

EIPS/eip-5793.md
cc: @MariusVanDerWijden blocking https://github.com/ethereum/EIPs/pull/8146
=> Update EIP-5793: Move to Last Call

EIPS/eip-4844.md
EIP-4844 is about to be implemented in Dencun and should therefore be moved to Last Call.
=> Update EIP-4844: Move to Last Call

EIPS/eip-7251.md
Fix COMPOUNDING_WITHDRAWAL_PREFIX typo
=> Update EIP-7251: Fix typo EIP-7251 typo

EIPS/eip-7044.md
=> Update EIP-7044: Move to Last Call

EIPS/eip-7045.md
Move EIP 7045 to last call in preparation for the dencun upgrade
=> Update EIP-7045: Move to Last Call

EIPS/eip-5656.md
5656 is part of Dencun, which is going live.
=> Update EIP-5656: Move to Last Call

EIPS/eip-7569.md
Being deployed on testnets already!
=> Update EIP-7569: Move to Last Call

EIPS/eip-7039.md
=> Update EIP-7039: Update eip-7039.md

EIPS/eip-2070.md
See https://github.com/ethereum/EIPs/pull/8005#issuecomment-1845557812, cc: @axic
=> Update EIP-2070: Move to Withdrawn

EIPS/eip-7568.md
2070 is now `Withdrawn`, let's see if it works...!
=> Update EIP-7568: Mention 2070 in 7568

EIPS/eip-7607.md, EIPS/eip-osaka.md
On ACDE#180, we agreed to prioritize Verkle Trees for Osaka. This Meta EIP reflects this.
=> Add EIP: Hardfork Meta - Osaka

EIPS/eip-7600.md
We agreed to move 2537 from CFI to Included on ACDE#181
=> Update EIP-7600: Mark 2537 as Included

EIPS/eip-5806.md
=> Update EIP-5806: Add restriction to create2 and selfdestruct/deactivate

EIPS/eip-3540.md
A couple of changes cherry-picked from a bigger update at #8152
=> Update EIP-3540: Move to Review

EIPS/eip-4844.md
=> Update EIP-4844: Fix typo in EIP-4844

EIPS/eip-5806.md
This reverts commit 82621ec29c69bc408f7efd8bf81f9d876217eedc.
--
=> Update EIP-5806: Disable create2 following pushback

EIPS/eip-5920.md
This PR tries to make the gas costs more clear (and changes them as well.)
=> Update EIP-5920: change gas costs

EIPS/eip-2537.md
=> Update EIP-2537: Move to Review

EIPS/eip-2537.md
=> Update EIP-2537: Update eip-2537.md

EIPS/eip-7609.md
=> Update EIP-7609: reduce SLOPE coefficient in eip-7609

EIPS/eip-7623.md
* improve phrasing
* fix spelling mistakes
* remove create2 consideration
* add % of accounts affected
=> Update EIP-7623: Improve phrasing

EIPS/eip-3074.md
=> Update EIP-3074: typo

EIPS/eip-2537.md
* Add timestamp-based forking
* update precompile address range
=> Update EIP-2537: Update to reflect timestamp-based forking and tightly pack precompile address range

index.html
=> Website: Fixes ECH discord link

EIPS/eip-4788.md
=> Update EIP-4788: Move to Final

EIPS/eip-7377.md
Moving back to draft as it is still being considered for an upgrade.
=> Update EIP-7377: Move to Draft

EIPS/eip-7600.md
Decided on https://github.com/ethereum/pm/issues/987
=> Update EIP-7600: Add MaxEB + ILs

EIPS/eip-7609.md
update security considerations with reference points to sstore and existing tstore.
=> Update EIP-7609: update security considerations with reference points

EIPS/eip-7044.md, EIPS/eip-7514.md
Moves EIP-7514 to Final, links the test cases and adds security considerations.
=> Update EIP-7044: Move to Final

EIPS/eip-7569.md
Requires all Dencun EIPs to be Final
=> Update EIP-7569: Move to Final

EIPS/eip-7651.md
Replace the identity precompile with EVM code that has equivalent functionality.
=> Add EIP: EVM-ify the identity precompile

EIPS/eip-7667.md
=> Update EIP-7667: Update eip-7667.md

EIPS/eip-5792.md
=> Update EIP-5792: Fix typo

EIPS/eip-7620.md
Add rules so that in the InitcodeTransaction empty lists and entries are invalid
=> Update EIP-7620: Update InitcodeTransaciton validation

EIPS/eip-5792.md
=> Update EIP-5792: revert 5792 editorial changes

EIPS/eip-7587.md
=> Update EIP-7587: Move to Last Call

_config.yml
=> wrong word check

EIPS/eip-1052.md
=> Update EIP-1052: fix typo

EIPS/eip-2026.md
Fixes the typo in the eip-2026.
=> Update EIP-2026: Fix typo in eip-2026

EIPS/eip-6690.md
=> Update EIP-6690: fix typo

EIPS/eip-7523.md
=> Update EIP-7523: fix typo

EIPS/eip-3074.md
Update EIP-3074: Fix typos and grammar
=> Update EIP-3074: Fix typos and grammar

EIPS/eip-3074.md
=> Update EIP-3074: Update eip-3074.md

EIPS/eip-7684.md, EIPS/eip9999.md
Automatically withdraw deposits for existing validator records but with distinct execution withdrawal credentials
=> Add EIP: Return deposits for distinct credentials

EIPS/eip-5792.md
=> Update EIP-5792: Move to Review

EIPS/eip-2537.md
=> Update EIP-2537: Update eip-2537.md - minor change in Field to curve mapping

EIPS/eip-7620.md
Opening the PR for visibility, but likely more entries will be added as an outcome of ongoing discussions
=> Update EIP-7620: Expand the Rationale section & clarifications

EIPS/eip-7002.md
This updates the EIP to support partial withdrawals in accordance with max eb.
=> Update EIP-7002: add support for partial withdrawals, rename exits

EIPS/eip-7002.md
exit-> count fix, I noticed a small bug introduced in this PR: https://github.com/ethereum/EIPs/pull/8406
cc: @lightclient
=> Update EIP-7002: Fix after renaming fields (exit->count)

.github/renovate.json
I already just close 99% of renovate PRs. I don't think it is necessary in this repo.
=> Config: Disable renovate

EIPS/eip-2982.md
=> Update EIP-2982: Fix typos

EIPS/eip-7685.md
request for clarification on fem https://ethereum-magicians.org/t/eip-7685-general-purpose-execution-layer-requests/19668/4?u=matt
=> Update EIP-7685: clarify intra-type ordering

EIPS/eip-7002.md
=> Update EIP-7002: make 7685 ordering explicit

EIPS/eip-101.md
=> Update EIP-101: fix typo

EIPS/eip-1.md
=> Update EIP-1: it's -> its

EIPS/eip-7701.md, EIPS/eip-9999.md
=> Add EIP: Native Account Abstraction with EOF

EIPS/eip-1901.md, EIPS/eip-3155.md, EIPS/eip-615.md
Hello, I've found some **outdated links** to external resources in old EIPs, this PR fixes them.
=> Update EIP-1901: outdated links

EIPS/eip-7692.md, EIPS/eip-eof-meta.md
=> Add EIP: EVM Object Format (EOFv1) Meta

EIPS/eip-4762.md
This is a proposal not to charge the witness costs for some basic operations, that break a lot of tooling.
These witness costs that would not be charged are:
- The tx's `from` and `to` addresses
=> Update EIP-4762: Move to Draft

EIPS/eip-7600.md
Changes decided on [ACDE#187](https://github.com/ethereum/pm/issues/1029)
=> Update EIP-7600: Update eip-7600.md

EIPS/eip-7702.md
Reviewers @vbuterin @SamWilsn @adietrichs @lightclient
Start the signer accounts warm
=> Update EIP-7702: Warm Signers

EIPS/eip-7543.md
it actually is arbitrary precision. the theory is. i did not add that before because in practice, the machine is limited. however, i think it is important to understand, that it has as much precision as any finite machine allows. within that limit, you can count on arbitrary precision here.
=> Update EIP-7543: Add "arbitrary precision" to title

EIPS/eip-7069.md
Clarifications after feedback received on R&D discord
=> Update EIP-7069: clarify EOF vs 7069 interactions

EIPS/eip-5450.md
Otherwise the reference to 2.3 was off
=> Update EIP-5450: Fix indentation and numbering

EIPS/eip-1474.md
Adding some commas to the net_version usage example
--
=> Update EIP-1474: Update eip-1474.md Fixing the net_version usage example (adding missed comma and deleting the excess onse) 

EIPS/eip-5450.md
Reported via https://github.com/ipsilon/eof/pull/121
=> Update EIP-5450: fix typo

EIPS/eip-7705.md, EIPS/nonreentrant.md
=> Add EIP: NONREENTRANT and REENTRANT opcodes

EIPS/eip-7549.md
=> Update EIP-7549: Update eip-7549 with latest version

EIPS/eip-2935.md
cleanup and add some clarifications
=> Update EIP-2935: Cleanup references and add some blockhash opcode clarifications

EIPS/eip-2935.md
some more proof reading and cleanup
=> Update EIP-2935: Further cleanup of the text

EIPS/eip-7703.md, EIPS/eip-draft_increase_calldata_cost.md
This EIP intends to replace EIP-7623
* Add EIP to increase calldata costs
=> Add EIP: Increase calldata cost

EIPS/eip-5806.md
=> Update EIP-5806: grammar correction

EIPS/eip-7002.md
=> Update EIP-7002: Move to Review

EIPS/eip-7698.md
=> Update EIP-7698: Move to Review

EIPS/eip-7547.md
=> Update EIP-7547: Move to Review

EIPS/eip-7692.md
=> Update EIP-7692: Move to Review

EIPS/eip-6110.md
=> Update EIP-6110: Move to Review

EIPS/eip-2935.md
=> Update EIP-2935: Move to Review

EIPS/eip-7594.md
=> Update EIP-7594: Move to Review

EIPS/eip-7623.md
=> 7623: move to review

EIPS/eip-7636.md
I believe I am allowed to move EIPs to Last Call
=> Update EIP-7636: Move to Last Call

EIPS/eip-5792.md
push EIP-5792 last call date back
=> Update EIP-5792: Push last call date back

EIPS/eip-4762.md
cleanup as per the discussions
=> Update EIP-4762: Cleanup/refactor the text as per clarifications

EIPS/eip-7620.md
Align with https://github.com/ipsilon/eof/pull/135
=> Update EIP-7620: Disallow referencing by both RETURNCONTRACT and EOFCREATE

EIPS/eip-663.md
Closes https://github.com/ipsilon/eof/issues/142
=> Update EIP-663: Fix markdown rendering

EIPS/eip-663.md
=> Update EIP-663: Fix markdown rendering 2

EIPS/eip-5792.md
=> Update EIP-5792: Push 5792 Last Call Back

EIPS/eip-7636.md
This is a premptive PR and it should only be merged on 2024-07-09
=> Update EIP-7636: Move to Final

EIPS/eip-7251.md
=> Update EIP-7251: fix typos

EIPS/eip-2294.md
=> Update EIP-2294: Move to Review

EIPS/eip-7702.md
Uses same key from pricing table.
=> Update EIP-7702: Update eip-7702.md, copypasta fix

.github/workflows/jekyll-label-bot.yml
=> CI: Update jekyll-label-bot.yml

EIPS/eip-7732.md
Updates the CL spec links to the merged commit
=> Update EIP-7732: Links to consensus repo

EIPS/eip-7702.md
This adds some notes about security considerations of 7702 that have been in discussion for a while.
=> Update EIP-7702: add more security considerations

EIPS/eip-5792.md
move EIP-5792 to last call with deadline of 9/5/2024
=> Update EIP-5792: Move to Last Call

EIPS/eip-7251.md
=> Update EIP-7251: typo in the code

EIPS/eip-7251.md
Remove reference to "custom ceilings" feature which has been removed from this EIP
=> Update EIP-7251: remove custom ceilings prose

EIPS/eip-7702.md
=> Update EIP-7702: Small clarification fix

EIPS/eip-7607.md
**Fulu** named as next consensus layer upgrade and **Fusaka** (Fulu + Osaka) for combined upgrade at ACDC #140. https://ethereum-magicians.org/t/all-core-devs-consensus-acdc-140-august-22-2024/20768
=> Update EIP-7607: Update eip-7607 with Fusaka name

EIPS/eip-7723.md
=> Update EIP-7723: Move to Review

EIPS/eip-7745.md
Fix order of operations in `reverse_transform` pseudocode function
=> Update EIP-7745: Fix reverse_transform

EIPS/eip-6404.md
Out of scope for Prague, so moving this back from Review.
=> Update EIP-6404: Move to Draft

EIPS/eip-6493.md
Out of scope for Prague, so moving this back from Review.
=> Update EIP-6493: Move to Draft

EIPS/eip-4762.md
=> Update EIP-4762: Add clarifications for the system contracts

EIPS/eip-7761.md
Distilled from [Eth R&D discord conversation](https://discord.com/channels/595666850260713488/718596092828057631/1284596590681526396)
=> Update EIP-7761: Fill Endgame AA's Rationale section

EIPS/eip-7685.md
=> Update EIP-7685: fix stale function name

EIPS/eip-7762.md
Currently a blocker for https://github.com/ethereum/EIPs/pull/8911
=> Update EIP-7762: Move to Review

EIPS/eip-7685.md
=> Update EIP-7685: fix typo

EIPS/eip-7495.md, EIPS/eip-7688.md, assets/eip-7495/remerkleable.patch, assets/eip-7495/tests.py
Reflects changes in v1.5.0-alpha.8 base spec.
=> Update EIP-7495: Rename `PendingBalanceDeposit` > `PendingDeposit`

.github/workflows/ci.yml, config/eipw.toml
See [`CHANGELOG.md`](https://github.com/ethereum/eipw/blob/master/CHANGELOG.md)
=> CI: Upgrade to eipw 0.9

config/eip-editors.yml
=> Add g11tech to other EIP categories for editing approval

EIPS/eip-6913.md
I am withdrawing this EIP in favor of EIP-7702 which accomplishes the same purpose and has more support.
Change EIP-6913 Status to Withdrawn
=> Update EIP-6913: Move to Withdrawn

.github/workflows/ci.yml, .github/workflows/jekyll.yml
=> CI: Bump setup-ruby to v1.196.0

EIPS/eip-7251.md
CONSOLIDATION_REQUEST_PREDEPLOY_ADDRESS -> 0x01aBEa29659e5e97C95107F20bb753cD3e09bBBb
--
=> Update EIP-7251: [EIP-7251] Update CONSOLIDATION_REQUEST_PREDEPLOY_ADDRESS

EIPS/eip-7002.md
WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS -> 0x09Fc772D0857550724b07B850a4323f39112aAaA
--
=> Update EIP-7002: [EIP-7002] Updated WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS

EIPS/eip-7701.md
=> Update EIP-7701: EIP-7701 update

EIPS/eip-7790.md, EIPS/eip-xxxx.md
This EIP proposes increasing the gas limit through EIP7783 in the span of 2 years from 30 to 60 million. starting in february 2025.
- After 6 months: Gas Limit = 37.5 Mn
- After 12 months: Gas Limit = 45 Mn
- After 18 months: Gas Limit = 52.5 Mn
- After 24 months: Gas Limit = 60 Mn
=> Add EIP: Controlled Gas Limit Increase Guidelines

config/eipw.toml
Update eipw.toml: Fixes ethereum/eipw#113
There's a more permanent fix upcoming in https://github.com/eips-wg/build/blob/master/.github/actions/checkout-eips/action.yml but that's a while out.
=> Config: Fixes ethereum/eipw#113

EIPS/eip-7610.md
=> Update EIP-7610: Move to Last Call

EIPS/eip-7587.md
In practice this EIP is already Final, this doc was just out of date. h/t to @poojaranjan for the reminder, thanks!
=> Update EIP-7587: Move to Final

EIPS/eip-7623.md
Addressing the suggestions raised by @shemnon in [this](https://github.com/ethereum/pm/issues/1197) issue.
=> Update EIP-7623: Update EIP-7762 with additional security considerations

EIPS/eip-7756.md
* remove required column in favour of multiple sections
* editing cleanup
--
=> Update EIP-7756: Cleanup

EIPS/eip-7623.md
Polishing text, fixing typos, and clarifying certain statements.
=> Update EIP-7623: Clarify and polish text

EIPS/eip-7251.md
Followup to:
* https://github.com/lightclient/sys-asm/pull/37
* https://github.com/ethereum/consensus-specs/pull/4020
=> Update EIP-7251: Set MAX_CONSOLIDATIONS=2

EIPS/eip-6916.md
Moving EIP 6916 to last call of the review. It has now been implemented in 4 clients so core devs had enough time to review how it works
=> Update EIP-6916: Move to Last Call

EIPS/eip-7542.md
=> Update EIP-7542: Move to Withdrawn

EIPS/eip-7251.md
=> Update EIP-7251: Update eip-7251.md

EIPS/eip-7691.md
=> Update EIP-7691: Update eip-7691.md

EIPS/eip-6110.md
=> Update EIP-6110: Update eip-6110.md

EIPS/eip-2935.md
=> Update EIP-2935: Update eip-2935.md

EIPS/eip-7808.md
=> Update EIP-7808: Move to Review

EIPS/eip-7723.md
=> Update EIP-7723: Escape Latex

EIPS/eip-7691.md
=> Update EIP-7691: Typo Fix

EIPS/eip-2537.md
Pairing costs are calculated in two locations, but the recent update addressed only one of them. This PR corrects the oversight and ensures both locations are updated appropriately.
--
- If matching on email address, the email address is the one …
=> Update EIP-2537: Update eip-2537 Adjusted pairing costs in the 2nd place

index.html
fixed typo to maintain consistency
--
=> Website: Update index.html

EIPS/eip-5792.md
=> Update EIP-5792: Add status codes"

EIPS/eip-7723.md
Adds clarifications for non-core EIPs included in network upgrades, and other rephrasings.
=> Update EIP-7723: Add non-Core EIPs

EIPS/eip-7549.md
EIP-7549 is included in Electra
=> Update EIP-7549: Move to Review

EIPS/eip-7519.md, EIPS/eip-7692.md
EIPs are still viable, there just hasn't been any edits for a 6 month stretch.
=> Update EIP-7519: Move to Draft

EIPS/eip-7600.md
=> Update EIP-7600: Add EIP-7840

EIPS/eip-7788.md
Corrected "chosing" to "choosing"
=> Update EIP-7788: fix spelling eip-7788.md

EIPS/eip-7823.md
This PR clarifies analysis results units.
=> Update EIP-7823: Clarify analysis results values.

EIPS/eip-6110.md
Updates wording, terms, numbers and links to the CL spec. In addition updates rationale of the `index` field
=> Update EIP-6110: Polish and actualise

EIPS/eip-7600.md
=> Update EIP-7600: Add testnet fork times

EIPS/eip-7702.md
=> Update EIP-7702: add rationale around refund mechanism

EIPS/eip-7702.md
=> Update EIP-7702: Move to Last Call

EIPS/eip-2935.md
=> Update EIP-2935: Move to Last Call

EIPS/eip-7732.md
=> Update EIP-7732: fix typos

EIPS/eip-7840.md
=> Update EIP-7840: Move to Last Call

EIPS/eip-7723.md
=> Update EIP-7723: Move to Last Call

EIPS/eip-2537.md
=> Update EIP-2537: Move to Last Call

EIPS/eip-7691.md
=> Update EIP-7691: Move to Last Call

EIPS/eip-7623.md
=> Update EIP-7623: Move to Last Call

EIPS/eip-7607.md
=> Update EIP-7607: Proposing 7805 for fusaka

EIPS/eip-7783.md
=> Update EIP-7783: Add exponential gas limit increase strategy to EIP7783

EIPS/eip-7600.md
=> Update EIP-7600: EL vs. CL EIP lists

EIPS/eip-7002.md, assets/eip-7002/fee_analysis.md
* Update rationale
* Provide detailed analysis of the fee mechanism
* Move to last call
=> Update EIP-7002: Move to Last Call

EIPS/eip-7600.md
=> Update EIP-7600: Move to Last Call

EIPS/eip-7783.md
This PR adds an additional gas limit increase strategy to the EIP, called the stepwise linear strategy.
=> Update EIP-7783: Add stepwise linear strategy

EIPS/eip-7607.md
=> Update EIP-7607: propose EIP-7783

EIPS/eip-3155.md
replaces https://github.com/ethereum/EIPs/pull/9397#pullrequestreview-2635488483
=> Update EIP-3155: Move to Last Call

EIPS/eip-4750.md, EIPS/eip-7698.md
These two EOF EIPs moved into stagnet as we waited our turn.
Move back to review.
=> Update EIP-4750: Move to Review

EIPS/eip-7002.md, EIPS/eip-7251.md, EIPS/eip-7685.md
Felix made many meaningful and material contribution to the request EIPs in Pectra and I think he deserves to be added as a co-author.
sys-asm commits: https://github.com/lightclient/sys-asm/commits/main/?author=fjl
EIP commits: https://github.com/ethereum/EIPs/commits/master/?author=fjl
=> Update EIP-7002: Add felix to request eips

EIPS/eip-7745.md
=> Update EIP-7745: improved row mapping, introduced mapping layers

EIPS/eip-5450.md, EIPS/eip-7620.md, EIPS/eip-7698.md, EIPS/eip-7873.md
Aligns with https://github.com/ipsilon/eof/pull/182, will be proposed for eof-devnet-1 as a QoL change
=> Update EIP-5450: Rename RETURNCONTRACT to RETURNCODE

EIPS/eip-7819.md
=> Update EIP-7819: Clarify specifications

.github/workflows/jekyll.yml
this might help to resolve recent CI issues
=> CI: Switch to upload-artifact@v4

EIPS/eip-7870.md
=> Update EIP-7870: Move to Review

EIPS/eip-663.md
six month auto-stagnate bots are annoying.
=> Update EIP-663: Move to Review

EIPS/eip-7903.md, EIPS/eip-xxxx.md
=> Add EIP: Remove Initcode Size Limit

EIPS/eip-7607.md
=> Update EIP-7607: propose eips 7791 and 7903 for inclusion in osaka

EIPS/eip-7607.md
=> Update EIP-7607: add eip-7907 to fusaka meta

EIPS/eip-7607.md
=> Update EIP-7607: Propose EIP-7917 for inclusion in Fusaka

EIPS/eip-####.md, EIPS/eip-7919.md
Adds meta EIP tracking the "SSZ" effort.
=> Add EIP: Pureth Meta

EIPS/eip-7898.md, EIPS/eip-uncouple-payload.md
=> Add EIP: Uncouple execution payload from beacon block

EIPS/eip-1015.md
Hello,
I have some grammatical suggestions for this text:
First, "The contract *should NOT be used to* to decide software updates, to freeze funds, change contracts balances or anything on the consensus layer other than the strict definition of where block rewards go"
"*should NOT be used to* to" could be *should NOT be used* to"
"change contracts balances" could be "change contract balances"
Second, a typo in "Votes weighted by ether balance (optionally with multipliers if the voters where committed to locking votes)"
"where" should be "were"
Thanks.
--
When opening a pull request to submit a new EIP, please use the suggested template: …
=> Update EIP-1015: Update eip-1015.md

EIPS/eip-7251.md
Following from https://github.com/ethereum/EIPs/pull/9508
=> Update EIP-7251: Add system call properties and directive for failure cases

EIPS/eip-7600.md
Tentatively agreed to on [ACDE#208](https://github.com/ethereum/pm/issues/1374), to confirm on [ACDC#154](https://github.com/ethereum/pm/issues/1399)
=> Update EIP-7600: Pectra Tentative Mainnet Activation Time

EIPS/eip-7600.md
=> Update EIP-7600: Add Hoodi

EIPS/eip-7251.md
=> Update EIP-7251: Fix typos in EIP-7251 (from author no farming)

EIPS/eip-7907.md
=> Update EIP-7907: update initcode limit in EIP 7907

EIPS/eip-7702.md
Preparing a PR to clean up the overall EIP some now that everything is steady. Want to adjust the line length here first with no content changes.
=> Update EIP-7702: reduce line width to 80 char

EIPS/eip-7923.md
fix a typo -- thanks to @jochem-brouwer for finding
=> Update EIP-7923: update a typo in the gas schedule

EIPS/eip-3607.md
=> Update EIP-3607: Fix typo

EIPS/eip-7577.md
=> Update EIP-7577: typo fix

EIPS/eip-4444.md
Hi,
I noticed a typo and I also suggest an improvement for clarity in this text:
1. "pronouncination" should be "pronunciation".
Original: "When pronouncing the EIP number, it MUST be pronounced EIP 'four fours'. All other pronounciations are incorrect"
Corrected: "When pronouncing the EIP number, it MUST be pronounced EIP 'four fours'. All other pronunciations are incorrect",
2. "too old" could be clarified as "outdated" or "expired", but it's not necessarily a typo—just a possible improvement for clarity.
Original: "...whether a given hash is invalid or just too old"
Suggested revision: "...whether a given hash is invalid or just outdated".
Thanks.
--
When opening a pull request to …
=> Update EIP-4444: Update eip-4444.md

EIPS/eip-7607.md
Reflects decisions from ACDC #154 and ACDC #155
=> Update EIP-7607: update Fusaka CFI and SFI list

EIPS/eip-7702.md
** work in progress**
- replace "designator" terminology with "indicator"
- improve readability of specification section
=> Update EIP-7702: refactor for better readability

EIPS/eip-7912.md, EIPS/pragmatic-swap-dup.md
Adding a stack arg based approach for swap, dup, and exchange.
=> Add EIP: Pragmatic stack manipulation tools

EIPS/eip-7748.md
Addresses some comments that arrived after the previous PR auto-merged.
Also fixes some linter issues.
=> Update EIP-7748: refactor eip7610 account handling code

EIPS/eip-2539.md
`an an` - `an` --fix duplicate
=> Update EIP-2539: fix duplicate eip-2539.md

EIPS/eip-7939.md
=> Update EIP-7939: fix typo in code comment

EIPS/eip-7907.md
=> Update EIP-7907: 256KB and 512KB hex values

EIPS/eip-7912.md
=> Update EIP-7912: fix typo, add optimization

EIPS/eip-7607.md
~~Still waiting for EIP number assignment, but proposing this for Fusaka.~~
~~https://github.com/ethereum/EIPs/pull/9501~~
EIP number added and merged.
=> Update EIP-7607: Add "Pragmatic expansion of stack manipulation tools" as DFI for Fusaka

EIPS/eip-7702.md
improve the verbiage a bit more
=> Update EIP-7702: more nits

EIPS/eip-5792.md
=> Update EIP-5792: Typo fix in CAIP-25 sentence of eip-5792.md

EIPS/eip-7892.md
Update the consensus config format to mirror current consensus proposal:
- ethereum/consensus-specs#4277
=> Update EIP-7892: Consensus Config Format

EIPS/eip-7607.md
On [ACDE#211] we agreed to SFI EIP-7935 and CFI EIP-7934
=> Update EIP-7607: Add ACDE#211 SFI & CFI'd EIPs

EIPS/eip-7701.md
=> Update EIP-7701: Replace 'n' with 'txparam_id' in the table

EIPS/eip-7701.md
=> Update EIP-7701: Fix the discussions link

EIPS/eip-7886.md
=> Update EIP-7886: polish eip rational

EIPS/eip-7702.md
In EIP 7702 update with fixing some minor typos.
=> Update EIP-7702: correct minor typos.

EIPS/eip-7939.md
=> Update EIP-7939: Strengthen motivation with SP1 optimized example, update authors

EIPS/eip-7793.md, EIPS/eip-7843.md
Change to assertion so transaction index can be statically determined.
=> Update EIP-7793: Change TXINDEX to ASSERTTXINDEX

EIPS/eip-7691.md
=> Update EIP-7691: Move to Final

EIPS/eip-7549.md
=> Update EIP-7549: Move to Final

EIPS/eip-6110.md
=> Update EIP-6110: Move to Final

EIPS/eip-2935.md
=> Update EIP-2935: Move to Final

EIPS/eip-7840.md
=> Update EIP-7840: Move to Final

EIPS/eip-7793.md, EIPS/eip-7843.md
Change from a precompile back to an opcode.
=> Update EIP-7843: change to opcode

EIPS/eip-7907.md
Trying to pull what seems to be consensus ideas and discussions from eth magicians thread into the EIP.
also link and "init" prefix for clarification in initcode spec line
=> Update EIP-7907: warm cold table with gas cost and scenarios

EIPS/eip-7607.md
Reflects the decisions from [ACDE#212](https://ethereum-magicians.org/t/all-core-devs-execution-acde-212-may-22-2025/24118/3).
=> Update EIP-7607: ACDE#212 Changes

EIPS/eip-7937.md
=> Update EIP-7937: Split EOF support specifications

EIPS/eip-2935.md
remove TBD from final EIP and link respective tests
=> Update EIP-2935: link execution spec tests

_includes/head.html
=> Website: Spelling issue

EIPS/eip-7907.md
Just wanted to make a clear and strong case of the developer experience benefits from this eip
=> Update EIP-7907: add strong devex motivation examples

EIPS/eip-7702.md
=> Update EIP-7702: Move to Final

EIPS/eip-7939.md
=> Update EIP-7939: Update EIP-7939

EIPS/eip-7804.md
This pull request introduces several minor corrections and improvements to the EIP-7804 document. The changes include fixing typographical errors, improving wording for clarity, and ensuring consistency throughout the text.
=> Update EIP-7804: Minor Typographical and Clarity Improvements in EIP-7804

EIPS/eip-7944.md, EIPS/eip-7956.md
=> Add EIP: Tx Ordering via Block-level Randomness

EIPS/eip-7950.md
Move the status to review.
The proposal is ready and has been under discussions for quite a while already.
=> Update EIP-7950: Move to Review

index.html
ref: https://fedi.limes.pink/@limes/112405829139042214
=> Website: Fix discord badge images

EIPS/eip-7907.md
=> Update EIP-7907: add lightclient and rakita to authors list

EIPS/eip-6404.md, EIPS/eip-6465.md
Use EIP-7495 / EIP-7916 for forward compatibility.
=> Update EIP-6465: Adopt `ProgressiveContainer` / `ProgressiveList`

EIPS/eip-7951.md
As discussed on the recent ACD
=> Update EIP-7951: update gas costs for R1 verification

EIPS/eip-7819.md
=> Update EIP-7819: Update EIP-7819

EIPS/eip-7939.md
=> Update EIP-7939: Move to Review

EIPS/eip-3026.md
This pull request corrects several typographical errors and improves the clarity of the EIP-3026 document.
=> Update EIP-3026: fix typos and improve clarity

EIPS/eip-1108.md
Hi! I update broken link. ref: https://cs.nyu.edu/~bb/#publications
=> Update EIP-1108: fixed dead link

EIPS/eip-7736.md
=> Update EIP-7736: fix typo in check_epoch_end pseudocode

EIPS/eip-5792.md
=> Update EIP-5792: Correct misspelling

EIPS/eip-7960.md
[conscise ----> concise](https://www.oxfordlearnersdictionaries.com/definition/english/concise) 
--
=> Update EIP-7960: fix typo in "concise"

EIPS/eip-7862.md
Updating specifications to match the ethereum/execution-specs
=> Update EIP-7862: Add Exec Specs

EIPS/eip-7956.md
Updating Specification. Proposing source of randomness with EIP-7998.
--
=> Update EIP-7956: Update eip-7956.md

EIPS/eip-7883.md, assets/eip-7883/call_analysis.md, assets/eip-7883/entity_analysis.md
This analysis has been updated to reflect the latest changes in EIP-7883 and has been shared in ACDE Nr. 215:
https://github.com/ethereum/pm/issues/1601
=> Update EIP-7883: Add empirical analysis

EIPS/eip-7928.md
This PR is based on discussions here that continued in the block access list discord channel:
https://github.com/ethereum/pm/issues/1652
=> Update EIP-7928: Update System Contract Handling

EIPS/eip-7979.md
Github Markdown is not the same.
=> Update EIP-7979: mostly formatting

EIPS/eip-7928.md
Updated based on discussions on ACDE: 
https://github.com/ethereum/pm/issues/1652
System Contract handling: index 0 and index `len(txs) +1`.
Move from SSZ to RLP, for now.
State Locations are still kept.
=> Update EIP-7928: Update system contract handling and move from ssz to rlp

EIPS/eip-1051.md
=> Update EIP-1051: fix typo

EIPS/eip-7898.md
enshrinment ->enshrinement 
usedful->useful
=> Update EIP-7898: fix typo

EIPS/eip-7928.md
This makes the eip more readable and comprehensible.
=> Update EIP-7928: Make specification section clearer with dedicated sections.

EIPS/eip-7917.md
=> Update EIP-7917: Update URLs and reflect changes in helper function

EIPS/eip-7607.md
Move `Informational` EIP out of the list of `Core` EIPs
--
=> Update EIP-7607: Update eip-7607.md

EIPS/eip-7773.md
Replaces the following PRs to address merge conflicts: 
* https://github.com/ethereum/EIPs/pull/10185
* https://github.com/ethereum/EIPs/pull/10145
* https://github.com/ethereum/EIPs/pull/10110
=> Update EIP-7773: Add EIPs 7981, 7999, 7932 and 7980 to PFI

EIPS/eip-7807.md
Fix plural forms, eliminate word repetition, and add missing articles for improved readability
=> Update EIP-7807: fix/correct style issues

EIPS/eip-7778.md
The word "limit" in the title was technically incorrect and probably confusing.
=> Update EIP-7778: improve title

EIPS/eip-7636.md
After the 3 pull requests to fix one letter in a withdrawn EIP, I decided to fix it because I am tired of these PRs.
=> Update EIP-7636: Fix the typo, stop people sending PRs

EIPS/eip-7976.md, EIPS/eip-7981.md
I clarified how the EIPs concretely impact the worst-case block size.
=> Update EIP-7976: improve wording

EIPS/eip-2780.md
Adding @benaadams as co-author.
=> Update EIP-2780: Move to Draft

EIPS/eip-2780.md
=> Update EIP-2780: Refresh and modernize

EIPS/eip-2780.md
=> Update EIP-2780: improve wording and clarify

EIPS/eip-7594.md
addressing this comment, https://github.com/ethereum/EIPs/pull/9588/files#r2325136236
nice catch @fradamt
=> Update EIP-7594: update table formatting

EIPS/eip-2003.md
https://ethereum.github.io/evmc/vmtester.html - broken
https://evmc.ethereum.org/vmtester.html - working
=> Update EIP-2003: fix broken link

EIPS/eip-2780.md
=> Update EIP-2780: Change recommendation to 6k

EIPS/eip-2780.md
=> Update EIP-2780: Add solady tx

EIPS/eip-2780.md
=> Update EIP-2780: Add rational to not price as calldata

EIPS/eip-2780.md
=> Update EIP-2780: Rephrase

EIPS/eip-2780.md
=> Update EIP-2780: Formatting

EIPS/eip-2780.md
=> Update EIP-2780: Add equivalent gas-limit increase

EIPS/eip-7748.md
Fix various grammatical errors and improve text clarity throughout the document
=> Update EIP-7748: Update EIP-7748

EIPS/eip-7980.md
I am going to withdraw this and make a new EIP for P256, just to preserve history
=> Update EIP-7980: Move to Withdrawn

EIPS/eip-7928.md
Clarified what to do with reverted calls.
=> Update EIP-7928: Further clarify reverts

EIPS/eip-7928.md
This PR implements the self-destruct logic discussed on https://github.com/ethereum/pm/issues/1738
=> Update EIP-7928: Clarify self destruct

EIPS/eip-7819.md
=> Update EIP-7819: Document address collision risks in EIP-7819

EIPS/eip-7979.md
Improved CFG explanation and moved to Rationale, other tweaks and random typos
=> Update EIP-7979: Update eip-7979.md

EIPS/eip-7782.md
=> Update EIP-7782: Update authors

EIPS/eip-2780.md
=> Update EIP-2780: Update authors

EIPS/eip-6789.md, EIPS/eip-7266.md, EIPS/eip-7791.md
=> Update EIP-6789: Use Name Alias

EIPS/eip-7898.md
=> Update EIP-7898: fix a typo

EIPS/eip-7870.md
Using ACDC #166 as a reference, see comment: https://github.com/ethereum/pm/issues/1740#issuecomment-3346511119
=> Update EIP-7870: Move to Living

EIPS/eip-7928.md
Clarified by @raxhvl here: https://discord.com/channels/595666850260713488/1364000387195076608/1423948774765498388
=> Update EIP-7928: Clarify EIP 7702

EIPS/eip-7702.md
=> Update EIP-7702: Correct link formatting

EIPS/eip-7636.md
=> Update EIP-7636: fix typo

EIPS/eip-1.md
Update EIP-1: clarify language for `Last Call` status definition.
=> Update EIP-1: Update eip-1.md

EIPS/eip-8007.md
=> Update EIP-8007: Update EIP-8007
